<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<link href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" rel="stylesheet" type="text/css" />
<?php $this->headScript()->offsetSetFile(18,$this->baseUrl().'/js/jquery.fileDownload.js', 'text/javascript');?>
<script type="text/javascript" src="/js/dateFormat.js"></script>
<style type="text/css">
    
     #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
    #dialog-form
    {
    	font-size: 16px;
    	font-weight: bold;
    	z-index: 999999999;
    }
    
    #dialog-form textarea
    {
	    resize: none;
	    width: 305px;
    }
    
    #optimization_value
    {
    	position: relative;
    	width: 300px;
    	z-index: 999999999;
    }
    
    #csv_all
    {
    	position: relative;
    	width: 24px;
    	height: 24px;
    	cursor: pointer;
    	float: right;
    	top: 60px;
    	background-image: url(/images/csv-24.gif);
    	z-index: 100;
    }
    
</style>
<script type="text/javascript" charset="utf-8">
		var current_site_id;
		var last_server_response = new Array();
		var sending_data;
		function optimization_values(site_id)
		{
			  window.current_site_id = site_id;
		      $.ajax({
		            type: "POST",
		            url: '/administrator/sites/ajax-optimization-get-values',
		            dataType: 'script',
		            data: {'siteId' : site_id},
		            success: function (data) {
			            if(data[0] != undefined)
			            {
				            if(data[0].Value != undefined && data[0].Notes != undefined && data[0].SiteID != undefined)
				            {
					            $("#optimization_value").val(data[0].Value);
					            $("#optimization_notes").val(data[0].Notes);
					            window.current_site_id = data[0].SiteID;
						    }
				        }
			            else
			            {
				            $("#optimization_value").val("");
				            $("#optimization_notes").val("");
					    }
		            	$("#dialog-form").dialog("open");
		            }
		        });
		}
		
        $(document).ready(function() {

            $("#filter-date").datepicker({
                showOn : 'focus',
                'dateFormat' : "yy-mm-dd"                                
            });
            <?php if($this->compare == true):?>
            	$('#filter-date').val('<?php echo $this->date1 ?>');
            <?php else: ?>
            	$('#filter-date').val('<?php echo date('Y-m-d', strtotime('-1 day'))?>');
            <?php endif;?>
            
            $("#filter-date2").datepicker({
                showOn : 'focus',
                'dateFormat' : "yy-mm-dd"                                
            });
            <?php if($this->compare == true):?>
            	$('#filter-date2').val('<?php echo $this->date2 ?>');
            <?php else: ?>
            	$('#filter-date2').val('<?php echo date('Y-m-d')?>');
            <?php endif; ?>

			$("#csv_all").click(function()
			{
				window.sending_data = new Array();
				for(var i = 0; i < window.last_server_response.length; i++ )
				{
					var item = [
								window.last_server_response[i][0],
								window.last_server_response[i][1],
								window.last_server_response[i][2],
								window.last_server_response[i][3],
								window.last_server_response[i][4],
								window.last_server_response[i][5],
								window.last_server_response[i][6],
								window.last_server_response[i][7],
								window.last_server_response[i][8],
								window.last_server_response[i][9],
								window.last_server_response[i][10],
								window.last_server_response[i][11],
								window.last_server_response[i][12],
								window.last_server_response[i][17],
								];
					window.sending_data.push(item);
				}
				if(window.sending_data.length > 0)
				{
					var sending_header = [
						  					 'PID',
						  					 'SID',
						  					 'Website',
						  					 'Contact',
						  					 'Impress Yestarday',
						  					 'Impress 2 day ago',
						  					 'Impress Change',
						  					 'Denied Impress',
						  					 'Alexa Rank',
						  					 'Top Alexa',
						  					 'Live',
						  					 'EverLive',
						  					 'DFP',
						  					 'Optimization Value'
					  					 ];
				    $.fileDownload('/administrator/ajax/ajax-make-csv', {
				        httpMethod: "POST",
						data: 
						{
							csv_filename: "approved_sites",
							csv_header: JSON.stringify(sending_header),
							csv_data: JSON.stringify(window.sending_data)
						}
				    });
				}
				else
				{
					alert('Empty table');
				}
			});
            
    		$("#dialog-form").dialog({
    			autoOpen: false,
    			height: 300,
    			width: 350,
    			modal: true,
    			buttons: 
        		{
	    			"Save": function() 
	    			{
	    			      $.ajax({
	    			            type: "POST",
	    			            url: '/administrator/sites/ajax-optimization-set-values',
	    			            data: 
		    			        {
			    			        'siteId' : window.current_site_id,
			    			        'value' : $("#optimization_value").val(),
			    			        'notes' : $("#optimization_notes").val() 
			    			    },
	    			            success: function (data) {
		    			            if(data.error != undefined)
			    			            alert('Illegal characters in value');
		    			            else
		    			            {
			    			            if(data.Value != undefined)
			    			            	$("#opt_"+window.current_site_id).html(data.Value);
			    			            else
			    			            	$("#opt_"+window.current_site_id).html("Add Value");
		    							$("#dialog-form").dialog( "close" );
			    			        }
	    			            }
	    			        });
		    		},
	    			Cancel: function() 
	    			{
	    				$( this ).dialog( "close" );
	    			}
    			},
    			});


        	  
                var countLive = 0;            
                var filter = $('#filter').val();
                <?php if($this->dataAuth->role == 'super'):?>
                    var accounts = $('#accounts').val();
                <?php else:?>
                    var accounts = <?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>;
                <?php endif;?>    
                var filterType = $('#filterType').val();
                var filterSize = $('#filterSize').val();
                var filterCategory = $('#filterCategory').val();
                var filterDate1 = $('#filter-date').val();
                var filterDate2 = $('#filter-date2').val();
                
                
                var oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/sites/ajax-approved',
                        "fnServerParams": function ( aoData ) {aoData.push( { "name": "filter", "value": filter }, { "name": "filterType", "value": filterType }, { "name": "accounts", "value": accounts }, { "name": "filterCategory", "value": filterCategory }, { "name": "filterSize", "value": filterSize }, { "name": "PubID", "value": <?php echo $this->PubID ? $this->PubID : 0; ?> }, { "name": "filterDate1", "value": filterDate1 }, { "name": "filterDate2", "value": filterDate2 } ); },
                        "fnDrawCallback": function( oSettings ) { $('#count-live').html(countLive); countLive = 0; display('none'); },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100,
                        'fnServerData' : function(sSource, aoData, fnCallback ){
                            $.ajax({
                                'dataType': 'json',
                                'type': 'GET',
                                'url': sSource,
                                'data': aoData,
                                'success': [fnCallback,function(data)
                                {
                                	window.last_server_response = data.aaData;
                                }]
                            });
                        },
                        "aoColumns": [
                            { 
                              "sTitle": "PID",
                              "fnRender": function(obj){ 	
                                  return obj.aData[0]; } 
                            },
                            { 
                              "sTitle": "SID",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Website",
                              "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[1]+'">'+obj.aData[2]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Contact",
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[0]+'">'+obj.aData[3]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Impres yesterday",
                              "fnRender": function(obj){ return obj.aData[4]; } 
                            },
                            { 
                              "sTitle": "Impres 2 day ago",
                              "fnRender": function(obj){ return obj.aData[5]; } 
                            },
                            { 
                              "sTitle": "Impres change",
                              "fnRender": function(obj){ var percent = 0; if(obj.aData[6]) percent = obj.aData[6]; return percent+'%'; } 
                            },
                            { 
                              "sTitle": "Denied Impres Yesterday",
                              "fnRender": function(obj){ return '<a style="cursor: pointer" onClick="showNotApproved('+obj.aData[1]+')">'+obj.aData[7]+'</a>'; } 
                            },
                            { 
                                "sTitle": "Revenue",
                                "fnRender": function(obj)
                                {
                                    if(obj.aData[8] != null)
									 	return parseFloat(obj.aData[8]).toFixed(2);
                                    else
                                        return 0;
	                             } 
                            },                            
                            { 
                              "sTitle": "Alexa rank",
                              "fnRender": function(obj){ return obj.aData[9]; } 
                            },
                            { 
                              "sTitle": "Top Alexa Country",
                              "fnRender": function(obj){ return obj.aData[10]; } 
                            },                            
                            { 
                              "sTitle": "Live",
                              "fnRender": function(obj){ 
                                  if(obj.aData[11]){ countLive ++; return  '<a href="#" onclick="updateInfo(\'live\', \''+obj.aData[18]+'\', '+obj.aData[1]+', \'red\')"><img src="/images/status-green-check.gif"></a>'; }
                                  else            {               return  '<a href="#" onclick="updateInfo(\'live\', \''+obj.aData[18]+'\', '+obj.aData[1]+', \'green\')"><img src="/images/stats-red-x.gif"></a>';    } 
                                  
                                  }
                                                        
                            },
                            { 
                              "sTitle": "Ever Live",
                              "fnRender": function(obj){  
                                  
                                  if(obj.aData[12]) return '<img src="/images/status-green-check.gif"/>';
                                  else             return '<img src="/images/stats-red-x.gif"/>';       } 
                            },
                            { 
                              "sTitle": "Tags",
                              "bSortable": false,
                              "fnRender": function(obj){  
                                  if(obj.aData[13] == 4)
                                  	return '<a href="/administrator/tags/edit/tag/'+obj.aData[17]+'/site/'+obj.aData[1]+'/user/'+obj.aData[0]+'">G</a>';
                                  else if(obj.aData[13] == 5)
                                  	return '<a href="/administrator/tags/edit/tag/'+obj.aData[17]+'/site/'+obj.aData[1]+'/user/'+obj.aData[0]+'">R</a>';
                                  else if(obj.aData[13] == 6)
                                  	return '<a href="/administrator/tags/edit/tag/'+obj.aData[17]+'/site/'+obj.aData[1]+'/user/'+obj.aData[0]+'">B</a>';
                                  else if(obj.aData[13] == 7)
                                  	return '<a href="/administrator/tags/edit/tag/'+obj.aData[17]+'/site/'+obj.aData[1]+'/user/'+obj.aData[0]+'">M</a>';                                  	
                                  else if(obj.aData[13] == 8)
                                  	return '<a href="/administrator/tags/edit/tag/'+obj.aData[17]+'/site/'+obj.aData[1]+'/user/'+obj.aData[0]+'">P</a>';                                  	
                                  else
                                  	return '';
								}  
                                                 
                            },
                            { 
                                "sTitle": "Optimization Value",
                                "fnRender": function(obj){ return '<a href="#" id="opt_'+obj.aData[1]+'" onClick="optimization_values('+obj.aData[1]+')">'+obj.aData[18]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Login",
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[0]+'" target="_blank">Login</a>'; } 
                            },
                            { 
                              "sTitle": "CSV",
                              "sClass": "csv",
                              "bSortable": false,
                              "fnRender": function(obj){ return '<div id="csv_'+obj.aData[1]+'"><a onClick="getCsv('+obj.aData[1]+')">create</a></div>'; obj.aData[0]; }
                            }
                        ],                                                
                        "aaSorting": [[ 2, "asc" ]]
                         
                } );
                
                $('#filter').change(function(){ filter = $('#filter').val(); oTable.fnClearTable(); display('block'); });
                $('#accounts').change(function(){ accounts = $('#accounts').val(); oTable.fnClearTable(); display('block'); });
                $('#filterType').change(function(){ filterType = $('#filterType').val(); oTable.fnClearTable(); display('block'); });
                $('#filterSize').change(function(){ filterSize = $('#filterSize').val(); oTable.fnClearTable(); display('block'); });
                $('#filterCategory').change(function(){ filterCategory = $('#filterCategory').val(); oTable.fnClearTable(); display('block'); });
        } );
  
function updateInfo(action, name, id, color)
{   
    var popup=prompt('Your Name:',name)
    
    if(popup){
        location.href = '/administrator/sites/update/act/'+action+'/name/'+popup+'/id/'+id+'/color/'+color;
    }else{
        return false;
    }
}

function getCsv(id){
    
    $('#csv_'+id).html('loading...');
    
    $.ajax({ url : '/administrator/ajax/csv',
                       data : { id : id },
                       type : "POST",
                       dataType : "json",

             success : function(response) { 

                   if(response.result.status){ 

                      $('#csv_'+id).html('<a href="'+response.result.file+'">download</a>');

                   } else { 
                   
                      $('#csv_'+id).html('not found');
                   
                   }

               },
               
             error : function(){ $('#csv_'+id).html('error'); }
     });
    
}

function loginUser(id){ 

    location.href='/administrator/index/auth/id/'+id;
    
}

function showNotApproved(siteID){
    
    $.fancybox({
            'width'	: '75%',
            'height'	: '75%',
            'href'      : '/administrator/url/index/id/'+siteID,
            'autoScale'    	: false,
            'transitionIn'	: 'none',
            'transitionOut'	: 'none',
            'type'		: 'iframe'
    }); 
}

function display(status)
{
    $('#mask').css('display', status);
    $('#loading').css('display', status);         
}

</script>


<div id="dialog-form" title="Optimization Values">
	<form>
		<fieldset>
			<label for="optimization_value">Potential Additional Daily Revenue:</label><br/>
			$<input type="text" name="optimization_value" id="optimization_value" class="text ui-widget-content ui-corner-all" /><br/>
			<label for="optimization_notes">Notes:</label><br/>
			<textarea rows="8" cols="20" type="text" name="optimization_notes" id="optimization_notes" value="" class="text ui-widget-content ui-corner-all"></textarea>
		</fieldset>
	</form>
</div>


<h1>Approved Websites</h1>
<div class="contUsL" style="width: 750px;">
<h2>Total sites live: <span id="count-live"></span></h2>
<h2><a href="/administrator/sites/live">View Daily Stats</a></h2>
<p>
    Date1 &nbsp;- <input type="text" name="filter-date" id="filter-date" style="margin-left: 9px;"/>    
    
    <input type="text" name="filter-date2" id="filter-date2" style="margin-left: 20px; margin-right: 7px;"/> -&nbsp; Date2
    
</p>
<p>
Status: <select style="margin-left: 14px;" id="filter">
	<option value="all">All</option>
	<option value="live">Live Sites</option>
	<option value="no_longer">No Longer</option>
	<option value="never_live">Never Live</option>
        <option value="store_tag_url">Enable Full URL</option>
    </select>    
    
    <select id="accounts">
        <?php if($this->dataAuth->role == 'super'):?>
            <option value="-1">All</option>
            <?php foreach($this->contactManager as $iter):?>
                 <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
            <?php endforeach;?>
        <?php else: ?>
            <option value="<?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>">Show My Accounts</option>                 
            <option value="-1">Show All Accounts</option>
        <?php endif;?>    
    </select>
<!--<a id="letter_link" href="/administrator/sites/notification">Notifications</a>-->
</p>
<p>
Site Type: <select id="filterType">
        <option value="all">All</option>
        <option value="4">Google Admanager</option>
        <option value="5">Rubicon</option>
        <option value="6">Burst</option>
        <option value="7">MadX</option>        
        <option value="8">Pubmatic</option>        
        <option value="1">No Tags</option>                
    </select>
</p>
<p>    
   Category: <select name="filterCategory" id="filterCategory">
        <option value="all">All</option>
        <?php foreach($this->category as $iter):?>
        <option value="<?php echo $iter['id']?>"><?php echo $iter['name'];?></option>
        <?php endforeach;?>
    </select>
    
    <select name="filterSize" id="filterSize">
            <option value="all">Show All AdSize</option>
            
            <?php foreach($this->size as $iter):?>
                 <option value="<?php echo $iter['id']?>"><?php echo $iter['name']?></option>
            <?php endforeach;?>

    </select>
</p>
<div id="csv_all"></div>
    
    
</p>
<br /><br />
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
                    <th width="5%">PID</th>
                    <th width="5%">SID</th>
                    <th width="20%">Website</th>
                    <th width="20%">Contact</th>
                    <th width="10%">Impres yesterday</th>
                    <th width="10%">Impres 2 day ago</th>
                    <th width="10%">Impres change</th>
                    <th width="10%">Denied Impres Yesterday</th>
                    <th width="10%">Revenue</th>
                    <th width="10%">Alexa rank</th>
                    <th width="10%">Top Alexa Country</th>
                    <th width="10%">Live</th>
                    <th width="10%">Ever Live</th>
                    <th width="10%">DFP</th>
                    <th width="20%">Optimization Value</th>  
                    <th width="10%">Login</th>
                    <th width="20%">CSV</th>
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot>
		<tr>
                    <th>PID</th>
                    <th>SID</th>
                    <th>Website</th>
                    <th>Contact</th>
                    <th>Impres yesterday</th>
                    <th>Impres 2 day ago</th>
                    <th>Impres change</th>
                    <th>Denied Impres Yesterday</th>
                    <th>Revenue</th>
                    <th>Alexa rank</th>
                    <th>Top Alexa Country</th>
                    <th>Live</th>
                    <th>Ever Live</th>
                    <th>DFP</th>
                    <th>Optimization Value</th>
                    <th>Login</th>
                    <th>CSV</th>                    
		</tr>
	</tfoot>
</table>
</div> 

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
