<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" src="/js/jquery.fileDownload.js"></script>
<script type="text/javascript" src="/js/dateFormat.js"></script>

<style type="text/css">
    
     #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
    #dialog-form
    {
    	font-size: 16px;
    	font-weight: bold;
    	z-index: 999999999;
    }
    
    #dialog-form textarea
    {
	    resize: none;
	    width: 305px;
    }
    
    #optimization_value
    {
    	position: relative;
    	width: 300px;
    	z-index: 999999999;
    }
    
    #csv_all
    {
    	position: relative;
    	width: 24px;
    	height: 24px;
    	cursor: pointer;
    	float: left;
    	top: 21px;
        left: 308px;
    	background-image: url(/images/csv-24.gif);
    	z-index: 100;
    }
    #dsp_all
    {
    	position: relative;
    	width: 24px;
    	height: 24px;
    	cursor: pointer;
    	float: left;
    	top: 21px;
        left: 308px;
    	background-image: url(/images/dsp-24.png);
    	z-index: 100;
    }
    .emptyPadding{ padding: 0px !important; }
    #block_prev_live{ display: none; margin-top: 10px; float: left; }
    .itemEcpm{ cursor: pointer; }
    
    #users_wrapper{ top: -25px; }
    #users_filter{ float: left; }
    #tableScroll{ 
        width: 1300px; 
        overflow-y: auto;
        margin-top: 20px;
        float: left;
        resize: horizontal;
    }
    
    /*#tableRotate, #tableScroll{
        transform:rotateX(180deg);
        -ms-transform:rotateX(180deg);  
        -webkit-transform:rotateX(180deg);  
    }*/
    
    
</style>
<script type="text/javascript" charset="utf-8">
		var current_site_id;
		var last_server_response = new Array();
		var sending_data;
                var oTable = new Object();
		function optimization_values(site_id)
		{
			  window.current_site_id = site_id;
		      $.ajax({
		            type: "POST",
		            url: '/administrator/sites/ajax-optimization-get-values',
		            dataType: 'script',
		            data: {'siteId' : site_id},
		            success: function (data) {
			            if(data[0] != undefined)
			            {
				            if(data[0].Value != undefined && data[0].Notes != undefined && data[0].SiteID != undefined)
				            {
					            $("#optimization_value").val(data[0].Value);
					            $("#optimization_notes").val(data[0].Notes);
					            window.current_site_id = data[0].SiteID;
						    }
				        }
			            else
			            {
				            $("#optimization_value").val("");
				            $("#optimization_notes").val("");
					    }
		            	$("#dialog-form").dialog("open");
		            }
		        });
		}
		
        $(document).ready(function() {
        
                        var widthWindow = parseInt(getClientWidth() - 200);
                                                         
                        $("#filter-date").datepicker({
                            showOn : 'focus',
                            'dateFormat' : "yy-mm-dd"                                
                        });
                        <?php if($this->compare == true):?>
                        	$('#filter-date').val('<?php echo $this->date1 ?>');
                        <?php else: ?>
                        	$('#filter-date').val('<?php echo date('Y-m-d', strtotime('-1 day'))?>');
                        <?php endif;?>
                        
                        $("#filter-date2").datepicker({
                            showOn : 'focus',
                            'dateFormat' : "yy-mm-dd"                                
                        });
                        <?php if($this->compare == true):?>
	                    	$('#filter-date2').val('<?php echo $this->date2 ?>');
	                    <?php else: ?>
                        	$('#filter-date2').val('<?php echo date('Y-m-d')?>');
                        <?php endif; ?>



			$("#csv_all").click(function()
			{
				window.sending_data = new Array();
				for(var i = 0; i < window.last_server_response.length; i++ )
				{
					var item = [
								window.last_server_response[i][0],
								window.last_server_response[i][1],
								window.last_server_response[i][2],
								window.last_server_response[i][3],
								window.last_server_response[i][4],
								window.last_server_response[i][5],
								window.last_server_response[i][7],
								window.last_server_response[i][8],
								window.last_server_response[i][14],
								window.last_server_response[i][15],
								window.last_server_response[i][16],
								window.last_server_response[i][17],
								window.last_server_response[i][20],
								window.last_server_response[i][25],
								];
					window.sending_data.push(item);
				}
				if(window.sending_data.length > 0)
				{
					var sending_header = [
						  					 'PID',
						  					 'SID',
						  					 'Website',
						  					 'Contact',
						  					 'Impress Yestarday',
						  					 'Impress 2 day ago',
						  					 'Impress Change',
						  					 'Denied Impress',
						  					 'Alexa Rank',
						  					 'Top Alexa',
						  					 'Live',
						  					 'EverLive',
						  					 'DFP',
						  					 'Optimization Value'
					  					 ];
				    $.fileDownload('/administrator/ajax/ajax-make-csv', {
				        httpMethod: "POST",
						data: 
						{
							csv_filename: "approved_sites",
							csv_header: JSON.stringify(sending_header),
							csv_data: JSON.stringify(window.sending_data)
						}
				    });
				}
				else
				{
					alert('Empty table');
				}
			});
            
			$("#dsp_all").click(function()
			{
				window.sending_data = new Array();
				for(var i = 0; i < window.last_server_response.length; i++ )
				{
					var item = [
								window.last_server_response[i][1]
								];
					window.sending_data.push(item);
				}
				
				var sending_header = [
					  					 'Site Name',
					  					 'Site URL',
					  					 'Monthly Impressions',
					  					 'Category'
				  					 ];
				  					 
			    $.fileDownload('/administrator/ajax/ajax-make-dsp', {
			        httpMethod: "POST",
					data: 
					{
						csv_filename: "dsp",
						csv_header: JSON.stringify(sending_header),
						csv_data: JSON.stringify(window.sending_data),
						export_all: $('#export_all').prop('checked')
					}
			    });
			    
			});            
            
    		$("#dialog-form").dialog({
    			autoOpen: false,
    			height: 300,
    			width: 350,
    			modal: true,
    			buttons: 
        		{
	    			"Save": function() 
	    			{
	    			      $.ajax({
	    			            type: "POST",
	    			            url: '/administrator/sites/ajax-optimization-set-values',
	    			            data: 
		    			        {
			    			        'siteId' : window.current_site_id,
			    			        'value' : $("#optimization_value").val(),
			    			        'notes' : $("#optimization_notes").val() 
			    			    },
	    			            success: function (data) {
		    			            if(data.error != undefined)
			    			            alert('Illegal characters in value');
		    			            else
		    			            {
			    			            if(data.Value != undefined)
			    			            	$("#opt_"+window.current_site_id).html(data.Value);
			    			            else
			    			            	$("#opt_"+window.current_site_id).html("Add Value");
		    							$("#dialog-form").dialog( "close" );
			    			        }
	    			            }
	    			        });
		    		},
	    			Cancel: function() 
	    			{
	    				$( this ).dialog( "close" );
	    			}
    			}
    			});


        	  
                var countLive = 0;            
                
                <?php if(!empty($this->filter)):?>
                    var filter = '<?php echo $this->filter ?>';    
                    $('#filter').val(filter);
                <?php else:?>
                    var filter = $('#filter').val(); 
                <?php endif;?>               
            
                <?php if($this->dataAuth->role == 'super'):?>
                    var accounts = $('#accounts').val();
                <?php else:?>
                	var accounts = $('#accounts').val();
                //var accounts = <?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>;
                <?php endif;?>  
                    
                //var filterAdxApprove = $('#adx_approve_show:checked').val() ? 1 : 0;   
                var filterPrevNotif = 1;
                var filterDate1 = $('#filter-date').val();
                var filterDate2 = $('#filter-date2').val();
                var filterSize = $('#filterSize').val();
                var siteType = $('#siteType').val();
                var filterValue = $('#filterValue').val();
                var publisherId = $('#publisherId').val();
                                      
                oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/sites/ajax-approved',
                        "fnServerParams": function ( aoData ) {aoData.push( { "name": "filter", "value": filter }, { "name": "accounts", "value": accounts }, { "name": "filterDate1", "value": filterDate1 }, { "name": "filterDate2", "value": filterDate2 }, { "name": "filterCategory", "value": $("#filterCategory").val() }, { "name": "filterSize", "value": filterSize }, { "name": "filterPrevNotif", "value": filterPrevNotif }, { "name": "PubID", "value": <?php echo $this->PubID ? $this->PubID : 0; ?> }, { "name": "siteType", "value": siteType }, { "name": "filterValue", "value": filterValue }, { "name": "publisherId", "value": publisherId } ); },
                        "fnDrawCallback": function( oSettings ) {                            
                                                                    $('#count-live').html(countLive); countLive = 0; 
                                                                    
                                                                    var widthTable = parseInt($('#users').css('width'));
                                                                    
                                                                    if(widthTable > widthWindow){ $('#tableScroll').css('width', widthWindow); }
                                                                                            else{ $('#tableScroll').css('width', widthTable);  }
                                                                                             
                                                                    display('none');  
                                                                },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100,
                        'fnServerData' : function(sSource, aoData, fnCallback ){
                            $.ajax({
                                'dataType': 'json',
                                'type': 'GET',
                                'url': sSource,
                                'data': aoData,
                                'success': [fnCallback,function(data)
                                {
                                	window.last_server_response = data.aaData;
                                }]
                            });
                        },
                        "aoColumns": [
                            { 
                              "sTitle": "PID",
                              "bVisible": <?php echo $this->column['PubID'] ?>,
                              "sClass": "emptyPadding",
                              "fnRender": function(obj){ var result = '<span style="display: block; padding: 4px 8px; font-size: 12px;">'+obj.aData[0]+'</span>';
                                                         var adxStatus = parseInt(obj.aData[27]);
                                                         
                                       if(adxStatus == 1 || 
                                          adxStatus == 4){ result = '<span style="background: #FFA301; display: block; padding: 4px 8px; font-size: 12px;">'+obj.aData[0]+'</span>'; }
                                  else if(adxStatus == 2){ result = '<span style="background: #F20300; display: block; padding: 4px 8px; font-size: 12px;">'+obj.aData[0]+'</span>'; }
                                  
                                  return result ; } 
                            },
                            { 
                              "sTitle": "SID",
                              "bVisible": <?php echo $this->column['SiteID'] ?>,
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Website",
                              "bVisible": <?php echo $this->column['Website'] ?>,
                              "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[1]+'">'+obj.aData[2]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Contact",
                              "bVisible": <?php echo $this->column['Contact'] ?>,
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[28]+'">'+obj.aData[3]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Impres1 <?php echo date("n/j/y", strtotime('-1 day')) ?>",
                              "bVisible": <?php echo $this->column['Impres_yesterday'] ?>,
                              "fnRender": function(obj){ return number_format(obj.aData[4],0,'.',','); } 
                            },
                            { 
                              "sTitle": "Impres2 <?php echo date("n/j/y") ?>",
                              "bVisible": <?php echo $this->column['Impres_2day_ago'] ?>,
                              "fnRender": function(obj){ return number_format(obj.aData[5],0,'.',','); } 
                            },
                            { 
                              "sTitle": "Impres change",
                               "bVisible": <?php echo $this->column['Impres_change'] ?>,
                              "fnRender": function(obj){ return (parseInt(obj.aData[6]) < 0 ? '-'+number_format(Math.abs(obj.aData[6]),0,'.',',') : number_format(obj.aData[6],0,'.',',')); } 
                            },
                            { 
                              "sTitle": "Impres change%",
                              "bVisible": <?php echo $this->column['Impres_change_percent'] ?>,
                              "fnRender": function(obj){ var percent = 0; if(obj.aData[7]) percent = obj.aData[7]; return percent+'%'; } 
                            },
                            { 
                              "sTitle": "Denied Impres <?php echo date("n/j/y") ?>",
                              "bVisible": <?php echo $this->column['Denied_Impres_Yesterday'] ?>,
                              "fnRender": function(obj){ return '<a style="cursor: pointer" onClick="showNotApproved('+obj.aData[1]+')">'+number_format(obj.aData[8],0,'.',',')+'</a>'; } 
                            },
                            { 
                              "sTitle": "Impres avg7day <?php echo date("n/j/y") ?>",
                              "bVisible": <?php echo $this->column['Impres_avg_7day'] ?>,
                              "fnRender": function(obj){ return number_format(obj.aData[9],0,'.',','); } 
                            },
                            { 
                                "sTitle": "Revenue1 <?php echo date("n/j/y", strtotime('-1 day')) ?>",
                                "bVisible": <?php echo $this->column['Revenue_Today'] ?>,
                                "fnRender": function(obj)
                                {
                                    var impress = parseInt(obj.aData[29]);
                                    var revenue = parseFloat(obj.aData[10]).toFixed(2);
                                    var CPM = 0;
                                    
                                    if(revenue > 0 && impress){ CPM = parseFloat(revenue * 1000 / impress).toFixed(2); }
                                    /*else if(!impress){ CPM = '<a id="ecpm-'+obj.aData[1]+'" class="itemEcpm" onClick="getAbsEcpm('+obj.aData[1]+')">abs</a>'; }*/

                                    return revenue+' ('+CPM+')';
                                }                              
                            },
                            { 
                                "sTitle": "Revenue2 <?php echo date("n/j/y") ?>",
                                "bVisible": <?php echo $this->column['Revenue_Yesterday'] ?>,
                                "fnRender": function(obj)
                                {
                                    var impress = parseInt(obj.aData[30]);
                                    var revenue = parseFloat(obj.aData[11]).toFixed(2);
                                    var CPM = 0;
                                    
                                    if(revenue > 0 && impress){ CPM = parseFloat(revenue * 1000 / impress).toFixed(2); }
                                    /*else if(!impress){ CPM = '<a id="ecpm1-'+obj.aData[1]+'" class="itemEcpm" onClick="getAbsEcpm('+obj.aData[1]+')">abs</a>'; }*/

                                    return revenue+' ('+CPM+')';                             
	                        } 
                            },   
                            { 
                                "sTitle": "Revenue Change",
                                "bVisible": <?php echo $this->column['Revenue_change'] ?>,
                                "fnRender": function(obj)
                                {
                                    return parseFloat(obj.aData[12]).toFixed(2);                                                     
	                        } 
                            },   
                            { 
                                "sTitle": "Revenue Change%",
                                "bVisible": <?php echo $this->column['Revenue_change_percent'] ?>,
                                "fnRender": function(obj)
                                {
                                    var revenue = parseFloat(obj.aData[13]);
                                    
                                    return revenue ? revenue.toFixed(2)+'%' : '0%';                                                     
	                        } 
                            },   
                            { 
                              "sTitle": "Alexa rank",
                              "bVisible": <?php echo $this->column['Alexa_rank'] ?>,
                              "fnRender": function(obj){ return number_format(obj.aData[14],0,'.',','); } 
                            },
                            { 
                              "sTitle": "Top Alexa Country",
                              "bVisible": <?php echo $this->column['Top_Alexa_Country'] ?>,
                              "fnRender": function(obj){ return number_format(obj.aData[15],0,'.',',')+'('+obj.aData[32]+')'; } 
                            },                            
                            { 
                              "sTitle": "Live",
                              "bVisible": <?php echo $this->column['Live'] ?>,
                              "fnRender": function(obj){ 
                                  if(parseInt(obj.aData[16])){ countLive ++; return  '<a href="#" onclick="updateInfo(\'live\', \''+obj.aData[25]+'\', '+obj.aData[1]+', \'red\')"><img src="/images/status-green-check.gif"></a>'; }
                                  else                       {               return  '<a href="#" onclick="updateInfo(\'live\', \''+obj.aData[25]+'\', '+obj.aData[1]+', \'green\')"><img src="/images/stats-red-x.gif"></a>';    } 
                                  
                                  }
                                                        
                            },
                            { 
                              "sTitle": "Ever Live",
                              "bVisible": <?php echo $this->column['Ever_Live'] ?>,
                              "fnRender": function(obj){  
                                  
                                  var notifiStatus = parseInt(obj.aData[26]);
                                  
                                  if(parseInt(obj.aData[17])) return '<img src="/images/status-green-check.gif"/>';
                                  else
                                  {
										if(notifiStatus == 3 || notifiStatus == 2 || notifiStatus == 1)
										{
											return '<img onClick="setGreyStatus('+obj.aData[1]+')" style="cursor: pointer;" src="/images/stats-orange-x.png">';
										}
										else if(notifiStatus == 4)
										{
											return '<img src="/images/stats-grey-x.png">';
										}
										else
										{
											return '<img onClick="setOrangeStatus('+obj.aData[1]+')" style="cursor: pointer;" src="/images/stats-red-x.gif"/>';
										}
                                  }
                              }                        
                                      //return  (notifiStatus == 3 || notifiStatus == 2 || notifiStatus == 1) ? '<img onClick="setOrangeStatus('+obj.aData[1]+')" style="cursor: pointer;" src="/images/stats-orange-x.png">' : '<img onClick="setOrangeStatus('+obj.aData[1]+')" style="cursor: pointer;" src="/images/stats-red-x.gif"/>'; }  
                            },
                            { 
                              "sTitle": "First Live",
                              "bVisible": <?php echo $this->column['First_Live'] ?>,
                              "bSortable": true,
                              "fnRender": function(obj){ return obj.aData[18]; }             
                            },
                            { 
                              "sTitle": "Tag Create",
                              "bVisible": <?php echo $this->column['Tag_Create'] ?>,
                              "bSortable": true,
                              "fnRender": function(obj){ return obj.aData[19]; }             
                            },                            
                            { 
                              "sTitle": "Tags",
                              "bVisible": <?php echo $this->column['Tags'] ?>,
                              "fnRender": function(obj){
                                  return '<a href="/administrator/tags/edit/site/'+obj.aData[1]+'">'+obj.aData[20]+'</a>';
                              } 
                            },                            
                            { 
                              "sTitle": "Contact",
                              "bVisible": true,
                              "bSortable": false,
                              "fnRender": function(obj){
                            	  return '<button style="cursor: pointer" onClick="mailContact('+obj.aData[31]+')">Contact</button>';
                              }             
                            },
                            { 
                                "sTitle": "Optimization Value",
                                "bVisible": <?php echo $this->column['Optimization_Value'] ?>,
                                "fnRender": function(obj){ return '<a href="#" id="opt_'+obj.aData[1]+'" onClick="optimization_values('+obj.aData[1]+')">'+obj.aData[25]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Login",
                              "bVisible": <?php echo $this->column['Login'] ?>,
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[28]+'" target="_blank">Login</a>'; } 
                            },
                        ],                                                
                        "aaSorting": [[ 2, "asc" ]]
                         
                } );

                <?php if($this->compare == true):?>
	                oTable.fnSettings().aoColumns[4].nTh.innerHTML = 'Impres1 '+$('#filter-date').val();   
	                oTable.fnSettings().aoColumns[10].nTh.innerHTML = 'Revenue1  '+$('#filter-date').val();
                    oTable.fnSettings().aoColumns[5].nTh.innerHTML = 'Impres2 '+$('#filter-date2').val();
                    oTable.fnSettings().aoColumns[8].nTh.innerHTML = 'Denied Impres '+$('#filter-date2').val();
                    oTable.fnSettings().aoColumns[9].nTh.innerHTML = 'Impres avg7day '+$('#filter-date2').val();
                    oTable.fnSettings().aoColumns[11].nTh.innerHTML = 'Revenue2  '+$('#filter-date2').val(); 
                <?php endif;?>
                if(filter == 'never_live_3' || filter == 'never_live_10'){ $('#block_prev_live').css('display', 'block'); }
                else{ $('#block_prev_live').css('display', 'none');  }
                
                $('#filter').change(function(){ 
                
                    filter = $('#filter').val(); 
                    
                    if(filter == 'never_live_3' || filter == 'never_live_10'){ $('#block_prev_live').css('display', 'block'); }
                                            else{ $('#block_prev_live').css('display', 'none');  }
                    
                    oTable.fnClearTable(); 
                    display('block'); 
                });

                $('#filterCategory').change(function(){oTable.fnClearTable(); display('block'); });
                $('#accounts').change(function(){ accounts = $('#accounts').val(); oTable.fnClearTable(); display('block'); });
                $('#filterSize').change(function(){ filterSize = $('#filterSize').val(); oTable.fnClearTable(); display('block'); });
                //$('#adx_approve_show').change(function(){ filterAdxApprove = ($('#adx_approve_show:checked').val() ? 1 : 0); oTable.fnClearTable(); display('block'); });
                //$('#users_filter input').keyup(function(){ if($('#adx_approve_show:checked').val()){ filterAdxApprove = 0; $('#adx_approve_show').removeAttr('checked'); } });
                $('#filterPrevNotif').change(function(){ filterPrevNotif = ($('#filterPrevNotif:checked').val() ? 1 : 0); oTable.fnClearTable(); display('block'); });
                $('#filterValue').change(function(){ filterValue = $('#filterValue').val(); oTable.fnClearTable(); display('block'); });
                
                $('#filter-date').change(function(){ 
                    
                    filterDate1 = $('#filter-date').val(); 
                    oTable.fnClearTable(); 
                    display('block'); 
					
					/*
                    var date1 = new Date(filterDate1);   
                    date1.setDate(date1.getUTCDate());
                    date1 = date1.format("m/d/yy");
                    */
                    var date1 = filterDate1;
                    /*day2ago.setDate(day2ago.getDate() - 2);*/    
                    
                    oTable.fnSettings().aoColumns[4].nTh.innerHTML = 'Impres1 '+date1;   
                    oTable.fnSettings().aoColumns[10].nTh.innerHTML = 'Revenue1  '+date1;
                });
                
                $('#filter-date2').change(function(){ 
                    
                    filterDate2 = $('#filter-date2').val(); 
                    oTable.fnClearTable(); 
                    display('block'); 
                    
                    /*              
                    var date2 = new Date(filterDate2);
                    date2.setDate(date2.getUTCDate());
                    date2 = date2.format("m/d/yy");                    
                    */
                    
                    var date2 = filterDate2;
                    
                    oTable.fnSettings().aoColumns[5].nTh.innerHTML = 'Impres2 '+date2;
                    oTable.fnSettings().aoColumns[8].nTh.innerHTML = 'Denied Impres '+date2;
                    oTable.fnSettings().aoColumns[9].nTh.innerHTML = 'Impres avg7day '+date2;
                    oTable.fnSettings().aoColumns[11].nTh.innerHTML = 'Revenue2  '+date2;
            
                });
                
                $('#siteType').change(function(){siteType = $('#siteType').val(); if(siteType==8) $("#publisherId").css('display', 'block'); else $("#publisherId").css('display', 'none'); oTable.fnClearTable(); display('block'); });

                $('#publisherId').change(function(){publisherId = $('#publisherId').val(); oTable.fnClearTable(); display('block'); });
                                    
        });
  
function updateInfo(action, name, id, color)
{   
    var popup=prompt('Your Name:',name)
    
    if(popup){
        location.href = '/administrator/sites/update/act/'+action+'/name/'+popup+'/id/'+id+'/color/'+color;
    }else{
        return false;
    }
}

function getCsv(id){
    
    $('#csv_'+id).html('loading...');
    
    $.ajax({ url : '/administrator/ajax/csv',
                       data : { id : id },
                       type : "POST",
                       dataType : "json",

             success : function(response) { 

                   if(response.result.status){ 

                      $('#csv_'+id).html('<a href="'+response.result.file+'">download</a>');

                   } else { 
                   
                      $('#csv_'+id).html('not found');
                   
                   }

               },
               
             error : function(){ $('#csv_'+id).html('error'); }
     });    
}

function getAbsEcpm(SiteID){

    display('block');
    
    $.ajax({ url : '/administrator/ajax/get-abs-ecpm',
                       data : { SiteID : SiteID },
                       type : "POST",
                       dataType : "json",

             success : function(response) { 

                   display('none');
             },
               
             error : function(){ alert('Ajax Error! please try again.'); display('none'); }
     });  
}

function loginUser(id){ 

    location.href='/administrator/index/auth/id/'+id;
    
}

function showNotApproved(siteID){
    
    $.fancybox({
            'width'	: '75%',
            'height'	: '75%',
            'href'      : '/administrator/url/index/id/'+siteID,
            'autoScale'    	: false,
            'transitionIn'	: 'none',
            'transitionOut'	: 'none',
            'type'		: 'iframe'
    }); 
}

function display(status)
{
    $('#mask').css('display', status);
    $('#loading').css('display', status);         
}

function setOrangeStatus(id)
{
    $.fancybox({
            'width' : '80%',
            'height': '85%',
            'href'  : '/administrator/sites/mail-ever-live/id/'+id,
            'autoScale'     : false,
            'transitionIn'  : 'none',
            'transitionOut' : 'none',
            'type'	    : 'iframe',
            'onClosed'      : function(){ oTable.fnClearTable(); }
    });    
}

function setGreyStatus(id)
{
    $.fancybox({
            'width' : '80%',
            'height': '85%',
            'href'  : '/administrator/sites/mail-ever-live/id/'+id+'/never/10',
            'autoScale'     : false,
            'transitionIn'  : 'none',
            'transitionOut' : 'none',
            'type'	    : 'iframe',
            'onClosed'      : function(){ oTable.fnClearTable(); }
    });    
}

function editColumn()
{
    $.fancybox({
            'width' : '50%',
            'height': '85%',
            'href'  : '/administrator/sites/approved-column',
            'autoScale'     : false,
            'transitionIn'  : 'none',
            'transitionOut' : 'none',
            'type'	    : 'iframe',
            'onClosed'      : function(){ location.reload(); }
    });    
}

function mailContact(PubID)
{
    $.fancybox({
        'width'	: '75%',
        'height'	: '80%',
        'href'          : '/administrator/sites/contact/PubID/'+PubID,
        'autoScale'    	: false,
        'transitionIn'	: 'none',
        'transitionOut'	: 'none',
        'type'		: 'iframe',
        'onClosed'      : function(){ oTable.fnClearTable(); }
    }); 
}

function number_format( number, decimals, dec_point, thousands_sep ) {	// Format a number with grouped thousands
	// 
	// +   original by: Jonas Raoni Soares Silva (http://www.jsfromhell.com)
	// +   improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
	// +	 bugfix by: Michael White (http://crestidg.com)

	var i, j, kw, kd, km;

	// input sanitation & defaults
	if( isNaN(decimals = Math.abs(decimals)) ){
		decimals = 2;
	}
	if( dec_point == undefined ){
		dec_point = ",";
	}
	if( thousands_sep == undefined ){
		thousands_sep = ".";
	}

	i = parseInt(number = (+number || 0).toFixed(decimals)) + "";

	if( (j = i.length) > 3 ){
		j = j % 3;
	} else{
		j = 0;
	}

	km = (j ? i.substr(0, j) + thousands_sep : "");
	kw = i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thousands_sep);
	//kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).slice(2) : "");
	kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).replace(/-/, 0).slice(2) : "");


	return km + kw + kd;
}

function getClientWidth()
{
  return document.compatMode=='CSS1Compat' && !window.opera?document.documentElement.clientWidth:document.body.clientWidth; 
}

</script>


<div id="dialog-form" title="Optimization Values">
	<form>
		<fieldset>
			<label for="optimization_value">Potential Additional Daily Revenue:</label><br/>
			$<input type="text" name="optimization_value" id="optimization_value" class="text ui-widget-content ui-corner-all" /><br/>
			<label for="optimization_notes">Notes:</label><br/>
			<textarea rows="8" cols="20" type="text" name="optimization_notes" id="optimization_notes" value="" class="text ui-widget-content ui-corner-all"></textarea>
		</fieldset>
	</form>
</div>


<h1>Approved Websites</h1>
<div class="contUsL" style="width: 850px;">
<h2>Total sites live: <span id="count-live"></span></h2>

<p>
    <a href="/administrator/sites/live" style="margin-left: 55px;">View Daily Stats</a>
    &nbsp;&nbsp;&nbsp;&nbsp;    
    <a onClick="editColumn()" style="cursor: pointer;">Edit Columns</a>
    
    <!--<input type="checkbox" name="adx_approve_show" id="adx_approve_show" value="1" checked style="background: none; height: 15px; width: 20px; margin-left: 125px;"/>
    <span style="">Show Only AdX Approved Users</span>-->
</p>
<p>
    Date1 &nbsp;- <input type="text" name="filter-date" id="filter-date" style="margin-left: 9px;"/>    
    
    <input type="text" name="filter-date2" id="filter-date2" style="margin-left: 20px; margin-right: 7px;"/> -&nbsp; Date2
    
</p>
<p>
Status: <select style="margin-left: 14px;" id="filter">
	<option value="all">All</option>
	<option value="live">Live Sites</option>
	<option value="no_longer">No Longer</option>
	<option value="never_live">Never Live</option>
    <option value="store_tag_url">Enable Full URL</option>
    <option value="never_live_3">Never Live (3 Days+)</option>
    <option value="never_live_10">Never Live (10 Days+)</option>
	<option value="live_no_passback">Live & No Passbacks</option>
    </select>    
    
    <select id="accounts" style="margin-left: 20px;">
        <?php if($this->dataAuth->role == 'super'):?>
            <option value="-1">All</option>
            <?php foreach($this->contactManager as $iter):?>
                 <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
            <?php endforeach;?>
        <?php else: ?>
        	<option value="-1">Show All Accounts</option>
            <option value="<?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>">Show My Accounts</option>                 
        <?php endif;?>    
    </select>
    
    
<!--<a id="letter_link" href="/administrator/sites/notification">Notifications</a>-->
</p>

<p>  
Category: <select name="filterCategory" id="filterCategory" style="margin-left: -1px;">
            <option value="0">All</option>            
            <?php foreach($this->category as $iter):?>
                 <option value="<?php echo $iter['id']?>"><?php echo $iter['name']?></option>
            <?php endforeach;?>
	  </select>

    <select name="filterSize" id="filterSize" style="margin-left: 20px;">
            <option value="0">Show All AdSize</option>            
            <?php foreach($this->size as $iter):?>
                 <option value="<?php echo $iter['id']?>"><?php echo $iter['name']?></option>
            <?php endforeach;?>
    </select>
</p>
<p>
Site Type: <select id="siteType">
        <option value="all">All</option>
        <option value="4">Google Admanager</option>
        <option value="5">Rubicon</option>
        <option value="6">Burst</option>
        <option value="7">MadX</option>        
        <option value="8">Pubmatic</option>
        <option value="9">Amazon</option>
        <option value="10">PulsePoint</option>
        <option value="1">No Tags</option>
    </select>
    
    <span style="margin-left: 17px;">Impressions Value:</span> 
    <select name="filterValue" id="filterValue" style="margin-left: 10px;">
       <option value="total">Total Impressions</option>            
       <option value="paid" selected>Paid Impressions</option> 
    </select>      
</p>
<p>
    <select name="publisherId" id="publisherId" style="display: none">
        <option value="0">Select publisherId</option>
    	<option value="63240"> - Tier 1 (RJ.Muldoon - 63240)</option>
    	<option value="49542"> - Tier 2 (Pat.Darms - 49542)</option>
    	<option value="68582"> - Tier 3 (YieldGo - 68582)</option>
    </select>	
</p>
    <div id="block_prev_live">   
        <input type="checkbox" name="filterPrevNotif" id="filterPrevNotif" value="1" checked style="background: none; height: 15px; width: 20px; margin-left: 50px; float: left;"/>
        <span style="float: left;">Hide Previously Notified Sites</span>
    </div>
    <!--<div style="float: right; height: 25px; width: 300px; margin-right: 73px; margin-top: 10px;">
        <input type="checkbox" name="export_all" id="export_all" value="1" checked style="background: none; height: 15px; width: 15px; float: left;"/>
        <span style="float: left; margin-left: 3px;">Export all sites</span>
    </div>-->

<div id="tableScroll">
    <div id="tableRotate">
        
<div id="csv_all"></div>
<!--<div id="dsp_all"></div>-->

<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
                    <th width="5%">PID</th>
                    <th width="5%">SID</th>
                    <th width="20%">Website</th>
                    <th width="20%">Contact</th>
                    <th width="10%">Impres yesterday</th>
                    <th width="10%">Impres 2day ago</th>
                    <th width="10%">Impres change</th>
                    <th width="10%">Impres change%</th>
                    <th width="10%">Denied Impres Yesterday</th>
                    <th width="10%">Impres Avg 7day</th>
                    <th width="10%">Revenue Today</th>
                    <th width="10%">Revenue Yesterday</th>
                    <th width="10%">Revenue Change</th>
                    <th width="10%">Revenue Change%</th>
                    <th width="10%">Alexa rank</th>
                    <th width="10%">Top Alexa Country</th>
                    <th width="10%">Live</th>
                    <th width="10%">Ever Live</th>
                    <th width="10%">First Live</th>
                    <th width="10%">Tag Create</th>
                    <th width="20%">Tags</th>
                    <th width="10%">Contact</th>
                    <th width="20%">Optimization Value</th>  
                    <th width="10%">Login</th>
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot>
		<tr>
                    <th>PID</th>
                    <th>SID</th>
                    <th>Website</th>
                    <th>Contact</th>
                    <th>Impres yesterday</th>
                    <th>Impres 2day ago</th>
                    <th>Impres change</th>
                    <th>Impres change%</th>
                    <th>Denied Impres Yesterday</th>
                    <th>Impres Avg 7day</th>
                    <th>Revenue Today</th>
                    <th>Revenue Yesterday</th>
                    <th>Revenue Change</th>
                    <th>Revenue Change%</th>
                    <th>Alexa rank</th>
                    <th>Top Alexa Country</th>
                    <th>Live</th>
                    <th>Ever Live</th>
                    <th>First Live</th>
                    <th>Tag Create</th>                    
                    <th>Tags</th>
                    <th>Contact</th>
                    <th>Optimization Value</th>
                    <th>Login</th>                  
		</tr>
	</tfoot>
</table>
</div>
    
    </div>
</div>

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>