<style>
    #cke_BlacKlist{margin-left: 156px;}
</style>
<script type="text/javascript">
    $(document).ready(function(){
        $('#BlacKlist').ckeditor(function(){ },{
            toolbar : [],
            width : '300px',
            height : '150px',
            language : 'en',
            enterMode : CKEDITOR.ENTER_BR,
            shiftEnterMode : CKEDITOR.ENTER_BR

        });
        var editorServing = $('#BlacKlist').ckeditorGet();
    })
</script>
<br><br>
<form action="" method="post" class="sign-up">
    <div class="contUsL" style="width: 700px;">

        <p><label style="width: 160px;">List: </label> <textarea id="BlacKlist" cols="50" row="5" name="list" >
            <?php
            $list = preg_split('/[\n]/', $this->formValues['list']);
            foreach($list as $key => $iter){

                $iter = trim($iter);
                $BR = isset($list[$key+1]) ? '<br />' : '';

                echo $iter.$BR;

            }?>
        </textarea>
            <?php if(isset($this->formErrors['list'])): ?>
        <ul class="error">
            <?php foreach($this->formErrors['list'] as $errors): ?>
                <li><?php echo $errors ?></li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        </p>

        <p><a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Save</a></p>
        <input type="submit" id="subForm" style="display: none;" />
    </div>
</form>


<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('#topMenu a', {hover: true});
    Cufon.replace('#topMenu a');
    Cufon.replace('.error', {color: 'red'});

</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('.footerBann h5');
    Cufon.replace('.footerBann p');
    Cufon.replace('.footerBann a', {hover: true});
    Cufon.replace('.contactUs h1');
    Cufon.replace('h1');
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
    Cufon.replace('#footCopyr');
    Cufon.replace('.fMenu a');
    Cufon.replace('.contactUs p');
    Cufon.replace('.contUsL label');
    Cufon.replace('#location');
    Cufon.replace('.contBtn p');
    Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
    Cufon.replace('.fMenu h4');
    Cufon.replace('.headquaters');
</script>