<style type="text/css">
    
    
    #main{ display: block; width: 1024px; }
    #main #left{ display: block; float: left; width: 350px; margin-right: 10px; }
    #main #left #mySubmit{ display: block; float: left; height: 28px; width: 160px; font-size: 16px; background-color: #8E8E8E; color: #FFFFFF; cursor: pointer; margin-top: 7px; }
    #main #left #mySubmit:hover{ background-color: #029D44; }
    #main #left #mySubmit span{ float: left; margin: 5px 0px 0px 48px; }
    #main #left #myButton{ display: block; float: left; height: 28px; width: 179px; font-size: 16px; background-color: #8E8E8E; color: #FFFFFF; cursor: pointer; margin-top: 7px; margin-left: 10px; }
    #main #left #myButton:hover{ background-color: #CC0000; }
    #main #left #myButton span{ float: left; margin: 5px 0px 0px 40px; }
    #main #left form textarea { width: 350px; height: 210px; }
    
    #main #right{ display: block; float: left; width: 550px; }
    
    #main #right table { border: 1px solid #DBDFE6; }
    #main #right table #label-mail {}
    #main #right table #value-mail { width: 650px; border: 1px solid #DBDFE6; padding: 5px; }
    #main #right table #label-subject {}
    #main #right table #value-subject { width: 650px; border: 1px solid #DBDFE6; padding: 5px; }
    #main #right table #label-body { vertical-align: top; padding-top: 5px; }
    #main #right table #value-body { width: 650px; border: 1px solid #DBDFE6; padding: 5px; }
    
    
</style>

<script type="text/javascript" src="/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript">

  $(document).ready(function(){
      
      $('#left #reason').keyup(function(){ 
     
           var value = $('#left #reason').val();
                                           
           $('#right #reason-target').html(value.replace(/\n/g,"<br>"));
           
           if(value.length) $('#space').html('<br />');
           else             $('#space').html('');  
               
      });
      
      $('#mySubmit').click(function(){
          
          $('#mail-status').val(1);
          $('#subject').val($('#value-subject').html());
          $('#text').val($('#value-body').html());
          
          $('#left form').submit();
      });
      
      $('#myButton').click(function(){
          
          $('#mail-status').val(0);
          
          $('#left form').submit();
      });
            
  });        

</script>

<?php if(empty($this->message)):?>

<div id="main">
    
    <div id="left">

        <form method="post" action="">
            
            <textarea name="reasen" id="reason" placeholder="enter reason"></textarea>
            <a id="mySubmit"><span>Send Email</span></a><a id="myButton"><span>Don't Send Email</span></a>    
            
            <input type="hidden" name="subject" id="subject" value=""/>
            <input type="hidden" name="text" id="text" value=""/>
            <input type="hidden" name="mail-status" id="mail-status" value=""/>

        </form>
        
    </div>
    <div id="right">
        
        <table>
            
            <tr>
                <td id="label-mail">To:</td>
                <td id="value-mail"><?php echo $this->data->email;?></td>
            </tr>
            <tr>
                <td id="label-subjet">Subject:</td>
                <td id="value-subject"><?php echo $this->data->SiteName;?> Disabled</td>
            </tr>
            <tr>
                <td id="label-body">Body:</td>
                <td id="value-body">Hello,<br /><br />
After reviewing your website, <?php echo $this->data->SiteName?>, we have found it's in violation of one or more of our Terms of Service. As a result, the ad tags have been disabled, and the site is no longer eligible for participation in the MadAds Media publisher network.<br />
<b id="reason-target"></b><br /><span id="space"></span>
If you feel this is a mistake, please feel free to respond to this email.<br /><br />
Regards,<br />
The MadAds Media Publisher Team</td>
            </tr>            
            
        </table>
        
    </div>
    
</div>    

<?php else:?><?php echo $this->message;?><?php endif;?>

