
<style type="text/css">
    
     #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
</style>
<script type="text/javascript" charset="utf-8">

        $(document).ready(function() {   

                var accounts = 'all';
                var filterType = $('#filterType').val();
           
                
                var oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/sites/ajax-deducted',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "filterType", "value": filterType }, { "name": "accounts", "value": accounts } ); },
                        "fnDrawCallback": function( oSettings ) {  },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100
                        ,
                        "aoColumns": [
                            { 
                              "sTitle": "PID",
                              "fnRender": function(obj){ return obj.aData[0]; } 
                            },
                            { 
                              "sTitle": "SID",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Website",
                              "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[1]+'">'+obj.aData[2]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Contact",
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[0]+'">'+obj.aData[3]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Date Disabled",
                              "fnRender": function(obj){ return obj.aData[4] /*? $.format.date(new Date(obj.aData[4]), "yyyy MMM, dd") : ''*/; } 
                            },
                            { 
                              "sTitle": "Deduct Revenue Date",
                              "fnRender": function(obj){ return obj.aData[5] /*? $.format.date(new Date(obj.aData[5]), "yyyy MMM, dd") : ''*/; } 
                            },
                            { 
                              "sTitle": "Network Deducted",
                              "fnRender": function(obj){ return obj.aData[6]; } 
                            },
                            { 
                              "sTitle": "Total Revenue Deducted",
                              "fnRender": function(obj){ return obj.aData[7]; } 
                            },
                            { 
                              "sTitle": "Cron Status",
                              "fnRender": function(obj){ return obj.aData[8]; } 
                            }                    
                                          
                        ],                                                
                        "aaSorting": [[ 2, "asc" ]]
                         
                } );
                
                $('#filterType').change(function(){ filterType = $('#filterType').val(); oTable.fnClearTable(); });
                $('#accounts').change(function(){ accounts = $('#accounts').val(); oTable.fnClearTable(); });

        } );



function display(status)
{
    $('#mask').css('display', status);
    $('#loading').css('display', status);         
}
        

</script>


<h1>Deducted Revenue</h1>
<div class="contUsL" style="width: 950px;">

<p>
    Site Type: 
    <select id="filterType">
        <option value="all">All</option>
        <option value="4">Google Admanager</option>
        <option value="5">Rubicon</option>
        <option value="6">Burst</option>
        <option value="7">MadX</option>
        <option value="8">Pubmatic</option>
        <option value="9">Amazon</option>
        <option value="10">PulsePoint</option>
    </select>
    <select id="accounts">
        <option value="all">Show All Accounts</option>
        <option value="my">Show My Accounts</option>
    </select>
</p> 

<br /><br />
<table width="940px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
                    <th width="5%">PID</th>
                    <th width="5%">SID</th>
                    <th width="20%">Website</th>
                    <th width="20%">Contact</th>
                    <th width="15%">Date Disabled</th>
                    <th width="15%">Deduct Revenue Date</th>
                    <th width="15%">Network Deducted</th>
                    <th width="15%">Total Revenue Deducted</th>
                    <th width="10%">Cron Status</th>                   
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot>
		<tr>
                    <th>PID</th>
                    <th>SID</th>
                    <th>Website</th>
                    <th>Contact</th>
                    <th>Date Disabled</th>
                    <th>Deduct Revenue Date</th>
                    <th>Network Deducted</th>
                    <th>Total Revenue Deducted</th>
                    <th>Cron Status</th>                    
		</tr>
	</tfoot>
</table>
</div> 

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
