<link href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<style type="text/css">
    
    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    td.details{ background-color: inherit; border: 2px solid #A19B9E; }  
    #filter-site{ margin-left: 125px; }
    #url-group-site{ width: 900px !important; }
    
    .table-id{ width: 30px !important; }
    .table-name{ width: 250px !important; }
    .table-link{ width: 70px !important; }
    .table-link-big{ width: 100px !important; }
    .table-date{ width: 100px !important; }
    .details{ }
    
    .url-holder{ display: block; width: 950px; }
    .url-item{ display: block; float: left; width: 940px; margin: 1px 0; padding: 3px; border: 1px solid #B7B7B7; }
    .url-name{ display: block; float: left; width: 820px; }
    .url-action{ display: block; float: left; width: 55px; background-color: #B7B7B7; text-align: center; margin-left: 5px; }
    .url-action a{ color: white; font-weight: 600 }
    
</style>
<script type="text/javascript" charset="utf-8">

        var oTable = null;
        var filter = null;
        var filterSite = null;

        $(document).ready(function() {   
            
                filter = $('#filter').val();
                filterSite = $('#filter-site').val();
            
                oTable = $('#url').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "bAutoWidth": false,
                        "sAjaxSource": '/administrator/sites/ajax-get-denied-url',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "filter", "value": filter }, { "name": "filterSite", "value": filterSite } ); },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100
                        ,
                        "aoColumns": [
                            { 
                              "sTitle": "PID",
                              "sClass": "table-id",
                              "fnRender": function(obj){ return obj.aData[0]; } 
                            },
                            { 
                              "sTitle": "SID",
                              "sClass": "table-id",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Website",
                              "sWidth": "250px",
                              "sClass": "table-name",
                              "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[1]+'">'+obj.aData[2]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Contact",
                              "sClass": "table-name",
                              "fnRender": function(obj){ return obj.aData[3]; } 
                            },
                            { 
                              "sTitle": "Blocked URL",
                              "sClass": "table-link",
                              "fnRender": function(obj){ return '<img src="/images/details_open.png">'; } 
                            },
                            { 
                              "sTitle": "Site",
                              "sClass": "table-link-big",
                              "bSortable": false,
                              "fnRender": function(obj){ var name = filterSite=='group' ? 'Hide All Page URLs' : 'Hide Entire Site';
                                                         if(obj.aData[5]) return '<a style="cursor: pointer;" onClick="hideSite(0,\''+obj.aData[1]+'\')">Hidden</a>'; 
                                                                     else return '<a style="cursor: pointer;" onClick="hideSite(1,\''+obj.aData[1]+'\')">'+name+'</a>'; } 
                            },
                            { 
                              "sTitle": "Url",
                              "sClass": "table-link-big",
                              "bSortable": false,
                              "fnRender": function(obj){ var resultUrl = filterSite == 'group' ? '' : encodeURIComponent(obj.aData[9]); 
                                                         if(obj.aData[6]) return '<a style="cursor: pointer;" onClick="hideUrl(0,\''+resultUrl+'\')">Hidden</a>'; 
                                                                     else return '<a style="cursor: pointer;" onClick="hideUrl(1,\''+resultUrl+'\')">Hide Page URL</a>'; } 
                            },
                            { 
                              "sTitle": "Notify",
                              "sClass": "table-link",
                              "bSortable": false,
                              "fnRender": function(obj){ var resultUrl = filterSite == 'group' ? '' : encodeURIComponent(obj.aData[9]); 
                                                         return '<a style="cursor: pointer;" onClick="fancySend('+obj.aData[1]+',\''+resultUrl+'\')">Notify</a>'; } 
                            },                                
                            { 
                              "sTitle": "Date",
                              "sClass": "table-date",
                              "fnRender": function(obj){ return $.format.date(new Date(obj.aData[8]), "yyyy MMM, dd"); } 
                            },        
                            
                        ],                                                
                        "aaSorting": [[8, "desc" ]],
                        "fnDrawCallback": function(oSettings){
                            $("#url tbody td img").click();
                            
                            $('td.details').css('border', '2px');
           
                            if(filterSite=='group') $('td.details').css('border', '0px !important'); 
                                               else $('td.details').css('border', '2px solid #A19B9E');                                               
                            display('none');      
                        }                         
                });       
                
                $('#filter').change(function(){ getFilter(); });
                $('#filter-site').change(function(){ getFilter(); });
                
                $('#url tbody td img').live('click', function () {
                    var nTr = $(this).parents('tr')[0];                
                    if ( oTable.fnIsOpen(nTr) )
                    {
                        /* This row is already open - close it */
                        this.src = "/images/details_open.png";
                        oTable.fnClose( nTr );
                    }
                    else
                    {
                        /* Open this row */
                        this.src = "/images/details_close.png";
                        var objTr = oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
                        objTr.setAttribute('class', nTr.className);
                        objTr.getElementBy
                    }
                } );                
        });
        
        function getFilter()
        {   
            var oldFilter = filter;
            var oldFilterSite = filterSite;
            
            filter = $('#filter').val(); 
            filterSite = $('#filter-site').val();
            
            oTable.fnClearTable();  

            $('td.details').css('border', '2px');

            if(filter=='pending'){ 
                oTable.fnSetColumnVis(5,false, false);
                oTable.fnSetColumnVis(7,false, false);
            }else if(oldFilter=='pending'){ 
                oTable.fnSetColumnVis(5,true, false);
                oTable.fnSetColumnVis(7,true, false);                        
            }             
            if(filterSite=='group'){ 
                $('td.details').css('border', '0px !important');
                oTable.fnSetColumnVis(6,false, false);
                oTable.fnSetColumnVis(7,false, false);
            }else if(oldFilterSite=='group'){ 
                oTable.fnSetColumnVis(6,true, false);
                oTable.fnSetColumnVis(7,true, false);                        
            }             
        }
        
        function hideUrl(value, url)
        {
            display('block'); 
            
            url = decodeURIComponent(url);
            
            $.ajax({ url : '/administrator/ajax/denied-url-hide',
                         data : { url : url, value : value },
                         async: true,
                         type: "POST",
                         dataType : "json",

                 success : function(response) { 

                     oTable.fnClearTable();  

                 }, error : function(){ display('none'); alert('ajax error'); }
            });
        }
        
        function hideSite(value, SiteID)
        {
            display('block'); 
            
            $.ajax({ url : '/administrator/ajax/denied-site-hide',
                         data : { SiteID : SiteID, value : value },
                         async: true,
                         type: "POST",
                         dataType : "json",

                 success : function(response) { 

                     oTable.fnClearTable();

                 }, error : function(){ display('none'); alert('ajax error'); }
            });
        }
        
        function display(status)
        {
            $('#mask').css('display', status);
            $('#loading').css('display', status);         
        }


function fnFormatDetails ( oTable, nTr )
{
    var aData = oTable.fnGetData( nTr );
    var SiteID = aData[1];
    var sOut = aData[9];  
    
    var result = '';
    
    if(filterSite == 'group'){
    
        if(sOut){
    
            var arrUrl = sOut.split(';;');    

            if(arrUrl.length){

                result += '<div class="url-holder">';

                $.each(arrUrl ,function(key, iter){

                    var tmp = iter.split('::');

                    var hiden = parseInt(tmp[0]);
                    var url = tmp[1];

                    if(hiden) result += '<div class="url-item"><div class="url-name">'+url+'</div><div class="url-action"><a style="cursor: pointer;" onClick="hideUrl(0,\''+encodeURIComponent(url)+'\')">Hidden</a></div><div class="url-action"><a style="cursor: pointer;" onClick="fancySend('+SiteID+',\''+encodeURIComponent(url)+'\')">Notify</a></div></div>';
                         else result += '<div class="url-item"><div class="url-name">'+url+'</div><div class="url-action"><a style="cursor: pointer;" onClick="hideUrl(1,\''+encodeURIComponent(url)+'\')">Hide Url</a></div><div class="url-action"><a style="cursor: pointer;" onClick="fancySend('+SiteID+',\''+encodeURIComponent(url)+'\')">Notify</a></div></div>'; 

                 }); result += '</div>';

             }
         }
         
      } else result = sOut;
                            
    return result;
}

function fancySend(id, url)
{   
   $.fancybox({
		'width'	: '75%',
		'height': '75%',
                'href'  : '/administrator/sites/send/?id='+id+'&url='+url,
                'autoScale'     : false,
                'transitionIn'  : 'none',
		'transitionOut'	: 'none',
		'type'		: 'iframe',
                'onClosed'	: function(){ if(confirm("Update table?")){ oTable.fnClearTable(); display('block'); }  }
   });    
}
</script>
<h1>Banned URLs</h1>
<div class="contUsL" style="width: 850px;">
<p>
   <select id="filter">
	<option value="all">All</option>
	<option value="hide" selected>Need To Review</option>
	<option value="hidden">Hidden</option>
        <option value="pending">Pending Correction</option>
   </select>
    
   <select id="filter-site">
	<option value="group" selected>Group By Site</option>
	<option value="list">List All URLs</option>
   </select>
</p>
    
<br /><br />
<table cellpadding="0" cellspacing="0" border="0" class="display" id="url">
	<thead>
		<tr>
                    <th>PID</th>
                    <th>SID</th>
                    <th>Website</th>
                    <th>Contact</th>
                    <th>Blocked URL</th>
                    <th>Site</th>
                    <th>Url</th>
                    <th>Notify</th>
                    <th>Date</th>
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot>
		<tr>
                    <th>PID</th>
                    <th>SID</th>
                    <th>Website</th>
                    <th>Contact</th>
                    <th>Blocked URL</th>
                    <th>Site</th>
                    <th>Url</th>
                    <th>Notify</th>
                    <th>Date</th>
		</tr>
	</tfoot>
</table>
</div> 

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
