
<script type="text/javascript">
    
    $(document).ready(function(){     
        
        var oTable = $('#users').dataTable({});
        
    });
        
</script>

<h1>Report Generation Payments Due</h1>
<br /><br />
<div class="contUsL" style="width: 750px;">
    <table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
        <thead>
            <tr>
                <th width="40%">Date</th>
                <th width="20%">Year</th>
                <th width="20%">Month</th>
                <th width="20%">Status</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $iter):?>
                <tr>
                    <td><?php echo $iter->date?></td>
                    <td><?php echo $iter->year;?></td>
                    <td><?php echo $iter->month;?></td>
                    <td><?php echo $iter->getStatus($this->time);?></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
