<?php $this->headScript()->offsetSetFile(18,$this->baseUrl().'/js/jquery.fileDownload.js', 'text/javascript');?>
<style>
#csv_all
{
	position: relative;
	width: 24px;
	height: 24px;
	cursor: pointer;
	float: right;
	top: 45px;
	background-image: url(/images/csv-24.gif);
	z-index: 9999999;
}
</style>
<script type="text/javascript" charset="utf-8">
		var last_server_response = new Array();
		var sending_data;
        $(document).ready(function() {

			$("#csv_all").click(function()
					{
						window.sending_data = new Array();
						for(var i = 0; i < window.last_server_response.length; i++ )
						{
							var item = [
										window.last_server_response[i][0],
										window.last_server_response[i][1],
										window.last_server_response[i][2],
										window.last_server_response[i][3],
										window.last_server_response[i][4],
										window.last_server_response[i][5],
										window.last_server_response[i][6],
										window.last_server_response[i][7],
										window.last_server_response[i][8],
										window.last_server_response[i][9],
										window.last_server_response[i][10]
										];
							window.sending_data.push(item);
						}
						if(window.sending_data.length > 0)
						{
							var sending_header = [
								  					 'PID',
								  					 'SID',
								  					 'Website',
								  					 'Contact',
								  					 ''+$('#date1').val()+'',
								  					 ''+$('#date2').val()+'',
								  					 'Impress Change',
								  					 'Alexa Rank',
								  					 'Live',
								  					 'EverLive',
								  					 'DFP'
							  					 ];
						    $.fileDownload('/administrator/ajax/ajax-make-csv', {
						        httpMethod: "POST",
								data: 
								{
									csv_filename: "impress_stats",
									csv_header: JSON.stringify(sending_header),
									csv_data: JSON.stringify(window.sending_data)
								}
						    });
						}
						else
						{
							alert('Empty table');
						}
					});

               
            
        $( ".datepicker" ).datepicker({
                        showOn:'focus',
                        'dateFormat'  : "yy-mm-dd"
                        })	
            
                var countLive = 0;            
                var filter = $('#filter').val();
                var filterType = $('#filterType').val();
                var date1 = $('#date1').val();
                var date2 = $('#date2').val();
                <?php if($this->dataAuth->role == 'super'):?>
                    var accounts = $('#accounts').val();
                <?php else:?>
                    var accounts = <?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>;
                <?php endif;?>    
				var impress = $('#impress').val();
				
                var oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/sites/ajax-stats',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "filter", "value": filter }, { "name": "date1", "value": date1 }, { "name": "date2", "value": date2 }, { "name": "filterType", "value": filterType }, { "name": "accounts", "value": accounts }, { "name": "impress", "value": impress } ); },
                        "fnDrawCallback": function( oSettings ) { $('#count-live').html(countLive); countLive = 0; },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        'fnServerData' : function(sSource, aoData, fnCallback ){
                            $.ajax({
                                'dataType': 'json',
                                'type': 'GET',
                                'url': sSource,
                                'data': aoData,
                                'success': [fnCallback,function(data)
                                {
                                	window.last_server_response = data.aaData;
                                }]
                            });
                        },
                        "iDisplayLength": 100
                        ,
                        "aoColumns": [
                            { 
                              "sTitle": "PID",
                              "fnRender": function(obj){ return obj.aData[0]; } 
                            },
                            { 
                              "sTitle": "SID",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Website",
                              "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[1]+'">'+obj.aData[2]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Contact",
                              "fnRender": function(obj){ return obj.aData[3]; } 
                            },
                            { 
                              "sTitle": date1,
                              "fnRender": function(obj){ return obj.aData[4]; } 
                            },
                            { 
                              "sTitle": date2,
                              "fnRender": function(obj){ return obj.aData[5]; } 
                            },
                            { 
                              "sTitle": "Impres change",
                              "fnRender": function(obj){ return obj.aData[6]; } 
                            },
                            { 
                              "sTitle": "Alexa rank",
                              "fnRender": function(obj){ return obj.aData[7]; } 
                            },
                            { 
                              "sTitle": "Live",
                              "fnRender": function(obj){ 
                                  
                                  if(obj.aData[8]){ countLive ++; return  '<a href="#" onclick="updateInfo(\'live\', \''+obj.aData[13]+'\', '+obj.aData[1]+', \'red\')"><img src="/images/status-green-check.gif"></a>'; }
                                  else            {               return  '<a href="#" onclick="updateInfo(\'live\', \''+obj.aData[13]+'\', '+obj.aData[1]+', \'green\')"><img src="/images/stats-red-x.gif"></a>';    } 
                                  
                                  }
                                                        
                            },
                            { 
                              "sTitle": "Ever Live",
                              "fnRender": function(obj){  
                                  
                                  if(obj.aData[9]) return '<img src="/images/status-green-check.gif"/>';
                                  else             return '<img src="/images/stats-red-x.gif"/>';       } 
                            },
                            { 
                              "sTitle": "DFP",
                              "bSortable": false,
                              "fnRender": function(obj){  
                                  
                                  if(obj.aData[10] == 4) return '<img src="/images/status-green-check.gif">';
                                  else                   return '<img src="/images/stats-red-x.gif">';    }  
                                                 
                            },
                            { 
                              "sTitle": "Login",
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[0]+'" target="_blank">Login</a>'; } 
                            },
                            { 
                              "sTitle": "CSV",
                              "sClass": "csv",
                              "bSortable": false,
                              "fnRender": function(obj){ return '<div id="csv_'+obj.aData[1]+'"><a onClick="getCsv('+obj.aData[1]+')">create</a></div>'; obj.aData[0]; }
                            }
                                          
                        ],                                                
                        "aaSorting": [[ 2, "asc" ]]
                         
                } );
                
                $('#filter').change(function(){ filter = $('#filter').val(); filterType = $('#filterType').val(); date1 = $('#date1').val(); date2 = $('#date2').val(); oTable.fnSettings().aoColumns[4].nTh.innerHTML = date1; oTable.fnSettings().aoColumns[5].nTh.innerHTML = date2; oTable.fnDraw();  });
                $('#filterType').change(function(){ filter = $('#filter').val(); filterType = $('#filterType').val(); date1 = $('#date1').val(); date2 = $('#date2').val(); oTable.fnSettings().aoColumns[4].nTh.innerHTML = date1; oTable.fnSettings().aoColumns[5].nTh.innerHTML = date2; oTable.fnDraw();  });
                $('#date1').change(function () {filter = $('#filter').val(); filterType = $('#filterType').val(); date1 = $('#date1').val(); date2 = $('#date2').val(); oTable.fnSettings().aoColumns[4].nTh.innerHTML = date1; oTable.fnSettings().aoColumns[5].nTh.innerHTML = date2; oTable.fnDraw();});
                $('#date2').change(function () {filter = $('#filter').val(); filterType = $('#filterType').val(); date1 = $('#date1').val(); date2 = $('#date2').val(); oTable.fnSettings().aoColumns[4].nTh.innerHTML = date1; oTable.fnSettings().aoColumns[5].nTh.innerHTML = date2; oTable.fnDraw();});  
                $('#accounts').change(function(){ accounts = $('#accounts').val(); oTable.fnClearTable(); });
                $('#impress').change(function(){ impress = $('#impress').val(); oTable.fnClearTable(); });
        } );
  
function updateInfo(action, name, id, color)
{   
    var popup=prompt('Your Name:',name)
    
    if(popup){
        location.href = '/administrator/sites/update/act/'+action+'/name/'+popup+'/id/'+id+'/color/'+color;
    }else{
        return false;
    }
}

function getCsv(id){
    
    $('#csv_'+id).html('loading...');
    
    $.ajax({ url : '/administrator/ajax/csv',
                       data : { id : id },
                       type : "POST",
                       dataType : "json",

             success : function(response) { 

                   if(response.result.status){ 

                      $('#csv_'+id).html('<a href="'+response.result.file+'">download</a>');

                   } else { 
                   
                      $('#csv_'+id).html('not found');
                   
                   }

               },
               
             error : function(){ $('#csv_'+id).html('error'); }
     });
    
}

function loginUser(id){ 

    location.href='/administrator/index/auth/id/'+id;
    
}

</script>
<h1>Impressions stats</h1>
<div class="contUsL" style="width: 750px;">
<h2>Total sites live: <span id="count-live"></span></h2>
<h2><a href="/administrator/sites/live">View Daily Stats</a></h2>
<p>
    Status: <select id="filter">
	<option value="all">All</option>
	<option value="live">Live Sites</option>
	<option value="no_longer">No Longer</option>
	<option value="never_live">Never Live</option>
        <option value="store_tag_url">Enable Full URL</option>
    </select>
    
    <select id="accounts">
    <?php if($this->dataAuth->role == 'super'):?>
        <option value="-1">All</option>
        <?php foreach($this->contactManager as $iter):?>
             <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
        <?php endforeach;?>
    <?php else: ?>
        <option value="<?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>">Show My Accounts</option>                 
        <option value="-1">Show All Accounts</option>
    <?php endif;?>    
    </select>        
<!--<a id="letter_link" href="/administrator/sites/notification">Notifications</a>-->
</p>
<p>
    Site Type: <select id="filterType">
	<option value="all">All</option>
	<option value="4">Google Admanager</option>
        <option value="5">Rubicon</option>
        <option value="6">Burst</option>
        <option value="7">MadX</option>
        <option value="8">Pubmatic</option>
        <option value="9">Amazon</option>
        <option value="10">PulsePoint</option>
    </select>
    
    Impression: <select id="impress">
	<option value="impress">Total (Sent) Impressions</option>
        <option value="paid">Paid Impressions</option>
    </select>    
</p>
<p>Date 1: <input type="text" class="datepicker" name="date1" value="<?php echo date("Y-m-d", time()-86400) ?>" id="date1" /> Date 2: <input type="text" class="datepicker" name="date2" value="<?php echo date("Y-m-d", time()-172800) ?>" id="date2" /></p>
<br /><br />
<div id="csv_all"></div>
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
                    <th width="5%">PID</th>
                    <th width="5%">SID</th>
                    <th width="20%">Website</th>
                    <th width="20%">Contact</th>
                    <th width="10%">Date 1</th>
                    <th width="10%">Date 2</th>
                    <th width="10%">Impres change</th>
                    <th width="10%">Alexa rank</th>
                    <th width="10%">Live</th>
                    <th width="10%">Ever Live</th>
                    <th width="10%">DFP</th>
                    <th width="10%">Login</th>
                    <th width="20%">CSV</th>
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot>
		<tr>
                    <th>PID</th>
                    <th>SID</th>
                    <th>Website</th>
                    <th>Contact</th>
                    <th>Date 1</th>
                    <th>Date 2</th>
                    <th>Impres change</th>
                    <th>Alexa rank</th>
                    <th>Live</th>
                    <th>Ever Live</th>
                    <th>DFP</th>
                    <th>Login</th>
                    <th>CSV</th>
		</tr>
	</tfoot>
</table>
</div> 
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>