<script type="text/javascript" charset="utf-8">
jQuery.fn.dataTableExt.oSort['num-html-asc']  = function(a,b) {
    var x = a.replace( /<.*?>/g, "" );
        x = x.replace( /#/g, "" );
    var y = b.replace( /<.*?>/g, "" );
        y = y.replace( /#/g, "" );
    x = parseFloat( x );
    y = parseFloat( y );
    return ((x < y) ? -1 : ((x > y) ?  1 : 0));
};
 
jQuery.fn.dataTableExt.oSort['num-html-desc'] = function(a,b) {
    var x = a.replace( /<.*?>/g, "" );
        x = x.replace( /#/g, "" );
    var y = b.replace( /<.*?>/g, "" );
        y = y.replace( /#/g, "" );
    x = parseFloat( x );
    y = parseFloat( y );
    return ((x < y) ?  1 : ((x > y) ? -1 : 0));
};
        $(document).ready(function() {           
                var oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": -1,
                        "aoColumns": [
                            { "sType": "num-html" },
                            { "sType": "num-html" },
                            null,
                            null,
                            null,
                            null,
                            {"bSortable": false }
                        ],                                                
                        "aaSorting": [[ 2, "asc" ]]
                } );

                $('#dateSel').datepicker({
                	'dateFormat'  : "yy-mm-dd"
                });

                $('.goSite').click(function(){
                	location.href = '/administrator/sites/live/'+$('#dateSel').val();
                });
        } );
        
function updateInfo(action, name, id, color)
{
    var popup=prompt('Your Name:',name)
    
    if(popup){
        location.href = '/administrator/sites/update/act/'+action+'/name/'+popup+'/id/'+id+'/color/'+color;
    }else{
        return false;
    }
}        
</script>
<h1>Live Websites</h1>
<div class="contUsL" style="width: 750px;">
<h2>Total sites live: <?php echo count($this->sites); ?></h2>
<br /><br />
Select date: <input type="text" id="dateSel" value="<?php echo $this->date; ?>" /> 
<br />
<a class="sendMasBtn goSite" style="width: auto; float: left;" href="#">View</a>
<br /><br />
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
			<th width="5%">PID</th>
			<th width="5%">SID</th>
			<th width="30%">Website</th>
			<th width="30%">Contact</th>
            <th width="10%">Live</th>
            <th width="10%">Privacy Policy</th>
            <th width="10%">Login</th>
		</tr>
	</thead>
	<tbody>
<?php if($this->sites): ?>
    <?php foreach($this->sites as $item) :?>
        <tr>
            <td><a href="/administrator/sites/approved/id/<?php echo $item['PubID'] ?>">#<?php echo $item['PubID'] ?></a></td>
            <td><?php echo $item['SiteID']?></td>
            <td><a href="/administrator/sites/view/id/<?php echo $item['SiteID'] ?>"><?php echo $item['SiteName'] ?></a></td>
            <td><?php echo $item['email'] ?></td>
            <td><?php echo $item['live']==1 ? '<a href="#" onclick="updateInfo(\'live\', \''.$item['live_name'].'\', '.$item['SiteID'].', \'red\')"><img src="/images/status-green-check.gif"></a>' : '<a href="#" onclick="updateInfo(\'live\', \''.$item['live_name'].'\', '.$item['SiteID'].', \'green\')"><img src="/images/stats-red-x.gif"></a>' ?></td>
            <td><?php echo $item['privacy']==1 ? '<a href="#" onclick="updateInfo(\'privacy\', \''.$item['privacy_name'].'\', '.$item['SiteID'].', \'red\')"><img src="/images/status-green-check.gif"></a>' : '<a href="#" onclick="updateInfo(\'privacy\', \''.$item['privacy_name'].'\', '.$item['SiteID'].', \'green\')"><img src="/images/stats-red-x.gif"></a>' ?></td>
            <td><a href="#" onclick="location.href='/administrator/index/auth/id/<?php echo $item['user_id']; ?>'">Login</a></td>
        </tr>    
    <?php endforeach; ?>
<?php endif; ?>
	</tbody>
	<tfoot>
		<tr>
			<th>PID</th>
			<th>SID</th>
			<th>Website</th>
			<th>Contact</th>
            <th>Live</th>
            <th>Privacy Policy</th>
            <th>Login</th>
		</tr>
	</tfoot>
</table>
</div> 
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>