<script type="text/javascript" charset="utf-8">

        $(document).ready(function() {   
            
                <?php if($this->dataAuth->role == 'super'):?>
                    var accounts = $('#accounts').val();
                <?php else:?>
                    var accounts = <?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>;
                <?php endif;?>    
                
                var oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/sites/ajax-new',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "accounts", "value": accounts } ); },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100
                        ,
                        "aoColumns": [
                            { 
                              "sTitle": "PID",
                              "fnRender": function(obj){ return '#'+obj.aData[0]; } 
                            },
                            { 
                              "sTitle": "Website",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Contact",
                              "fnRender": function(obj){ return obj.aData[2]; } 
                            },
                            { 
                              "sTitle": "Created",
                              "fnRender": function(obj){ return $.format.date(new Date(obj.aData[3]), "yyyy MMM, dd"); } 
                            },
                            { 
                              "sTitle": "View",
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/sites/viewnew/id/'+obj.aData[4]+'">View</a>'; } 
                            }
                        ],                                                
                        "aaSorting": [[ 0, "asc" ]]
                         
                } );
                
                $('#accounts').change(function(){ accounts = $('#accounts').val(); oTable.fnClearTable();});
        } );  
</script>
<h1>New Websites</h1>
<div class="contUsL" style="width: 750px;">
<p>
    <select id="accounts">
    <?php if($this->dataAuth->role == 'super'):?>
        <option value="-1">All</option>
        <?php foreach($this->contactManager as $iter):?>
             <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
        <?php endforeach;?>
    <?php else: ?>
        <option value="<?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>">Show My Accounts</option>                 
        <option value="-1">Show All Accounts</option>
    <?php endif;?>    
    </select>        
</p>    
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
                    <th width="5%">PID</th>
                    <th width="30%">Website</th>
                    <th width="30%">Contact</th>
                    <th width="25%">Created</th>
                    <th width="10%">View</th>
		</tr>
	</thead>
	<tbody>
	</tbody>
	<tfoot>
		<tr>
                    <th>PID</th>
                    <th>Website</th>
                    <th>Contact</th>
                    <th>Created</th>
                    <th>View</th>
		</tr>
	</tfoot>
</table>
</div> 
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>