		<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>	<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
	<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript" charset="utf-8">
        $(document).ready(function() {           
                var oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": -1,
                        "aoColumns": [
							{"bSortable": false },                                      
                            null,
                            null,
                            {"sType": "numeric" }, 
                            null,
                            null,
                            {"sType": "numeric" },
                            {"sType": "numeric" }, 
                            {"sType": "numeric" }, 
                            {"bSortable": false },
                            {"bSortable": false }
                        ],                                                
                        "aaSorting": [[ 1, "desc" ]],
                        "fnHeaderCallback": function(nHead, aData, iStart, iEnd, aiDisplay){
                            
                            	var iTotal = 0;
                            	for ( var i=0 ; i<aData.length ; i++ ){
                            		iTotal += aData[i][3]*1;
                                }                         
                        		nHead.getElementsByTagName('th')[3].innerHTML = "Revenue (Total: "+Number(iTotal).toFixed(2)+")";
                            }
                } );
                
                $('.goSite').click(function(){
                    var id = $(this).attr('real');
                    var site = $('#siteItem_'+id+' option:selected').val();
                    if(site){
                        location.href = '/administrator/sites/view/id/'+site;
                    }else{
                        return false;
                    }
                })
                
            	$(".fancyFrame").fancybox({
            		'width'				: '75%',
            		'height'			: '75%',
                    'autoScale'     	: false,
                    'transitionIn'		: 'none',
            		'transitionOut'		: 'none',
            		'type'				: 'iframe'
            	});            	

            	$("#GeneretePayment").fancybox({            		
            		'width'				: '30%',
            		'height'			: '30%',
                    'autoScale'     	: false,
                    'transitionIn'		: 'none',
            		'transitionOut'		: 'none',
            		'type'				: 'iframe',
            		'onClosed'			: function () { document.location = '/administrator/sites/payments/'; }
            	});            	
				/*
            	$(".paidComent").fancybox({            		
            		'titlePosition'		: 'inside',
            		'transitionIn'		: 'fade',
            		'transitionOut'		: 'fade',
            		'autoDimensions'	: false,
            		'width'				: 360,
            		'height'			: 200,
            		'onComplete'		: function () { alert($(this).attr('real')); $("#paidDiv").css('display', 'block'); }
            	});     
				*/
            	$(".paidComent").click(function(){
            		$("#PubIDComment").val($(this).attr('real'));
					$.fancybox({
	            		'titlePosition'		: 'inside',
	            		'transitionIn'		: 'fade',
	            		'transitionOut'		: 'fade',
	            		'autoDimensions'	: false,
	            		'width'				: 360,
	            		'height'			: 200,
	            		'href'				: '#paidDiv',
	            		'onComplete'		: function () { $("#paidDiv").css('display', 'block'); },
						'onClosed'			: function () { $("#paidDiv").css('display', 'none'); $("#PubIDComment").val(''); $("#textComment").val(''); }
            					
					});
					return false;
                });       	

				$("#CommentPost").click(function(){
					$("#AjaxLoader").css('display', 'block');
					$.ajax({
						'url'			:  '/administrator/sites/setcoment/year/<?php echo $this->year?>/month/<?php echo $this->month?>/PubID/'+$("#PubIDComment").val(),
						'data'			:  'comment='+$("#textComment").val(),
						'type'			:  'POST',
						'dataType'		:  'json',
						'success'		:   function(data){
								if(data.error){
									alert(data.error);
								}else if(data.status=='OK'){
									$("#Publisher_"+data.PubID).css('background-color', '#02EA2C');
									$("#Publisher_"+data.PubID).html('<a class="sendMasBtn viewpaidComent" style="width: auto;" real="'+data.PubID+'" href="#">Revert</a>');
									$("#AjaxLoader").css('display', 'none');
									$.fancybox.close();
								}else{
									alert("Application ERROR!!!");
								}
							}
					});
					return false;
				});
            	/*
            	$(".viewpaidComent").fancybox({            		
            		'width'				: '50%',
            		'height'			: '50%',
                    'autoScale'     	: false,
                    'transitionIn'		: 'none',
            		'transitionOut'		: 'none',
            		'type'				: 'iframe'
            	});            	
            	*/

				$(".viewpaidComent").live('click', function(){
					$("#PubIDComment").val($(this).attr('real'));
					$.fancybox({
	            		'width'				: '50%',
	            		'height'			: '50%',
	                    'autoScale'     	: false,
	                    'transitionIn'		: 'none',
	            		'transitionOut'		: 'none',
	            		'type'				: 'iframe',
						'href'				: '/administrator/sites/viewcomment/year/<?php echo $this->year?>/month/<?php echo $this->month?>/PubID/'+$("#PubIDComment").val(),
						'onClosed'			: function () { $("#paidDiv").css('display', 'none'); $("#PubIDComment").val(''); $("#textComment").val(''); }
					});
					return false;
				})
            	
            	$(".viewNotes").fancybox({            		
            		'width'				: '50%',
            		'height'			: '50%',
                    'autoScale'     	: false,
                    'transitionIn'		: 'none',
            		'transitionOut'		: 'none',
            		'type'				: 'iframe',
            		'onClosed'			: function () { document.location = location.href; }
            	});            	

            	$(".sendMail").fancybox({            		
            		'width'				: '50%',
            		'height'			: '70%',
                    'autoScale'     	: false,
                    'transitionIn'		: 'none',
            		'transitionOut'		: 'none',
            		'type'				: 'iframe'
            	});            	
            	
        } );
</script>

<h1>Payments Due</h1>
<div class="contUsL" style="width: 750px;">
<p>
    <a href="/administrator/contact/index">Contact Info Changes (<?php echo $this->contact;?>)</a>
</p>    
<p>
    <a href="/administrator/sites/generate/" title="Generate Payment Report" id="GeneretePayment">Generate Payment Report</a>
    <a style="margin-left: 5px;" href="/administrator/sites/generate-report">(view report)</a>
</p>
<p><strong>Year:</strong>
<?php
    for($i=2011; $i<=date("Y"); $i++){
        if($i==date("Y"))
            echo "<a href='".$this->url(array('year'=>$i, 'month'=>date("n")))."'>$i</a>";
        else
            echo "<a href='".$this->url(array('year'=>$i, 'month'=>date("n")))."'>$i</a> | ";
    }
?>
</p>
<p><strong>Month:</strong>
<?php
    for($j=1; $j<=12; $j++){

        if($j == date('n')){
        
            echo "<a href='".$this->url(array('month'=>$j))."'>" .date("F", mktime(0, 0, 0, $j,   date("d"),   date("Y")))."</a>&nbsp;&nbsp;";
            
            if(date("Y")==$this->year) break;
            
        } else {
            
            echo "<a href='".$this->url(array('month'=>$j))."'>" .date("F", mktime(0, 0, 0, $j,   date("d"),   date("Y")))."</a>&nbsp;&nbsp;";
        }
    }
?>

</p>
<p><select onchange="location.href='<?php echo $this->url(array('month'=>$this->month, 'year'=>$this->year, 'filter'=>'')) ?>/'+this.options[this.selectedIndex].value">
	<option value="all" <?php echo $this->filter=='all' ? 'selected="selected"' : ''?>>All</option>
	<option value="paid" <?php echo $this->filter=='paid' ? 'selected="selected"' : ''?>>Paid</option>
	<option value="unpaid" <?php echo $this->filter=='unpaid' ? 'selected="selected"' : ''?>>Unpaid</option>
	<option value="minimum" <?php echo $this->filter=='minimum' ? 'selected="selected"' : ''?>>Under Minimum</option>
        <option value="unpaid_minimum" <?php echo $this->filter=='unpaid_minimum' ? 'selected="selected"' : ''?>>Unpaid (Minimum Met)</option>
</select></p>
<br><br>
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
			<th width="1%"></th>
			<th width="30%">Publisher</th>
            <th width="10%">Email</th>
			<th width="10%">Revenue</th>
			<th width="10%">Payment Profile?</th>
            <th width="10%">Payment Type</th>
            <th width="10%">Minimum Payment</th>
            <th width="5%">$ Carried Over</th>
            <th width="5%">Total Due</th>
            <th width="5%"></th>
            <th width="5%">Note</th>
		</tr>
	</thead>
	<tbody>
<?php if($this->users): ?>
	<?php $totalRevenue = 0;?>
    <?php foreach($this->users as $item):  ?>
    
    <?php
            if(!$item['name'] 
                || !$item['payType'] 
                || (!$item['street1'] && !$item['street2']) 
                || !$item['country'] 
                || !$item['state']
                || !$item['city']
                || !$item['zip']
                || !$item['paymentAmout']
                || !$item['paymentBy']
                || ($item['country'] == 238 ? !$item['w9'] : false)){
                $paymaentInfo = '<a href="/administrator/sites/sendmail/id/'.$item['id'].'" class="sendMail"><img src="/images/stats-red-x.gif"></a>'; 
                $cssrow = 'style="background-color:#D3D3D3"';
            }elseif($item['paymentBy']==2 && !$item['paypalmail']){
                $paymaentInfo = '<a href="/administrator/sites/sendmail/id/'.$item['id'].'" class="sendMail"><img src="/images/stats-red-x.gif"></a>';
                $cssrow = 'style="background-color:#D3D3D3"';
            }elseif($item['paymentBy']==3 && (!$item['bank'] || !$item['bankName'] || !$item['accType'] || !$item['accNumber'] || !$item['confirmAccNumber'] || !$item['routNumber'] || !$item['confirmRoutNumber'])){
                $paymaentInfo = '<a href="/administrator/sites/sendmail/id/'.$item['id'].'" class="sendMail"><img src="/images/stats-red-x.gif"></a>';
                $cssrow = 'style="background-color:#D3D3D3"';
            }elseif($item['paymentBy']==4 && (!$item['bankName2'] || !$item['bankAdress'] || !$item['accName2'] || !$item['accNumber2'] || !$item['swift'] || !$item['iban'])){  
                $paymaentInfo = '<a href="/administrator/sites/sendmail/id/'.$item['id'].'" class="sendMail"><img src="/images/stats-red-x.gif"></a>';
                $cssrow = 'style="background-color:#D3D3D3"';
            }else{
                $paymaentInfo = '<img src="/images/status-green-check.gif">';
                $cssrow = null;
            }    
            
            
            switch($item['paymentBy']){
                case 1:
                    $paymaentType = '<a href="/administrator/sites/userpayment/id/' .$item['id']. '" class="fancyFrame">Check</a>';
                    break;
                case 2:
                    $paymaentType = '<a href="/administrator/sites/userpayment/id/' .$item['id']. '" class="fancyFrame">Paypal</a>';
                    break;
                case 3:
                    $paymaentType = '<a href="/administrator/sites/userpayment/id/' .$item['id']. '" class="fancyFrame">ACH</a>';
                    break;
                case 4:
                    $paymaentType = '<a href="/administrator/sites/userpayment/id/' .$item['id']. '" class="fancyFrame">Wire Transfer</a>';
                    break;
                default:
                    $paymaentType = '';
                    break;
            }
            
            if($item['paymentsComment']){
            	$fontRow='background-color:#02EA2C';
            }elseif($item['total']>=$item['paymentMinimum'] && !$item['paymentsComment']){
            	$fontRow='background-color:#FF0400';
            }elseif($item['total']<$item['paymentMinimum']){
            	$fontRow='background-color:#FFA100';
            }
            else{
            	$fontRow = 'background-color:none;';
            }
            
            if($cssrow){
            	$fontRow='background-color:#D3D3D3';
            }
            
            $revenue = number_format($item['revenue'], 2, ".", "");
            $totalRevenue += $revenue;
    ?>
    		
    
        <tr>
            <td style="<?php echo $fontRow?>" id="Publisher_<?php echo $item['id']?>"><?php echo $item['paymentsComment'] ? '<a class="sendMasBtn viewpaidComent" style="width: auto;" real="'.$item['id'].'" href="#">Revert</a>' : '<a class="sendMasBtn paidComent" style="width: auto;" real="'.$item['id'].'" href="#paidDiv">Paid</a>'?></td>
            <td><?php echo $item['name'] ?>             
            <?php
                $sites = explode(",", $item['sites']);
                if($sites){
                    echo '<select id="siteItem_' .$item['id']. '" style="width: auto;">';
                    foreach($sites as $site){
                        $settings = explode(":", $site);
                        echo "<option value='" .trim($settings[0]). "'>" .$settings[1]. "</option>";
                    }
                    echo '</select>';
                }
             ?>            
            </td>
            <td><?php echo $item['email'] ?></td>
            <td><?php echo $revenue; ?></td>
            <td><?php echo $paymaentInfo ?></td>
            <td><?php echo $paymaentType ?></td>
            <td><?php echo $item['paymentMinimum'] ?></td>
            <td><?php echo number_format($item['carried'], 2, ".", "") ?></td>
            <td><?php echo number_format($item['total'], 2, ".", "") ?></td>
            <td><a href="#" onclick="location.href='/administrator/index/auth/id/<?php echo $item['id']; ?>'">Login</a></td>
            <td><?php echo $item['paymentsNote'] ? '<a href="/administrator/sites/comments/id/'.$item['noteID'].'/year/'.$this->year.'/month/'.$this->month.'/PubID/'.$item['id'].'" class="viewNotes"><img src="/images/status-green-check.gif"></a>' : '<a href="/administrator/sites/comments/id/'.$this->noteID.'/year/'.$this->year.'/month/'.$this->month.'/PubID/'.$item['id'].'" class="viewNotes"><img src="/images/stats-red-x.gif"></a>'?></td>
        </tr>    
    <?php endforeach; ?>
<?php endif; ?>
	</tbody>
	<tfoot>
		<tr>
			<th></th>
			<th>Publisher</th>
            <th>Email</th>
			<th>Revenue</th>
			<th>Payment Profile?</th>
            <th>Payment Type</th>
            <th>Minimum Payment</th>
            <th>$ Carried Over</th>
            <th>Total Due</th>
            <th></th>
            <th>Note</th>
		</tr>
	</tfoot>
</table>

<div id="paidDiv">
<img alt="" id="AjaxLoader" src="/images/ajax-loader.gif" style="display: none">
	<form action="#" method="post">
		<input type="hidden" id="PubIDComment" value="" />
		<p>Comment:	
		<textarea rows="7" id="textComment" cols="50"></textarea></p>
		<br><br>
		<a class="sendMasBtn" id="CommentPost" title="" href="#">Save</a>
	</form>
</div>
</div> 
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>