<iframe id="tab-all" src="http://scripts.madadsmedia.com/users-reports/sekindo/index.php" width="750" height="800" />

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('#topMenu a', {hover: true});
    Cufon.replace('#topMenu a');
    Cufon.replace('.error', {color: 'red'});

</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('.footerBann h5');
    Cufon.replace('.footerBann p');
    Cufon.replace('.footerBann a', {hover: true});
    Cufon.replace('.contactUs h1');
    Cufon.replace('h1');
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
    Cufon.replace('#footCopyr');
    Cufon.replace('.fMenu a');
    Cufon.replace('.contactUs p');
    Cufon.replace('.contUsL label');
    Cufon.replace('#location');
    Cufon.replace('.contBtn p');
    Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
    Cufon.replace('.fMenu h4');
    Cufon.replace('.headquaters');
</script>