<style>
    
    #submit
    { 
        background: #8E8E8E;
        border: 1px solid #797979;
        color: #FFFFFF;
        float: right;
        font-size: 16px;
        height: 28px;
        line-height: 28px;
        margin: -1px 3px 0 0;
        text-align: center;
        width: 129px;    
    }
    
    #submit:hover{ background: #DC2323; border: 0 none; }
    
    .errors{ color: #FF0000; font-weight: bold; }
    .errors li{ color: #FF0000; }
    
</style>


<div class="contUsL">

    <h1>Edit Task</h1>
    <br />
    
    <?php if(empty($this->message)):?>

        <?php echo $this->form; ?>
    
    <?php else:?>
    
        <?php echo $this->message; ?>
    
    <?php endif;?>

</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>