<style type="text/css">
    
    #report{ width: 900px; }
    
</style>
<script type="text/javascript">
        
        jQuery(document).ready(function(){
              
             $('#task').dataTable({
                 "bProcessing": true,
                 "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                 "iDisplayLength": -1,
                 "aoColumns": [
                     null,
                     null,
                     null,
                     null,
                     null,
                     null
                 ],
                  "aaSorting": [[ 3, "asc" ]]
             }); 
        });

        
</script>

<h1>Sizes</h1>
<div id="showTable" class="contUsL" style="width: 900px;">
<a href="/administrator/task/add/">Create new Task</a>
<table width="900px" cellpadding="0" cellspacing="0" border="0" class="display" id="task">

    <thead>
        
        <tr>
            <th width="30%">Name</th>
            <th width="40%">Link</th>
            <th width="20%">For</th>
            <th width="10%">Position</th>
            <th></th>
            <th></th>
        </tr>
        
    </thead>
    <tbody>
       
        <?php foreach ($this->dataTask as $iter): ?>
        <tr>
            <td><?php echo $iter['name'] ?></td>
            <td><a tagret="_blank" href="<?php echo $iter['link'] ?>"><?php echo $iter['link'] ?></a></td>
            <td><?php echo $iter['for'] ?></td>
            <td><?php echo $iter['position'] ?></td>
            <td><a href="/administrator/task/edit/id/<?php echo $iter['id']?>">edit</a></td>
            <td><a href="/administrator/task/delete/id/<?php echo $iter['id']?>" onclick="return confirm('Delete this Task?');">delete</a></td>
        </tr>
        <?php endforeach; ?>        

    </tbody>
        
</table>    
    
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
