<div class="contactUs">
                      <h3>
                          <?php if($this->message): ?>
                            <p class="contUsSlog"><?php echo $this->message; ?></p>
                          <?php elseif($this->messageTitle): ?>
                            <p class="contUsSlog"><?php echo $this->messageTitle; ?></p>
                          <?php else: ?>
                            <p class="contUsSlog">Use the form below to retrieve your password</p>
                          <?php endif; ?>
                      </h3>
    <?php if(!$this->message): ?>
                <div id="contForm">

            <form method="post" class="sign-up" style="width: 430px;">
            <div class="contUsL">
            <?php if($this->message): ?>
                <p style="color: red;"><?php echo $this->message ?></p>
            <?php endif; ?>    
            
            <p><label>Password:</label><input type="password" name="password" /></p>
                <?php if($this->formErrors['password']): ?>
                    <ul class="error"> 
                    <?php foreach($this->formErrors['password'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>    
            
            <p><label>Verify Password:</label><input type="password" name="passwordConfirm" /></p>
                <?php if($this->formErrors['passwordConfirm']): ?>
                    <ul class="error">
                    <?php foreach($this->formErrors['passwordConfirm'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>    
            
            </div>
            
                    <div class="contBtn"> 
                    <a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Submit</a>
                    </div>
            <input type="submit" id="subForm" style="display: none;" />            
            
            </form>        
       </div>
    <?php endif; ?>
</div>


<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
    Cufon.replace('.error', {color: 'red'});	    

</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
