<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<style type="text/css">
    
    #report{ width: 1124px; }
    
    a.link{ cursor: pointer; }
    
    #showResult{ display: none; }
    
    #showResult table{
        width: 750px;
        border-collapse: collapse;
        border: 1px #B7B7B7 solid;
    }
    
    #showResult table tr td{

        border: 1px #B7B7B7 solid;
        font-size: 14px;
        font-family: Arial,Helvetica,sans-serif;
        padding: 5px;
        width: 50%;
    }
    
    #showResult table tr th{
        
        border: 1px #B7B7B7 solid;
        font-size: 16px;
        font-family: Arial,Helvetica,sans-serif;
        padding: 5px;
        width: 50%;
        text-align: center;
    }
    
    #showResult table tr td.ok{ color: green; }
    #showResult table tr td.error{ color: red; }
    
    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #message{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #message span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
    #revert-tag{ cursor: pointer; font-size: 14px; color: red; }
    
</style>
<script type="text/javascript">

var oTable4 = null;

jQuery.fn.dataTableExt.oSort['num-html-asc']  = function(a,b) {
    var x = a.replace( /<.*?>/g, "" );
        x = x.replace( /#/g, "" );
    var y = b.replace( /<.*?>/g, "" );
        y = y.replace( /#/g, "" );
    x = parseFloat( x );
    y = parseFloat( y );
    return ((x < y) ? -1 : ((x > y) ?  1 : 0));
};
 
jQuery.fn.dataTableExt.oSort['num-html-desc'] = function(a,b) {
    var x = a.replace( /<.*?>/g, "" );
        x = x.replace( /#/g, "" );
    var y = b.replace( /<.*?>/g, "" );
        y = y.replace( /#/g, "" );
    x = parseFloat( x );
    y = parseFloat( y ); 
    return ((x < y) ?  1 : ((x > y) ? -1 : 0));
};

$(document).ready(function(){
    <?php if($this->dataAuth->role == 'super'):?>
        var accounts = $('#accounts').val();
    <?php else:?>
        var accounts = <?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>;
    <?php endif;?>    
    
    var live = $('#live').val();
    
    var oTable1 = $('#siteMissing').dataTable( {
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": '/administrator/burst/ajax-burst-requests',
            "fnServerParams": function ( aoData ) {  aoData.push( { "name": "accounts", "value": accounts }, { "name": "live", "value": live } ); },
			"fnCreatedRow": function (nRow, aData, iDataIndex) {
			        $(nRow).find("td:nth-child(4)").attr('id', 'process_' + aData[11]);
			   		},            
            "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
            "iDisplayLength": 100,
            "aoColumns": [
                { 
                  "sType": "num-html", 
                  "sTitle": "ID#",
                  "fnRender": function(obj){return obj.aData[0];}
                  
                },
                { 
                  "sTitle": "Website",
                  "sClass": "SiteName",
                  "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[2]+'">'+obj.aData[1]+'</a>'; }
                },
                { 
                  "sTitle": "Pubmatic API",  
                  "bSortable": false,
                  "fnRender": function(obj){ return '<span id="api_'+obj.aData[3]+'" class="sendMasBtn link createSite" style="width: 60px; cursor: pointer">Create</span>'; }
                },
                { 
                  "sTitle": "Processed",  
                  "bSortable": false,
                  "fnRender": function(obj){ 
	                  	if(obj.aData[12]){
		                  	return '<img src="/images/status-green-check.gif">';
	                  	}else{
		                  	if(obj.aData[4]==1) return '<img src="/images/status-green-check.gif">';
		                  	else if(obj.aData[4]==2) return '<img src="/images/stats-orange-x.png">';
		                  	else return ''; 		                  	
	                  	}
	                  }
                },
                {  
                  "bSortable": false,  
                  "fnRender": function(obj){ return '<a onclick="fancySend('+obj.aData[11]+'); return false;" href="#">Deny</a>'; }
                },
                {  
	              "sTitle": "Date",  
                  "bSortable": true,  
                  "fnRender": function(obj){ if(obj.aData[5]){ var datArr = obj.aData[5].split('-'); var tmpArr = datArr[2].split(' '); return datArr[1]+'/'+tmpArr[0]+'/'+datArr[0]; }else{ return '';}; }
                  //"fnRender": function(obj){ return obj.aData[5]; }
                },
                {  
	              "sTitle": "Tags Live",  
                  "bSortable": true,  
                  "fnRender": function(obj){
		                  		if(obj.aData[6]==1) return '<img src="/images/status-green-check.gif">';
			                  	else return '<img src="/images/stats-red-x.gif">'; 		                  	
							}
                },
                {  
	              "sTitle": "Impressions",  
                  "bSortable": true,  
                  "fnRender": function(obj){
		                  		if(obj.aData[7]) return obj.aData[7];
			                  	else return ''; 		                  	
							}
                },  
                { 
                  "sTitle": "Alexa rank",
                  "bVisible": true,
                  "fnRender": function(obj){ return number_format(obj.aData[8],0,'.',','); } 
                },
                { 
                  "sTitle": "Top Alexa Country",
                  "bVisible": true,
                  "fnRender": function(obj){ return number_format(obj.aData[9],0,'.',',')+'('+obj.aData[10]+')'; } 
                },                                                          
                {  
	              "sTitle": "Login",  
                  "bSortable": false,  
                  "fnRender": function(obj){
		                  		return '<a href="/administrator/index/auth/id/'+obj.aData[13]+'" target="_blank">Login</a>'; 		                  	
							}
                }                
            ],
            "aaSorting": [[ 5, "desc" ]]
    });
            
    $('#accounts').change(function(){ accounts = $('#accounts').val(); oTable1.fnClearTable();});

    $('#live').change(function(){ live = $('#live').val(); oTable1.fnClearTable(); });

	$(".createSite").live("click", function(){
		createSite($(this).attr('id'), $(this).attr('id').replace("api_", ""));		
	});

    $("#fancybox-close").click(function(){
        oTable1.fnClearTable();
    });                
})

function redirect(){ document.location.reload(); }

function processing()
{
    $('#mask').css("display","block");
    $('#message').css("display","block");
}

function unProcessing()
{
    $('#mask').css("display","none");
    $('#message').css("display","none");   
}

function createSite(buttonID, siteID)
{   
   $.fancybox({
		'width'	: '75%',
		'height': '75%',
                'href'  : '/administrator/pubmatic/add-site/id/'+siteID+'/new_burst/1',
                'autoScale'     : false,
                'transitionIn'  : 'none',
		'transitionOut'	: 'none',
		'type'		: 'iframe',
		'onStart': function(){setprocess(siteID);}
   });    
}

function fancySend(id)
{   
   $.fancybox({
		'width'	: '75%',
		'height': '75%',
                'href'  : '/administrator/burst/deny/id/'+id,
                'autoScale'     : false,
                'transitionIn'  : 'none',
		'transitionOut'	: 'none',
		'type'		: 'iframe'
   });    
}      

function setprocess(id)
{
	$.post("/administrator/burst/update-status/", { id: id } );
	$("#process_"+id).html('<img src="/images/status-green-check.gif">');
}

function number_format( number, decimals, dec_point, thousands_sep ) {	// Format a number with grouped thousands
	// 
	// +   original by: Jonas Raoni Soares Silva (http://www.jsfromhell.com)
	// +   improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
	// +	 bugfix by: Michael White (http://crestidg.com)

	var i, j, kw, kd, km;

	// input sanitation & defaults
	if( isNaN(decimals = Math.abs(decimals)) ){
		decimals = 2;
	}
	if( dec_point == undefined ){
		dec_point = ",";
	}
	if( thousands_sep == undefined ){
		thousands_sep = ".";
	}

	i = parseInt(number = (+number || 0).toFixed(decimals)) + "";

	if( (j = i.length) > 3 ){
		j = j % 3;
	} else{
		j = 0;
	}

	km = (j ? i.substr(0, j) + thousands_sep : "");
	kw = i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thousands_sep);
	//kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).slice(2) : "");
	kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).replace(/-/, 0).slice(2) : "");


	return km + kw + kd;
}
</script>
<link href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" rel="stylesheet" type="text/css" />
<h1>Burst Requests</h1>
<div id="showTable" class="contUsL" style="width: 910px;">
    
<p>
    <select id="accounts">
    <?php if($this->dataAuth->role == 'super'):?>
        <option value="-1">All</option>
        <?php foreach($this->contactManager as $iter):?>
             <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
        <?php endforeach;?>
    <?php else: ?>
        <option value="<?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>">Show My Accounts</option>                 
        <option value="-1">Show All Accounts</option>
    <?php endif;?>    
    </select>        
</p>     
        
<p>
Status: <select style="margin-left: 14px;" id="live">
	<option value="all">All</option>
	<option value="live">Live Sites</option>
	<option value="no_longer">No Longer</option>
</select>    
</p>        
        <table width="870px" cellpadding="0" cellspacing="0" border="0" class="display" id="siteMissing">
        	<thead>
        		<tr>
                            <th width="10%">ID #</th>
                            <th width="35%">Website</th>
                            <th width="7%">Create Placements</th>
                            <th width="7%">Processed</th>
                            <th width="5%"></th>
                            <th width="7%">Date</th>                            
                            <th width="7%">Tags Live</th>                                                        
                            <th width="7%">Impressions</th>                                                        
                            <th width="7%">Alexa rank</th>                                                        
                            <th width="7%">Top Alexa Country</th>                                                        
                            <th width="7%">Login</th>                                                        
        		</tr>
        	</thead>
        	<tbody></tbody>
        	<tfoot>
        		<tr>
                            <th>ID #</th>
                            <th>Website</th>
                            <th>Create Placements</th>
                            <th>Processed</th>
                            <th></th>
                            <th>Date</th>         
                            <th>Tags Live</th>                                                                                                                                   
                            <th>Impressions</th> 
                            <th>Alexa rank</th>                                                        
                            <th>Top Alexa Country</th>                                                                                                                                                                       
                            <th>Login</th>                                                        
        		</tr>
        	</tfoot>
        </table> 
        <div class="clear"></div>         
                
</div>    
<div id="mask"></div>
<div id="message"><span>processing...</span></div>


<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>