<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<link href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" rel="stylesheet" type="text/css" />
<?php $this->headScript()->offsetSetFile(18,$this->baseUrl().'/js/jquery.jeditable.js', 'text/javascript');?>
<style type="text/css">    
     #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading
    { 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
    #dialog-form
    {
    	font-size: 16px;
    	font-weight: bold;
    	z-index: 999999999;
    }
    
    #dialog-form textarea
    {
	    resize: none;
	    width: 305px;
    }
    
    #optimization_value
    {
    	position: relative;
    	width: 300px;
    	z-index: 999999999;
    }
    
    #csv_all
    {
    	position: relative;
    	width: 24px;
    	height: 24px;
    	cursor: pointer;
    	float: right;
    	top: 60px;
    	background-image: url(/images/csv-24.gif);
    	z-index: 100;
    }
    
    #report
    {
	   background-image: none;
       border-right: solid 1px white;
       border-left: solid 1px #E2E2E2;
    }
    #reportL
    {
	   background-image: none;
       border-right: solid 1px white;
       border-left: solid 1px #E2E2E2;
    }
    .contUsL
    {
	   margin-left: 15px;
    }
    
    #update_rows
    {
    	position: relative;
    	float: right;
    	margin-left: 23px;
    }
       
    .save_btn input
    {
    	float: left;
    } 
    .save_btn button
    {
    	margin-left: 10px;
    	display: inline-block;
    	float: left;
    	cursor: pointer;
    	width: 60px;
    	padding: 0px;
    }
    
    .save_btn
    {
		position: relative;
		margin: 0px;
		padding: 0px;
    }
    
    tr
    {
	    height: 37px; /* or whatever height you need to make them all consistent */
	}
	
	table.display 
	{
		margin: 0 auto;
		width: 1105px;
		clear: both;
		border-collapse: collapse;
		table-layout: fixed;
		word-wrap:break-word;
	}
	
	.select_all, .selected
	{
		border-color: black;
		border-width: 1px;
		border-style: solid;
	}
	
	#cpm_filter
	{
		position: relative;
		width: 190px;
		float: left;
	}
	
	#cpm_filter span, #cpm_filter select
	{
		position: relative;
		display: block;
		float: left;
		width: 80px;
	}
	
	#cpm_filter select
	{
		top: -5px;
	}
	
	#all_cpm
	{
		margin-left: 10px;
		width: 80px;
	}
	
	#updatable
	{
		position: relative;
		top: 5px;
	}


</style>
<script type="text/javascript" charset="utf-8">
var group;
var params;
var revenue;
var site_id;
var cpm_filter = 0;
        $(document).ready(function() 
        {
            function jCancel()
            {
            	oTable.fnDraw();
            } 


            $("#cpm_filter").change(function()
            {
				window.cpm_filter = $("#cpm_filter option:selected").val();
				oTable.fnDraw();
            });
                      
	        $(".datepicker").datepicker({
	            showOn:'focus',
	            'dateFormat'  : "yy-mm-dd"
            });

            $(".save_btn input").live('keyup', function (e) 
            {
                var data_siteid = $(this).parent().parent().attr('data-siteid');
                var data_adsize = $(this).parent().parent().attr('data-adsize');
                var class_name = $(this).parent().parent().attr('class');
                if(class_name == 'impression_data')
                {
                	var impressions = parseFloat($(this).val());
                	var cpm = parseFloat($('.cpm_data[data-siteid="'+data_siteid+'"][data-adsize="'+data_adsize+'"]').html());
                	var revenue = ((impressions * cpm) / 1000).toFixed(2);
                	if(isNaN(revenue))
                		revenue = 0;
                	$('.revenue_data[data-siteid="'+data_siteid+'"][data-adsize="'+data_adsize+'"]').html(revenue);     
                }
                else if(class_name == 'cpm_data')
                {
                	var cpm = parseFloat($(this).val());
                	var impressions = parseFloat($('.impression_data[data-siteid="'+data_siteid+'"][data-adsize="'+data_adsize+'"]').html());
					console.log(cpm);
					console.log(impressions);
                	var revenue = ((impressions * cpm) / 1000).toFixed(2);
                	if(isNaN(revenue))
                    	revenue = 0;
                	$('.revenue_data[data-siteid="'+data_siteid+'"][data-adsize="'+data_adsize+'"]').html(revenue);    
                }
            });	
            
            var date = $('#date').val();
            //var date = '2013-12-19';
            window.group = $('#group_by').val();
              
            var oTable = $('#users').dataTable( {
	            "bProcessing": true,
	            "bServerSide": true,
	            "sAjaxSource": '/administrator/burst/get-ajax',
	            "bAutoWidth": false,
                "fnServerParams": function ( aoData ) 
                { 
                	aoData.push( { "name": "date", "value": date }, { "name": "group", "value": window.group }, { "name": "cpm_filter", "value": window.cpm_filter} );
                	window.params = aoData;
                },            
                "fnDrawCallback": function( oSettings ) 
                {
                    if(window.group == 'size')
	                	$('.total_impression_data, .impression_data, .cpm_data, .revenue_data', oTable.fnGetNodes()).editable('/administrator/burst/update-ajax', 
	                    {
	                		"callback": function( sValue, y ) 
	                		{
	                			var aPos = oTable.fnGetPosition( this );
	                			var json_return = jQuery.parseJSON(sValue);
	                			if(json_return != undefined)
	                			{
									if(json_return.status == 1)
									{
										oTable.fnUpdate( json_return.data, aPos[0], aPos[1] ,false);
									}
									else
									{
										alert('Error');
									}
										oTable.fnDraw();
	                    		}
	                			else
	                				oTable.fnDraw();
	                		},
	                		submitdata : function(value, settings) 
	                		{
	                		     return {
	                    		     		data_type: $(this).attr('data-type'),
	                    		     		site_id: $(this).attr('data-siteid'),
	                    		     		adsize: $(this).attr('data-adsize'),
	                    		     		query_date: date,
	                    		         	value: $('.save_btn input').val(),
	                        		    };
	                		},
	                		submit : 'Save',
	                		cancel : 'Cancel',
	                		width: '50px',
	                		cssclass : "save_btn",
	                		height: "28px",
	                		onreset: jCancel,
	                	});
                },
	            "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
	            "iDisplayLength": 100,
	            "aoColumns": [
	                { 
	                  "sTitle": "Site",
	                  "sWidth": "16%",
	                  "fnRender": function(obj)
	                  { 
						  return obj.aData[0];	
			          } 
	                },
	                { 
	                  "sTitle": "AdSize",
	                  "sWidth": "16%",
	                  "fnRender": function(obj){ return obj.aData[1]; } 
	                },	                
	                { 
	                  "sTitle": "Total Impressions",
	                  "sClass": "total_impression_data",
	                  "sWidth": "16%",
	                  "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
	                        $(nTd).attr('data-siteid', oData[8]);
	                        $(nTd).attr('data-adsize', oData[9]);
	                        $(nTd).attr('data-type', 'total_impression_data');
	                  },
	                  "fnRender": function(obj)
	                  { 
	                  		return obj.aData[2];
	                  } 
	                },
	                { 
		                  "sTitle": "Paid Impressions",
		                  "sClass": "impression_data",
		                  "sWidth": "16%",
		                  "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
		                        $(nTd).attr('data-siteid', oData[8]);
		                        $(nTd).attr('data-adsize', oData[9]);
		                        $(nTd).attr('data-type', 'impression_data');
		                  },
		                  "fnRender": function(obj)
		                  { 
		                  		return obj.aData[3];
		                  } 
		                },
	                { 
	                  "sTitle": "CPM",
	                  "sClass": "cpm_data",
	                  "sWidth": "16%",
	                  "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
	                        $(nTd).attr('data-siteid', oData[8]);
	                        $(nTd).attr('data-adsize', oData[9]);
	                        $(nTd).attr('data-type', 'cpm_data');
	                  },
	                  "fnRender": function(obj)
	                  { 
						    return obj.aData[4];
		              } 	                 
	                },
	                { 
	                  "sTitle": "Revenue",
	                  "sClass": "revenue_data",
	                  "sWidth": "16%",
	                  "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
	                        $(nTd).attr('data-siteid', oData[8]);
	                        $(nTd).attr('data-adsize', oData[9]);
	                        $(nTd).attr('data-type', 'revenue_data');
	                  },
	                  "fnRender": function(obj)
	                  { 
		                  return obj.aData[5]; 
		              } 
	                }
	            ],                                                
	            "aaSorting": [[ 0, "asc" ]],
                "fnHeaderCallback": function(nHead, aData, iStart, iEnd, aiDisplay)
                {
					if(window.group == 'size')
						j = 0;
					else
						j = -1;
	                    var iTotal2 = 0;
	                    var iTotal3 = 0;
	                    var iTotal4 = 0;
	                    var iTotal5 = 0;
	                    for ( var i=0 ; i<aData.length ; i++ )
	                    {
	                            iTotal2 += aData[i][2]*1;
	                            iTotal3 += aData[i][3]*1;
	                            iTotal4 += aData[i][4]*1;
	                            iTotal5 += aData[i][5]*1;
	                    }
	                    nHead.getElementsByTagName('th')[2+j].innerHTML = "Total Impressions<br> (Total: "+Number(iTotal2).toFixed(2)+")";
	                    nHead.getElementsByTagName('th')[3+j].innerHTML = "Paid Impressions<br> (Total: "+Number(iTotal3).toFixed(2)+")";
	                    nHead.getElementsByTagName('th')[4+j].innerHTML = "CPM<br> (Total: "+Number(iTotal4).toFixed(2)+")";
	                    nHead.getElementsByTagName('th')[5+j].innerHTML = "Revenue<br> (Total: "+Number(iTotal5).toFixed(2)+")";
					}
                    
            } );                
            
            $('#date').change(function () 
            {
                date = $('#date').val(); oTable.fnDraw();
            });
            
        	
            $('#group_by').change(function () 
            {
            	window.group = $('#group_by').val(); 
            	if(window.group == 'group')
                {
                    //$("#updatable").css('visibility', 'hidden');
            		oTable.fnSetColumnVis(1,false, false);
				}else
				{
					oTable.fnSetColumnVis(1,true, false);
					//$("#updatable").css('visibility', 'visible');            		         		
				}
            	oTable.fnDraw(); 
            });

            $("#update_rows").click(function()
            {
                if(window.params != undefined)
					$.ajax({
						  type: 'POST',
						  url: '/administrator/burst/update-ajax-all',
						  dataType: 'json',
						  data: 
					      {
							    value : $('#all_cpm').val(),
							    params: window.params
						  },
						  success: function(data)
						  {
						  		oTable.fnDraw();	
						  }
						});
            });

        } );  
        
</script>

<h1>Burst CPM & Revenue</h1>
<div class="contUsL" style="width: 935px;">
<p> Date: <input type="text" class="datepicker" name="date" id="date" value="<?php echo date("Y-m-d"); ?>" />   
<select id="group_by">
	<option value="group">Group by sizes</option>
	<option value="size" selected="selected">Show with sizes</option>
<select/></p><br /><br />

<p id="cpm_filter">
	<span>CPM filter:</span>
	<select id="cpm_filter">
		<option value="0" selected>All</option>
		<option value="0.05">0.05</option>
		<option value="0.10">0.10</option>
		<option value="0.15">0.15</option>
		<option value="0.20">0.20</option>
		<option value="0.25">0.25</option>
		<option value="0.30">0.30</option>
		<option value="0.40">0.40</option>
		<option value="0.50">0.50</option>
		<option value="0.60">0.60</option>
		<option value="0.75">0.75</option>
		<option value="0.85">0.85</option>
		<option value="1.00">1.00</option>
		<option value="1.50">1.50</option>
		<option value="Max Fill">Max Fill</option>
	</select>
</p>
<div id="updatable" style="float: left;">Set The CPM For The Following Sites: <input type="text" id="all_cpm" name="cpm" value="0.00" /><button id="update_rows">Update Rows</button></div>
<br>

<table width="1090px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
            <th>Site</th>
            <th>AdSize</th>
            <th>Total Impressions</th>
            <th>Paid Impressions</th>
            <th>CPM</th>
            <th>Revenue</th>
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot>
		<tr>
            <th>Site</th>
            <th>AdSize</th>            
            <th>Total Impressions</th>
            <th>Paid Impressions</th>
            <th>CPM</th>
            <th>Revenue</th>
		</tr>
	</tfoot>
</table>
<br><br>

</div> 

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
