<style type="text/css">
    
    #report{ width: 900px; }
    
</style>
<script type="text/javascript">
        
        jQuery(document).ready(function(){
              
             $('#table_referral_user').dataTable({
                 "bProcessing": true,
                 "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                 "iDisplayLength": -1,
                 "aoColumns": [
                     null,
                     null,
                     null,
                     null,
                     null,
                     null,
                     null,
                     null,
                     null
                 ],
                  "aaSorting": [[ 7, "asc" ]]
             }); 
        });

        
</script>

<h1>Sizes</h1>
<div id="showTable" class="contUsL" style="width: 950px;">
    <a href="/administrator/sizes/add/">Create new size</a>
<table width="940px" cellpadding="0" cellspacing="0" border="0" class="display" id="table_referral_user">

    <thead>
        
        <tr>
            <th width="7%">id</th>
            <th width="20%">Name</th>
            <th width="7%">Size</th>
            <th width="10%">rp_zonesize</th>
            <th width="15%">rp_account / rp_site / rp_zonesize (Max_Fill)</th>
            <th width="20%">rp_account / rp_site / rp_zonesize (Floor_Tag)</th>
            <th width="15%">rp_account / rp_site / rp_zonesize (Limited)</th>
            <th width="7%">position</th>
            <th width="7%">active</th>
        </tr>
        
    </thead>
    <tbody>
            <?php if($this->sizes): ?>
                <?php foreach ($this->sizes as $size): ?>
        <tr>
            <td><?php echo $size->id ?></td>
            <td><a href="/administrator/sizes/edit/id/<?php echo $size->id?>"><?php echo $size->name ?></a></td>
            <td><?php echo $size->width.'x'.$size->height ?></td>
            <td><?php echo $size->rp_zonesize;?></td>
            <td><?php echo $size->rp_account_max_fill .' / '. $size->rp_site_max_fill .' / '. $size->rp_zonesize_max_fill;?></td>
            <td><?php echo $size->rp_account_floor_tag .' / '. $size->rp_site_floor_tag .' / '. $size->rp_zonesize_floor_tag;?></td>
            <td><?php echo $size->rp_account_limited .' / '. $size->rp_site_limited .' / '. $size->rp_zonesize_limited;?></td>
            <td><?php echo $size->position ?></td>
            <td><?php echo $size->active ? '<img src="/images/status-green-check.gif"/>' : '<img src="/images/stats-red-x.gif"/>'; ?></td>
        </tr>
                <?php endforeach; ?>
            <?php endif; ?>

    </tbody>
        
</table>    
    
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>