<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<style type="text/css">
#report {
	width: 1124px;
}

a.link {
	cursor: pointer;
}

#showTable {
	width:950px;
}

#showResult {
	display: none;
}

#showResult table {
	width: 750px;
	border-collapse: collapse;
	border: 1px #B7B7B7 solid;
}

#showResult table tr td {
	border: 1px #B7B7B7 solid;
	font-size: 14px;
	font-family: Arial, Helvetica, sans-serif;
	padding: 5px;
	width: 50%;
}

#showResult table tr th {
	border: 1px #B7B7B7 solid;
	font-size: 16px;
	font-family: Arial, Helvetica, sans-serif;
	padding: 5px;
	width: 50%;
	text-align: center;
}

#showResult table tr td.ok {
	color: green;
}

#showResult table tr td.error {
	color: red;
}

#mask {
	position: fixed;
	height: 100%;
	width: 100%;
	display: none;
	opacity: 0.3;
	filter: alpha(opacity = 30);
	background-color: #000000;
	z-index: 9000;
	left: 0;
	top: 0;
}

#message {
	position: fixed;
	display: none;
	height: 50px;
	width: 200px;
	z-index: 10000;
	border: 1px solid #B7B7B7;
	border-radius: 4px;
	background-color: #F4F4F4;
	left: 43%;
	top: 44%;
}

#message span {
	font-size: 14px;
	display: block;
	margin: 15px 0px 0px 62px;
}

.dataTables_filter {
	text-align:left;
}

.dataTables_filter label {

}


</style>
<script type="text/javascript">
var pendingTable,approvedTable, deniedTable;

function closeFancybox(){
    $.fancybox.close();
}
function redrawTables(){
	pendingTable.fnClearTable(true);
	approvedTable.fnClearTable(true);
	deniedTable.fnClearTable(true);
}

$(function(){
	
    var category = $('#categoriesSelect').val();
    var country = $('#countriesSelect').val();
    
	var options =  {
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": null,
        "fnServerParams": function ( aoData ) {  
            aoData.push( { "name": "category", "value": category } ); 
            aoData.push( { "name": "country", "value": country } ); 
		},
        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
        "iDisplayLength": 50,
        "aoColumns": [
            { 
              "sType": "num-html", 
              "sTitle": "ID#",
              "fnRender": function(obj){ 
					var id = obj.aData["id"];
                    return id;
              	}
            },
            { 
              "sTitle": "Site",
              "fnRender": function(obj){ 
                  return obj.aData['site'];
                   }
            },
            { 
                "sTitle": "Site Url",
                "fnRender": function(obj){ 
                    return "<a href=\""+obj.aData["site_url"]+"\" target=\"_blank\">" +obj.aData['site_url'] + "</a>";
               		}
            },            
            {  
              "sTitle": "Category",
              "fnRender": function(obj){ return obj.aData["category"]; }
            },
            {  
                "sTitle": "Alexa Rank",
                "fnRender": function(obj){ return "<a href=\""+obj.aData["site_url"]+"\" target=\"_blank\">" +obj.aData["alexa_rank"].toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "</a>";  }
            },
            { 
              "sType" : "numeric",
              "sTitle": "Average Monthly Impressions",
              "fnRender": function(obj){ return obj.aData["avg_monthly_impressions"].toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","); }
			},
            { 
	              "sType" : "numeric",
	              "sTitle": "Average RTB Clearing Price",
	              "fnRender": function(obj){ return obj.aData["avg_rtb_clearing_price"]; }
			},
        ],
        "fnDrawCallback": function(){

			$("#message").hide();

			function actionHandler(e){

				e.preventDefault();
				$("#message").show();

				var selectedTab = $("#tabs li.ui-tabs-selected");
				var selectedIndex = $("#tabs li").index(selectedTab);

				switch (selectedIndex){
					case 0 :
						pendingTable.fnSettings().bProcessing = true;
						approvedTable.fnSettings().bProcessing = false;
						deniedTable.fnSettings().bProcessing = false;
						break;
					case 1:
						pendingTable.fnSettings().bProcessing = false;
						approvedTable.fnSettings().bProcessing = true;
						deniedTable.fnSettings().bProcessing = false;
						break;
					case 2:
						pendingTable.fnSettings().bProcessing = false;
						approvedTable.fnSettings().bProcessing = false;
						deniedTable.fnSettings().bProcessing = true;
						break;
				}
								
				var href = $(this).attr("href");

				$.get(href,function(res){

					if (!res.error){
						if (typeof console == "object")
							console.log(res.data)

						redrawTables();	
					}
					else {
						if (typeof console == "object")
							console.log(res.data)
						$("#message").hide();
					}
				});
			}

			$(this).find(".pendingAction").click(actionHandler);  			
			$(this).find(".approvalAction").click(function(e){
				e.preventDefault();
				$(this).fancybox({ 'width': 450, 'height':240 });

			});            
			$(this).find(".denyAction").click(actionHandler);
			$(this).find(".viewAction").click(function(e){
				e.preventDefault();
				$(this).fancybox({ 'width': 450, 'height':450 });
			});

        },
        "aaSorting": [[ 0, "asc" ]]
	};

	var pendingColumn =  {  
            "sTitle": "Pending",
            "bSortable": false,
            "fnRender": function(obj){ 
				var id = obj.aData["id"];
			    var html = '<a class="pendingAction" site_id="'+id+'" href="/administrator/exchangesites/pending/id/'+id+'"><img src="/images/question.gif" width="16" height="16" /></a>';
			    return html;
            }
        };	

	var approvalColumn =  {  
            "sTitle": "Approve",
            "bSortable": false,
            "fnRender": function(obj){ 
				var id = obj.aData["id"];
			    var html = '<a class="iframe approvalAction" site_id="'+id+'" href="/administrator/exchangesites/approval/id/'+id+'"><img src="/images/status-green-check.gif" width="16" height="16" /></a>';
			    return html;
            }
        };
    var denyColumn = 
        {  
            "sTitle": "Deny",
            "bSortable": false,
            "fnRender": function(obj){ 
				var id = obj.aData["id"];
                var html = '<a class="denyAction" site_id="'+id+'" href="/administrator/exchangesites/deny/id/'+id+'"><img src="/images/stats-red-x.gif" width="16" height="16" /></a>';
				return html;
            }
        };
    var viewColumn =    {  
            "sTitle": "View",
            "bSortable": false,
            "fnRender": function(obj){ 
				var id = obj.aData["id"];
                var html = '<a class="iframe viewAction" site_id="'+id+'" href="/administrator/exchangesites/view/id/'+id+'"><img src="/images/details_open.png" width="16" height="16" /></a>';
				return html;
            }
        };      
	
	options.aoColumns.push(approvalColumn,denyColumn,viewColumn);
    options.sAjaxSource = "/administrator/exchangesites/data/status/pending";
    pendingTable = $('#pendingTable').dataTable(options);
	
	options.aoColumns.splice(7,3);
	options.aoColumns.push(pendingColumn,denyColumn,viewColumn);
	options.sAjaxSource = "/administrator/exchangesites/data/status/approved";
	approvedTable = $('#approvedTable').dataTable(options);
	
	options.aoColumns.splice(7,3);
	options.aoColumns.push(approvalColumn,pendingColumn,viewColumn);
	options.sAjaxSource = "/administrator/exchangesites/data/status/denied";
	deniedTable = $('#deniedTable').dataTable(options);

    $('#categoriesSelect').change(function(){ 
    	category = $('#categoriesSelect').val(); 
        pendingTable.fnClearTable();  
    });

    $('#countriesSelect').change(function(){ 
    	country = $('#countriesSelect').val(); 
        pendingTable.fnClearTable();  
    });

    var selectedCategory;
	
	$("#tabs").tabs({
		select: function(event, ui){
			if (ui.index > 0){
				selectedCategory = $('#categoriesSelect').val();
				$('#categoriesSelect').val(null);
				category = "";
			}
			else if (ui.index == 0 && selectedCategory.length >0 ){
				category = selectedCategory;
				$('#categoriesSelect').val(category);
			}
		}
	});
});

</script>
<link href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" rel="stylesheet" type="text/css" />
<h1>Potential Exchange Sites</h1>
<div id="showTable" class="contUsL" >
	<div id="tabs">
		<ul>
			<li><a href="#pendingTab">Pending</a></li>
			<li><a href="#approvedTab">Approved</a></li>
			<li><a href="#deniedTab">Denied</a></li>
		</ul>

		<div id="pendingTab">
		
			<div>
			    <div class="dataTables_length">
			    	<label>Categories
				        <select id="categoriesSelect">
				        	<option value="">Select Category</option>
				        <?php  foreach ($this->categories as $category): ?>
				            <option value="<?php  echo $category->category?>"><?php echo $category->name?></option>
				        <?php  endforeach; ?>
				        </select>
			        </label>
			    </div>	
			    
			    <div class="dataTables_filter">
			    	<label style="width:300px">Average Impressions by Country
				    	<select id="countriesSelect">
				        	<option value="">Select Country</option>
				        <?php  foreach ($this->countries as $col=>$country): ?>
				            <option value="<?php  echo $col?>"><?php echo (($country == "usa" || $country=="uk") ? strtoupper($country) : ucwords(str_replace("_"," ",$country))); ?></option>
				        <?php  endforeach; ?>
				        </select>
			    	</label>
			    </div>					
			</div>
	    	
		    
			<table width="870px" cellpadding="0" cellspacing="0" border="0" class="display" id="pendingTable">
				<thead>
					<tr>
						<th width="5%">ID #</th>
						<th width="15%">Site</th>
						<th width="15%">Site Url</th>
						<th width="15%">Category</th>
						<th width="15%">Alexa Rank</th>
						<th width="15%">Average Monthly Impressions</th>
						<th width="10%">Average RTB Clearing Price</th>
						<th width="3%">Approve</th>
						<th width="3%">Deny</th>
						<th width="3%">View</th>
					</tr>
				</thead>
				<tbody></tbody>
				<tfoot>
					<tr>
						<th>ID #</th>
						<th>Site</th>
						<th>Site Url</th>
						<th>Category</th>
						<th>Alexa Rank</th>
						<th>Average Monthly Impressions</th>
						<th>Average RTB Clearing Price</th>
						<th>Approve</th>
						<th>Deny</th>
						<th>View</th>
					</tr>
				</tfoot>
			</table>
			<div class="clear"></div>
		</div>

		<div id="approvedTab">
			<table width="870px" cellpadding="0" cellspacing="0" border="0" class="display" id="approvedTable">
				<thead>
					<tr>
						<th width="5%">ID #</th>
						<th width="15%">Site</th>
						<th width="15%">Site Url</th>
						<th width="15%">Category</th>
						<th width="15%">Alexa Rank</th>
						<th width="15%">Average Monthly Impressions</th>
						<th width="10%">Average RTB Clearing Price</th>
						<th width="3%">Pending</th>
						<th width="3%">Deny</th>
						<th width="3%">View</th>
					</tr>
				</thead>
				<tbody></tbody>
				<tfoot>
					<tr>
						<th>ID #</th>
						<th>Site</th>
						<th>Site Url</th>
						<th>Category</th>
						<th>Alexa Rank</th>
						<th>Average Monthly Impressions</th>
						<th>Average RTB Clearing Price</th>
						<th>Pending</th>
						<th>Deny</th>
						<th>View</th>
					</tr>
				</tfoot>
			</table>
			<div class="clear"></div>
		</div>

		<div id="deniedTab">
			<table width="870px" cellpadding="0" cellspacing="0" border="0" class="display" id="deniedTable">
				<thead>
					<tr>
						<th width="5%">ID #</th>
						<th width="15%">Site</th>
						<th width="15%">Site Url</th>
						<th width="15%">Category</th>
						<th width="15%">Alexa Rank</th>
						<th width="15%">Average Monthly Impressions</th>
						<th width="10%">Average RTB Clearing Price</th>
						<th width="3%">Pending</th>
						<th width="3%">Deny</th>
						<th width="3%">View</th>
					</tr>
				</thead>
				<tbody></tbody>
				<tfoot>
					<tr>
						<th>ID #</th>
						<th>Site</th>
						<th>Site Url</th>
						<th>Category</th>
						<th>Alexa Rank</th>
						<th>Average Monthly Impressions</th>
						<th>Average RTB Clearing Price</th>
						<th>Approve</th>
						<th>Pending</th>
						<th>View</th>
					</tr>
				</tfoot>
			</table>
			<div class="clear"></div>
		</div>


	</div>
</div>

<div id="mask"></div>
<div id="message">
	<span>processing...</span>
</div>


<script
	type="text/javascript" src="/font/cufon-yui.js"></script>
<script
	type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script
	type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script
	type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script
	type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>

