

<script type="text/javascript" charset="utf-8">

        $(document).ready(function() {   
            
        $(".datepicker").datepicker({
                        showOn:'focus',
                        'dateFormat'  : "yy-mm-dd"
                        });
	
                                    
        }); 
        
</script>

<form action="" method="post" class="sign-up">
<div class="contUsL" style="width: 700px;">    
    
    <p>
         <label>User: </label>
         <select name="adminID" id="userSearch">
             <?php foreach($this->admins as $item): ?>
                    <option value="<?php echo $item->id ?>" <?php echo $item->id==$this->formValues['adminID'] ? 'selected="selected"' : '' ?>><?php echo "#".$item->id.": ".$item->name." (".$item->email.")" ?></option>
             <?php endforeach; ?>
         </select>
    <?php if(isset($this->formErrors['adminID'])): ?>
        <ul class="error">
        <?php foreach($this->formErrors['adminID'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                         
    </p>
    
    
    <p><label>Date: </label> <input type="text" name="date_alert" class="datepicker" value="<?php echo $this->formValues['date_alert'] ?>" />
    <?php if(isset($this->formErrors['date_alert'])): ?>
        <ul class="error">
        <?php foreach($this->formErrors['date_alert'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                
    </p>
        
    <p><label>Message: </label> <textarea name="message" style="width:500px; height:100px; "><?php echo $this->formValues['message'] ?></textarea><br>
    <?php if(isset($this->formErrors['message'])): ?>
        <ul class="error">
        <?php foreach($this->formErrors['message'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                
    </p>
    

    
<p><a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Save</a></p>
<input type="submit" id="subForm" style="display: none;" />
</div>
</form>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
    Cufon.replace('.error', {color: 'red'});	    

</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
    Cufon.replace('h1');				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('#location');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.headquaters');		
</script>    