<link href="/styles/jquery-ui-1.8.18.custom.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/style.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/reset.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/table.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="/js/jquery-ui-1.8.18.custom.min.js"></script>
<script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/js/jquery-date-format.js"></script>

<style type="text/css">
    
    #report{ background: white; }
    .filter-date{ display: block; float: left; }
    .filter-date label{ display: block; float: left; width: 45px; margin-right: 10px; }
    .filter-date input{ display: block; float: left; width: 105px; border-right: 1px solid #D3D3D3; }
    .filter-date #d-end{ width: 20px; }
    .filter-date buttom{ display: block; float: left; width: 70px; height: 26px; background: #DADADA; font-size: 15px; font-weight: 600; line-height: 27px; text-align: center; cursor: pointer; margin-left: 5px; }
    #url-psa_filter input[type=text]{ border-right: 1px solid #D3D3D3; }
    #url-psa_filter label{ width: 55px; }
    .dataTables_filter{ width: 41%; }    
    
    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
</style>
<script type="text/javascript" charset="utf-8">

        var dateStart = '<?php echo $this->date['start'];?>';
        var dateEnd = '<?php echo $this->date['end']?>';
        var oTable = new Object();
        
        dateStart = $.format.date(new Date(dateStart), "yyyy-MM-dd");
        dateEnd = $.format.date(new Date(dateEnd), "yyyy-MM-dd");

        $(document).ready(function(){   
                
                oTable = $('#url-psa').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/url/get-ajax',
                        "fnServerParams": function ( aoData ) { aoData.push( { "name": "SiteID", "value": <?php echo $this->siteID;?> },{ "name": "date_start", "value": dateStart },{ "name": "date_end", "value": dateEnd } ); },
                        "fnDrawCallback": function( oSettings ) {  },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100
                        ,
                        "aoColumns": [
                            { 
                              "sTitle": "Url",
                              "fnRender": function(obj){ return obj.aData[0]; }   
                            },
                            { 
                              "sTitle": "Last Update",
                              "fnRender": function(obj){ return $.format.date(new Date(obj.aData[1]), "yyyy MMM, dd"); } 
                            },  
                            { 
                              "sTitle": "Count",
                              "fnRender": function(obj){ return obj.aData[2]; } 
                            },  
                            { 
                              "sTitle": "Approve URL",
                              "fnRender": function(obj){ return '<a style="cursor: pointer;" onClick="approveUrl(\''+obj.aData[3]+'\');">add/approve</a>'; } 
                            }  
                        ],                                                
                        "aaSorting": [[ 0, "asc" ]]
                         
                });
                
                $("#date-start").datepicker({dateFormat: 'yy M, dd'});
                $("#date-end").datepicker({dateFormat: 'yy M, dd'});

        });

function updateTable()
{
    dateStart = $('#date-start').val();
    dateEnd = $('#date-end').val();
    
    dateStart = $.format.date(new Date(dateStart), "yyyy-MM-dd");
    dateEnd = $.format.date(new Date(dateEnd), "yyyy-MM-dd");
    
    oTable.fnClearTable();
}

function approveUrl(url){
    
    <?php if($this->data['tag_type'] == 4):?>
        if(!confirm("This is a site in AdX.  Be sure to approve the URLs in AdX/Adsense ?")) return false;
    <?php endif;?>
    
    display('block');
            
    $.ajax({ url : '/administrator/ajax/approve-psa-url',
                       data : { SiteID : <?php echo $this->siteID?>, url : encodeURIComponent(url) },
                       type : "POST",
                       dataType : "json",

             success : function(response) { 

                       oTable.fnClearTable();
                       
                       display('none');
             },
               
             error : function(){ display('none'); alert('ajax error'); }
     });    
}

function display(status)
{
    $('#mask').css('display', status);
    $('#loading').css('display', status);         
}

</script>

<div id="content">
    <div id="report">

<h1>Not Approved Url</h1>
<div class="contUsL" style="width: 750px;">
    
<br /><br />   
<div class="filter-date">  
    <label id="d-start">From</label>
    <input id="date-start" name="date-start" value="<?php echo $this->date['start'];?>" type="text"/>
    <label id="d-end">To</label>
    <input id="date-end" name="date-end" value="<?php echo $this->date['end'];?>" type="text"/> 
    <buttom onClick="updateTable();">Filter</buttom>
</div>

<br /><br />
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="url-psa">
	<thead>
		<tr>
                    <th width="60%">Url</th>
                    <th width="15%">Last Update</th>
                    <th width="10%">Count</th>  
                    <th width="15%">Approve URL</th>  
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot>
		<tr>
                    <th>Url</th>
                    <th>Last Update</th>
                    <th>Count</th>  
                    <th>Approve URL</th>
		</tr>
	</tfoot>
</table>
</div> 

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>

</div>
</div>
