<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>

<style type="text/css">
    
    .respondedButton{ 
        background-color: #8e8e8e;
        border: 1px solid #797979;
        color: #ffffff;
        cursor: pointer;
        font-size: 15px !important;
        height: 25px;
        width: 53px; 
    } 
    .respondedButton:hover{
        background-color: #dc2323;
        border: 0 none;
        padding: 1px;
    }
    .respondedCheck{
        width: 10px !important;
        float: left;
        margin-right: 5px;
    }
    
    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
</style>  

<script type="text/javascript" charset="utf-8">

var oTable1 = new Object();
var oTable2 = new Object();

$(document).ready(function() {   
    
    var date60day = new Date();
        date60day.setHours(00, 00, 00);
        date60day.setDate(date60day.getDate() - 60);    

    oTable1 = $('#all-data').dataTable( {
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": '/administrator/all/ajax-get',
                "fnServerParams": function ( aoData ) {  aoData.push( { "name": "filterSearch", "value": "<?php echo $this->value; ?>" } ); },
                "fnDrawCallback": function( oSettings ) { display('none'); },
                "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "iDisplayLength": 100,
                "aoColumns": [
                    { 
                      "sTitle": "PubID",
                      "fnRender": function(obj){ return obj.aData[0]; } 
                    },
                    { 
                      "sTitle": "SiteID",
                      "fnRender": function(obj){ return obj.aData[1]; } 
                    },
                    { 
                      "sTitle": "Website",
                      "fnRender": function(obj){ 
	                      if(obj.aData[2])
	                      	return '<a href="/administrator/sites/view/id/'+obj.aData[12]+'">'+obj.aData[2]+'</a>';
	                      else
	                      	return '<a href="/administrator/index/view/id/'+obj.aData[11]+'">'+obj.aData[13]+'</a>';
	                      	 } 
                    },
                    { 
                      "sTitle": "Contact",
                      "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[11]+'">'+obj.aData[3]+'</a>'; } 
                    },
                    { 
                      "sTitle": "Contact",
                      "fnRender": function(obj){ return '<button style="cursor: pointer" onClick="mailContact('+obj.aData[4]+')">Contact</button>'; } 
                    },
                    { 
                      "sTitle": "Status Site",
                      "sClass": "",
                      "bSortable": false,
                      "fnRender": function(obj){ 
                          
                          var result = '';
                     
                          switch(parseInt(obj.aData[5]))
                          {
                              case 1 : result = 'new';      break;
                              case 2 : result = 'rejected'; break;
                              case 3 : result = 'approved'; break;    
                              default: result = 'waiting';
                          }
                          
                          return result; 
                      }
                    },
                    {
                      "sTitle": "Status User",
                      "bSortable": false,
                      "fnRender": function(obj){ 
                          
                          var result = '';
                          if(obj.aData[6]==0 && obj.aData[14]==0 && obj.aData[15]==1)
	                          result = 'waiting';
                          else if(obj.aData[6]==0 && obj.aData[14]==0)
                          	result = 'new';
                          else if(obj.aData[14]==1)
                          	result = 'rejected';
                          else if(obj.aData[6]==1)
                          	result = 'approved';
                          	 	                                                                              
                          return result; } 
                    },
                    {
                      "sTitle": "Status Adx",
                      "bSortable": false,
                      "fnRender": function(obj){ 
                          
                          var result = '';                  
                          
                          switch(parseInt(obj.aData[7]))
                          {
                              case 1 : result = 'new';      break;
                              case 2 : result = 'rejected'; break;
                              case 3 : result = 'approved'; break;   
                              case 4 : result = 'invited';  break;
                              case 5 : result = 'expired';  break;    
                          }
                          
                          if(obj.aData[7] == '4' && obj.aData[16]){ 
                             if((new Date(obj.aData[16]+' 00:00:00')) <= date60day){ result = 'never'; } 
                          }                          
                          
                          return result; } 
                    },
                    { 
                      "sTitle": "Live",
                      "bVisible": true,
                      "bSortable": false,
                      "fnRender": function(obj){ 
                          if(parseInt(obj.aData[8])){ return  '<img src="/images/status-green-check.gif">'; }
                          else{ return  '<img src="/images/stats-red-x.gif">';} 
                          
                          }
                                                
                    },
                    { 
                      "sTitle": "Ever Live",
                      "bVisible": true,
                      "bSortable": false,
                      "fnRender": function(obj){  
                          
                          var notifiStatus = parseInt(obj.aData[17]);
                          
                          if(parseInt(obj.aData[9])) return '<img src="/images/status-green-check.gif"/>';
                          else
                          {
								if(notifiStatus == 3 || notifiStatus == 2 || notifiStatus == 1)
								{
									return '<img style="cursor: pointer;" src="/images/stats-orange-x.png">';
								}
								else if(notifiStatus == 4)
								{
									return '<img src="/images/stats-grey-x.png">';
								}
								else
								{
									return '<img style="cursor: pointer;" src="/images/stats-red-x.gif"/>';
								}
                          }
                      }                        
                    },                    
                    { 
                      "sTitle": "",
                      "bSortable": false,
                      "fnRender": function(obj){ return '<a target="_blank" href="/administrator/index/auth/id/'+obj.aData[10]+'">login</a>'; } 
                    }
                ],                                                
                "aaSorting": [[ 1, "desc" ]],
                "fnDrawCallback": function(oSettings){ display('none'); } 
        });

    oTable2 = $('#all-recruiting').dataTable( {
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": '/administrator/all/ajax-get-recruiting',
                "fnServerParams": function ( aoData ) {  aoData.push( { "name": "filterSearch", "value": "<?php echo $this->value; ?>" } ); },
                "fnDrawCallback": function( oSettings ) { display('none'); },
                "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "iDisplayLength": 100,
                "aoColumns": [
                    { 
                      "sTitle": "Responded",
                      "fnRender": function(obj){ return '<input type="checkbox" class="respondedCheck" data-val="'+obj.aData[0]+'" data-id="'+obj.aData[7]+'" name="responded'+obj.aData[7]+'" value="1" '+(parseInt(obj.aData[0]) ? 'checked' : '')+'/>'; } 
                    },
                    { 
                      "sTitle": "Website",
                      "fnRender": function(obj){ return obj.aData[1]; } 
                    },
                    { 
                      "sTitle": "Email",
                      "fnRender": function(obj){ return obj.aData[2]; } 
                    },
                    { 
                      "sTitle": "Created",
                      "fnRender": function(obj){ return $.format.date(new Date(obj.aData[3]), "yyyy MMM, dd"); } 
                    },
                    { 
                      "sTitle": "Created By",
                      "fnRender": function(obj){ return obj.aData[4]; } 
                    },
                    { 
                      "sTitle": "Updated",
                      "fnRender": function(obj){ return $.format.date(new Date(obj.aData[5]), "yyyy MMM, dd"); } 
                    },               
                    { 
                      "sTitle": "Updated By",
                      "bSortable": false,
                      "fnRender": function(obj){ return obj.aData[6]; } 
                    },

                ],                                                
                "aaSorting": [[ 1, "desc" ]],
                "fnDrawCallback": function(oSettings){ display('none'); } 
        }); 
        
        $('#all-recruiting tbody td .respondedCheck').live('change', function(){

                var nTr = $(this).parents('tr')[0]; 
                
                var children = $(nTr).children();
                var id = $(children[0]).find('.respondedCheck').attr('data-id');
                var valOrigin = $(children[0]).find('.respondedCheck').attr('data-val');
                var valReal = $(children[0]).find('.respondedCheck').attr('checked') ? 1 : 0;
              
                if($(children[0]).find('button').length == 0){ 
                
                     $('<button onclick="saveResponded('+id+')" class="respondedButton">Save</button>').appendTo(children[0]);
            
                } else if(valOrigin == valReal) {
                    
                     $($(children[0]).find('.respondedButton')).replaceWith('');
                }
        }); 
                    
        $("#tabs").tabs();
});

function saveResponded(id)
{
    var value = $('input[name="responded'+id+'"]').attr('checked') ? 1 : 0

    display('block');
    
    $.ajax({ url : '/administrator/all/ajax-save-responded',
         data : { id : id, value : value },
         async: false,
         type : "POST",
         dataType : "json",

         success : function(response) { 

            if(response.status){

                var parentTD = $('input[name="responded'+id+'"]').parent('td');
                var parentTR = $(parentTD).parent('tr');
                var childrenTR = $(parentTR).children();
                
                $(childrenTR[5]).html($.format.date(new Date(response.date_updated), "yyyy MMM, dd"));
                $(childrenTR[6]).html(response.updated_by);
                                    
                $($(parentTD).find('.respondedButton')).replaceWith('');
               
            } else { alert('ajax error'); }
            
            display('none');

         }, error : function(){ display('none'); alert('ajax request return error'); }
    });
}


function display(status)
{
    $('#mask').css('display', status);
    $('#loading').css('display', status);         
}

function mailContact(PubID)
{
    $.fancybox({
        'width'	: '75%',
        'height'	: '80%',
        'href'          : '/administrator/sites/contact/PubID/'+PubID,
        'autoScale'    	: false,
        'transitionIn'	: 'none',
        'transitionOut'	: 'none',
        'type'		: 'iframe',
        'onClosed'      : function(){ oTable1.fnClearTable(); }
    }); 
}

</script>

<div class="contUsL" style="width: 750px;">
    
    <h1>Summary Data</h1>
    
    <br /><br />
    
    <div id="tabs">
        
        <ul>
            <li><a href="#tabs-1">Sites / Users</a></li>
            <li><a href="#tabs-2">Recruiting</a></li>
        </ul>

        <div id="tabs-1">    
        
            <table width="870px" cellpadding="0" cellspacing="0" border="0" class="display" id="all-data">
                    <thead>
                            <tr>
                                <th width="5%">PubID</th>
                                <th width="5%">SiteID</th>
                                <th width="30%">Website</th>
                                <th width="40%">Contact</th>
                                <th width="5%">Contact</th>
                                <th width="5%">Status Site</th>
                                <th width="5%">Status User</th>
                                <th width="5%">Status Adx</th>
                                <th width="5%">live</th>
                                <th width="5%">ever live</th>                                
                                <th width="5%"></th>
                            </tr>
                    </thead>
                    <tbody></tbody>
                    <tfoot>
                            <tr>
                                <th>PubID</th>
                                <th>SiteID</th>
                                <th>Website</th>
                                <th>Contact</th>
                                <th>Contact</th>
                                <th>Status Site</th>
                                <th>Status User</th>
                                <th>Status Adx</th>
                                <th>live</th>
                                <th>ever live</th>                                
                                <th></th>                      
                            </tr>
                    </tfoot>
            </table>

        </div>        
        <div id="tabs-2">
            
            <table width="870px" cellpadding="0" cellspacing="0" border="0" class="display" id="all-recruiting">
                    <thead>
                            <tr>
                                <th width="5%">Responded</th>
                                <th width="30%">Website</th>
                                <th width="30%">Email</th>
                                <th width="10%">Created</th>
                                <th width="20%">Created By</th>
                                <th width="10%">Updated</th>
                                <th width="20%">Updated By</th>
                                <th width="5%"></th>
                            </tr>
                    </thead>
                    <tbody></tbody>
                    <tfoot>
                            <tr>
                                <th>Responded</th>
                                <th>Website</th>
                                <th>Email</th>
                                <th>Created</th>
                                <th>Created By</th>
                                <th>Updated</th>
                                <th>Updated By</th>
                                <th></th>                      
                            </tr>
                    </tfoot>
            </table>
            
        </div>            
            
</div>

<div id="mask"></div>
<div id="loading"><span>processing...</span></div> 

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
//	Cufon.replace('.contInf h3', {hover: true});	
//	Cufon.replace('.contInf h3');
//	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
//	Cufon.replace('.footerBann h5');		
//	Cufon.replace('.footerBann p');	
//	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
//		Cufon.replace('#footCopyr');	
//		Cufon.replace('.contInf p', {hover: true});		
//		Cufon.replace('.contInf p', {color: '#333333'});	
//		Cufon.replace('.contInf p.white', {color: '#FFF'});	
//		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>