<div class="container">
    <h2 class="text-center"><?php echo $this->action ?> PulsePoint API account</h2>
    <?php if(count($this->formErrors)): ?>
        <div class="alert alert-danger" role="alert">
            <ul>
                <?php foreach($this->formErrors as $error): ?>
                    <?php foreach($error as $item): ?>
                        <li><?php echo $item; ?></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php endif; ?>
    <form  method="post" class="form-horizontal">
        <div class="form-group <?php if(isset($this->formErrors['user_name'])) echo "has-error" ?>">
            <label class="col-sm-2" for="user_name">User name: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" value="<?php echo $this->formValues['user_name'] ?>" name="user_name" id="user_name">
            </div>
        </div>
        <div class="form-group <?php if(isset($this->formErrors['acc_num'])) echo "has-error" ?>">
            <label class="col-sm-2" for="acc_num">Acc Num: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" value="<?php echo $this->formValues['acc_num'] ?>" name="acc_num" id="acc_num">
            </div>
        </div>
        <div class="form-group <?php if(isset($this->formErrors['token'])) echo "has-error" ?>">
            <label class="col-sm-2" for="token">Token: </label>
            <div class="col-sm-5">
                <input type="text" class="form-control" value="<?php echo $this->formValues['token'] ?>" name="token" id="token">
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Save</button>
            <a class="btn btn-danger" href="/administrator/pp-accounts" role="button">Cancel</a>
        </div>
    </form>
</div>