<style>
.review-site, .review-user
{
	cursor: pointer;
}
</style>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />

<script type="text/javascript" charset="utf-8">
        $(document).ready(function() {   

            $("#tabs").tabs(); 
 
            <?php if($this->dataAuth->role == 'super'):?>
                var accounts = $('#accounts').val();
            <?php else:?>
                var accounts = <?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>;
            <?php endif;?>    
            
                var oTable = $('#sites').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/co-site-approvals/ajax-get',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "accounts", "value": accounts }, { "name": "type", "value": "site" }  ); },
                        "aLengthMenu": [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, -1], [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, "All"]],
                        "iDisplayLength": 20,
                        "aoColumns": [ 
                            { 
                              "sTitle": "Website",
                              "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[5]+'">'+obj.aData[0]+'</a>'; } 
                            },                            
                            { 
                              "sTitle": "Contact",
                               "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[9]+'">'+obj.aData[1]+'</a>'; }                             
                            },
                            { 
                                "sTitle": "AlexaRank",
                                 "fnRender": function(obj){ return obj.aData[2]; }                             
                            },
                            { 
                                "sTitle": "AlexaRankUS",
                                 "fnRender": function(obj){ return obj.aData[3]; }                             
                            },       
                            { 
                              "sTitle": "Approved By",
                              "fnRender": function(obj){ return obj.aData[4]; } 
                            },       
                            { 
                              "sTitle": "Review",
                               "fnRender": function(obj)
                               { 
                                   return '<button class="review-site" data-id="'+obj.aData[5]+'">Review</button>'; 
                               }                             
                            },
                            { 
                              "sTitle": "Deny",
                               "fnRender": function(obj){ return '<a href="#" onClick="fancySend('+obj.aData[6]+',0); return false;">Deny</a>'; }                             
                            },                                    
                            { 
                              "sTitle": "",
                              "bSortable": false,
                              "fnRender": function(obj){return '<img src="/images/details_open.png">'; } 
                            }, 
                            { 
                              "sTitle": "",
                              "bSortable": false,
                              "bVisible": false,
                              "fnRender": function(obj){return obj.aData[8]; } 
                            }                                                                                        
                        ],                       
                        "aaSorting": [[ 0, "asc" ]]
                } );

                var oTable2 = $('#users').dataTable( {
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": '/administrator/co-site-approvals/ajax-get',
                    "fnServerParams": function ( aoData ) {  aoData.push( { "name": "accounts", "value": accounts }, { "name": "type", "value": "user" }  ); },
                    "aLengthMenu": [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, -1], [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, "All"]],
                    "iDisplayLength": 20,
                    "aoColumns": [ 
                        { 
                          "sTitle": "Website",
                          "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[5]+'">'+obj.aData[0]+'</a>'; } 
                        },                            
                        { 
                          "sTitle": "Contact",
                           "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[9]+'">'+obj.aData[1]+'</a>'; }                             
                        }, 
                        { 
                            "sTitle": "AlexaRank",
                             "fnRender": function(obj){ return obj.aData[2]; }                             
                        },
                        { 
                            "sTitle": "AlexaRankUS",
                             "fnRender": function(obj){ return obj.aData[3]; }                             
                        },     
                        { 
                          "sTitle": "Approved By",
                          "fnRender": function(obj){ return obj.aData[4]; } 
                        },       
                        { 
                          "sTitle": "Review",
                           "fnRender": function(obj){ return '<button class="review-user" data-id="'+obj.aData[5]+'">Review</button>';  }                             
                        },
                        { 
                          "sTitle": "Deny",
                           "fnRender": function(obj){ return '<a href="#" onClick="fancySend('+obj.aData[6]+',1); return false;">Deny</a>'; }                             
                        },                                    
                        { 
                          "sTitle": "",
                          "bSortable": false,
                          "fnRender": function(obj){return '<img src="/images/details_open.png">'; } 
                        }, 
                        { 
                          "sTitle": "",
                          "bSortable": false,
                          "bVisible": false,
                          "fnRender": function(obj){return obj.aData[8]; } 
                        }                                                                                        
                    ],                       
                    "aaSorting": [[ 0, "asc" ]]
            } );
                
                $('#accounts').change(function(){ accounts = $('#accounts').val(); oTable.fnClearTable();oTable2.fnClearTable();});
                
                $("#fancybox-close").click(function(){
                    oTable.fnClearTable();
                    oTable2.fnClearTable();
                })                
                
                $('#users tbody td img, ').live('click', function () {
                    var nTr = $(this).parents('tr')[0];                
                    if ( oTable2.fnIsOpen(nTr) )
                    {
                        /* This row is already open - close it */
                        this.src = "/images/details_open.png";
                        oTable2.fnClose( nTr );
                    }
                    else
                    {
                        /* Open this row */
                        this.src = "/images/details_close.png";
                        var objTr = oTable2.fnOpen( nTr, fnFormatDetails(oTable2, nTr), 'details' );
                    }
                } );   


                $('#sites tbody td img, ').live('click', function () {
                    var nTr = $(this).parents('tr')[0];                
                    if ( oTable.fnIsOpen(nTr) )
                    {
                        /* This row is already open - close it */
                        this.src = "/images/details_open.png";
                        oTable.fnClose( nTr );
                    }
                    else
                    {
                        /* Open this row */
                        this.src = "/images/details_close.png";
                        var objTr = oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
                    }
                } );             
                
                $('.selectUrls').live('change', function () {
                    var id = $(this).attr('real');
                    var value = $(this).val();
                    $("#urlNude_"+id).attr('href', 'https://www.google.com/search?'+value+'+%22nude%22&hl=en&tbo=d&tbm=isch+%22nude%22&hl=en&tbo=d&tbm=isch');
                    $("#urlPorn_"+id).attr('href', 'https://www.google.com/search?'+value+'+%22porn%22&hl=en&tbo=d&tbm=isch+%22porn%22&hl=en&tbo=d&tbm=isch');
                    $("#urlSex_"+id).attr('href', 'https://www.google.com/search?'+value+'+%22sex%22&hl=en&tbo=d&tbm=isch+%22sex%22&hl=en&tbo=d&tbm=isch');
                    $("#urlNSFW_"+id).attr('href', 'https://www.google.com/search?'+value+'+%22nsfw%22&hl=en&tbo=d&tbm=isch+%22nsfw%22&hl=en&tbo=d&tbm=isch');
                    $("#urlFuck_"+id).attr('href', 'https://www.google.com/search?'+value+'+%22fuck%22&hl=en&tbo=d&tbm=isch+%22fuck%22&hl=en&tbo=d&tbm=isch');
                });

                $('.review-site').live('click', function()
                {
                    window.location.href = '/administrator/co-site-approvals/approve-site/id/'+$(this).attr('data-id');
                });

                $('.review-user').live('click', function()
                {
                	window.location.href = '/administrator/co-site-approvals/approve-user/id/'+$(this).attr('data-id');
                });


        } );     
        
function fancySend(id,user)
{   
   $.fancybox({
		'width'	: '75%',
		'height': '75%',
                'href'  : '/administrator/co-site-approvals/send/id/'+id+'/user/'+user,
                'autoScale'     : false,
                'transitionIn'  : 'none',
		'transitionOut'	: 'none',
		'type'		: 'iframe'
   });    
}      


function fancyApprove(id)
{   
   $.fancybox({
		'width'	: '75%',
		'height': '75%',
                'href'  : '/administrator/co-site-approvals/new-approved/id/'+id,
                'autoScale'     : false,
                'transitionIn'  : 'none',
		'transitionOut'	: 'none',
		'type'		: 'iframe'
   });    
} 

function fnFormatDetails ( oTable, nTr )
{
    var aData = oTable.fnGetData( nTr );
    var WebSite = aData[10];
    var urls = aData[8];
    var siteID = aData[5];
    var urlsData = urls.split(/[\n]/);

    if(urlsData.length>10){
        var txt = '';
        var count = 0;
        var countPage = 1;
        var url = '';  
        var urlFirst = '';  
        txt='<select class="selectUrls" real="'+siteID+'" style="width:30px;">';
        $.each(urlsData, function(key, iter){
            iter = iter.replace('http://', '');
            iter = iter.replace('https://', '');
            iter = iter.replace('www.', '');
            if(count==0)
                url+='q=site:'+iter;
            else    
                url+='+OR+site:'+iter;
            count++;
            
            if(count==10){
                count=0;
                txt+='<option value="'+url+'">'+countPage+'</option>';
                if(countPage==1)
                    urlFirst=url;
                url = '';
                countPage++;
            }
        });        
        txt+='</select>';
        
        txt+='<a class="sendMasBtn" id="urlAlexa_'+siteID+'" style="float: left" title="" href="http://www.alexa.com/siteinfo/'+WebSite+'" target="_blank">Clickstream</a> \n\
                <a class="sendMasBtn" id="urlNude_'+siteID+'" style="float: left" title="" href="https://www.google.com/search?'+urlFirst+'+%22nude%22&hl=en&tbo=d&tbm=isch+%22nude%22&hl=en&tbo=d&tbm=isch" target="_blank">Nude</a> \n\
                <a class="sendMasBtn" id="urlPorn_'+siteID+'" style="float: left" title="" href="https://www.google.com/search?'+urlFirst+'+%22porn%22&hl=en&tbo=d&tbm=isch+%22porn%22&hl=en&tbo=d&tbm=isch" target="_blank">Porn</a> \n\
                <a class="sendMasBtn" id="urlSex_'+siteID+'" style="float: left" title="" href="https://www.google.com/search?'+urlFirst+'+%22sex%22&hl=en&tbo=d&tbm=isch+%22sex%22&hl=en&tbo=d&tbm=isch" target="_blank">Sex</a> \n\
                <a class="sendMasBtn" id="urlNSFW_'+siteID+'" style="float: left" title="" href="https://www.google.com/search?'+urlFirst+'+%22nsfw%22&hl=en&tbo=d&tbm=isch+%22nsfw%22&hl=en&tbo=d&tbm=isch" target="_blank">NSFW</a> \n\
                <a class="sendMasBtn" id="urlFuck_'+siteID+'" style="float: left" title="" href="https://www.google.com/search?'+urlFirst+'+%22fuck%22&hl=en&tbo=d&tbm=isch+%22fuck%22&hl=en&tbo=d&tbm=isch" target="_blank">Fuck</a>';
        
        return txt;
    }else{
        var count = 0;
        var url = '';
        $.each(urlsData, function(key, iter){
            iter = iter.replace('http://', '');
            iter = iter.replace('https://', '');
            iter = iter.replace('www.', '');
            if(count==0)
                url+='q=site:'+iter;
            else    
                url+='+OR+site:'+iter;
            count++;
        });
        
        return '<a class="sendMasBtn" style="float: left" title="" href="http://www.alexa.com/siteinfo/'+WebSite+'" target="_blank">Clickstream</a> \n\
                <a class="sendMasBtn" style="float: left" title="" href="https://www.google.com/search?'+url+'+%22nude%22&hl=en&tbo=d&tbm=isch+%22nude%22&hl=en&tbo=d&tbm=isch" target="_blank">Nude</a> \n\
                <a class="sendMasBtn" style="float: left" title="" href="https://www.google.com/search?'+url+'+%22porn%22&hl=en&tbo=d&tbm=isch+%22porn%22&hl=en&tbo=d&tbm=isch" target="_blank">Porn</a> \n\
                <a class="sendMasBtn" style="float: left" title="" href="https://www.google.com/search?'+url+'+%22sex%22&hl=en&tbo=d&tbm=isch+%22sex%22&hl=en&tbo=d&tbm=isch" target="_blank">Sex</a> \n\
                <a class="sendMasBtn" style="float: left" title="" href="https://www.google.com/search?'+url+'+%22nsfw%22&hl=en&tbo=d&tbm=isch+%22nsfw%22&hl=en&tbo=d&tbm=isch" target="_blank">NSFW</a> \n\
                <a class="sendMasBtn" style="float: left" title="" href="https://www.google.com/search?'+url+'+%22fuck%22&hl=en&tbo=d&tbm=isch+%22fuck%22&hl=en&tbo=d&tbm=isch" target="_blank">Fuck</a>';
    }
}
</script>

    <h1>Co-Site Approvals</h1>
<div class="contUsL" style="width: 880px;">
<p>
    <select id="accounts">
    <?php if($this->dataAuth->role == 'super'):?>
        <option value="-1">All</option>
        <?php foreach($this->contactManager as $iter):?>
             <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
        <?php endforeach;?>
    <?php else: ?>
        <option value="<?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>">Show My Account</option>                 
        <option value="-1">Show All Accounts</option>
    <?php endif;?>    
    </select>        
</p>
<br>



    <div id="tabs">        
		<ul>
		            <li><a href="#new_users">New Users</a></li>   
                    <li><a href="#new_sites">New Sites</a></li>                 
		</ul>        
        
    <div id="new_sites">
        <table width="830px" cellpadding="0" cellspacing="0" border="0" class="display" id="sites">
        	<thead>
        		<tr>
                            <th width="25%">Website</th>
                            <th width="25%">Contact</th>
                            <th width="25%">AlexaRank</th>
                            <th width="25%">AlexaRankUS</th>
                            <th width="25%">Contact</th>
                            <th width="20%">Approved By</th>
                            <th width="5%">Review</th>
                            <th width="5%">Deny</th>
                            <th width="5%"></th>
        		</tr>
        	</thead>            
        	<tbody>
        	</tbody>            
        	<tfoot>
        		<tr>
                            <th>Website</th>
                            <th>Contact</th>
                            <th>AlexaRank</th>
                            <th>AlexaRankUS</th>
                            <th>Approved By</th>
                            <th>Review</th>
                            <th>Deny</th>
                            <th></th>
        		</tr>
        	</tfoot>
        </table>      
    </div>
        
    <div id="new_users">        
            <table width="830px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
        	<thead>
        		<tr>
                            <th width="25%">Website</th>
                            <th width="25%">Contact</th>
                            <th width="25%">AlexaRank</th>
                            <th width="25%">AlexaRankUS</th>
                            <th width="20%">Approved By</th>
                            <th width="5%">Review</th>
                            <th width="5%">Deny</th>
                            <th width="5%"></th>
        		</tr>
        	</thead>            
        	<tbody>
        	</tbody>            
        	<tfoot>
        		<tr>
                            <th>Website</th>
                            <th>Contact</th>
                            <th>AlexaRank</th>
                            <th>AlexaRankUS</th>
                            <th>Approved By</th>
                            <th>Review</th>
                            <th>Deny</th>
                            <th></th>
        		</tr>
        	</tfoot>
        </table> 
    </div>  
        
    </div>






<br><br>
</div>    
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>