<style>
     #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
    #report
    {
	   background-image: none;
       border-right: solid 1px #E2E2E2;
       border-left: solid 1px #E2E2E2;
    }
    #reportL
    {
	   background-image: none;
       border-right: solid 1px #E2E2E2;
       border-left: solid 1px #E2E2E2;
    }
    .contUsL
    {
	   margin-left: 125px;
    }
    
    #add_news
    {
    	cursor: pointer;
    }
    
    #datepicker_add, #datepicker_edit
    {
    	width: 70px;
    	border-color: silver;
    	border-style: solid;
    	border-width: 1px;
    }
    
    #news_title_add, #news_title_edit
    {
    	width: 599px;
    	border-color: silver;
    	border-style: solid;
    	border-width: 1px;
    }
    

</style>
<script type="text/javascript" charset="utf-8">
var news_id;
        $(document).ready(function() 
        {
        	$("#datepicker_add, #datepicker_edit").datepicker();

			
	        var config =
	        {
	            height: 220,
	            width: 600,
	            resize_enabled: false,
	            language: 'en',
	            entities  : false,
	            basicEntities : false,
	            entities_greek : false,
	            entities_latin : false,
	            htmlEncodeOutput : false,
	            enterMode: Number(2),
	            toolbar: [
	              		{ name: 'document', items: [ 'Source', '-', 'Cut', 'Copy', 'Paste','Bold', 'Italic', 'Underline', 'Link'   ] },	// Defines toolbar group with name (used to create voice label) and items in 3 subgroups.

	              	]
	        };
	       
	    	$('#editor_add,#editor_edit').ckeditor(config);
	    	
			$("#add_news").click(function()
			{ 
				clear_dialog();
				$("#dialog-form-add").dialog("open");
			});
			
			$(".delete").live("click",function()
			{
				var answer = confirm ("Are you sure?");
				if(answer)
				{
					var item = $(this).attr('data-id');
					$.ajax({
						  type: 'POST',
						  url: '/administrator/news/delete',
						  dataType: 'json',
						  data: {
							  id : item,
							  csrf : $("#csrf").val(),
							  },
						  success: function(data){
						  	if(data.error != 0)
						  	{
							  	if(data.error == 2)
								  	alert('ERROR: CSRF');
							  	else
									alert('ERROR: DB');
							}
						  	else
						  	{	
						  		oTable.fnClearTable();	
							}
						  }
						});
				}
			});





			

			$(".edit").live("click",function()
			{
				var item = $(this).attr('data-id');
				$.ajax({
					  type: 'POST',
					  url: '/administrator/news/edit',
					  dataType: 'json',
					  data: {
						  itemId : item,
						  csrf : $("#csrf").val(),
						  },
					  success: function(data){
					  	if(data.error != 0)
					  	{
							alert('ERROR: DB');
						}
					  	else
					  	{	
						  	window.news_id = item;
					  		$("#news_title_edit").val(data.data.title);
					  		$("#editor_edit").val(data.data.text);
					  		$("#datepicker_edit").val(data.data.date);
					  		$("#access_edit option[selected]").removeAttr("selected");
					  		$("#access_edit option[value='"+data.data.access+"']").attr("selected","true");					  		  
							if(data.data.published == "1")
								$("#news_published_edit").attr("checked","true");
							else
								$("#news_published_edit").removeAttr("checked");

							if(data.data.position_left == "1")
								$("#position_left_edit").attr("checked",true);
							else
								$("#position_left_edit").attr("checked",false);

							if(data.data.position_above == "1")
								$("#position_above_edit").attr("checked",true);
							else
								$("#position_above_edit").attr("checked",false);

							$("#dialog-form-edit").dialog('open');
						}
					  }
					});
			});




			
            
    		$("#dialog-form-add").dialog({
    			autoOpen: false,
    			height: 630,
    			width: 625,
    			resizable: false,
    			modal: true,
    			buttons: 
        		{
	    			"Add": function() 
	    			{
	    			      $.ajax({
	    			            type: "POST",
	    			            url: '/administrator/news/add',
	    			            dataType: 'json',
	    			            data: 
		    			        {
									'news_title': $("#news_title_add").val(),
									'news_text' : $("#editor_add").val(),
									'published' : $("#news_published_add").attr('checked'),
									'access' : $("#access_add").val(),
									'csrf' : $("#csrf").val(),
									'date' : $("#datepicker_add").val(),
									'position_left' : $("#position_left").attr('checked'),
									'position_above' : $("#position_above").attr('checked')
			    			    },
	    			            success: function (data) {
									switch(data.error)
									{
										case 1:
											alert('Error: Title is empty');
											break;
										case 2:
											alert('Error: Text is empty');
											break; 
										case 3:
											alert('Error: Date is not valid');
											break; 
										case 4:
											alert('Error: Database');
											break;
										case 5:
											alert('Error: CSRF');
											break;
										case 0:
										default:
											oTable.fnClearTable();
											$("#dialog-form-add").dialog('close');
											break;   
									}
	    			            }
	    			        });
		    		},
	    			"Cancel": function() 
	    			{
	    				$(this).dialog( "close" );
	    			}
    			},
    			});

    		$("#dialog-form-edit").dialog({
    			autoOpen: false,
    			height: 630,
    			width: 625,
    			resizable: false,
    			modal: false,
    			buttons: 
        		{
	    			"Save": function() 
	    			{
	    			      $.ajax({
	    			            type: "POST",
	    			            url: '/administrator/news/add',
	    			            dataType: 'json',
	    			            data: 
		    			        {
			    			        'newsId': window.news_id,
									'news_title': $("#news_title_edit").val(),
									'news_text' : $("#editor_edit").val(),
									'published' : $("#news_published_edit").attr('checked'),
									'access' : $("#access_edit").val(),
									'csrf' : $("#csrf").val(),
									'date' : $("#datepicker_edit").val(),
									'position_left' : $("#position_left_edit").attr('checked'),
									'position_above' : $("#position_above_edit").attr('checked')
			    			    },
	    			            success: function (data) {
									switch(data.error)
									{
										case 1:
											alert('Error: Title is empty');
											break;
										case 2:
											alert('Error: Text is empty');
											break; 
										case 3:
											alert('Error: Date is not valid');
											break; 
										case 4:
											alert('Error: Database');
											break;
										case 5:
											alert('Error: CSRF');
											break;
										case 0:
										default:
											oTable.fnClearTable();
											$("#dialog-form-edit").dialog('close');
											break;   
									}
	    			            }
	    			        });
		    		},
	    			"Cancel": function() 
	    			{
	    				$(this).dialog( "close" );
	    			}
    			},
    			});
                
                var oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/news/ajax-get',
                        "fnServerParams": function ( aoData ) {  aoData.push(); },
                        "fnDrawCallback": function( oSettings ) {display('none');},                      
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100,
                        "aoColumns": [
                            { 
                              "sTitle": "NID",
                              "fnRender": function(obj){ return obj.aData[0]; } 
                            },
                            { 
                              "sTitle": "Title",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Created",
                              "fnRender": function(obj){ return obj.aData[2];} 
                            },
                            { 
                              "sTitle": "Published",
                              "fnRender": function(obj){return obj.aData[3];} 
                            },
                            { 
                                "sTitle": "Published For",
                                "fnRender": function(obj){ return obj.aData[4];} 
                            },
                            { 
                                "sTitle": "Edit",
                                "bSortable": false,
                                "fnRender": function(obj){ return '<a href="#" class="edit" data-id="'+obj.aData[0]+'">Edit</a>'; } 
                            },
                            { 
                                "sTitle": "Delete",
                                "bSortable": false,
                                "fnRender": function(obj){ return '<a href="#" class="delete" data-id="'+obj.aData[0]+'">Delete</a>'; } 
                            }
                        ],                                                
                        "aaSorting": [[ 0, "DESC" ]]
                         
                } );
       });
        
function display(status)
{
	$('#mask').css('display', status);
	$('#loading').css('display', status);         
}

function clear_dialog()
{
	$("#news_title_add").val("");
	$("#editor_add").val("");
	$("#access_add option[selected]").removeAttr("selected");
	$("#access_add option[value='3']").attr("selected","true");
	$("#news_published_add").attr("checked","true");
	$("#datepicker_add").val('<?php echo $this->time;?>');

}
</script>


<div id="dialog-form-add" title="Add news">
	<form>
		<form method="post">
			<p>
				Title:<br/>
				<input type="text" name="news_title" id="news_title_add">
			</p>
			<br/>			
			<p>
				Text<br/>
				<textarea id="editor_add" name="news_text">
				<p>&nbsp;</p>
				</textarea>
			</p>
			<br/>
			<p>
			Publish for:<br/>
			<select name="access" id="access_add">
				<option value="1">AdX registered</option>
				<option value="2">Non-AdX registered</option>
				<option value="4">Only Burst</option>
				<option value="5">Rubicon publishers only</option>
				<option value="3" selected="true">All</option>			
			</select>
			</p>
			<br>
			<p>
				<input type="checkbox" name="position_left" id="position_left" value="1"> add it to the left panel
			</p>
			<br>
			<p>
				<input type="checkbox" name="position_above" id="position_above" value="1"> add it above the reporting
			</p>
			<br/>
			<p>Date:<br/> <input type="text" id="datepicker_add" name="news_date_add" value="<?php echo $this->time;?>" /></p><br/><br/> 
			<p>Published:<br/> <input type="checkbox" id="news_published_add" name="news_published" checked="true" /></p>
		</form>
	</form>
</div>

<div id="dialog-form-edit" title="Edit news">
	<form>
		<form method="post">
			<p>
				Title:<br/>
				<input type="text" name="news_title" id="news_title_edit">
			</p>
			<br/>			
			<p>
				Text<br/>
				<textarea id="editor_edit" name="news_text">
				<p>&nbsp;</p>
				</textarea>
			</p>
			<br/>
			<p>
			Publish for:<br/>
			<select name="access" id="access_edit">
				<option value="1">AdX registered</option>
				<option value="2">Non-AdX registered</option>
				<option value="4">Only Burst</option>	
				<option value="5">Rubicon publishers only</option>							
				<option value="3" selected="true">All</option>			
			</select>
			</p>
			<br>
			<p>
				<input type="checkbox" name="position_left" id="position_left_edit" value="1"> add it to the left panel
			</p>
			<br>
			<p>
				<input type="checkbox" name="position_above" id="position_above_edit" value="1"> add it above the reporting
			</p>
			<br/>
			<p>Date:<br/> <input type="text" id="datepicker_edit" name="news_date_edit" value="<?php echo $this->time;?>" /></p><br/><br/> 
			<p>Published:<br/> <input type="checkbox" id="news_published_edit" name="news_published" checked="true" /></p>
			<input type="hidden" id="csrf" value="<?php echo $this->csrf;?>" name="csrf">
		</form>
	</form>
</div>


<h1>News</h1>
<div class="contUsL" style="width: 750px;">
	<button id="add_news">ADD</button>
	<br/><br />
		<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
			<thead>
				<tr>
					<th width="5%">NID</th>
					<th width="30%">Title</th>
					<th width="10%">Created</th>
					<th width="20%">Published</th>
					<th width="20%">Published For</th>
					<th width="5%">Edit</th>
					<th width="5%">Delete</th>
				</tr>
			</thead>
			<tbody></tbody>
			<tfoot>
				<tr>
					<th>NID</th>
					<th>Title</th>
					<th>Created</th>
					<th>Published</th>
					<th>Published For</th>
					<th>Edit</th>
					<th>Delete</th>                   
				</tr>
			</tfoot>
	</table>
</div>
 
<div id="mask"></div>
<div id="loading"><span>processing...</span></div>
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
