<div class="contactUs">
<?php if(!$this->message): ?>
        	<h1>Contact Us</h1>
            <p class="contUsSlog">Use the form below to contact us with any questions or concerns.</p>
            <div id="contForm">
            
			<form method="post" class="sign-up">
            <input type="hidden" name="publisherID" value="<?php echo $this->formValues['publisherID'] ?>" />
                	<div class="contUsL">
            <p><label>Full Name: </label><input type="text" name="FullName" value="<?php echo $this->formValues['FullName'] ?>" /></p>
            <?php if($this->formErrors['FullName']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['FullName'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>            
            <p><label>Title: </label><input type="text" name="Title" value="<?php echo $this->formValues['Title'] ?>" /></p>
            <?php if($this->formErrors['Title']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['Title'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <p><label>Company: </label><input type="text" name="Company" value="<?php echo $this->formValues['Company'] ?>" /></p>
            <?php if($this->formErrors['Company']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['Company'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>            
            <p><label>E-mail: </label><input type="text" name="email" value="<?php echo $this->formValues['email'] ?>" /></p>
            <?php if($this->formErrors['email']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['email'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <p><label>Phone: </label><input type="text" name="phone" value="<?php echo $this->formValues['phone'] ?>" /></p>
            <?php if($this->formErrors['phone']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['phone'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>                                        
            <p><label>Type of Inquiry: </label>
                <select name="inquiry" id="inquiry">
                    <option>Please Select...</option>
                    <option value="Advertising" <?php echo $this->formValues['inquiry']=='Advertising' ? 'selected' : '' ?> >Advertising</option>
                    <option value="Publisher" <?php echo $this->formValues['inquiry']=='Publisher' ? 'selected' : '' ?> >Publisher</option>
                    <option value="General" <?php echo $this->formValues['inquiry']=='General' ? 'selected' : '' ?> >General</option>
                    <option value="Billing" <?php echo $this->formValues['inquiry']=='Billing' ? 'selected' : '' ?> >Billing</option>
                </select>
            </p>
            <?php if($this->formErrors['inquiry']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['inquiry'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>   
			<?php if($this->formValues['site']): ?>
	            <p><label>Affected Site: </label>
	            	<?php if(count($this->formValues['site'])==1): ?>
	            		<select name="site" id="site">
	            			<?php foreach($this->formValues['site'] as $site): ?>
	            				<option value="<?php echo $site ?>"><?php echo $site ?></option>
	            			<?php endforeach; ?>
	            		</select>
	            	<?php else: ?>
	            		<select name="site" id="site">
	            		<option>Choose One</option>
	            			<?php foreach($this->formValues['site'] as $site): ?>
	            				<option value="<?php echo $site ?>"><?php echo $site ?></option>
	            			<?php endforeach; ?>
	            		</select>	            	
	            	<?php endif; ?>
	            </p>
	            <?php if($this->formErrors['site']): ?>
	                <ul class="error">
	                <?php foreach($this->formErrors['site'] as $errors): ?>
	                    <li><?php echo $errors ?></li>
	                <?php endforeach; ?>
	                </ul>
	            <?php endif; ?>   
            <?php endif; ?>
                    </div>
                                                                                                                                                                         
            <div><textarea name="question" rows="10" cols="10" onfocus="if (this.value=='Enter message here...') this.value=''" onblur="if (this.value==''){this.value='Enter message here...'}"><?php echo $this->formValues['question'] ? $this->formValues['question'] : "Enter message here..." ?></textarea></div>
            <?php if($this->formErrors['question']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['question'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
                    <div class="contBtn"> 
                    <p>Or feel free to email us at <a href="mailto:support@madadsmedia.com" title="">support@madadsmedia.com</a></p>           
                    <a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Send Message</a>
                    </div>    
            <input type="hidden" id="csrf" value="<?php echo $this->csrf;?>" name="csrf">                                       
            <input type="submit" id="subForm" style="display: none;" />
            </form>
            </div>
			<div class="clear" style="height:40px;"></div>            
        	<h1>Our Locations</h1>
            <p class="contUsSlog"></p>
			<br>
			<div class="contUsL" id="location" style="width:880px;">
			<div style="float:left; width:220px;">
			<b class="headquaters">New Jersey (Headquarters)</b><br>
			717 Fellowship Rd.<br>
			Suite D<br>
			Mount Laurel, NJ 08054<br>
			856-874-8928<br>
			</div>
			<!--<div style="float:left; width:220px;">
			<b class="headquaters">New Jersey (Headquaters)</b><br>
			717 Fellowship Rd.<br>
			Suite D<br>
			Mount Laurel, NJ 08054<br>
			856-874-8928<br>
			</div>-->
			</div>          
<?php else: ?>
    <h1><?php echo $this->message ?></h1>
<?php endif; ?>            
</div>
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
    Cufon.replace('.error', {color: 'red'});	    

</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('#location');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.headquaters');		
</script>