<?php
    // Content-Type
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    // doctype
    echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php
        // meta tegs
        echo $this->headMeta();
    ?>
    <?php
        // title
        echo $this->headTitle();
    ?>
    <?php
        // styles and javascripts
        $this->headLink()->appendStylesheet($this->baseUrl().'/styles/style_admin.css');
        $this->headLink()->appendStylesheet($this->baseUrl().'/styles/reset.css');
        //$this->headLink()->appendStylesheet($this->baseUrl().'/styles/jqueryui.css');
        $this->headLink()->appendStylesheet($this->baseUrl().'/styles/jquery-ui.min.css');
        $this->headLink()->appendStylesheet($this->baseUrl().'/styles/jquery.jqplot.min.css');
        $this->headLink()->appendStylesheet($this->baseUrl().'/styles/table.css');
        $this->headLink()->appendStylesheet($this->baseUrl().'/styles/form.css');

        echo $this->headLink();

        $this->headScript()->offsetSetFile(1,$this->baseUrl().'/js/jquery-1.6.2.min.js', 'text/javascript');
        $this->headScript()->offsetSetFile(2,$this->baseUrl().'/js/jquery-ui.min.js', 'text/javascript');
        $this->headScript()->offsetSetFile(3,$this->baseUrl().'/js/jquery.ulslide.js', 'text/javascript');
        $this->headScript()->offsetSetFile(4,$this->baseUrl().'/js/excanvas.js', 'text/javascript', array('conditional' => 'lt IE 9'));
        $this->headScript()->offsetSetFile(5,$this->baseUrl().'/js/jquery.jqplot.min.js', 'text/javascript');

        $this->headScript()->offsetSetFile(6,$this->baseUrl().'/js/plugins/jqplot.highlighter.min.js', 'text/javascript');
        $this->headScript()->offsetSetFile(7,$this->baseUrl().'/js/plugins/jqplot.cursor.min.js', 'text/javascript');
        $this->headScript()->offsetSetFile(8,$this->baseUrl().'/js/plugins/jqplot.dateAxisRenderer.min.js', 'text/javascript');

        $this->headScript()->offsetSetFile(9,$this->baseUrl().'/js/plugins/jqplot.canvasTextRenderer.min.js', 'text/javascript');
        $this->headScript()->offsetSetFile(10,$this->baseUrl().'/js/plugins/jqplot.canvasAxisTickRenderer.min.js', 'text/javascript');
        $this->headScript()->offsetSetFile(11,$this->baseUrl().'/js/plugins/jqplot.categoryAxisRenderer.min.js', 'text/javascript');
        $this->headScript()->offsetSetFile(12,$this->baseUrl().'/js/plugins/jqplot.barRenderer.min.js', 'text/javascript');
        $this->headScript()->offsetSetFile(13,$this->baseUrl().'/js/plugins/jqplot.pointLabels.min.js', 'text/javascript');

        $this->headScript()->offsetSetFile(14,$this->baseUrl().'/js/jquery.dataTables.min.js', 'text/javascript');

        $this->headScript()->offsetSetFile(15,$this->baseUrl().'/js/ckeditor/ckeditor.js','text/javascript');
        $this->headScript()->offsetSetFile(16,$this->baseUrl().'/js/ckeditor/adapters/jquery.js','text/javascript');

        $this->headScript()->offsetSetFile(17,$this->baseUrl().'/js/jquery-date-format.js','text/javascript');

        echo $this->headScript();
    ?>
<link rel="icon" type="image/x-icon" href="/images/favicon.ico" />

<style type="text/css">

    ul li a { cursor: pointer; }

    .report-sublist { display: none; background-color: #F9F9F9; }
    .report-sublist li {  }
    .report-sublist li:hover { background-color: #E3F2E1; }
    #menu_optimization li a, #menu_recruiting li a { background: none; }

</style>

<script type="text/javascript">

   $(document).ready(function(){

       if(<?php echo $this->layout()->nav=='optimization_done' ? 1 : 0 ?>||<?php echo $this->layout()->nav=='optimization_pending' ? 1 : 0 ?>||<?php echo $this->layout()->nav=='optimization_all' ? 1 : 0 ?>)
            $('#menu_optimization').css('display', 'block');
       else $('#menu_optimization').css('display', 'none');

       <?php
	   		$controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
	    	if ($controller == "recruiting"):
    	?>
	    	$('#menu_recruiting').show();
	   	<?php
	   		endif;
    	?>
    	
        $('.adminSearch input[name="valueSearch"]').keyup(function(e){ if(e.which == 13){ $('.adminSearch input[type="button"]').click(); } });        
    	
   });

   function changeTask(id, status, link)
   {
        displayAdmin('block');

        $.ajax({ url : '/administrator/ajax/set-task-status',
                     data : { id : id, status : status },
                     type : "POST",
                     async: true, 
                     dataType : "json",

             success : function(response) { location.reload();  

             }, error : function(){ displayAdmin('none'); alert('ajax request return error'); }});     
        
   }
   
   function displayAdmin(status)
   {       
        $('#mask-admin').css('display', status);
        $('#loading-admin').css('display', status);       
   }
   
   function searchAdmin()
   {
       var valueSearch = $('input[name="valueSearch"]').val();       
        if(valueSearch.length){ window.location.href='/administrator/all/index/value/'+valueSearch; 
                              /*window.open("/administrator/all/index/value/"+valueSearch);*/ }
   }      
</script>

</head>
<body>
<div id="wrapper">
 <div id="mainInsideIn">
	<!--header top-->
    <div id="headerTop">
    	<div id="hTopInn">
	    	<div id="logo"><a href="/" title=""><img src="/images/logo_new.png" width="316" height="101" alt="" /></a></div>
            <div id="topMenu">
            	<ul>
                  <?php if(Zend_Auth::getInstance()->getIdentity()): ?>
                    <li><a href="/" title=""><span>Home</span></a></li>
                        <li <?php if($this->layout()->nav=='dashboard') echo 'class="cur"' ?>><a href="/administrator/dashboard/"><span>Dashboard</span></a></li>
                	<li <?php if($this->layout()->nav=='report' || $this->layout()->nav=='adcode' || $this->layout()->nav=='contact' || $this->layout()->nav=='password' || $this->layout()->nav=='payment') echo 'class="cur"' ?>><a href="/report/" ><span>My Account</span></a></li>
                	<li <?php if($this->layout()->nav=='contacts') echo 'class="cur"' ?>><a href="/contact-us/" ><span>Contact Us</span></a></li>
                  <?php else: ?>
                    <li <?php if($this->layout()->nav=='home') echo 'class="cur"' ?> ><a href="/" title=""><span>Home</span></a></li>
                	<li <?php if($this->layout()->nav=='login') echo 'class="cur"' ?> ><a href="/login/" title=""><span>Login</span></a></li>
                	<li <?php if($this->layout()->nav=='apply') echo 'class="cur"' ?> ><a href="/registration/" title=""><span> Apply Now</span></a></li>
                	<li <?php if($this->layout()->nav=='about') echo 'class="cur"' ?> ><a href="/about-us/" title=""><span>Why Us?</span></a></li>
                	<li <?php if($this->layout()->nav=='contacts') echo 'class="cur"' ?> ><a href="/contact-us/" title=""><span>Contact Us</span></a></li>
                 <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
	<!--//header top-->
    <!--content-->
    <div id="content" style="width: 100%">
        <?php if($this->PaymentError==1): ?>
            <a href="/payment" style="background-color:#D73A3A; border:1px solid #D73A3A; display:block; width:950px; color:#FFF; font-weight:bold; font-size:16px; text-align:center; padding:3px;">Please update your payment profile in order to receive payments.</a>
        <?php endif; ?>

        <?php if($this->layout()->countAlerts>0): ?>
            <a href="/administrator/alerts/" style="background-color:#FF0000; border:1px solid #FF0000; display:block; width:950px; color:#FFF; font-weight:bold; font-size:16px; text-align:center; padding:3px; margin-top:2px;">You Have (<?php echo $this->layout()->countAlerts ?>) Alert For Today</a>
        <?php endif; ?>

        <?php if($this->layout()->siteCorrection):?>
            <a href="/administrator/pending-correction/" style="background-color:#18A037; border:1px solid #D73A3A; display:block; width:950px; color:#FFF; font-weight:bold; font-size:16px; text-align:center; padding:3px;"><?php echo $this->layout()->siteCorrection['SiteName']?> has corrections pending.  Please follow up now.</a>
        <?php endif;?>

            <div id="report" style="width: 1150px;">
        	<!--LEFT COLLUM-->
            <div id="reportL">
                <div class="adminSearch">
                    <input type="text" name="valueSearch" placeholder="Search Admin" value="<?php echo isset($this->layout()->searchValue) ? $this->layout()->searchValue : ''; ?>"/>
                    <input type="button" onClick="searchAdmin()" value="Search"/>
                </div> 
                <br><br><br>            
				<ul>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
                        <li class="title">Today's Checklist</li>    
                        
                        <?php foreach($this->layout()->dataTask as $iter):?>
                        
                        	<?php if($iter['link'] == '/administrator/index/approved/') $iter['link'] = '/administrator/index/approved#from_checklist';?>
                            <?php if($iter['status'] == 1):?>
                                <li><input type="checkbox" style="margin: 5px 7px 0px 0px; float: left;" onClick="changeTask(<?php echo $iter['id'].', 0' ?>)" checked="checked"/><a style="background: none; padding: 0px;" title=""><span style="color: grey; text-decoration: line-through;"><?php echo $iter['name'];?></span></a></li>
                            <?php else:?>
                                <li><input type="checkbox" style="margin: 5px 7px 0px 0px; float: left;" onClick="changeTask(<?php echo $iter['id'].', 1' ?>)" /><a style="background: none; padding: 0px;" title="" href="<?php echo $iter['link']?>"><span><?php echo $iter['name'];?></span></a></li>
                            <?php endif;?>    
                                
                        <?php endforeach;?>
                    <?php endif; ?>
				
					<li class="title">User Management</li>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
					<li <?php if($this->layout()->nav=='dashboard') echo 'class="cur"' ?> ><a href="/administrator/dashboard" title=""><span>Dashboard</span></a></li>
                    <?php endif; ?>
					<li <?php if($this->layout()->nav=='new') echo 'class="cur"' ?> ><a href="/administrator/" title=""><span>New Users (<?php echo $this->layout()->countNewUsers['count'] ?>)</span></a></li>
					<!--
					<li <?php if($this->layout()->nav=='new-2') echo 'class="cur"' ?> ><a href="/administrator/index/new2/" title=""><span>New Users - 2 (<?php echo $this->layout()->countNewUsers2['count'] ?>)</span></a></li>-->
					<li <?php if($this->layout()->nav=='approve') echo 'class="cur"' ?> ><a href="/administrator/index/approved/" title="" class="contInfLink"><span>Approved Users</span></a></li>
					<li <?php if($this->layout()->nav=='deny') echo 'class="cur"' ?> ><a href="/administrator/index/all/" title="" class="addCode"><span>Denied Users</span></a></li>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
					<li <?php if($this->layout()->nav=='adx_registration') echo 'class="cur"' ?> ><a href="/administrator/adx/index" title="" class="paymProf"><span>AdX Registrations (<?php echo $this->layout()->countAdxRegistration;?>)</span></a></li>
                    <?php endif; ?>
					<li <?php if($this->layout()->nav=='newWaiting') echo 'class="cur"' ?> ><a href="/administrator/index/new-waiting" title=""><span>New Users - Waiting (<?php echo $this->layout()->countNewUsersWaiting['count'] ?>)</span></a></li>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
					<li <?php if($this->layout()->nav=='user_news') echo 'class="cur"' ?> ><a href="/administrator/news/index" title=""><span>News</span></a></li>
                    <?php endif; ?>
					
					<li class="title">Website Management</li>
					<li <?php if($this->layout()->nav=='mewSites') echo 'class="cur"' ?> ><a href="/administrator/sites/new/" title="" class="addCode"><span>New Websites (<?php echo $this->layout()->countNewSites ?>)</span></a></li>
					<li <?php if($this->layout()->nav=='co-site') echo 'class="cur"' ?>><a href="/administrator/co-site-approvals/" title="" class="paymProf"><span>Co-Site Approvals (<?php echo $this->layout()->countCoSiteApprov ?>)</span></a></li>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
					<li <?php if($this->layout()->nav=='pending-correct') echo 'class="cur"' ?>><a href="/administrator/pending-correction/" title="" class="paymProf"><span>Pending Correction (<?php echo $this->layout()->countPending ?>)</span></a></li>
                    <?php endif; ?>
					<li <?php if($this->layout()->nav=='approveSites') echo 'class="cur"' ?> ><a href="/administrator/sites/approved/" title="" class="contInfLink"><span>Approved Websites</span></a></li>
					<li <?php if($this->layout()->nav=='inactiveSites') echo 'class="cur"' ?> ><a href="/administrator/sites/inactive/" title="" class="contInfLink"><span>Inactive Websites</span></a></li>
					<li <?php if($this->layout()->nav=='denySites') echo 'class="cur"' ?> ><a href="/administrator/sites/denied/" title="" class="addCode"><span>Denied WebSites</span></a></li>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
					<li <?php if($this->layout()->nav=='addSites') echo 'class="cur"' ?>><a href="/administrator/sites/add-ajax" title="" class="paymProf"><span>Add New Sites</span></a></li>
                                    <!--<li <php if($this->layout()->nav=='optimization_done' || $this->layout()->nav == 'optimization_pending') echo 'class="cur"' ?>><a onClick="$('#menu_optimization').toggle('slow')"><span class="addCode">Site Optimizations</span></a></li>
					<div id="menu_optimization" class="report-sublist">
						<li <php if($this->layout()->nav == 'optimization_pending') echo 'class="cur"' ?>><a href="/administrator/optimization/pending"><span>Pending Optimizing</span></a></li>
						<li <php if($this->layout()->nav=='optimization_done') echo 'class="cur"' ?>><a href="/administrator/optimization/done"><span>Done Optimizing</span></a></li>
						<li <php if($this->layout()->nav == 'optimization_all') echo 'class="cur"' ?>><a href="/administrator/optimization/all"><span>All Websites</span></a></li>
					</div>-->
					<li <?php if($this->layout()->nav=='floor_tags') echo 'class="cur"' ?>><a href="/administrator/cpm/index/" title="" class="paymProf"><span>Floor Tags (<?php echo $this->layout()->countNewFloor ?>)</span></a></li>
					<li <?php if($this->layout()->nav=='tags') echo 'class="cur"' ?> ><a href="/administrator/tags/" title="" class="paymProf"><span>Generate Ad Tags (<?php echo $this->layout()->test['count']+$this->layout()->testAdx['count']; ?>)</span></a></li>
					<li <?php if($this->layout()->nav=='deductedSites') echo 'class="cur"' ?> ><a href="/administrator/sites/deducted/" title="" class="contInfLink"><span>Deducted Revenue</span></a></li>
					<li <?php if($this->layout()->nav=='updatePlacement') echo 'class="cur"' ?> ><a href="/administrator/pubmatic/update-placement/" title="" class="contInfLink"><span>Update Pubmatic Placements</span></a></li>
                    <li><a href="/administrator/revshares" title="" class="contInfLink"><span>Sites Revshares</span></a></li>
                    <?php endif; ?>
					<li class="title">Content Management</li>
					<li <?php if($this->layout()->nav=='checker') echo 'class="cur"' ?>><a href="/administrator/checker/" title="" class="addCode"><span>Content Checker</span></a></li>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
					<li><a href="/administrator/index/urllookup" title="" class="addCode"><span>URL Lookup</span></a></li>
					<li><a href="/administrator/index/psaurls" title="" class="addCode"><span>PSA URLs</span></a></li>
					<li <?php if($this->layout()->nav=='sizes-requests') echo 'class="cur"' ?>><a href="/administrator/sizes-requests"  title="" class="paymProf"><span>Ad Size Requests (<?php echo $this->layout()->countWantBaner ?>)</span></a></li>
					<li <?php if($this->layout()->nav=='burts-requests') echo 'class="cur"' ?>><a href="/administrator/burst/burst-requests"  title="" class="paymProf"><span>Burst Upgrades (<?php echo $this->layout()->countBurstRequest ?>)</span></a></li>
					<li <?php if($this->layout()->nav=='iframe-requests') echo 'class="cur"' ?>><a href="/administrator/iframe-requests"  title="" class="paymProf"><span>Iframe Tag Requests (<?php echo $this->layout()->countWantIframe ?>)</span></a></li>
                    <?php endif; ?>
					<li class="title">Settings & Stats</li>
					<!--<li><a href="#" title="" class="contInfLink" onClick="$('#menu_pubmatic').toggle('slow'); return false;"><span>PubMatic API</span></a></li>
					<div id="menu_pubmatic" class="report-sublist">
						<li><a href="/administrator/pubmatic/publisher"><span>Users</span></a></li>
						<li><a href="/administrator/pubmatic/sites"><span>Sites</span></a></li>
					</div>-->
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
                    <li><a href="/administrator/pp-accounts" title="" class="addCode"><span>PulsePoints accounts</span></a></li>
                    <li><a href="/administrator/networks" title=""><span>Networks</span></a></li>
                    <li><a href="/administrator/api-manager"><span>API Manager</span></a></li>
					<li <?php if($this->layout()->nav=='brust_cpm') echo 'class="cur"' ?>><a href="/administrator/burst/" title=""><span>Burst CPM & Revenue</span></a></li>
					<li <?php if($this->layout()->nav=='csv2') echo 'class="cur"' ?>><a href="/administrator/sites/csv2/" title="" class="paymProf"><span>Rubicon CSV 2</span></a></li>
					<li <?php if($this->layout()->nav=='pub_csv') echo 'class="cur"' ?>><a href="/administrator/sites/pubmatic-csv/" title="" class="paymProf"><span>Pubmatic CSV</span></a></li>
                    <li <?php if($this->layout()->nav=='amazon_csv') echo 'class="cur"' ?>><a href="/administrator/sites/amazon-csv/" title="" class="paymProf"><span>Amazon CSV</span></a></li>
                    <li <?php if($this->layout()->nav=='pulse_csv') echo 'class="cur"' ?>><a href="/administrator/sites/pulse-csv/" title="" class="paymProf"><span>PulsePoint CSV</span></a></li>
                    <li <?php if($this->layout()->nav=='popC_csv') echo 'class="cur"' ?>><a href="/administrator/sites/pop-csv/" title="" class="paymProf"><span>PopCash CSV</span></a></li>
                    <li <?php if($this->layout()->nav=='sekindo_csv') echo 'class="cur"' ?>><a href="/administrator/sites/sekindo-csv/" title="" class="paymProf"><span>Sekindo CSV</span></a></li>
                    <li <?php if($this->layout()->nav=='aol_csv') echo 'class="cur"'; ?>><a href="/administrator/sites/aol-csv" title="" class="paymProf"><span>AOL CSV</span></a></li>
                    <li <?php if($this->layout()->nav=='aol_outstream_csv') echo 'class="cur"'; ?>><a href="/administrator/sites/aol-outstream-csv" title="" class="paymProf"><span>AOL Outstream CSV</span></a></li>
                    <li <?php if($this->layout()->nav=='b_real_time_csv') echo 'class="cur"'; ?>><a href="/administrator/sites/b-real-time-csv" title="" class="paymProf"><span>bRealTime CSV</span></a></li>
					<li <?php if($this->layout()->nav=='report') echo 'class="cur"' ?>><a href="/administrator/report/" title="" class="paymProf"><span>Execute the report generation</span></a></li>
					<?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
                	<li <?php if($this->layout()->nav=='payDue') echo 'class="cur"' ?> ><a href="/administrator/payments/" title=""><span>Payments Due</span></a></li>
                	<li <?php if($this->layout()->nav=='payDueBeta') echo 'class="cur"' ?> ><a href="/administrator/payments/beta" title=""><span>Payments Due 2 (Beta)</span></a></li>
					<li <?php if($this->layout()->nav=='daily') echo 'class="cur"' ?> ><a href="/administrator/index/daily/" title=""><span>Daily Stats</span></a></li>
                	<?php endif; ?>
					<li <?php if($this->layout()->nav=='impress') echo 'class="cur"' ?> ><a href="/administrator/sites/impress-stats/" title=""><span>Impressions stats</span></a></li>
					<?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
					<li <?php if($this->layout()->nav=='network') echo 'class="cur"' ?> ><a href="/administrator/index/network/" title=""><span>Network Stats</span></a></li>
					<li <?php if($this->layout()->nav=='new-account') echo 'class="cur"' ?> ><a href="/administrator/index/new-account/" title=""><span>New Accounts</span></a></li>					
                    <?php endif; ?>
					<?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
					<li><a href="/administrator/referral/index/" title="" class="addCode"><span>Referral System</span></a></li>
					<li><a href="/administrator/referral/user/" title="" class="addCode"><span>Referred Users</span></a></li>
					<li><a href="/administrator/setting/edit/" title="" class="addCode"><span>Settings</span></a></li>
					<?php endif; ?>
					<li><a href="/administrator/system/index" title="" class="addCode"><span>System</span></a></li>
                    <?php endif; ?>
					<?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
					<li><a href="/administrator/sizes/index/" title="" class="addCode"><span>Sizes</span></a></li>
					<li <?php if($this->layout()->nav=='contact_notification') echo 'class="cur"'; ?>><a href="/administrator/contactnotification/index/" title="" class="paymProf"><span>Contact Notification</span></a></li>
					<li <?php if($this->layout()->nav=='blacklists') echo 'class="cur"' ?> ><a href="/administrator/sites/blacklists/" title=""><span>Blacklists</span></a></li>
					<li <?php if($this->layout()->nav=='exchange') echo 'class="cur"' ?>><a href="/administrator/exchange/" title="" class="addCode"><span>Exchange Stats</span></a></li>
					<li><a style='background: url("/images/leftLi.png") no-repeat scroll left -62px transparent;' href="/administrator/sites/notification/" title="" class="addCode"><span>Notifications</span></a></li>
					<?php endif; ?>
					<?php if (Zend_Auth::getInstance()->getIdentity()->email == "fcsadmin@gmail.com"){ ?><li><a href="/administrator/system/activity" title="" class="addCode"><span>Activity</span></a></li><?php } ?>
					<li <?php if($this->layout()->nav=='alerts') echo 'class="cur"' ?> ><a href="/administrator/alerts/" title="" class="contInfLink"><span>Alerts</span></a></li>
                    <?php if (Zend_Auth::getInstance()->getIdentity()->role != "support"): ?>
					<li><a href="#" title="" class="contInfLink" onClick="$('#menu_recruiting').toggle('slow'); return false;"><span>Recruiting Emailer</span></a></li>
					<div id="menu_recruiting" class="report-sublist">
						<li><a href="/administrator/recruiting/index"><span>Activities</span></a></li>
						<li><a href="/administrator/recruiting/pending"><span>Leads</span></a></li>
						<li><a href="/administrator/recruiting/responded"><span>Opportunities</span></a></li>
						<li><a href="/administrator/recruiting/neverresponded"><span>Never Responded</span></a></li>
						<li><a href="/administrator/recruiting/closed"><span>Closed Leads</span></a></li>
                        <li><a href="/administrator/recruiting/closed-opportunities"><span>Closed Opportunities</span></a></li>
						<li><a href="/administrator/recruiting/stats"><span>Recruiting Stats</span></a></li>
						<li><a href="/administrator/recruiting/potentialsites?page=0"><span>Sites</span></a></li>
					</div>
					<li><a href="/administrator/exchangesites/index/" title="" class="addCode"><span>Potential Exchange Sites</span></a></li>
					<li class="addCode"><a href="/ticket/upload/scp/tickets.php" target="_blank" title="" style="background-position: left -61px;"><span>Mail</span></a></li>
                        <li <?php if($this->layout()->nav=='task') echo 'class="cur"' ?>><a href="/administrator/task/index" title="" class="paymProf"><span>Task</span></a></li>
                    <?php endif; ?>
				</ul>
				<?php /*
            	<ul>    <li <?php if($this->layout()->nav=='dashboard') echo 'class="cur"' ?> ><a href="/administrator/dashboard" title=""><span>Dashboard</span></a></li>
                	<li <?php if($this->layout()->nav=='new') echo 'class="cur"' ?> ><a href="/administrator/" title=""><span>New Users (<?php echo $this->layout()->countNewUsers['count'] ?>)</span></a></li>
                        <li <?php if($this->layout()->nav=='co-site') echo 'class="cur"' ?>><a href="/administrator/co-site-approvals/" title="" class="paymProf"><span>Co-Site Approvals (<?php echo $this->layout()->countCoSiteApprov ?>)</span></a></li>
                        <li <?php if($this->layout()->nav=='sizes-requests') echo 'class="cur"' ?>><a href="/administrator/sizes-requests"  title="" class="paymProf"><span>Ad Size Requests (<?php echo $this->layout()->countWantBaner ?>)</span></a></li>
                	<li <?php if($this->layout()->nav=='newWaiting') echo 'class="cur"' ?> ><a href="/administrator/index/new-waiting" title=""><span>New Users - Waiting (<?php echo $this->layout()->countNewUsersWaiting['count'] ?>)</span></a></li>
                        <li <?php if($this->layout()->nav=='denied-url') echo 'class="cur"' ?> ><a href="/administrator/sites/denied-url/" title="" class="addCode"><span>Banned URLs (<?php echo $this->layout()->countDeniedUrl ?>)</span></a></li>
               	        <li <?php if($this->layout()->nav=='deny') echo 'class="cur"' ?> ><a href="/administrator/index/all/" title="" class="addCode"><span>Denied Users</span></a></li>
                        <li <?php if($this->layout()->nav=='denySites') echo 'class="cur"' ?> ><a href="/administrator/sites/denied/" title="" class="addCode"><span>Denied WebSites</span></a></li>
                	<li <?php if($this->layout()->nav=='approve') echo 'class="cur"' ?> ><a href="/administrator/index/approved/" title="" class="contInfLink"><span>Approved Users</span></a></li>
                	<li <?php if($this->layout()->nav=='approveSites') echo 'class="cur"' ?> ><a href="/administrator/sites/approved/" title="" class="contInfLink"><span>Approved Websites</span></a></li>
                	<li <?php if($this->layout()->nav=='inactiveSites') echo 'class="cur"' ?> ><a href="/administrator/sites/inactive/" title="" class="contInfLink"><span>Inactive Websites</span></a></li>
                        <li <?php if($this->layout()->nav=='deductedSites') echo 'class="cur"' ?> ><a href="/administrator/sites/deducted/" title="" class="contInfLink"><span>Deducted Revenue</span></a></li>
                        <li <?php if($this->layout()->nav=='impress') echo 'class="cur"' ?> ><a href="/administrator/sites/impress-stats/" title=""><span>Impressions stats</span></a></li>
                        <li <?php if($this->layout()->nav=='adx_registration') echo 'class="cur"' ?> ><a href="/administrator/adx/index" title="" class="paymProf"><span>AdX Registrations (<?php echo $this->layout()->countAdxRegistration;?>)</span></a></li>
                        <?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
                        <li><a style='background: url("/images/leftLi.png") no-repeat scroll left -62px transparent;' href="/administrator/sites/notification/" title="" class="addCode"><span>Notifications</span></a></li>
                        <?php endif; ?>
                	<li <?php if($this->layout()->nav=='tags') echo 'class="cur"' ?> ><a href="/administrator/tags/" title="" class="paymProf"><span>Generate Ad Tags (<?php echo $this->layout()->test['count']+$this->layout()->testAdx['count']; ?>)</span></a></li>
                	<li <?php if($this->layout()->nav=='addSites') echo 'class="cur"' ?>><a href="/administrator/sites/add-ajax" title="" class="paymProf"><span>Add New Sites</span></a></li>
                        <?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
                	<li <?php if($this->layout()->nav=='blacklists') echo 'class="cur"' ?> ><a href="/administrator/sites/blacklists/" title=""><span>Blacklists</span></a></li>
                        <?php endif; ?>
                	<li <?php if($this->layout()->nav=='mewSites') echo 'class="cur"' ?> ><a href="/administrator/sites/new/" title="" class="addCode"><span>New Websites (<?php echo $this->layout()->countNewSites ?>)</span></a></li>
                        <?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
                	<li <?php if($this->layout()->nav=='payDue') echo 'class="cur"' ?> ><a href="/administrator/payments/" title=""><span>Payments Due</span></a></li>
                	<li <?php if($this->layout()->nav=='network') echo 'class="cur"' ?> ><a href="/administrator/index/network/" title=""><span>Network Stats</span></a></li>
                        <li <?php if($this->layout()->nav=='daily') echo 'class="cur"' ?> ><a href="/administrator/index/daily/" title=""><span>Daily Stats</span></a></li>
                        <?php endif; ?>
						<li><a href="/administrator/exchangesites/index/" title="" class="addCode"><span>Potential Exchange Sites</span></a></li>
                        <?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
                        <li><a href="/administrator/referral/index/" title="" class="addCode"><span>Referral System</span></a></li>
                        <li><a href="/administrator/referral/user/" title="" class="addCode"><span>Referred Users</span></a></li>
                        <?php endif; ?>
                        <li><a href="#" title="" class="contInfLink" onClick="$('#menu_recruiting').toggle('slow'); return false;"><span>Recruiting Emailer</span></a></li>
                        <div id="menu_recruiting" class="report-sublist">
	                        	<li><a href="/administrator/recruiting/index"><span>Activities</span></a></li>
	                        	<li><a href="/administrator/recruiting/pending"><span>Pending</span></a></li>
                        		<li><a href="/administrator/recruiting/responded"><span>Responded</span></a></li>
                        		<li><a href="/administrator/recruiting/neverresponded"><span>Never Responded</span></a></li>
                                        <li><a href="/administrator/recruiting/closed"><span>Closed Leads</span></a></li>
                                        <li><a href="/administrator/recruiting/stats"><span>Recruiting Stats</span></a></li>
                                        <li><a href="/administrator/recruiting/potentialsites?page=0"><span>Sites</span></a></li>
                        </div>
                        <li <?php if($this->layout()->nav=='csv2') echo 'class="cur"' ?>><a href="/administrator/sites/csv2/" title="" class="paymProf"><span>Rubicon CSV 2</span></a></li>
                        <?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
                        <li><a href="/administrator/setting/edit/" title="" class="addCode"><span>Settings</span></a></li>
                        <?php endif; ?>
			<li><a href="/administrator/system/index" title="" class="addCode"><span>System</span></a></li>
                        <li <?php if($this->layout()->nav=='floor_tags') echo 'class="cur"' ?>><a href="/administrator/cpm/index/" title="" class="paymProf"><span>Floor Tags (<?php echo $this->layout()->countNewFloor ?>)</span></a></li>
                        <?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
                        <li><a href="/administrator/sizes/index/" title="" class="addCode"><span>Sizes</span></a></li>
                        <li <?php if($this->layout()->nav=='contact_notification') echo 'class="cur"'; ?>><a href="/administrator/contactnotification/index/" title="" class="paymProf"><span>Contact Notification</span></a></li>
                        <?php endif; ?>
                        <li <?php if($this->layout()->nav=='optimization_done' || $this->layout()->nav == 'optimization_pending') echo 'class="cur"' ?>><a onClick="$('#menu_optimization').toggle('slow')"><span class="addCode">Site Optimizations</span></a></li>
                        <div id="menu_optimization" class="report-sublist">
                            <li <?php if($this->layout()->nav == 'optimization_pending') echo 'class="cur"' ?>><a href="/administrator/optimization/pending"><span>Pending Optimizing</span></a></li>
                            <li <?php if($this->layout()->nav=='optimization_done') echo 'class="cur"' ?>><a href="/administrator/optimization/done"><span>Done Optimizing</span></a></li>
                            <li <?php if($this->layout()->nav == 'optimization_all') echo 'class="cur"' ?>><a href="/administrator/optimization/all"><span>All Websites</span></a></li>
                        </div>
                        <li <?php if($this->layout()->nav=='report') echo 'class="cur"' ?>><a href="/administrator/report/" title="" class="paymProf"><span>Execute the report generation</span></a></li>
                        <?php if (Zend_Auth::getInstance()->getIdentity()->role == "super"): ?>
                        <li <?php if($this->layout()->nav=='exchange') echo 'class="cur"' ?>><a href="/administrator/exchange/" title="" class="addCode"><span>Exchange Stats</span></a></li>
                        <?php endif; ?>
                        <?php if (Zend_Auth::getInstance()->getIdentity()->email == "fcsadmin@gmail.com"){ ?><li><a href="/administrator/system/activity" title="" class="addCode"><span>Activity</span></a></li><?php } ?>
                	<li <?php if($this->layout()->nav=='alerts') echo 'class="cur"' ?> ><a href="/administrator/alerts/" title="" class="contInfLink"><span>Alerts</span></a></li>
                        <li <?php if($this->layout()->nav=='checker') echo 'class="cur"' ?>><a href="/administrator/checker/" title="" class="addCode"><span>Content Checker</span></a></li>
                        <li><a href="/administrator/index/urllookup" title="" class="addCode"><span>URL Lookup</span></a></li>
                        <li><a href="/administrator/index/psaurls" title="" class="addCode"><span>PSA URLs</span></a></li>

                        <li <?php if($this->layout()->nav=='pending-correct') echo 'class="cur"' ?>><a href="/administrator/pending-correction/" title="" class="paymProf"><span>Pending Correction (<?php echo $this->layout()->countPending ?>)</span></a></li>

                        <li class="addCode"><a href="http://madadsmedia.com/ticket/upload/scp/tickets.php" target="_blank" title="" style="background-position: left -61px;"><span>Mail</span></a></li>

                </ul>
				 */ ?>

                <div class="publisher">
                	<h4>Publisher: <span><?php echo Zend_Auth::getInstance()->getIdentity()->name ?></span></h4>
                    <p class="publMail"><a href="#" title=""><?php echo Zend_Auth::getInstance()->getIdentity()->email ?></a></p>
                    <a href="/logout/" title="" class="logOut"><span>LogOut</span></a>
                </div>

                <div class="advSmall"><a href="#" title=""><img src="/images/advSmall.png" width="160" height="207" alt="" /></a></div>
                <div class="advSmall"><a href="#" title=""><img src="/images/advSmall.png" width="160" height="207" alt="" /></a></div>
                <div class="advSmall"><a href="#" title=""><img src="/images/advSmall.png" width="160" height="207" alt="" /></a></div>
            </div>
        	<!--//LEFT COLLUM-->

        <?php echo $this->layout()->content; ?>
            <div id="mask-admin"></div>
            <div id="loading-admin"><span>processing...</span></div>                
        </div>
    </div>
    <!--//content-->
  <div id="footerBlock"></div>
 </div>
</div>
<div id="footerMain">
 <div id="footer">
 	<div id="footTop">
    	<div class="fMenu">
        	<h4>Pages</h4>
            <ul>
            	<li><a href="/" title="">Home</a></li>
            	<li><a href="/about-us/" title="">About Us</a></li>
            	<li><a href="/contact-us/" title="">Contact Us</a></li>
            	<li><a href="/faq/" title="">FAQ</a></li>
            </ul>
        </div>

    	<div class="fMenu">
        	<h4>Publishers</h4>
            <ul>
            	<li><a href="/registration/" title="">Apply Now</a></li>
            </ul>
        </div>

    	<div class="fMenu">
        	<h4>Follow Us</h4>
			<a href="http://www.facebook.com/MadAdsMediaLP" title="MadAds Media on Facebook" class="socLink" rel="nofollow"><img src="/images/faceBook.png" width="40" height="40" alt="" /></a>
			<a href="http://www.twitter.com/MadAdsMedia" title="MadAds Media on Twitter" class="socLink" rel="nofollow"><img src="/images/twitt.png" width="40" height="40" alt="" /></a>
        </div>
        
    	<div class="fMenu" style="margin-left:-10px; width:230px;">
			<a href="http://www.instantssl.com" title="Secured by Comodo" rel="nofollow" class="socLink"><img src="/images/comodo_secure_100x85_transp.png" alt="" width="90" /></a>
			<a href="http://www.gigenet.com/318.html" title="Proudly Hosted by Gigenet" rel="nofollow" target="_blank">Proudly hosted by: <img src="/images/gigenet-logo.png" alt="" width="90" /></a>
        </div>

        <div class="footerBann">
        	<h5>Have a question?</h5>
            <p>We're ready to answer!</p>
            <a href="/contact-us/" title="">Contact Us</a>
        </div>

    </div>

	<div id="footCopyr">&copy;2011-<?php echo date("Y"); ?> Mad Ads Media LP - All rights reserved.</div>
 </div>
</div>
</body>
</html>