<script type="text/javascript" charset="utf-8">

        $(document).ready(function() {                           
            
                <?php if($this->dataAuth->role == 'super'):?>
                    var managerAccount = $('#filterManager').val();
                <?php else:?>
                    var managerAccount = <?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>;
                <?php endif;?>                
                    
                $('#filterManager').change(function(){ managerAccount = $('#filterManager').val(); oTable.fnClearTable(); });                
     
                var oTable = $('#week-site').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/dashboard/ajax-site-day-statistic',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "filterDate", "value": '<?php echo $this->currentDate ?>' }, { "name": "manager", "value": managerAccount } ); },
                        "iDisplayLength": 100
                        ,
                        "aoColumns": [
                            { 
                              "sTitle": "PID",
                              "fnRender": function(obj){ return obj.aData[0]; } 
                            },
                            { 
                              "sTitle": "SID",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Website",
                              "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[1]+'">'+obj.aData[2]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Contact",
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[0]+'">'+obj.aData[3]+'</a>'; } 
                            },
                     
                            { 
                              //"sTitle": "Impressions",
                              "fnRender": function(obj){ return number_format(obj.aData[4],0,'.',','); } 
                            },
                            { 
                                //"sTitle": "Impressions",
                                "fnRender": function(obj){ return number_format(obj.aData[5],0,'.',','); } 
                            },
                            { 
                              //"sTitle": "Revenue",
                              "fnRender": function(obj){ return '$ '+number_format(obj.aData[6],2,'.',','); } 
                            },                            
                            { 
                              "sTitle": "Alexa rank",
                              "fnRender": function(obj){ return number_format(obj.aData[7],0,'.',','); } 
                            },
                            { 
                                "sTitle": "ECPM",
                                "fnRender": function(obj){ return number_format(obj.aData[9],2,'.',','); } 
                            },
                            { 
                                "sTitle": "",
                                "bSortable": false,
                                "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[0]+'" target="_blank">Login</a>'; } 
                              },
               
       
                  
                                                             
                        ],                                                
                        "aaSorting": [[ 5, "desc" ]]
                         
                } );     
                
  

        } );
        
function number_format( number, decimals, dec_point, thousands_sep ) {	// Format a number with grouped thousands
	// 
	// +   original by: Jonas Raoni Soares Silva (http://www.jsfromhell.com)
	// +   improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
	// +	 bugfix by: Michael White (http://crestidg.com)

	var i, j, kw, kd, km;

	// input sanitation & defaults
	if( isNaN(decimals = Math.abs(decimals)) ){
		decimals = 2;
	}
	if( dec_point == undefined ){
		dec_point = ",";
	}
	if( thousands_sep == undefined ){
		thousands_sep = ".";
	}

	i = parseInt(number = (+number || 0).toFixed(decimals)) + "";

	if( (j = i.length) > 3 ){
		j = j % 3;
	} else{
		j = 0;
	}

	km = (j ? i.substr(0, j) + thousands_sep : "");
	kw = i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thousands_sep);
	//kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).slice(2) : "");
	kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).replace(/-/, 0).slice(2) : "");


	return km + kw + kd;
}


</script>
<h1>Sites Statistic</h1>
<div id="showTable" class="contUsL" style="width: 900px;">
    
    <?php if($this->dataAuth->role == 'super'):?>
        <p>
            <span style="font-weight: 600">View As Account Manager:</span> 
            <select style="margin-left: 14px;" id="filterManager">
                <option value="-1">All</option>
                <?php foreach($this->contactManager as $iter):?>
                     <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
                <?php endforeach;?>
            </select>  
        </p>
    <?php endif;?>
    
    <table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="week-site">
            <thead>
                    <tr>
                        <th width="5%">PID</th>
                        <th width="5%">SID</th>
                        <th width="20%">Website</th>
                        <th width="20%">Contact</th>              
                        <th width="10%">Impressions (<?php echo date('n/d/y', strtotime($this->currentDate))?>)</th>
                        <th width="10%">Paid Impressions (<?php echo date('n/d/y', strtotime($this->currentDate))?>)</th>
                        <th width="10%">Revenue (<?php echo date('n/d/y', strtotime($this->currentDate))?>)</th>
                        <th width="10%">Alexa rank</th>
                        <th width="10%">ECPM</th>
                        <th></th>                        
                    </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
                    <tr>
                        <th>PID</th>
                        <th>SID</th>
                        <th>Website</th>
                        <th>Contact</th>                        
                        <th>Impressions (<?php echo date('n/d/y', strtotime($this->currentDate))?>)</th>
                        <th>Paid Impressions (<?php echo date('n/d/y', strtotime($this->currentDate))?>)</th>
                        <th>Revenue (<?php echo date('n/d/y', strtotime($this->currentDate))?>)</th>
                        <th>Alexa rank</th>
                        <th>ECPM</th>
                        <th></th>
                    </tr>
            </tfoot>
    </table>  
       
    
          
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
//	Cufon.replace('.contInf h3', {hover: true});	
//	Cufon.replace('.contInf h3');
//	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
//	Cufon.replace('.footerBann h5');		
//	Cufon.replace('.footerBann p');	
//	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
//		Cufon.replace('#footCopyr');	
//		Cufon.replace('.contInf p', {hover: true});		
//		Cufon.replace('.contInf p', {color: '#333333'});	
//		Cufon.replace('.contInf p.white', {color: '#FFF'});	
//		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>