<link href="/js/selectbox/selectbox.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/selectbox/jquery.selectbox.js"></script>

<style type="text/css">

    .sendMasBtn{ height: 20px; width: 50px; cursor: pointer; line-height: 17px; }
    .caseSelect{ width: 100% !important; min-width: 100px; height: 25px !important; }
    .caseSelect option{ height: 20px; color: white; text-align: center; font-size: 14px; padding-top: 5px; }

    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }

    #loading{
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }

    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px;
    }

    .filter-status{ width: 140px !important; }
    #table-filter{ margin-bottom: 10px; margin-top: 10px; }
    #table-filter th{ font-size: 15px; padding-right: 10px; }
    #table-filter td{ padding-right: 10px; }

    #table-label{ border: 1px solid #D1D1D1; padding-right: 3px; position: absolute; z-index: 10000; left: 965px; top: 55px; }
    #table-label td{ font-size: 15px; }
    #filter-top-us{ width: 17px; margin-right: 5px; float: left; height: 22px; margin-bottom: 10px; }
    #label-top-us{ width: 170px; font-size: 15px; }

</style>

<script type="text/javascript" charset="utf-8">

    var oCase = JSON.parse('<?php echo json_encode($this->case);?>');

    jQuery.fn.dataTableExt.oSort['string-case-asc']  = function(x,y) {
    	return ((x < y) ? -1 : ((x > y) ?  1 : 0));
    };

    jQuery.fn.dataTableExt.oSort['string-case-desc'] = function(x,y) {
    	return ((x < y) ?  1 : ((x > y) ? -1 : 0));
    };



    $(document).ready(function(){

         $('#filter-Media').val('all');
         $('#filter-UnderDog').val('all');
         $('#filter-ValueClick').val('all');
         $('#filter-Advertising').val('all');
         $('#filter-AudienceScience').val('all');

         var filterMedia = $('#filter-Media').val();
         var filterUnderDog = $('#filter-UnderDog').val();
         var filterValueClick = $('#filter-ValueClick').val();
         var filterAdvertising = $('#filter-Advertising').val();
         var filterAudienceScience = $('#filter-AudienceScience').val();
         var showLive = $('#show_live').attr('checked') == 'checked' ? 1 : 0;

         var filter = $('#filter').val();

          var oTable = $('#table_pending').dataTable( {
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": '/administrator/optimization/ajax-all',
                "fnServerParams": function ( aoData ) {  aoData.push( { "name": "filterMedia", "value": filterMedia },
                                                                      { "name": "filterUnderDog", "value": filterUnderDog },
                                                                      { "name": "filterValueClick", "value": filterValueClick },
                                                                      { "name": "filterAdvertising", "value": filterAdvertising },
                                                                      { "name": "filterAudienceScience", "value": filterAudienceScience },
                                                                      { "name": "filter", "value": filter },
                                                                      { "name": "showLive", "value": showLive }); },
                "fnDrawCallback": function( oSettings ) { /*$('.newStyleSelect').selectbox();*/ },
                "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "iDisplayLength": 100
                ,
                "aoColumns": [
                    {
                      "sTitle": "PubID",
                      "fnRender": function(obj){ return obj.aData[0]; }
                    },
                    {
                      "sTitle": "SiteID",
                      "fnRender": function(obj){ return obj.aData[1]; }
                    },
                    {
                      "sTitle": "Website",
                      "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[1]+'">'+obj.aData[2]+'</a>'; }
                    },
                    {
                      "sTitle": "Contact",
                      "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[0]+'">'+obj.aData[3]+'</a>'; }
                    },

                    {
                      "sTitle": "ValueClick",
                      "fnRender": function(obj){ return createSelect(obj.aData[4], obj.aData[1], 1); }
                    },
                    {
                      "sTitle": "Advertising.com",
                      "fnRender": function(obj){ return createSelect(obj.aData[5], obj.aData[1], 2); }
                    },
                    {
                      "sTitle": "Media.net",
                      "fnRender": function(obj){ return createSelect(obj.aData[6], obj.aData[1], 3); }
                    },
                    {
                      "sTitle": "24/7 Real Media",
                      "fnRender": function(obj){ return createSelect(obj.aData[7], obj.aData[1], 4); }
                    },
                    {
                      "sTitle": "AudienceScience",
                      "fnRender": function(obj){ return createSelect(obj.aData[8], obj.aData[1], 5); }
                    },
                    {
                      "sTitle": "",
                      "bSortable": false,
                      "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[9]+'">login</a>'; }
                    },
                    {
                      "sTitle": "",
                      "bSortable": false,
                      "fnRender": function(obj){ return '<span onClick="saveCase('+obj.aData[11]+')" id="saveCase-'+obj.aData[11]+'" class="sendMasBtn link" style="display: none;">save</span>'; }
                    },
                    {
                      "sTitle": "Alexa Rank",
                      "sType": 'string-case',
                      "fnRender": function(obj){ return obj.aData[12]; }
                    },
                    {
                      "sTitle": "Impressions Yesterday",
                      "sType": 'string-case',
                      "fnRender": function(obj){ return obj.aData[13]; }
                    },
                    {
                      "sTitle": "USA Impressions Yesterday",
                      "sType": 'string-case',
                      "fnRender": function(obj){ return obj.aData[14]; }
                    }
                ],
                "aaSorting": [[11, 'asc'], [12, 'asc'], [13, 'asc']]

        });

        $('#filter-ValueClick').change(function(){

            filterValueClick = $('#filter-ValueClick').val();

            colorFilter('#filter-ValueClick', filterValueClick);

            oTable.fnClearTable();

        });
        $('#filter-Advertising').change(function(){

            filterAdvertising = $('#filter-Advertising').val();

            colorFilter('#filter-Advertising', filterAdvertising);

            oTable.fnClearTable();

        });
        $('#filter-Media').change(function(){

            filterMedia = $('#filter-Media').val();

            colorFilter('#filter-Media', filterMedia);

            oTable.fnClearTable();

        });
        $('#filter-UnderDog').change(function(){

            filterUnderDog = $('#filter-UnderDog').val();

            colorFilter('#filter-UnderDog', filterUnderDog);

            oTable.fnClearTable();

        });
        $('#filter-AudienceScience').change(function(){

            filterAudienceScience = $('#filter-AudienceScience').val();

            colorFilter('#filter-AudienceScience', filterAudienceScience);

            oTable.fnClearTable();

        });

        $('#filter').change(function(){

            filter = $('#filter').val();

            oTable.fnClearTable();

        });

		$('#show_live').click(function() {
            showLive = $('#show_live').attr('checked') == 'checked' ? 1 : 0;
            oTable.fnClearTable();
		});

    });

    function colorFilter(id, value)
    {
        var bColor = 'url("/images/inpBg.png") no-repeat scroll left top';
        var fColor = 'black';

        if(value != 'all'){ bColor = oCase[value].color; }
        if(value == 4){ fColor = 'white'; }

        $(id).css('background', bColor);
        $(id).css('color', fColor);

        $(id+' option').css('background', 'white');
        $(id+' option').css('color', 'black');
    }

    function createSelect(id, SiteID, name)
    {
        if(id){

            var result = '<select onChange="changeCase('+SiteID+', '+name+')" id="select-'+SiteID+'-'+name+'" class="caseSelect newStyleSelect" style="background:'+oCase[id].color+' !important; color:'+oCase[id].color+' !important;">';
            $.each(oCase, function(key, iter){

                result += '<option value="'+key+'" style="background-color:'+iter.color+';" '+(id == key ? 'selected' : '')+'>'+iter.name+'</option>';
            });

        }else{

            var result = '<select onChange="changeCase('+SiteID+', '+name+')" id="select-'+SiteID+'-'+name+'" class="caseSelect newStyleSelect" style="background:'+oCase[4].color+' !important; color:'+oCase[4].color+' !important;">';
            $.each(oCase, function(key, iter){

                result += '<option value="'+key+'" style="background-color:'+iter.color+';" '+(4 == key ? 'selected' : '')+'>'+iter.name+'</option>';
            });
        }

        result += '</select>';

        return result;
    }

    function changeCase(SiteID, name)
    {
        var id = $('#select-'+SiteID+'-'+name).val();

        $('#saveCase-'+SiteID).css('display', 'block');

        $('#select-'+SiteID+'-'+name).css('color', oCase[id].color);
        $('#select-'+SiteID+'-'+name).css('background-color', oCase[id].color);
    }

    function saveCase(SiteID)
    {
        display('block');

        var ValueClick = $('#select-'+SiteID+'-1').val();
        var Advertising = $('#select-'+SiteID+'-2').val();
        var Media = $('#select-'+SiteID+'-3').val();
        var UnderDog = $('#select-'+SiteID+'-4').val();
        var AudienceScience = $('#select-'+SiteID+'-5').val();

        $.ajax({ url : '/administrator/ajax/save-optimization-status',
                 data : { SiteID : SiteID, ValueClick : ValueClick, Advertising : Advertising, Media : Media, UnderDog : UnderDog, AudienceScience : AudienceScience },
                 type : "POST",
                 dataType : "json",

                 success : function(response){

                    $('#saveCase-'+SiteID).css('display', 'none');
                    display('none');
                 },
                 error : function(){ dispaly('none'); alert('ajax save error'); }
         });
    }

    function display(status)
    {
        $('#mask').css('display', status);
        $('#loading').css('display', status);
    }

</script>

<div class="contUsL" style="width: 750px;">
<h1>All Websites</h1>

<!--<p>
    <input type="checkbox" name="filter-top-us" id="filter-top-us" value="1"/><label for="filter-top-us" id="label-top-us">Show Top USA Sites</label>
</p>-->
<p>
    <select id="filter">
        <option value="all">Show All Sites</option>
        <option value="pending">Pending Optimizing</option>
        <option value="done">Done Optimizing</option>
    </select>
</p>

<table id="table-filter">
    <tr>
        <th>ValueClick</th>
        <th>Advertising.com</th>
        <th>Media.net</th>
        <th>24/7 Real Media</th>
        <th>AudienceScience</th>
    </tr>
    <tr>
        <td>
            <select class="filter-status" id="filter-ValueClick">
                <option value="all">Show All</option>
                <?php foreach($this->case as $key=>$iter):?>
                      <option value="<?php echo $key?>"><?php echo $iter['name']?></option>
                <?php endforeach;?>
            </select>
        </td>
        <td>
            <select class="filter-status" id="filter-Advertising">
                <option value="all">Show All</option>
                <?php foreach($this->case as $key=>$iter):?>
                      <option value="<?php echo $key?>"><?php echo $iter['name']?></option>
                <?php endforeach;?>
            </select>
        </td>
        <td>
            <select class="filter-status" id="filter-Media">
                <option value="all">Show All</option>
                <?php foreach($this->case as $key=>$iter):?>
                      <option value="<?php echo $key?>"><?php echo $iter['name']?></option>
                <?php endforeach;?>
            </select>
        </td>
        <td>
            <select class="filter-status" id="filter-UnderDog">
                <option value="all">Show All</option>
                <?php foreach($this->case as $key=>$iter):?>
                      <option value="<?php echo $key?>"><?php echo $iter['name']?></option>
                <?php endforeach;?>
            </select>
        </td>
        <td>
            <select class="filter-status" id="filter-AudienceScience">
                <option value="all">Show All</option>
                <?php foreach($this->case as $key=>$iter):?>
                      <option value="<?php echo $key?>"><?php echo $iter['name']?></option>
                <?php endforeach;?>
            </select>
        </td>
    </tr>
</table>

<p>
	<label style="width: 210px;" for="show_live">Show Only Live & New Sites</label>
	<input type="checkbox" id="show_live" value="1" style="width: 20px" />
</p>

<table id="table-label">
    <tr>
        <td><div style="background: #01FF00; width: 30px; height: 25px; margin-right: 5px;"></div></td>
        <td>Approved</td>
    </tr>
    <tr>
        <td><div style="background: #FF950E; width: 30px; height: 25px; margin-right: 5px;"></div></td>
        <td>Pending</td>
    </tr>
    <tr>
        <td><div style="background: #FF0000; width: 30px; height: 25px; margin-right: 5px;"></div></td>
        <td>Denied</td>
    </tr>
    <tr>
        <td><div style="background: #000000; width: 30px; height: 25px; margin-right: 5px;"></div></td>
        <td>Not Eligible</td>
    </tr>
</table>

    <table width="870px" cellpadding="0" cellspacing="0" border="0" class="display" id="table_pending">
            <thead>
                    <tr>
                        <th width="7%">PubID</th>
                        <th width="7%">SiteID</th>
                        <th width="25%">Website</th>
                        <th width="25%">Contact</th>
                        <th width="10%">ValueClick</th>
                        <th width="10%">Advertising.com</th>
                        <th width="10%">Media.net</th>
                        <th width="10%">24/7 Real Media</th>
                        <th width="10%">AudienceScience</th>
                        <th width="10%"></th>
                        <th width="10%"></th>
                        <th width="10%">Alexa Rank</th>
                        <th width="10%">Impressions Yesterday</th>
                        <th width="10%">USA Impressions Yesterday</th>
                    </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
                    <tr>
                        <th>PubID</th>
                        <th>SiteID</th>
                        <th>Website</th>
                        <th>Contact</th>
                        <th>ValueClick</th>
                        <th>Advertising.com</th>
                        <th>Media.net</th>
                        <th>24/7 Real Media</th>
                        <th>AudienceScience</th>
                        <th></th>
                        <th></th>
                        <th>Alexa Rank</th>
                        <th>Impressions Yesterday</th>
                        <th>USA Impressions Yesterday</th>
                    </tr>
            </tfoot>
    </table>

</div>

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});
	Cufon.replace('.footerBann h5');
	Cufon.replace('.footerBann p');
	Cufon.replace('.footerBann a', {hover: true});
    Cufon.replace('h1');
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');
		Cufon.replace('.contInf p', {hover: true});
		Cufon.replace('.contInf p', {color: '#333333'});
		Cufon.replace('.contInf p.white', {color: '#FFF'});
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});

</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>