
<script type="text/javascript" charset="utf-8">

    $(document).ready(function(){
        
          var oTable = $('#table_pending').dataTable( {
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": '/administrator/optimization/ajax-pending',
                "fnServerParams": function ( aoData ) {  aoData.push( { "name": "filter", "value": 'new' } ); },
                "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "iDisplayLength": 100
                ,
                "aoColumns": [
                    { 
                      "sTitle": "PubID",
                      "fnRender": function(obj){ return obj.aData[0]; } 
                    },
                    { 
                      "sTitle": "SiteID",
                      "fnRender": function(obj){ return obj.aData[1]; } 
                    },
                    { 
                      "sTitle": "Website",
                      "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[10]+'">'+obj.aData[2]+'</a>'; } 
                    },
                    { 
                      "sTitle": "Contact",
                      "fnRender": function(obj){ return obj.aData[3]; } 
                    },
                    { 
                      "sTitle": "Impressions",
                      "fnRender": function(obj){ return obj.aData[4]; } 
                    },
                    { 
                      "sTitle": "Alexa rank",
                      "fnRender": function(obj){ return obj.aData[5]; } 
                    },
                    { 
                      "sTitle": "Floor Tags",
                      "fnRender": function(obj){ var result = 'No'; if(obj.aData[6] == 1) result = 'Yes'; return result; } 
                    },
                    { 
                      "sTitle": "Created",
                      "fnRender": function(obj){ return $.format.date(new Date(obj.aData[7]), "yyyy MMM, dd"); } 
                    },
                    { 
                      "sTitle": "",
                      "bSortable": false,
                      "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[9]+'">login</a>'; } 
                    },
                    { 
                      "sTitle": "",
                      "bSortable": false,
                      "fnRender": function(obj){ return '<a href="/administrator/optimization/change/SiteID/'+obj.aData[10]+'">done</a>'; } 
                    },
                    
                ],                                                
                "aaSorting": [[ 1, "asc" ]]

        });
    }); 

</script>

<div class="contUsL" style="width: 750px;">
<h1>Pending Optimizing</h1>

    <table width="870px" cellpadding="0" cellspacing="0" border="0" class="display" id="table_pending">
            <thead>
                    <tr>
                        <th width="7%">PubID</th>
                        <th width="7%">SiteID</th>
                        <th width="25%">Website</th>
                        <th width="25%">Contact</th>
                        <th width="10%">Impressions</th>
                        <th width="10%">Alexa rank</th>
                        <th width="10%">Floor Tags</th>
                        <th width="10%">Created</th>
                        <th width="10%"></th>
                        <th width="10%"></th>
                    </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
                    <tr>
                        <th>PubID</th>
                        <th>SiteID</th>
                        <th>Website</th>
                        <th>Contact</th>
                        <th>Impressions</th>
                        <th>Alexa rank</th>
                        <th>Floor Tags</th>
                        <th>Created</th>
                        <th></th>
                        <th></th>
                    </tr>
            </tfoot>
    </table>

</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>