<style type="text/css">

    #default_admin_form input[type="submit"]{ background: #8e8e8e; }
    #default_admin_form .name label{ padding-top: 5px; width: 175px; }
    #default_admin_form .parent label{ padding-top: 5px; width: 175px; }
    #default_admin_form .parent select{ width: 300px; }
    #default_admin_form .email label{ padding-top: 5px; width: 175px; }
    #default_admin_form .email select{ width: 300px; }

</style>

<br /><br />
<h1>Referral Add</h1>
<br />

<div class="contUsL" style="width: 750px;">
    <br /><br />

    <?php echo $this->form; ?>

</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('#topMenu a', {hover: true});
    Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('.contInf h3', {hover: true});
    Cufon.replace('.contInf h3');
    Cufon.replace('.contInf h3.white', {color: '#FFF'});
    Cufon.replace('.footerBann h5');
    Cufon.replace('.footerBann p');
    Cufon.replace('.footerBann a', {hover: true});
    Cufon.replace('h1');
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
    Cufon.replace('#footCopyr');
    Cufon.replace('.contInf p', {hover: true});
    Cufon.replace('.contInf p', {color: '#333333'});
    Cufon.replace('.contInf p.white', {color: '#FFF'});
    Cufon.replace('.fMenu a', {textDecoration: 'underline'});

</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
    Cufon.replace('.fMenu h4');
</script>