<style>

    #default_admin_form .name label{ padding-top: 5px; width: 175px; }
    #default_admin_form .parent label{ padding-top: 5px; width: 175px; }
    #default_admin_form .parent select{ width: 300px; }
    #default_admin_form .email label{ padding-top: 5px; width: 175px; }
    #default_admin_form .email select{ width: 300px; }

    #refLink label{ padding-top: 5px; width: 175px; }
    #refLink span{ font-size: 14px; color: #414141; padding-top: 5px; display: block; }

</style>

<script type="text/javascript">

    $(document).ready(function(){

        updateRefLink();

        $('#parentID').change(function(){ updateRefLink(); });

    });

    function updateRefLink()
    {
        var partnerID = $('#parentID').val();

        if(parseInt(partnerID)){ $('#refLink span').html('http://yieldselect.com/registration/ref/'+partnerID+'/<?php echo $this->data->id;?>'); }
        else{ $('#refLink span').html('http://yieldselect.com/registration/ref/<?php echo $this->data->id;?>'); }

    }

</script>

<h1>Edit Referral</h1>

<br />
<br />

<div id="default_admin_form">
    <form action="" method="post">

        <?php echo $this->form->name; ?>
        <?php echo $this->form->parentID; ?>
        <?php echo $this->form->email; ?>

        <div id="refLink">
            <label>Referral Link:</label>
            <span></span>
        </div>

        <?php echo $this->form->submit; ?>

    </form>
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('#topMenu a', {hover: true});
    Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('.contInf h3', {hover: true});
    Cufon.replace('.contInf h3');
    Cufon.replace('.contInf h3.white', {color: '#FFF'});
    Cufon.replace('.footerBann h5');
    Cufon.replace('.footerBann p');
    Cufon.replace('.footerBann a', {hover: true});
    Cufon.replace('h1');
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
    Cufon.replace('#footCopyr');
    Cufon.replace('.contInf p', {hover: true});
    Cufon.replace('.contInf p', {color: '#333333'});
    Cufon.replace('.contInf p.white', {color: '#FFF'});
    Cufon.replace('.fMenu a', {textDecoration: 'underline'});

</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
    Cufon.replace('.fMenu h4');
</script>