<style type="text/css">

    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }

    #loading{
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }

    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px;
    }

</style>
<script type="text/javascript">
        
        jQuery(document).ready(function(){
              
            $( ".datepicker" ).datepicker({
                            showOn:'focus',
                            'dateFormat'  : "yy-mm-dd"
                            })	

                var startDate = $('#startDate').val();
                var endDate = $('#endDate').val();

            var oTable = $('#table_referral').dataTable( {
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": '/administrator/referral/get-ajax',
                "fnServerParams": function ( aoData ) {  aoData.push( { "name": "startDate", "value": startDate }, { "name": "endDate", "value": endDate } ); },
                "fnDrawCallback": function( oSettings ) { display('none'); },
                "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                "iDisplayLength": 100
                ,
                "aoColumns": [
                    {
                        "sTitle": "ID",
                        "fnRender": function(obj){ return obj.aData[0]; }
                    },
                    {
                        "sTitle": "Name",
                        "fnRender": function(obj){ return obj.aData[1]; }
                    },
                    {
                        "sTitle": "AllClick",
                        "fnRender": function(obj){ return number_format(obj.aData[2],0,'.',','); }
                    },
                    {
                        "sTitle": "Click",
                        "fnRender": function(obj){ return number_format(obj.aData[3],0,'.',','); }
                    },
                    {
                        "sTitle": "Sign Ups",
                        "bSortable": false,
                        "fnRender": function(obj)
                        {
                            return '<a style="cursor: pointer;" href="/administrator/referral/signup/id/'+obj.aData[0]+'/startDate/'+$('#startDate').val()+'/endDate/'+$('#endDate').val()+'">'+number_format(obj.aData[4],0,'.',',')+'</a>';
                        }
                    },
                    {
                        "sTitle": "Conversion",
                        "fnRender": function(obj){ return number_format(obj.aData[5],0,'.',','); }
                    },
                    {
                        "sTitle": "Conversion %",
                        "bSortable": false,
                        "fnRender": function(obj){var percent=0; if(obj.aData[5]==0 || obj.aData[6]==0) percent=0; else percent = obj.aData[5]/obj.aData[6]; return percent.toFixed(2)+'%'; }
                    },
                    {
                        "sTitle": "Total Impressions",
                        "fnRender": function(obj){ return '<a style="cursor: pointer;" href="/administrator/referral/view/id/'+obj.aData[0]+'/from/'+$('#startDate').val()+'/to/'+$('#endDate').val()+'">'+number_format(obj.aData[7],0,'.',',')+'</a>'; }
                    },
                    {
                        "sTitle": "Total Revenue",
                        "fnRender": function(obj){ return '<a style="cursor: pointer;" href="/administrator/referral/view/id/'+obj.aData[0]+'/from/'+$('#startDate').val()+'/to/'+$('#endDate').val()+'">'+number_format(obj.aData[8],2,'.',',')+'</a>'; }
                    },
                    {
                        "sTitle": "",
                        "fnRender": function(obj){ return '<a style="cursor: pointer;" href="/administrator/referral/edit/id/'+obj.aData[0]+'">edit</a>'; }
                    },
                    {
                        "sTitle": "",
                        "fnRender": function(obj){ return '<a style="cursor: pointer;" onclick="return confirm(\'Delete ?\');" href="/administrator/referral/delete/id/'+obj.aData[0]+'">delete</a>'; }
                    }
                ],
                "aaSorting": [[ 0, "asc" ]]

            } );

            $('#startDate').change(function () {startDate = $('#startDate').val(); endDate = $('#endDate').val(); oTable.fnDraw();});
                $('#endDate').change(function () {startDate = $('#startDate').val(); endDate = $('#endDate').val(); oTable.fnDraw();});

            $('#selectDate').change(function(){

                var period = $('#selectDate option:selected').val();
                var str = period.split('_');

                startDate = str[0];
                endDate = str[1];

                $('#startDate').val(startDate);
                $('#endDate').val(endDate);

                display('block');
                oTable.fnDraw();
            });

        });

        function display(status)
        {
            $('#mask').css('display', status);
            $('#loading').css('display', status);
        }

jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "formatted-num-pre": function ( a ) {
        a = (a === "-" || a === "") ? 0 : a.replace( /[^\d\-\.]/g, "" );
        return parseFloat( a );
    },
 
    "formatted-num-asc": function ( a, b ) {
        return a - b;
    },
 
    "formatted-num-desc": function ( a, b ) {
        return b - a;
    }
} );  

function number_format( number, decimals, dec_point, thousands_sep ) {	// Format a number with grouped thousands
	// 
	// +   original by: Jonas Raoni Soares Silva (http://www.jsfromhell.com)
	// +   improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
	// +	 bugfix by: Michael White (http://crestidg.com)

	var i, j, kw, kd, km;

	// input sanitation & defaults
	if( isNaN(decimals = Math.abs(decimals)) ){
		decimals = 2;
	}
	if( dec_point == undefined ){
		dec_point = ",";
	}
	if( thousands_sep == undefined ){
		thousands_sep = ".";
	}

	i = parseInt(number = (+number || 0).toFixed(decimals)) + "";

	if( (j = i.length) > 3 ){
		j = j % 3;
	} else{
		j = 0;
	}

	km = (j ? i.substr(0, j) + thousands_sep : "");
	kw = i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thousands_sep);
	//kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).slice(2) : "");
	kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).replace(/-/, 0).slice(2) : "");


	return km + kw + kd;
}
</script>

<h1>Referral System</h1>
<br>
<div class="contUsL" style="width: 750px;">
<br /><br />
<?php $sMonth = date("m"); $sDay = date("d"); $sYear = date("Y"); $sDateNow = date("Y-m-d", mktime(0,0,0,$sMonth,$sDay,$sYear)); $sDateYesterday = date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-1,$sYear));
$reportStartDate = date("Y-m-d", strtotime(htmlentities($this->startDate)));
$reportEndDate = date("Y-m-d", strtotime(htmlentities($this->endDate))); ?>
<select id="selectDate" name="selectDate" style="margin-left: 60px;">
    <option value="<?php echo $sDateNow.'_'.$sDateNow; ?>" >Today</option>
    <option value="<?php echo $sDateYesterday.'_'.$sDateYesterday; ?>" >Yesterday</option>
    <option value="<?php echo date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-7,$sYear)).'_'.$sDateNow ?>" selected >Last 7 Days</option>
    <option value="<?php echo date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-30,$sYear)).'_'.$sDateNow ?>" >Last 30 Days</option>
    <option value="<?php echo date("Y-m-d", mktime(0,0,0,$sMonth,1,$sYear)).'_'.$sDateNow ?>" >This Month</option>
    <option value="<?php echo $this->firstReportDate.'_'.$sDateNow; ?>" >All Time</option>
</select>
<button onClick="document.getElementById('openAddReferral').click()" style="width: 180px; float: none; margin-left: 57px; cursor: pointer;" class="sendMasBtn">Add New Referral ID</button>
<a id="openAddReferral" href="/administrator/referral/add" target="_blank" style="display: none;"></a>
<br />
<p>Start Date: <input type="text" class="datepicker" name="startDate" value="<?php echo date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-7,$sYear)) ?>" id="startDate" /> End Date: <input type="text" class="datepicker" name="endDate" value="<?php echo $this->endDate; ?>" id="endDate" /></p>
<br>
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="table_referral">
    <thead>
    <tr>
        <th width="20%">ID</th>
        <th width="40%">Name</th>
        <th width="10%">AllClick</th>
        <th width="10%">Click</th>
        <th width="10%">Sign Ups</th>
        <th width="10%">Conversion</th>
        <th width="10%">Conversion %</th>
        <th width="10%">Total Impressions</th>
        <th width="10%">Total Revenue</th>
        <th width="10%"></th>
        <th width="10%"></th>
    </tr>
    </thead>
    <tbody></tbody>
    <tfoot>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>AllClick</th>
        <th>Click</th>
        <th>Sign Ups</th>
        <th>Conversion</th>
        <th>Conversion %</th>
        <th>Total Impressions</th>
        <th>Total Revenue</th>
        <th></th>
        <th></th>
    </tr>
    </tfoot>
</table>

</div>

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>