<script type="text/javascript">
        
        jQuery(document).ready(function(){
              
            $( ".datepicker" ).datepicker({
                            showOn:'focus',
                            'dateFormat'  : "yy-mm-dd"
                            })	

                var startDate = $('#startDate').val();
                var endDate = $('#endDate').val();
              
                var oTable = $('#table_referral').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/referral/get-view-ajax',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "refID", "value": <?php echo $this->refID ?> }, { "name": "startDate", "value": startDate }, { "name": "endDate", "value": endDate } ); },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100
                        ,
                        "aoColumns": [
                            { 
                              "sTitle": "Publisher",
                              "fnRender": function(obj){ 
                                  
                                  var res = null;
                                  var arr = obj.aData[5].split(/[,]/);
                                  
                                  res = obj.aData[0]+' <select id="siteItem_'+obj.aData[4]+'" style="width: auto;">';
                                  
                                  $.each(arr, function(key, iter){
              
                                      var value = iter.split(/[:]/);
              
                                      res += '<option value="'+value[0]+'">'+value[1]+'</option>';
                    
                                  });
                                  
                                  res += '</select><a href="#" onClick="goToSite('+obj.aData[4]+')" class="sendMasBtn goSite" style="width: auto;">Go</a>';
                                           
                                  return res;                              
                              } 
                            },
                            { 
                              "sTitle": "Email",
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[4]+'">'+obj.aData[1]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Total Impressions",
                              "fnRender": function(obj){ return number_format(obj.aData[2],0,'.',','); } 
                            },
                            { 
                              "sTitle": "Total Revenue",
                              "fnRender": function(obj){ return number_format(obj.aData[3],2,'.',','); } 
                            },
                            { 
                              "sTitle": "Login",
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[4]+'" target="_blank">Login</a>'; } 
                            },                            
                        ],                                                
                        "aaSorting": [[ 0, "asc" ]]
                         
                } );             
                        
                $('#startDate').change(function () {startDate = $('#startDate').val(); endDate = $('#endDate').val(); oTable.fnDraw();});
                $('#endDate').change(function () {startDate = $('#startDate').val(); endDate = $('#endDate').val(); oTable.fnDraw();});                                        
        });

jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "formatted-num-pre": function ( a ) {
        a = (a === "-" || a === "") ? 0 : a.replace( /[^\d\-\.]/g, "" );
        return parseFloat( a );
    },
 
    "formatted-num-asc": function ( a, b ) {
        return a - b;
    },
 
    "formatted-num-desc": function ( a, b ) {
        return b - a;
    }
} );  

function goToSite(id)
{ 
    var site = $('#siteItem_'+id+' option:selected').val();

    if(site){
        location.href = '/administrator/sites/view/id/'+site;
    }else{
        return false;
    }
}

function number_format( number, decimals, dec_point, thousands_sep ) {	// Format a number with grouped thousands
	// 
	// +   original by: Jonas Raoni Soares Silva (http://www.jsfromhell.com)
	// +   improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
	// +	 bugfix by: Michael White (http://crestidg.com)

	var i, j, kw, kd, km;

	// input sanitation & defaults
	if( isNaN(decimals = Math.abs(decimals)) ){
		decimals = 2;
	}
	if( dec_point == undefined ){
		dec_point = ",";
	}
	if( thousands_sep == undefined ){
		thousands_sep = ".";
	}

	i = parseInt(number = (+number || 0).toFixed(decimals)) + "";

	if( (j = i.length) > 3 ){
		j = j % 3;
	} else{
		j = 0;
	}

	km = (j ? i.substr(0, j) + thousands_sep : "");
	kw = i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thousands_sep);
	//kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).slice(2) : "");
	kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).replace(/-/, 0).slice(2) : "");


	return km + kw + kd;
}
</script>

<h1>Referral System</h1>
<div class="contUsL" style="width: 750px;">
    <br /><br />
    <?php $sMonth = date("m"); $sDay = date("d"); $sYear = date("Y"); $sDateNow = date("Y-m-d", mktime(0,0,0,$sMonth,$sDay,$sYear)); $sDateYesterday = date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-1,$sYear));
    $reportStartDate = date("Y-m-d", strtotime(htmlentities($this->startDate)));
    $reportEndDate = date("Y-m-d", strtotime(htmlentities($this->endDate))); ?>
    <select id="selectDate" name="selectDate" style="margin-left: 60px;">
        <option value="<?php echo $sDateNow.'_'.$sDateNow; ?>" <?php if($reportStartDate == $sDateNow && $reportEndDate == $sDateNow) echo ' selected' ;?>>Today</option>
        <option value="<?php echo $sDateYesterday.'_'.$sDateYesterday; ?>" <?php if( $reportStartDate == $sDateYesterday && $reportEndDate == $sDateYesterday ) echo ' selected' ;?>>Yesterday</option>
        <option value="<?php echo date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-7,$sYear)).'_'.$sDateNow ?>" <?php if( $reportStartDate == date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-7,$sYear)) && $reportEndDate == $sDateNow ) echo ' selected' ;?>>Last 7 Days</option>
        <option value="<?php echo date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-30,$sYear)).'_'.$sDateNow ?>" <?php if( $reportStartDate == date("Y-m-d", mktime(0,0,0,$sMonth,$sDay-30,$sYear)) && $reportEndDate == $sDateNow ) echo ' selected' ;?>>Last 30 Days</option>
        <option value="<?php echo date("Y-m-d", mktime(0,0,0,$sMonth,1,$sYear)).'_'.$sDateNow ?>" <?php if( $reportStartDate == date("Y-m-d", mktime(0,0,0,$sMonth,1,$sYear)) && $reportEndDate == $sDateNow ) echo ' selected' ;?>>This Month</option>
        <option value="<?php echo $this->firstReportDate.'_'.$sDateNow; ?>" <?php if( $reportStartDate == $this->firstReportDate && $reportEndDate == $sDateNow ) echo ' selected' ;?> selected>All Time</option>
    </select>
    <br/>
    <p>Start Date: <input type="text" class="datepicker" name="startDate" value="<?php echo $this->startDate ?>" id="startDate" /> End Date: <input type="text" class="datepicker" name="endDate" value="<?php echo $this->endDate ?>" id="endDate" /></p>
    <br>
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="table_referral">
    <thead>        
        <tr>
            <th width="40%">Publisher</th>
            <th width="30%">Email</th>
            <th width="10%">Total Impressions</th>
            <th width="10%">Total Revenue</th>
            <th width="10%">Login</th>
        </tr>       
    </thead>
    <tbody></tbody>
    <tfoot>        
        <tr>
            <th>Publisher</th>
            <th>Email</th>
            <th>Total Impressions</th>
            <th>Total Revenue</th>
            <th>Login</th>
        </tr>       
    </tfoot>        
</table>

</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>