<form method="post" action="">
    <div data-role="fieldcontain">
        <label for="email">Email: </label>
        <input type="email" name="email" id="email" value=""  />
    </div>	
    <div data-role="fieldcontain">
        <label for="password">Password: </label>
        <input type="password" name="password" id="password" value=""  />
    </div>	
    <button type="submit" name="submit" value="submit-value">Login</button>
</form>