
<script type="text/javascript">

   $(document).ready(function(){
       
        $('body').keypress(function(event){
                        
            if(event.which == 13){ 
            
               var mail = $('input[name=email]').val().length;
               var pass = $('input[name=password]').val().length;
               
               if(mail && pass) $('#subForm').click();
        
            };
            
        });
       
   });

</script>

<div class="contactUs">
            <div id="contForm">

    <form method="post" action="" style="width: 430px;">
    <?php if($this->message): ?>
        <p style="color: red;"><?php echo $this->message ?></p>
    <?php endif; ?>    
    <div class="contUsL">
    <p><label>Email: </label><input type="email" name="email" value="<?php echo $this->formValues['email'] ?>" autocomplete="off" /></p>
        <?php if($this->formErrors['email']): ?>
            <ul class="error">
            <?php foreach($this->formErrors['email'] as $errors): ?>
                <li><?php //echo $errors ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>    
    
    <p><label>Password: </label><input type="password" name="password" autocomplete="off"/></p>
        <?php if($this->formErrors['password']): ?>
            <ul class="error">
            <?php foreach($this->formErrors['password'] as $errors): ?>
                <li><?php //echo $errors ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>        
    </div>
                    <div class="contBtn">
                    	<p><a href="/forgot/" >Forgot your password?</a></p>
                        <a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Login</a>  
                    </div>
    <input type="submit" id="subForm" style="display: none;" />
    </form>  
    
    </div>  
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
        Cufon.replace('.error', {color: 'red'});
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
