<style type="text/css">
    label{ font-weight: 800; }
    input{ width: 650px; }
    .sendMasBtn{
          background-color: #8E8E8E;
          border: 1px solid #797979;
          color: #FFFFFF;
          float: right;
          font-size: 16px;
          height: 28px;
          line-height: 28px;
          margin: -1px 3px 0 0;
          text-align: center;
          width: 129px;
          text-decoration: none;
    }
    .sendMasBtn:hover { background-color: #DC2323; }
    
</style>
<div class="contUsL" style="width: 740px;">
    <?php if(empty($this->message)):?>
    <form action="" method="post" class="sign-up">

       <p>
            <label>Invite URL:</label>
            <input type="text" name="inviteURL" id="inviteURL" value="<?php echo $this->formValues['inviteURL'] ?>" placeholder="Google AdX" />
            <?php if(isset($this->formErrors['inviteURL'])): ?>
                <ul class="error">
                <?php foreach($this->formErrors['inviteURL'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>                                            
       </p>

       <p><a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Save</a></p>
       <input type="submit" id="subForm" style="display: none;" />     

    </form>
    <?php else:?>
       <?php echo $this->message;?>
    <?php endif;?>
</div>
