<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />
    <meta name="description" content="Increase Your Earnings.  Make the most of your impressions. Our optimization technology has websites seeing a 350% increase in revenue!" />
    <meta name="keywords" content="Increase Your Earnings, ad optimization, ad optimization for small websites, ad optimization for mid-sized websites, ad optimizer" />
    <title>MadAdsMedia.com - Increase Your Earnings</title>
    <!-- Bootstrap core CSS -->
    <link href="/styles/landing/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/styles/landing/style.css" rel="stylesheet">

    <!-- Fancybox CSS -->
    <link href="/fancybox2/jquery.fancybox.css" media="screen" rel="stylesheet" type="text/css" />

    <!-- Custom Google Font : Open Sans -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="/js/landing/html5shiv.js"></script>
    <script src="/js/landing/respond.min.js"></script>
    <![endif]-->

    <!-- Favicons -->
    <link rel="shortcut icon" href="/images/landing/favicon.png">
    <!-- Subtle Loading bar -->
    <script src="/js/landing/pace.js"></script>
</head>
<body>
<div class="preloader"></div>
<!-- Parallax Header Starts -->
<main id="top" class="masthead" role="main">
    <div class="container">
        <!-- Logo -->
        <div class="logo"> <a href="/"><img src="/images/landing/logo_white_bg (2).png" alt="readymade-logo"></a> </div>
        <!-- Hero Title -->
        <h1 class="main-title">Increase Your Earnings</h1>
        <!-- Sub Title -->
        <h4 class="sub-title">Monetize Smarter. Get Paid On Time. </h4>

        <!-- Quick Features + Lead Gen Form -->
        <div class="row has-margin-top-lg">
            <div class="col-sm-12 col-md-7 col-lg-6 col-lg-offset-1">
                <div class="quick-features">
                    <div class="featues-single"> <img src="/images/landing/tick.png" alt="tick" class="pull-left">
                        <h5>Industry High CPMs</h5>
                        <p>Our optimization technology is designed to make the most out of your impressions by auctioning them off to 100+ demand partners. </p>
                    </div>
                    <div class="featues-single"> <img src="/images/landing/tick.png" alt="tick" class="pull-left">
                        <h5>Dedicated Account Managers</h5>
                        <p>As a MadAds Media Publisher, you have the full support and expertise of our Account Managers.</p>
                    </div>
                    <div class="featues-single"> <img src="/images/landing/tick.png" alt="tick" class="pull-left">
                        <h5>Team of Optimization Specialists</h5>
                        <p>We work side-by-side with our Publishers, optimizing their websites to generate higher revenue.</p>
                    </div>
                    <div class="featues-single last"> <img src="/images/landing/tick.png" alt="tick" class="pull-left">
                        <h5>High Fill Rates</h5>
                        <p>While most ad networks can fill only the first few impressions, our mass pool of advertisers ensures a large majority of your impressions will be filled.</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-5 col-sm-12">
                <div class="relative-block">
                    <div class="signup-block">
                        <h3 class="form-title has-margin-bottom-sm text-center">Let's Get Started!</h3>
                        <form action="/registration/" class="form" role="form" method="POST" id="phpcontactform">
                            <div class="form-group">
                                <label>Email Address</label>
                                <input class="form-control input-med" name="email" id="email" type="email" placeholder="Enter your email" required>
                            </div>
                            <div class="form-group">
                                <label>Website URL</label>
                                <input class="form-control input-med" name="url" id="url" type="text" placeholder="http://">
                            </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input class="form-control input-med" name="password" id="password" type="password" placeholder="Password" required>
                            </div>
                            <div class="form-group">
                                <label>Confirm Password</label>
                                <input class="form-control input-med" name="passwordConfirm" id="passwordConfirm" type="password" placeholder="Confirm Password" required>
                            </div>
                            <div class="form-group">
                                <div class="checkbox">
                                    <label>
                                        <input name="term" id="term" type="checkbox" required>I agree to the terms/publisher guidelines
                                    </label>
                                </div>
                            </div>
                            <div class="form-group last">
                                <input type="submit" class="btn btn-warning btn-block btn-lg" value="Submit Now">
                            </div>
                            <p class="re-assure">We will not share your email. No spam. </p>
                        </form>
                        <span id="result" class="loading"></span> </div>
                </div>
            </div>
        </div>
        <!-- // Quick Features + Lead Gen Form Ends -->
    </div>
    <!--  Scroll to Explore -->
    <a href="#explore" class="scrollto">
        <p class="scrollto--arrow"><img src="/images/landing/down_arrow.png" alt="scroll down arrow"></p>
    </a>
    <!-- // Scroll to Explore Ends -->
</main>
<!-- // Parallax Header Ends -->

<!-- Client Logos -->

<div class="container">
    <div class="row">
        <div class="col-md-7 col-lg-6 col-lg-offset-1">
            <div class="as-seen-on"> We Work With 100s of The Industries Top Companies </div>
            <div class="logos"> <img src="/images/landing/rubiconHov.png" alt="logo"> <img src="/images/landing/mediaMathHov.png" alt="logo"> <img src="/images/landing/turnHov.png" alt="logo"> <img src="/images/landing/pubmaticHov.png" alt="logo"> <img src="/images/landing/quancastHov.png" alt="logo"> <img src="/images/landing/openXHov.png" alt="logo"> <img src="/images/landing/doubleClickHov.png" alt="logo"> </div>
        </div>
    </div>
</div>
<!-- // Client Logos Ends -->


<!-- Container -->
<div class="container">


    <!-- Features Section -->
    <div class="section-title">
        <h2>Ad Types We Offer </h2>
        <h4></h4>
    </div>
    <section class="row features">
        <!-- Feature 01 -->
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <div class="icon-wrap"> <img src="/images/landing/mobile.png" alt="icon"></div>
                <div class="caption">
                    <h4 class="zigzag-lead">Desktop &amp; Mobile CPM Ads </h4>
                    <p>We provide ads for all devices, offering the following IAB standard ad sizes: 728x90, 300x250, 336x280, 160x600, 468x60, 320x50, 320x100.</p>
                </div>
            </div>
        </div>

        <!-- Feature 02 -->
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <div class="icon-wrap"><img src="/images/landing/preroll.png" alt="icon"></div>
                <div class="caption">
                    <h4 class="zigzag-lead">Video VAST/VPAID</h4>
                    <p>Let us monetize your video content using  VAST/VPAID pre-rolls, mid-rolls, and post-rolls. Achieve CPMs up to 20x higher than traditional display ads. </p>
                </div>
            </div>
        </div>

        <!-- Feature 03 -->
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <div class="icon-wrap"> <img src="/images/landing/display.png" alt="icon"></div>
                <div class="caption">
                    <h4 class="zigzag-lead">Unique, Innovative Ad Units </h4>
                    <p>Increase your revenue with our unique ad units, including slider ads, content locking technologies, and many more. </p>
                </div>
            </div>
        </div>
    </section>
    <!-- // Features Section Ends -->

</div>
<!-- // Container Ends -->

<!-- Container -->
<div class="container" id="explore">
    <!-- Hero Image -->
    <div class="section-title">
        <h2>Make The Most From Your Website</h2>
        <h4>Take control over your impressions.</h4>
    </div>
    <div class="zigzag">
        <div class="row">
            <div class="col-md-4"> <img src="/images/landing/image_1.png" alt="img" class="img-responsive center-block"> </div>
            <div class="col-md-8">
                <h4 class="zigzag-lead">Optimized for Publishers</h4>
                <p>From our team of experts to our industry leading technology, we strive to deliver the best results. Our experts will work by your side to ensure your ads are in the best placements and making the most revenue possible.</p>
            </div>
        </div>
    </div>
</div>
<!-- // Container Ends -->




<!-- Container -->
<div class="container">

    <!-- FAQ -->
    <div class="section-title">
        <h2>Questions?</h2>
        <h4>Do you have any questions? We’ve got answers</h4>
    </div>
    <section class="row faq breath">
        <div class="col-md-6">
            <h6>What is MadAds Media?</h6>
            <p>MadAds Media is an alternative to Google AdSense, MadAdsMedia allows you to monetize your blog or website by displaying advertisements to your visitors. </p>
            <h6>What Are The Payment Terms?</h6>
            <p>Payments are made on a net-45 basis. You will receive payments 45 days after the current month's end (provided you met your set minimum payment).</p>
        </div>
        <div class="col-md-6">
            <h6>How Much Money Do I Need To Make Before I Can Receive Payment?</h6>
            <p>The minimum payment amount is determined by you. You can control the amount in the payment profile area of your account. The minimum you can select is $50.</p>
            <h6>Who Are Some Of Your Advertisers?</h6>
            <p>You'll see ads from  major brands that you'd typically see on TV and major news publications. The high quality advertisers will add instant credibility to your website or blog. </p>
        </div>
    </section>
    <!-- // End FAQ -->

</div>
<!-- // Container Ends -->

<!-- Parallax Footer Starts -->
<main class="footercta" role="main">
    <div class="container">

        <!-- Footer Title -->
        <div class="section-title">
            <h2>Ready to increase your revenue? </h2>
            <h4>Our publishers earn up to 300% higher revenue compared to other networks.<br>
                Discover what it is like to monetize smarter with MadAds Media.</h4>
        </div>
        <div class="row">
            <div class="col-md-12 text-center"> <a href="#top" class="btn btn-warning btn-lg gototop">GET STARTED</a> </div>
        </div>
    </div>
</main>
<!-- // Parallax Footer Ends -->

<!-- Container -->
<div class="container">
    <section class="row breath footercontent">
        <div class="col-sm-4"> <a href="http://twitter.com/madadsmedia" target="_blank" class="social"><img src="/images/landing/twitter.png" alt="twitter"></a> <a href="http://facebook.com/madadsmedialp" target="_blank" class="social"><img src="/images/landing/logo-fb.png" alt="twitter"></a></div>
        <div class="col-sm-4 madeby">
            <a href="http://www.gigenet.com/318.html" title="Proudly Hosted by Gigenet" rel="nofollow" target="_blank">Proudly hosted by:  <img src="/images/landing/Gigenet-Logo.png" alt="logo" width="90"></a>
        </div>
        <div class="col-sm-4 copyinfo">
            <p>©2011-2015 MadAds Media LP</p>
        </div>
    </section>
    <!-- // End Client Logos -->

</div>
<!-- // Container Ends -->

<!-- JS and analytics only. -->
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/js/landing/jquery.js"></script>
<script src="/js/landing/bootstrap.js"></script>
<script src="/js/landing/easing.js"></script>
<script src="/js/landing/nicescroll.js"></script>
<!--<script src="js/contact_form.js"></script>-->
<script src="/fancybox2/jquery.fancybox.js"></script>

<!-- Scroll to Explore -->

<script>


    $(function() {
        $('.scrollto, .gototop').bind('click',function(event){
            var $anchor = $(this);
            $('html, body').stop().animate({
                scrollTop: $($anchor.attr('href')).offset().top
            }, 1500,'easeInOutExpo');
            event.preventDefault();
        });

        $('#term').click(function(){
            if($(this).prop('checked')){
                $.fancybox({
                    'width'	: '75%',
                    'height': '75%',
                    'href'  : '/term',
                    'autoScale'     : false,
                    'transitionIn'  : 'none',
                    'transitionOut'	: 'none',
                    'type'		: 'iframe'
                });
            }
        });
    });


</script>
</body>
</html>