<style type="text/css"> 
    
    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #main{ display: block; width: 1300px; float: left; padding: 10px; }
    
    #main #left{ display: block; float: left; width: 700px; }
    #main #right{ display: block; float: left; width: 530px; margin-left: 15px; overflow: scroll; height: 549px; overflow-x: hidden; border: 1px solid #D3D3D3; padding-top: 4px; padding-left: 4px; }
    
    #right .itemMail{ display: block; float: left; width: 510px; }
    .itemMail .itemHead{ float: left; background: #D3D3D3; padding: 1px 5px 2px; width: 500px; }
    .itemMail .itemDate{ display: block; float: right; width: 150px; text-align: right; }
    .itemMail .itemAuthor{ display: block; float: left; width: 320px; }
    .itemMail .itemSubject{ display: block; float: left; width: 500px; padding: 0px 4px 0px 4px; border: 1px solid #D3D3D3; margin: 0px 0px 2px 0px; }
    .itemMail .itemText{ display: block; float: left; width: 500px; padding: 0px 4px 0px 4px; border: 1px solid #D3D3D3; margin: 2px 0px 7px 0px; }    

    #main #label-subject{ float: left; width: 100px; }
    #main #subject { float: left; width: 696px; margin-bottom: 2px; padding-left: 5px; }
    
    #main #label-text{ float: left; width: 100px; margin-top: 7px; }
    #main #text { float: left; width: 600px; height: 300px; margin-top: 7px; }

    #main .myButton{ display: block; float: right; height: 28px; font-size: 16px; background-color: #8E8E8E; color: #FFFFFF; cursor: pointer; margin-top: 7px; margin-right: 5px; position: relative; }
    #main .myButton:hover{ background-color: #DC2323; }
    #main .myButton span{ float: left; margin: 4px 20px 0px 20px; }   

    #cke_text{ margin-left: 0px; margin-top: 5px; }    
    .error{ color: #CF2B2B; font-weight: 600; font-size: 16px; display: block; }  

    #label-email{ margin-left: 5px; }
    #email{ width: 696px; padding-left: 5px; margin-bottom: 5px; margin-top: 2px; }
    .selectStaff{ padding-bottom: 5px; padding-left: 5px; }
    
</style>

<script type="text/javascript" src="/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/js/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>

<script type="text/javascript">

  var dataRecruiting = <?php echo json_encode($this->recruiting) ?>;

  $(document).ready(function(){
      
      <?php if(isset($this->close)):?>
          parent.jQuery.fancybox.close();
      <?php endif;?> 
     
      $('#text').ckeditor(function() {}, { 
                toolbar : [   [ 'Source','-','Save','NewPage','DocProps','Preview','Print','-','Templates' ],
                              [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ],
                              [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ],
                              [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ],
                              [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat','-','Blockquote','CreateDiv','-','BidiLtr','BidiRtl','-','Link','Unlink','Anchor' ],
                              [ 'NumberedList','BulletedList','-','Outdent','Indent','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock', 'Styles','Format','Font','FontSize','-','TextColor','BGColor' ],
                              [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ]],
                width : '685px',
                height : '300px',
                language : 'en',
                enterMode : CKEDITOR.ENTER_BR,
                filebrowserBrowseUrl : '/js/ckfinder/ckfinder.html',
                filebrowserImageBrowseUrl : '/js/ckfinder/ckfinder.html?type=Images',
                filebrowserFlashBrowseUrl : '/js/ckfinder/ckfinder.html?type=Flash',
                filebrowserUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
                filebrowserImageUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
                filebrowserFlashUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
      });
      
      if(parseInt(dataRecruiting.staff_id)){ $('#staff').val(dataRecruiting.staff_id); }
      
      setText();  
            
  });
  
  function validation(sendEmail)
  {
      var valid = true;
      
      $('.error').replaceWith('');
      
      if(!$('#email').val()){ $("<div class='error'>Field is required</div>").insertAfter("#email"); valid = false; }
      else{ if(!validateEmail($('#email').val())){ $("<div class='error'>Invalid format for Email adress</div>").insertAfter("#email"); valid = false; } }
      
      if(sendEmail){
      
          if(!$('#subject').val()){ $("<div class='error'>Field is required</div>").insertAfter("#subject"); valid = false; }

          var textEditor = $('#text').ckeditorGet(); 
          if(!textEditor.getData()){ $("<div class='error'>Field is required</div>").insertAfter("#cke_text"); valid = false; }   
      
      }
      
      return valid;
  }
  
  function setText()
  {       
      var text = "Hello,<br /><br />\r\n\r\nI was forwarded your contact information by a colleague of yours.  I'd be happy to speak to your futher about MadAdsMedia displaying ads on "+dataRecruiting.website+", as we've seen great success running ads on sites similar to yours.  Could I answer any questions for you, or interest you in a trial run with our company?<br /><br />\r\n\r\nThanks,";

      var editor = $('#text').ckeditorGet();      
          editor.setData(text);    
  } 
  
  function validateEmail($email)
  {
      var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
      if(!emailReg.test($email)){
            return false;
      } else {
            return true;
      }
  }
  
  function mySubmit(sendEmail)
  {
      $('#sendEmail').val(sendEmail); 
      
      if(validation(sendEmail)){ $('#main form').submit(); }      
  }
 
  function display(status)
  {
      $('#mask').css('display', status);      
  }

</script>

<div id="main">    
    <div id="left">

        <form method="post" action="" enctype="multipart/form-data">            
           
            <div id="form-field">
                
                <label id="label-email">New Email Address:</label>
                <input type="text" name="email" id="email" value="" placeholder="Enter new Email"/>
                
                <div class="selectStaff">
                    <label>From (Account Manager):</label>
                    <select name="staff" id="staff">
                        <?php foreach($this->staff as $iter):?>                    
                            <option value="<?php echo $iter['staff_id']?>"><?php echo $iter['name']?></option>                    
                        <?php endforeach;?>  
                    </select>
                </div>
                
                <input type="text" name="subject" id="subject" value="" placeholder="Enter Subject"/>
                <div style="clear: both"></div>            

                <textarea name="text" id="text"></textarea>            
            </div>
                     
            <input type="hidden" name="sendEmail" id="sendEmail" value=""/>
            <div style="clear: both"></div>     
            
            <a class="myButton" onClick="mySubmit(1)"><span>Save & Send Email</span></a>
            <a class="myButton" onClick="mySubmit(0)" style="margin-right: 335px;"><span>Save and DON'T Email</span></a>

        </form>
        
    </div>
    <div id="right">
        
        <?php foreach($this->data as $iter):?>
        
        <div class="itemMail">   
            <div class="itemHead">
                <div class="itemAuthor">sent by: <?php echo $iter['staff_email']; ?></div>
                <div class="itemDate"><?php echo date('M j, Y', strtotime($iter['created'])); ?></div>
            </div>
            <?php if(strlen($iter['subject'])):?>            
            	<div class="itemSubject"><?php echo $iter['subject']; ?></div>
            <?php endif;?>
            <div class="itemText"><?php echo $iter['text']; ?></div>            
        </div>
        
        <?php endforeach;?>
        
    </div>    
</div>

<?php if(!empty($this->message)):?>
<?php echo $this->message;?>
<?php endif; ?>

<div id="mask"></div>