<style type="text/css">

    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    .buttonStatus{         
        cursor: pointer;
        border: 1px solid #797979;
        background-color: #8e8e8e;
        color: #ffffff;
        float: left;
        font-size: 16px;
        height: 28px;
        line-height: 28px;
        margin: -1px 3px 0 0;
        text-align: center;  
        font-size: 12px;
        font-weight: 600;
    }
    .buttonStatus:hover{ background-color: #dc2323; }
    .sendMasBtn{ cursor: pointer; }
    .blockStatus{ width: 230px; display: block; }
    input[type=checkbox].response{ width: 10px; }
    input.datepicker
    {
            border: 1px silver solid;
            width: 200px; 
    }
    
    #tableScroll{ 
        width: 1300px; 
        overflow-y: auto;
        margin-top: 20px;
        float: left;
        resize: horizontal;
    }
    input[name="selectMethod"]{ margin-right: 4px; }
    #selectDiv .errorClose{ 
        color: red;
        font-family: Arial,Helvetica,sans-serif;
        font-size: 13px;
        font-weight: 600;
        width: 150px;
        clear: both;
        display: none;
        margin-top: 15px;
    }

</style>
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" src="/js/dateFormat.js"></script>
<script type="text/javascript">
   
        var pendingTable = new Object();
    
	$(function(){          

                $(".datepicker").datepicker({
                    showOn:'focus',
                    'dateFormat'  : "yy-mm-dd"
                })	

                var widthWindow = parseInt(getClientWidth() - 200);
                var only_manual = $('#only_manual:checked').val() ? 1 : 0;
                var emailedDate = $("#selectEmailed").val();
                var startDate = $('#startDate').val();
		var endDate = $('#endDate').val();  
                var accounts = $('#accounts').val();
                
                $(".click-24h").live('click', function(){ alert('The 24 Hour email was sent.'); });
                $(".click-not-24h").live('click', function(){ alert('The 24 Hour email was not sent.'); });
                                        
                $(".click-final").live('click', function(){ alert('The first email was sent.'); });
                $(".click-not-final").live('click', function(){ alert('The first email was not sent.'); });
                
                $(".click-followed").live('click', function(){ alert('The 2nd email was sent.'); });
                $(".click-not-followed").live('click', function(){ alert('The 2nd email was not sent.'); });
                
                $(".click-initial").live('click', function(){ alert('The 3rd email was sent.'); });
                $(".click-not-initial").live('click', function(){ alert('The 3rd email was not sent.'); });     

		var options =  {
	        "bProcessing": true,
	        "bServerSide": true,
	        "sAjaxSource": null,
	        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "startDate", "value": startDate }, { "name": "endDate", "value": endDate }, { "name": "accounts", "value": accounts }, { "name": "emailedDate", "value": emailedDate }, { "name": "only_manual", "value": only_manual } ); },
	        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
	        "iDisplayLength": 50,
	        "aoColumns": [
	            { 
	              "sType": "num-html", 
	              "sTitle": "ID#",
	              "fnRender": function(obj){ 
                          
			    var id = obj.aData[0];                                                
                                              
	                    return id;
	              	}
	            },
	            { 
		              "sTitle": "Website",
		              "fnRender": function(obj){ 

			              	var website = obj.aData[1];
			              	var re = /^http/;
							var href = (re.test(website)) ? website : "http://"+website;
			              
		                    return "<a href=\""+href+"\" target=\"_blank\">" +obj.aData[1] + "</a>";
	                   }
	            },
	            { 
	                "sTitle": "Email",
	                "fnRender": function(obj)
	                {
		                if(obj.aData[2] != undefined && obj.aData[2].length > 0) 
	                    	return "<a href=\"mailto:"+obj.aData[2]+"\" target=\"_blank\">" +obj.aData[2] + "</a>";
		                else if(obj.aData[15] != undefined && obj.aData[15].length >0)
			                return "<center><a class=\"buttonStatus\" style=\"cursor: pointer; width: 160px;\" href=\"http://"+obj.aData[15]+"\" target=\"_blank\">Open Contact Form</a></center>";
		                return "";
		            }
	            },        
                    { 
	                "sTitle": "",
                        "bSortable": false,
	                "fnRender": function(obj){ 
	                    return "<a style=\"cursor: pointer;\" onClick=\"editEmail("+obj.aData[3]+")\"><img src=\"/images/edit-pen-18.png\"></a>";
	               		}
	            },  
	            { 
	                "sTitle": "Status",
                        "sClass": "blockStatus",
                        "bSortable": false,
	                "fnRender": function(obj){ 
                            
                           var result = '';
                           
                           if(obj.aData[10] == '1') /*pending*/
                                result += '<a class="buttonStatus click-initial" style="width:40px; background-color: #DFDFDF; color: #8e8e8e;">Initial</a>';
                           else result += '<a class="buttonStatus" onClick="mailManual(1, '+obj.aData[13]+')" style="width:40px;">Initial</a>'; 
                           
                           if(obj.aData[14]) /*24 Hour*/
                                result += '<a class="buttonStatus click-24h" style="width:50px; background-color: #DFDFDF; color: #8e8e8e;">24Hour</a>';
                           else result += '<a class="buttonStatus" onClick="mailManual(4, '+obj.aData[13]+')" style="width:50px;">24Hour</a>'; 
                                                      
                           if(obj.aData[11] == '1') /*followed_up*/
                                result += '<a class="buttonStatus click-followed" style="width:80px; background-color: #DFDFDF; color: #8e8e8e;">Followed Up</a>';
                           else result += '<a class="buttonStatus" onClick="mailManual(2, '+obj.aData[13]+')" style="width:80px;">Followed Up</a>'; 

                           if(obj.aData[12] == '1') /*final*/
                                result += '<a class="buttonStatus click-final" style="width:40px; background-color: #DFDFDF; color: #8e8e8e;">Final</a>';
                           else result += '<a class="buttonStatus" onClick="mailManual(3, '+obj.aData[13]+')" style="width:40px;">Final</a>'; 
                           
                           return result;	                   	
	               	}
	            },            
	            { 
	                "sTitle": "Opportunity",
                        "bSortable": false,
	                "fnRender": function(obj){ 

                            var id = obj.aData[13];  
                  
                            if(parseInt(obj.aData[5]))
                                 return '<a href="#" style="width:60px; background-color: #DFDFDF;" class="sendMasBtn">Open</a>';                        
                            else return '<a href="#" real="'+id+'" style="width:60px;" class="sendMasBtn OpenOpportunity">Open</a>';

	               	}
	            },
                    { 
	                "sTitle": "Close Lead",
                        "bSortable": false,
	                "fnRender": function(obj){ 
                            
                            var id = obj.aData[13];
                            
                            if(parseInt(obj.aData[6])) 
                                 return "<a style=\"width:60px; background-color: #DFDFDF;\" class=\"sendMasBtn\">Closed</a>";
                            else return "<a href=\"#\" real=\""+id+"\" style=\"width:60px;\" class=\"sendMasBtn CloseLead\">Close</a>";
                                
	                    
                            
	               	}
	            },
                    { 
                        "sTitle": "Import Date",
                        "bSortable": true,
                        "fnRender": function(obj){ 
                            
                            return obj.aData[7];                   
                        
                        }         
                    },
                    { 
                        "sTitle": "Last Emailed",
                        "bSortable": true,
                        "fnRender": function(obj){ 
                            
                            if(obj.aData[8] && obj.aData[8] != '0000-00-00 00:00:00'){
                                
                                      var arr = obj.aData[8].split(" ");
                                      var date = new Date(arr[0]);
                                      
                                      date.setDate(date.getUTCDate());
                                      
                                   return  $.format.date(date, "yyyy MMM, dd");
                            } else return '';
                        }             
                    },
                    { 
	                "sTitle": "Manually Email",
                        "bSortable": false,
	                "fnRender": function(obj){ 
                                              
                            var res = '';                  
                                              
                            if(parseInt(obj.aData[9]))
                                 res = '<input type="checkbox" style="width: 10px;" value="1" onChange="setManual('+obj.aData[13]+', 0, this)" checked="checked">';                       	   		
                            else res = '<input type="checkbox" style="width: 10px;" value="0" onChange="setManual('+obj.aData[13]+', 1, this)">';                  	                        
 
                            return res; 
	               	}
	            },
                    {
                        "sTitle": "Delete",
                        "bSortable": false,
	                "fnRender": function(obj){                                             
                                              
                            return '<img src="/images/stats-red-x.gif" style="cursor: pointer;" onClick="if(confirm(\'Delete this row ?\')){ deleteRecruiting('+obj.aData[13]+') }"/>';                   	   		
                        }
                    }
	        ],
	        "fnDrawCallback": function(){
                
                       var widthTable = parseInt($('#pendingTable').css('width'));
                                                                    
                       if(widthTable > widthWindow){ $('#tableScroll').css('width', widthWindow); }
                                               else{ $('#tableScroll').css('width', widthTable);  }
                
                       display('none'); 
                },
	        "aaSorting": [[ 7, "desc" ]]
		};

	    options.sAjaxSource = "/administrator/recruiting/get-ajax-pending";
	    pendingTable = $('#pendingTable').dataTable(options);

        $('#startDate').change(function () {startDate = $('#startDate').val(); endDate = $('#endDate').val(); display('block'); pendingTable.fnDraw();});
        $('#endDate').change(function () {startDate = $('#startDate').val(); endDate = $('#endDate').val(); display('block'); pendingTable.fnDraw();});    
	$('#selectEmailed').change(function () {emailedDate = $('#selectEmailed').val(); display('block'); pendingTable.fnDraw();});        
	$('#only_manual').change(function () {only_manual = $('#only_manual:checked').val() ? 1 : 0; display('block'); pendingTable.fnDraw();})    
            
	    $('#selectDate').change(function(){

            var period = $('#selectDate option:selected').val();
            var str = period.split('_');  

            startDate = str[0];
            endDate = str[1];

            $('#startDate').val(startDate);
            $('#endDate').val(endDate);
            
            display('block');
            pendingTable.fnDraw();
        });

            
            $(".CloseLead").live('click', function(){
                var id = $(this).attr('real');
                $("#lineID").val(id);
                    $.fancybox({
                        'titlePosition'		: 'inside',
                        'transitionIn'		: 'fade',
                        'transitionOut'		: 'fade',
                        'autoDimensions'	: false,
                        'width'			: 260,
                        'height'		: 280,
                        'href'			: '#selectDiv',
                        'onComplete'		: function () { $("#selectDiv").css('display', 'block'); },
                        'onClosed'		: function () { $("#selectDiv").css('display', 'none'); 
                            
                                                                $("#lineID").val('');
                                                                $('#note_short').val(''); 
                                                                $('input[name="selectMethod"]').attr('checked', false);
                                                                $('input[name="never_contact"]').attr('checked', false); }

                    });
                return false;            
            });             
            $("#selectPost").click(function(){
            
                    var validClose = true;
                    var notes = $('#note_short').val(); 
                    var action = $('input[name="selectMethod"]:checked').val();
                    var never_contact = $('input[name="never_contact"]:checked').val() ? 1 : 0; 
                    
                    if(action){ $('#selectDiv .errorClose').css('display', 'none');  validClose = true;  }
                          else{ $('#selectDiv .errorClose').css('display', 'block'); validClose = false; }                    
            
                    if(validClose){
            
                        $("#AjaxLoader").css('display', 'block');
                        $.ajax({
                                'url'	:  '/administrator/recruiting/setclosed/',
                                'data'	:  'id='+$("#lineID").val()+'&action='+action+'&notes='+notes+'&never_contact='+never_contact,
                                'type'	:  'POST',
                                'dataType'	:  'json',
                                'success'   :   function(data){
                                                if(data.error){
                                                        alert(data.error);
                                                        $("#AjaxLoader").css('display', 'none');
                                                }else if(data.status=='OK'){
                                                        pendingTable.fnClearTable();
                                                        $("#AjaxLoader").css('display', 'none');
                                                        $.fancybox.close();
                                                }else{
                                                        alert("Application ERROR!!!");
                                                }
                                        }
                        });                    
                    }
                    return false;
            });  
            
            $(".OpenOpportunity").live('click', function(){
            
                    var id = $(this).attr('real');
                
                    $.fancybox({
                        'width'	        : '90%',
                        'height'	: '75%',
                        'href'          : '/administrator/recruiting/stage-opportunities/id/'+id,
                        'autoScale'    	: false,
                        'transitionIn'	: 'none',
                        'transitionOut'	: 'none',
                        'type'		: 'iframe',
                        'onClosed'      : function(){ display('block'); pendingTable.fnClearTable(); }
                    });                
                return false;            
            }); 

            $('#accounts').change(function(){ accounts = $('#accounts').val(); pendingTable.fnClearTable(); });            
	});
        
        function mailManual(orderID, recruitingID)
        {
            $.fancybox({
                'width'	        : '90%',
                'height'	: '75%',
                'href'          : '/administrator/recruiting/manually-notifi/order_id/'+orderID+'/recruiting_id/'+recruitingID,
                'autoScale'    	: false,
                'transitionIn'	: 'none',
                'transitionOut'	: 'none',
                'type'		: 'iframe',
                'onClosed'      : function(){ display('block'); pendingTable.fnClearTable(); }
            }); 
        }
        
        function setManual(id, value, element)
        {
              display('block');
            
              $.ajax({ url : '/administrator/recruiting/set-manual',
                      data : { id : id, value : value },
                      type : "POST",
                     async : false, 
                  dataType : "json",

             success : function(response) {                  
                 
                 if(response){
                     if(parseInt(value)){

                         $(element).attr('onChange', 'setManual('+id+', 0, this)');
                       
                     } else {

                         $(element).attr('onChange', 'setManual('+id+', 1, this)');        
                     }
                 } else { 
                     
                     if(parseInt(value)){ $(element).prop('checked', false); }
                                    else{ $(element).prop('checked', true); }
                     
                     alert('Please try again!'); 
                 }

                 display('none');

             }, error : function(){ display('none'); alert('ajax request return error'); }}); 
        }
        
        function editEmail(id)
        {
            $.fancybox({
                'width'	        : '90%',
                'height'	: '75%',
                'href'          : '/administrator/recruiting/edit-email/recruiting_id/'+id,
                'autoScale'    	: false,
                'transitionIn'	: 'none',
                'transitionOut'	: 'none',
                'type'		: 'iframe',
                'onClosed'      : function(){ display('block'); pendingTable.fnClearTable(); }
            }); 
        }
        
        function deleteRecruiting(id)
        {
            display('block');
            
            $.ajax({ url : '/administrator/recruiting/delete',
                      data : { recruiting_id : id },
                      type : "POST",
                     async : false, 
                  dataType : "json",

             success : function(response) {                  
                 
                 pendingTable.fnClearTable();
                 
                 if(!response){ alert('Please try again!'); }                 

             }, error : function(){ display('none'); alert('ajax request return error'); }}); 
        }
        
        function display(status)
        {
            $('#mask').css('display', status);
            $('#loading').css('display', status);         
        }
        
        function getClientWidth()
        {
          return document.compatMode=='CSS1Compat' && !window.opera?document.documentElement.clientWidth:document.body.clientWidth; 
        }
        
</script>

<div class="contUsL" style="float:left; width:750px;">

	<h1>Open Leads</h1>
	<br /><br />
        
        <select id="selectEmailed" name="selectEmailed">
                <option value="">Select Last Emailed</option>
                <option value="<?php echo date("Y-m-d", strtotime('-1 day'));?>" <?php echo date("Y-m-d", strtotime('-1 day')) == $this->emailed ? 'selected' : ''; ?>>1+ Days</option>
                <option value="<?php echo date("Y-m-d", strtotime('-2 day'));?>" <?php echo date("Y-m-d", strtotime('-2 day')) == $this->emailed ? 'selected' : ''; ?>>2+ Days</option>                    
                <option value="<?php echo date("Y-m-d", strtotime('-3 day'));?>" <?php echo date("Y-m-d", strtotime('-3 day')) == $this->emailed ? 'selected' : ''; ?>>3+ Days</option>
                <option value="<?php echo date("Y-m-d", strtotime('-4 day'));?>" <?php echo date("Y-m-d", strtotime('-4 day')) == $this->emailed ? 'selected' : ''; ?>>4+ Days</option> 
                <option value="<?php echo date("Y-m-d", strtotime('-5 day'));?>" <?php echo date("Y-m-d", strtotime('-5 day')) == $this->emailed ? 'selected' : ''; ?>>5+ Days</option>                              
                <option value="<?php echo date("Y-m-d", strtotime('-6 day'));?>" <?php echo date("Y-m-d", strtotime('-6 day')) == $this->emailed ? 'selected' : ''; ?>>6+ Days</option>  
                <option value="<?php echo date("Y-m-d", strtotime('-7 day'));?>" <?php echo date("Y-m-d", strtotime('-7 day')) == $this->emailed ? 'selected' : ''; ?>>7+ Days</option> 
        </select>  
        
        <input type="checkbox" name="only_manual" id="only_manual" value="1" <?php echo $this->manual == '1' ? 'checked' : ''; ?> style="background: none; height: 15px; width: 20px; margin-left: 22px;"/>
        <span style="">Show Only Manually Email</span>
        
        <br />
        
        <select id="accounts" style="top: 30px; margin-top: 7px;">
            <?php if($this->dataAuth->role == 'super'):?>
                <option value="-1">Select Recruiter</option>
                <?php foreach($this->contactManager as $iter):?>
                     <option value="<?php echo $iter['staff_id']?>" <?php if($iter['staff_id'] == $this->name):?>selected<?php endif;?>><?php echo $iter['mail'];?></option>
                <?php endforeach;?>    
            <?php else: ?>
                <option value="-1">Show All Accounts</option>
                <?php if(!empty($this->personalManager['staff_id'])):?>
                   <option value="<?php echo $this->personalManager['staff_id']; ?>" <?php if($iter['staff_id'] == $this->name):?>selected<?php endif;?>>Show My Account</option> 
                <?php endif;?>
            <?php endif;?>    
        </select>
                
<br/><br/>
	<p >Start Date: <input type="text" class="datepicker" name="startDate" value="<?php echo $this->startDate ?>" id="startDate" /> End Date: <input type="text" class="datepicker" name="endDate" value="<?php echo $this->endDate ?>" id="endDate" /></p>
	<br/>
	<div id="tableScroll">
      
		<table class="display" id="pendingTable" width="740px">
			<thead>
				<tr>
					<th width="5%">ID #</th>
					<th width="20%">Site</th>
					<th width="20%">Email</th>
                                        <th width="5%"></th>
					<th width="30%">Status</th>
					<th width="5%">Opportunity</th>
                                        <th width="5%">Close Lead</th>
                                        <th width="5%">Import Date</th>
                                        <th width="5%">Last Emailed</th>
                                        <th width="5%">Manually Email</th>
                                        <th width="5%">Delete</th>
				</tr>
			</thead>
			<tbody></tbody>
			<tfoot>
				<tr>
					<th>ID #</th>
					<th>Site</th>
					<th>Email</th>
                                        <th></th>
					<th>Status</th>
					<th>Opportunity</th>
                                        <th>Close Lead</th>
                                        <th>Import Date</th>
                                        <th>Last Emailed</th>
                                        <th>Manually Email</th>
                                        <th>Delete</th>
				</tr>
			</tfoot>
		</table>
      
	</div>
        
        <div id="selectDiv" style="display: none;">
        <img alt="" id="AjaxLoader" src="/images/ajax-loader.gif" style="display: none">
                <form action="#" method="post">
                        <input type="hidden" id="lineID" value="" />
                            <p style="padding-bottom: 2px;"><input name="selectMethod" type="radio" value="1"/><span>Not interested (undisclosed reason)</span></p>
                            <p style="padding-bottom: 2px;"><input name="selectMethod" type="radio" value="2"/><span>Asking CPM Too High</span></p>
                            <p style="padding-bottom: 2px;"><input name="selectMethod" type="radio" value="3"/><span>Never Responded</span></p>
                            <p style="padding-bottom: 2px;"><input name="selectMethod" type="radio" value="5"/><span>Site Does Not Have Ads</span></p> 
                            <p><input name="selectMethod" type="radio" value="4"/><span>Other</span></p>
                            <span class="errorClose">Fileld is required</span>
                        <p style="margin-top: 12px">
                            <input type="checkbox" name="never_contact"/><span style="margin-left: 5px;">Never Contact Site Again</span>
                        </p>
                        <p style="margin-top: 10px;">
                            <textarea name="note_short" id="note_short" style="width: 223px; height: 100px; padding: 3px 5px;" placeholder="Notes (keep it short)"></textarea>
                        </p>
                        <a class="sendMasBtn" style="width: 60px; margin-top: 10px;" id="selectPost" title="" href="#">Save</a>
                </form>
        </div>	
</div>

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script	type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script	type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
    Cufon.replace('h1');		
</script>