<style type="text/css">
    
    #wait{ width: 427px; border-collapse: collapse; border: 1px #B7B7B7 solid; margin-top: 20px; }
    #wait tr td{

        border: 1px #B7B7B7 solid;
        font-size: 13px;
        font-family: Arial,Helvetica,sans-serif;
        padding: 5px;
     }
    
    #wait tr th{
        
        border: 1px #B7B7B7 solid;
        font-size: 16px;
        font-family: Arial,Helvetica,sans-serif;
        padding: 5px;
        text-align: center;
    }
    
</style>     

<h1>Contact Info</h1>
            <div class="contUsL">
	    <form method="post" class="sign-up">
            
            <p><label>Contact Name: </label><input type="text" name="name" value="<?php echo $this->formValues['name'] ?>" /></p>
            <?php if($this->formErrors['name']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['name'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            
            <p><label>Company: </label><input type="text" name="company" value="<?php echo $this->formValues['company'] ?>" /></p>
            <?php if($this->formErrors['company']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['company'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <p><label>E-mail: </label><input type="text" name="email" value="<?php echo $this->formValues['email'] ?>" /></p>
            <?php if($this->formErrors['email']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['email'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <p><label>Phone: </label><input type="text" name="phone" value="<?php echo $this->formValues['phone'] ?>" /></p>
            <?php if($this->formErrors['phone']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['phone'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <p><label>Notifications</label> <input type="checkbox" id="notification_control_user" name="notification_control_user" value="1" <?php echo $this->formValues['notification_control_user']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /><span style="margin: 4px 90px 0px 0px; float: right;">(Email me with news & updates)</span></p>
            <br />
                        <a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Submit</a>  

        <input type="hidden" id="csrf" value="<?php echo $this->csrf;?>" name="csrf">    
     <input type="submit" id="subForm" style="display: none;" />
     </form>
     <br /><br />           
     <?php if($this->wait->id):?>           
         <table id="wait">
             <thead>
                 <tr>
                     <th colspan="2">Data that are awaiting confirmation admin</th>                 
                 </tr>
             </thead>
             <tbody>
                 <tr>
                     <td>Company</td>
                     <td><?php echo $this->wait->company;?></td>
                 </tr>
                 <tr>
                     <td>Name</td>
                     <td><?php echo $this->wait->name;?></td>
                 </tr>
                 <tr>
                     <td>Email</td>
                     <td><?php echo $this->wait->email;?></td>
                 </tr>
                 <tr>
                     <td>Phone</td>
                     <td><?php echo $this->wait->phone?></td>
                 </tr>
             </tbody>
         </table>     
     <?php endif;?>           
                
                
                
     </div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
        Cufon.replace('.error', {color: 'red'});
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
    Cufon.replace('h1');
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
