		<h1>Update Password</h1>
            <form method="post" class="sign-up">
            <div class="contUsL">
            <p><label>Old Password: </label><input type="password" name="oldPass" /></p>
            <?php if($this->formErrors['oldPass']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['oldPass'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            
            <p><label>New Password: </label><input type="password" name="password" /></p>
            <?php if($this->formErrors['password']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['password'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <p><label>Confirm New Password: </label><input type="password" name="passwordConfirm" /></p>
            <?php if($this->formErrors['passwordConfirm']): ?>
                <ul class="error">
                <?php foreach($this->formErrors['passwordConfirm'] as $errors): ?>
                    <li><?php echo $errors ?></li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <br />
                        <a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Submit</a>  

            </div>
     <input type="submit" id="subForm" style="display: none;" />
            </form>


<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
        Cufon.replace('.error', {color: 'red'});
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
    Cufon.replace('h1');
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
