<script type="text/javascript" src="/js/jquery.qtip.min.js"></script>
<link href="/styles/jquery.qtip.min.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript">
    $(document).ready(function(){                        
        $(".selectDate").click(function(){
            $("#search-start_date").val($(this).attr('start'));
            $("#search-end_date").val($(this).attr('end'));
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($(this).attr('start')))+' - '+$.datepicker.formatDate('M d, yy', new Date($(this).attr('end'))));            
        })
        
        $("#search-start_date").change(function(){
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($("#search-start_date").val()))+' - '+$.datepicker.formatDate('M d, yy', new Date($("#search-end_date").val())));                        
        })        

        $("#search-end_date").change(function(){
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($("#search-start_date").val()))+' - '+$.datepicker.formatDate('M d, yy', new Date($("#search-end_date").val())));                        
        })        

        $("#update").click(function(){
            $("#formDate").submit();       
        })

        $("#cancel").click(function(){
            $("#showBox").html($(this).attr('txt'));         
        })

    	$('.gtip').qtip({
    		content: 'ECPM and Revenue take 48 hours to display for new users.  After 3 days of finalized data, we will begin to provide accurate estimated data in real-time.',
    		position: {
    			my: 'top left',
    			target: 'mouse',
    			viewport: $(window), // Keep it on-screen at all times if possible
    			adjust: {
    				x: 10,  y: 10
    			}
    		},
    		hide: {
    			fixed: true // Helps to prevent the tooltip from hiding ocassionally when tracking!
    		},
    		style: 'ui-tooltip-shadow'
    	});
        
        $(".reportBox").tabs();

    }) ;   
</script>
<form name="size" method="get" id="formDate" action="">	
<input type="hidden" name="id" value="<?php echo $id ?>">				
            <!--report TOP-->                                            
            <div class="reportTop">
            	<h5>Earnings</h5>                
                <div class="dateBox">
                	<p class="dateBoxInn"><a href="#" title="" class="dateLink" id="showBox"><?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?> – <?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?></a></p>
                    <div class="subDate">
                    	<div class="dateRanch">
                        	<h5>Date Range </h5>
                            <input type="text" value="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?>" name="start_date" id="search-start_date"  onfocus="this.value=''" onblur="if (this.value==''){this.value=''}" class="datepicker" />
                            <input type="text" value="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?>" name="end_date" id="search-end_date"  onfocus="this.value=''" onblur="if (this.value==''){this.value=''}" class="datepicker"/>                            
                            <p>
                            	<a href="#" title="" class="dCancelBtn" id="cancel" txt="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?> – <?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?>">Cancel</a>
                            	<a href="#" title="" class="dUpdlBtn" id="update">Update</a>                            
                            </p>
                        </div>
                        
                        <div class="quickDate">
                        	<h5>Quick dates</h5>
                            <br class="clear" />
                            <ul>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y"); ?>" end="<?php echo date("M j, Y"); ?>" title="">Today</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-1,date("Y"))); ?>" title="">Yesterday</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-7,date("Y"))); ?>" end="<?php echo date("M j, Y"); ?>" title="">Last 7 days</a></li>
                            </ul>
                            
                            <ul class="rightUl">
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-30,date("Y"))); ?>" end="<?php echo date("M j, Y"); ?>" title="">Last 30 days</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("t"),date("Y"))); ?>" title="">This month:<span> <?php echo date("F") ?></span></a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m")-1,1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m")-1,date("t", mktime(0,0,0,date("m")-1,1,date("Y"))),date("Y"))); ?>" title="">Last month: <span><?php echo date("F", mktime(0,0,0,date("m")-1,1,date("Y"))); ?></span></a></li>
                            </ul>                            
                        </div>
                    </div>
                </div>
                <p class="sizeSel"><b>Size</b>
                	<select onchange="this.form.submit();" name="ad_size">
                    	<option value="">All Media Types</option>
        <?php foreach($this->ad_sizes as $ad_size) { ?>
            <option value="<?php echo htmlentities($ad_size["key"]); ?>"<?php if ($this->report_params["ad_size"] ==$ad_size["key"]) { echo ' selected'; } ?>><?php echo htmlentities($ad_size["value"]); ?></option>
        <?php } ?>
                    </select>
                </p>
                <p class="sizeSel"><b>Site</b>
                	<select onchange="this.form.submit();" name="site">
                    	<option value="">All Sites</option>
    <?php foreach($this->sites as $site) { ?>
        <option value="<?php echo htmlentities($site["SiteID"]); ?>"<?php if ($this->report_params["site"] ==$site["SiteID"]) { echo ' selected'; } ?>><?php echo htmlentities($site["SiteName"]); ?></option>  
    <?php } ?>
                    </select>
                </p> 
                <?php if(isset($this->fileCsv)):?>
                <p class="sizeSel">
                    <a href="<?php echo $this->fileCsv;?>">
                    <img src="/images/csv-24.gif"/>
                    </a>
                </p>
                <?php endif;?>
            </div>
            <!--//report TOP--> 
            <?php if($this->auth->role=='admin'):?>
            <br><br><br><p><label>Show Demand Sources</label><input type="checkbox" name="show_demand" <?php echo $this->report_params["show_demand"]==1 ? "checked='checked'" : '' ?> onclick="this.form.submit();" value="1" /></p>
            <?php endif;?>
            
</form>
<br><br><br>
<div class="reportBox" style="padding: 0; width: 743px;">	
	<ul>
		<li style="width: 100px"><a href="#rub">Rubicon</a></li>
		<li style="width: 100px"><a href="#google">Google</a></li>
		<li style="width: 100px"><a href="#estim">Estimated</a></li>
		<li style="width: 100px"><a href="#all">All</a></li>
	</ul> 
    
    <div id="rub">
	<?php 
	$totalimpressions = 0;
	$totalecpm = 0;
	$totalrevenue = 0;
	$asterics = false;
	
	$nodataImpres=false;
	$countEstim = 0;
	$count = 0;
	$line1_rub = "[";
	$line2_rub = "[";	
	?>
	
		<table cellpadding="0" cellspacing="0" id="reportTbl" style="width: 720px;">		
		<tr>			
		    <th>Date</th>			
		    <th>Impressions</th>
		    <th>eCPM</th>			
		    <th class="lastTh">Revenue</th>		
		</tr>																
	<?php if($this->report):?>
		<?php foreach ($this->report as $item):?>
			<?php 
				$nodataImpres=false;
			
				if($item['impressionRubicon']){
					$totalimpressions +=$item['impressionRubicon'];
					
					if($item['revenueRubicon']!=0)
						$ecpm = $item['revenueRubicon']*1000/$item['impressionRubicon'];
				}else{
					$ecpm = 0;
				}		
								
				$totalrevenue += $item['revenueRubicon'];
				
				//graph
				$count++;
				$formatLine_rub = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['Date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($item['impressionRubicon']).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($item['revenueRubicon'],2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm,2).'</td></tr></table>';
				
				if($count==count($this->report)){
					$line1_rub.= "['$item[Date]', ".str_replace(',','.',$item['impressionRubicon']).", '$formatLine_rub']";
					$line2_rub.= "['$item[Date]', ".str_replace(',','.',$item['revenueRubicon']).", '$formatLine_rub']";
				}else{
					$line1_rub.= "['$item[Date]', ".str_replace(',','.',$item['impressionRubicon']).", '$formatLine_rub'], ";
					$line2_rub.= "['$item[Date]', ".str_replace(',','.',$item['revenueRubicon']).", '$formatLine_rub'], ";
				}
			?>
			<tr>
				<td><?php echo $item['Date']?><?php echo $asterics?></td>
				<td><?php echo $nodataImpres ? '-' : number_format($item['impressionRubicon']) ?><?php echo $asterics?></td>
				<td><?php echo $ecpm==0 ? '-' : "$".number_format($ecpm,2)?><?php echo $asterics?></td>
				<td><?php echo $ecpm==0 ? '-' : "$".number_format($item['revenueRubicon'],2)?><?php echo $asterics?></td>
			</tr>
		<?php endforeach;?>
		
		<?php 
			$noresult_rub=false;
			$line1_rub.= "]";
			$line2_rub.= "]";
		?>	
	
	<?php else: ?>
		<?php 
	    $line1_rub = "[";
	    $line2_rub = "[";
	
	    $start = strtotime($this->report_params['start_date']);
	    $end = strtotime($this->report_params['end_date']);
	        
	    for($i=$start; $i<=$end; $i=$i+86400){
	                
	        $formatLine_rub = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
	        
	        $line1_rub.= "['".date("M d, Y", $i)."', 0.000, '$formatLine_rub'], ";
	        $line2_rub.= "['".date("M d, Y", $i)."', 0.00, '$formatLine_rub'], ";  
	    }
	
	    $line1_rub.= "]";
	    $line2_rub.= "]"; 
	    
	    $noresult_rub=true;
	    ?>	
	
	<?php endif;?>	
	<?php 
		if($totalimpressions > 0) {
			$totalecpm = $totalrevenue / ($totalimpressions/1000);
		}else{
			$totalecpm = "0.00";
		} 
	?>
		
		<tr>
			<td class="total">Totals </td>
			<td class="total"><?php echo number_format($totalimpressions) ?></td>
			<td class="total">$<?php echo number_format($totalecpm,2) ?></td>
			<td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
		</tr>
		</table>
		<div id="chartdiv_rub" style="height: 300px; width: 750px;"></div>        
    </div>
    
    <div id="google">
	<?php 
	$totalimpressions = 0;
	$totalecpm = 0;
	$totalrevenue = 0;
	$asterics = false;
	
	$nodataImpres=false;
	$countEstim = 0;
	$count = 0;
	$line1_gog = "[";
	$line2_gog = "[";	
	?>
	
		<table cellpadding="0" cellspacing="0" id="reportTbl" style="width: 720px;">		
		<tr>			
		    <th>Date</th>			
		    <th>Impressions</th>
		    <th>eCPM</th>			
		    <th class="lastTh">Revenue</th>		
		</tr>																
	<?php if($this->report):?>
		<?php foreach ($this->report as $item):?>
			<?php 
				$nodataImpres=false;
			
				if($item['impressionAdExchange']){
					$totalimpressions +=$item['impressionAdExchange'];
					
					if($item['revenueAdExchange']!=0)
						$ecpm = $item['revenueAdExchange']*1000/$item['impressionAdExchange'];
				}else{
					$ecpm = 0;
				}		
								
				$totalrevenue += $item['revenueAdExchange'];
				
				//graph
				$count++;
				$formatLine_gog = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['Date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($item['impressionAdExchange']).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($item['revenueAdExchange'],2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm,2).'</td></tr></table>';
				
				if($count==count($this->report)){
					$line1_gog.= "['$item[Date]', ".str_replace(',','.',$item['impressionAdExchange']).", '$formatLine_gog']";
					$line2_gog.= "['$item[Date]', ".str_replace(',','.',$item['revenueAdExchange']).", '$formatLine_gog']";
				}else{
					$line1_gog.= "['$item[Date]', ".str_replace(',','.',$item['impressionAdExchange']).", '$formatLine_gog'], ";
					$line2_gog.= "['$item[Date]', ".str_replace(',','.',$item['revenueAdExchange']).", '$formatLine_gog'], ";
				}
			?>
			<tr>
				<td><?php echo $item['Date']?><?php echo $asterics?></td>
				<td><?php echo $nodataImpres ? '-' : number_format($item['impressionAdExchange']) ?><?php echo $asterics?></td>
				<td><?php echo $ecpm==0 ? '-' : "$".number_format($ecpm,2)?><?php echo $asterics?></td>
				<td><?php echo $ecpm==0 ? '-' : "$".number_format($item['revenueAdExchange'],2)?><?php echo $asterics?></td>
			</tr>
		<?php endforeach;?>
		
		<?php 
			$noresult_gog=false;
			$line1_gog.= "]";
			$line2_gog.= "]";
		?>	
	
	<?php else: ?>
		<?php 
	    $line1_gog = "[";
	    $line2_gog = "[";
	
	    $start = strtotime($this->report_params['start_date']);
	    $end = strtotime($this->report_params['end_date']);
	        
	    for($i=$start; $i<=$end; $i=$i+86400){
	                
	        $formatLine_gog = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
	        
	        $line1_gog.= "['".date("M d, Y", $i)."', 0.000, '$formatLine_gog'], ";
	        $line2_gog.= "['".date("M d, Y", $i)."', 0.00, '$formatLine_gog'], ";  
	    }
	
	    $line1_gog.= "]";
	    $line2_gog.= "]"; 
	    
	    $noresult_gog=true;
	    ?>	
	
	<?php endif;?>	
	<?php 
		if($totalimpressions > 0) {
			$totalecpm = $totalrevenue / ($totalimpressions/1000);
		}else{
			$totalecpm = "0.00";
		} 
	?>
		
		<tr>
			<td class="total">Totals </td>
			<td class="total"><?php echo number_format($totalimpressions) ?></td>
			<td class="total">$<?php echo number_format($totalecpm,2) ?></td>
			<td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
		</tr>
		</table>
		<div id="chartdiv_gog" style="height: 300px; width: 750px;"></div>           
    </div>

    <div id="estim">
	<?php 
	$totalimpressions = 0;
	$totalecpm = 0;
	$totalrevenue = 0;
	$asterics = false;
	
	$nodataImpres=false;
	$countEstim = 0;
	$count = 0;
	$line1_est = "[";
	$line2_est = "[";	
	?>
	
		<table cellpadding="0" cellspacing="0" id="reportTbl" style="width: 720px;">		
		<tr>			
		    <th>Date</th>			
		    <th>Impressions</th>
		    <th>eCPM</th>			
		    <th class="lastTh">Revenue</th>		
		</tr>																
	<?php if($this->report):?>
		<?php foreach ($this->report as $item):?>
			<?php 
				$nodataImpres=false;
			
                                $totalimpressions +=$item['impressionEstimS'];
																	
				//graph
				$count++;
				$formatLine_est = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['Date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($item['impressionEstimS']).'</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
				
				if($count==count($this->report)){
					$line1_est.= "['$item[Date]', ".str_replace(',','.',$item['impressionEstimS']).", '$formatLine_est']";
					$line2_est.= "['$item[Date]', ".str_replace(',','.',0.00).", '$formatLine_est']";
				}else{
					$line1_est.= "['$item[Date]', ".str_replace(',','.',$item['impressionEstimS']).", '$formatLine_est'], ";
					$line2_est.= "['$item[Date]', ".str_replace(',','.',0.00).", '$formatLine_est'], ";
				}
			?>
			<tr>
				<td><?php echo $item['Date']?><?php echo $asterics?></td>
				<td><?php echo number_format($item['impressionEstimS']) ?></td>
				<td><?php echo '-' ?></td>
				<td><?php echo '-' ?></td>
			</tr>
		<?php endforeach;?>
		
		<?php 
			$noresult_est=false;
			$line1_est.= "]";
			$line2_est.= "]";
		?>	
	
	<?php else: ?>
		<?php 
	    $line1_est = "[";
	    $line2_est = "[";
	
	    $start = strtotime($this->report_params['start_date']);
	    $end = strtotime($this->report_params['end_date']);
	        
	    for($i=$start; $i<=$end; $i=$i+86400){
	                
	        $formatLine_est = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
	        
	        $line1_est.= "['".date("M d, Y", $i)."', 0.000, '$formatLine_est'], ";
	        $line2_est.= "['".date("M d, Y", $i)."', 0.00, '$formatLine_est'], ";  
	    }
	
	    $line1_est.= "]";
	    $line2_est.= "]"; 
	    
	    $noresult_est=true;
	    ?>	
	
	<?php endif;?>	
	<?php 
		if($totalimpressions > 0) {
			$totalecpm = "0.00";
		}else{
			$totalecpm = "0.00";
		} 
	?>
		
		<tr>
			<td class="total">Totals </td>
			<td class="total"><?php echo number_format($totalimpressions) ?></td>
			<td class="total">-</td>
			<td class="total lastTd">-</td>                                                            
		</tr>
		</table>
		<div id="chartdiv_est" style="height: 300px; width: 750px;"></div>                   
    </div>

    <div id="all">
<?php if($this->floor_pricing==1):?>
	<?php 
	$totalimpressions = 0;
	$totalPaidimpressions = 0;
	$totalecpm = 0;
	$totalrevenue = 0;
	
	$count = 0;
	$line1 = "[";
	$line2 = "[";
	$line3 = "[";	
	?>

	<table cellpadding="0" cellspacing="0" id="reportTbl" style="width: 720px;">		
	<tr>			
	    <th>Date</th>			
	    <th>Impressions</th>
	    <th>Paid Impressions</th>			
	    <th>eCPM</th>			
	    <th class="lastTh">Revenue</th>		
	</tr>																
	
	<?php if($this->report):?>
		<?php foreach ($this->report as $item):?>
			<?php 
                        
                        
				if($item['paid_impressions']){					
					$totalPaidimpressions +=$item['paid_impressions'];
					
					if($item['revenue']!=0)
						$ecpm = $item['revenue']*1000/$item['paid_impressions'];
				}else{
					$ecpm = 0;
				}
				
				if($item['impressions']){
					$totalimpressions +=$item['impressions'];
				}		

				if ($item['estimated']==1) {
					$asterics = '*';
					/*
					if($this->absEcpm>0 && $item['impressions']>0 && $item['revenue']==0){
						$ecpm = $this->absEcpm;
						$item['revenue'] = $this->absEcpm*$item['impressions']/1000;
						//$asterics = '';						
					}
					*/						
					if($this->absEcpm>0 && $item['paid_impressions']>0 && $item['revenue']==0){
						$ecpm = $this->absEcpm;
						$item['revenue'] = $this->absEcpm*$item['paid_impressions']/1000;
						//$asterics = '';
						
					}
				}else{
					$asterics = '';
				}
				
				
				$totalrevenue += $item['revenue'];
				
				$count++;
				
				$formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['Date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($item['impressions']).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($item['revenue'],2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm,2).'</td></tr></table>';
				$formatLinePaid = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['Date'])).'</td></tr><tr><td>Paid Impressions:</td><td>'.number_format($item['paid_impressions']).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($item['revenue'],2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm,2).'</td></tr></table>';
				
				if($count==count($this->report)){
					$line1.= "['$item[Date]', ".str_replace(',','.',$item['impressions']).", '$formatLine']";
					$line2.= "['$item[Date]', ".str_replace(',','.',$item['revenue']).", '$formatLine']";
					$line3.= "['$item[Date]', ".str_replace(',','.',$item['paid_impressions']).", '$formatLinePaid']";
				}else{
					$line1.= "['$item[Date]', ".str_replace(',','.',$item['impressions']).", '$formatLine'], ";
					$line2.= "['$item[Date]', ".str_replace(',','.',$item['revenue']).", '$formatLine'], ";
					$line3.= "['$item[Date]', ".str_replace(',','.',$item['paid_impressions']).", '$formatLinePaid'], ";
				}				
				
			?>
			<tr>
				<td><?php echo '<a href="/default/users/report-date/date/'.$item['Date'].'">'.$item['Date'].'<a>'?><?php echo $asterics?></td>
				<td><?php echo number_format($item['impressions']) ?><?php echo $asterics?></td>
				<td><?php echo number_format($item['paid_impressions']) ?><?php echo $asterics?></td>
				<td><?php echo $ecpm==0 ? $this->absEcpm==0 ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
				<td><?php echo ($ecpm==0) ? $this->absEcpm==0 ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($item['revenue'],2).$asterics?></td>
			</tr>
		<?php endforeach;?>
		
		<?php 
			$noresult=false;
			$line1.= "]";
			$line2.= "]";
			$line3.= "]";
		?>
			
	<?php else: ?>
		<?php 
	    $line1 = "[";
	    $line2 = "[";
	    $line3 = "[";
	
	    $start = strtotime($this->report_params['start_date']);
	    $end = strtotime($this->report_params['end_date']);
	        
	    for($i=$start; $i<=$end; $i=$i+86400){
	                
	        $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
	        $formatLinePaid = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Paid Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
	         
	        $line1.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
	        $line2.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";  
	        $line3.= "['".date("M d, Y", $i)."', 0.000, '$formatLinePaid'], ";
	    }
	
	    $line1.= "]";
	    $line2.= "]"; 
	    $line3.= "]";
	    
	    $noresult=true;
	    ?>
	<?php endif;?>	
	<?php 
		if($totalPaidimpressions > 0) {
			$totalecpm = $totalrevenue / ($totalPaidimpressions/1000);
		}else{
			$totalecpm = "0.00";
		} 
	?>
	
	<tr>
		<td class="total">Totals </td>
		<td class="total"><?php echo number_format($totalimpressions) ?></td>
		<td class="total"><?php echo number_format($totalPaidimpressions) ?></td>
		<td class="total">$<?php echo number_format($totalecpm,2) ?></td>
		<td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
	</tr>
	</table>
        <div id="chartdiv" style="height: 300px; width: 750px;"></div>

<?php else: ?>
	<?php 
	$totalimpressions = 0;
	$totalecpm = 0;
	$totalrevenue = 0;
	
	$nodataImpres=false;
	$countEstim = 0;
	$count = 0;
	$line1 = "[";
	$line2 = "[";	
	?>
	<table cellpadding="0" cellspacing="0" id="reportTbl" style="width: 720px;">		
	<tr>			
	    <th>Date</th>			
	    <th>Impressions</th>
	    <th>eCPM</th>			
	    <th class="lastTh">Revenue</th>		
	</tr>																
	
	<?php if($this->report):?>
		<?php foreach ($this->report as $item):?>
			<?php 
				$nodataImpres=false;
			
				if($item['paid_impressions']){
					$item['impressions']=$item['paid_impressions'];
				}
				
				if($item['impressions']){
					if($item['estimated']==1 && $this->previosAllocted && $this->previosImpressoin){
						$item['impressions'] = ($this->previosAllocted/$this->previosImpressoin)*$item['impressions'];
						$totalimpressions +=$item['impressions'];
					}else{
						$totalimpressions +=$item['impressions'];
					}
					
					if($item['revenue']!=0)
						$ecpm = $item['revenue']*1000/$item['impressions'];
				}else{
					$ecpm = 0;
				}		

				if ($item['estimated']==1 && $countEstim!=-1) {
					$countEstim++;
					$asterics = '*';
					if($this->absEcpm>0 && $item['impressions']>0 && $item['revenue']==0){
						$ecpm = $this->absEcpm;
						$item['revenue'] = $this->absEcpm*$item['impressions']/1000;
						//$asterics = '';
					}						
				}else{
					$asterics = '';
					$countEstim=-1;
				}
				
				if($countEstim==-1 && number_format($item['revenue'],2)==0){
					$item['revenue'] = 0;
					$ecpm = 0;
					$nodataImpres=true;
					if($item['impressions'])
						$totalimpressions = $totalimpressions - $item['impressions'];
				}
				
				$totalrevenue += $item['revenue'];
				
				//graph
				$count++;
				$formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['Date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($item['impressions']).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($item['revenue'],2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm,2).'</td></tr></table>';
				
				if($count==count($this->report)){
					$line1.= "['$item[Date]', ".str_replace(',','.',$item['impressions']).", '$formatLine']";
					$line2.= "['$item[Date]', ".str_replace(',','.',$item['revenue']).", '$formatLine']";
				}else{
					$line1.= "['$item[Date]', ".str_replace(',','.',$item['impressions']).", '$formatLine'], ";
					$line2.= "['$item[Date]', ".str_replace(',','.',$item['revenue']).", '$formatLine'], ";
				}
			?>
			<tr>
				<td><?php echo '<a href="/default/users/report-date/date/'.$item['Date'].'">'.$item['Date'].'<a>'?><?php echo $asterics?></td>
				<td><?php echo $nodataImpres ? '-' : number_format($item['impressions']) ?><?php echo $asterics?></td>
				<td><?php echo $ecpm==0 ? $this->absEcpm==0 ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
				<td><?php echo $ecpm==0 ? $this->absEcpm==0 ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($item['revenue'],2).$asterics?></td>
			</tr>
		<?php endforeach;?>
		
		<?php 
			$noresult=false;
			$line1.= "]";
			$line2.= "]";
		?>	
	
	<?php else: ?>
		<?php 
	    $line1 = "[";
	    $line2 = "[";
	
	    $start = strtotime($this->report_params['start_date']);
	    $end = strtotime($this->report_params['end_date']);
	        
	    for($i=$start; $i<=$end; $i=$i+86400){
	                
	        $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
	        
	        $line1.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
	        $line2.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";  
	    }
	
	    $line1.= "]";
	    $line2.= "]"; 
	    
	    $noresult=true;
	    ?>	
	
	<?php endif;?>	
	<?php 
		if($totalimpressions > 0) {
			$totalecpm = $totalrevenue / ($totalimpressions/1000);
		}else{
			$totalecpm = "0.00";
		} 
	?>
	<tr>
		<td class="total">Totals </td>
		<td class="total"><?php echo number_format($totalimpressions) ?></td>
		<td class="total">$<?php echo number_format($totalecpm,2) ?></td>
		<td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
	</tr>
	</table>
        <div id="chartdiv" style="height: 300px; width: 750px;"></div>
        <?php endif;?>
    </div>    
</div>
<div class="estimate"><h5>*Estimates Only. Numbers can take up to 2 days to finalize.</h5>	
</div><!--//estimate-->


<script type="text/javascript">
$(document).ready(function(){
	  var line1_rub = <?php echo $line1_rub ?>;
	  var line2_rub = <?php echo $line2_rub ?>;
	 
	  var plot1 = $.jqplot('chartdiv_rub', [line1_rub, line2_rub], {
	    series:[{renderer:$.jqplot.highlighter, label:'Impressions', color:'grey'}, {xaxis:'xaxis', yaxis:'y2axis', label:'Revenue', color:'red'}],
	    axesDefaults: {
	        tickRenderer: $.jqplot.CanvasAxisLabelRenderer,
	    },
	    highlighter: {
	      show: true,
	      showMarker:false,
	      tooltipAxes: 'both',
	      yvalues: 3,
	      // You can customize the tooltip format string of the highlighter
	      // to include any arbitrary text or html and use format string
	      // placeholders (%s here) to represent x and y values.
	      formatString:'<!--%s%s-->%s'
	    },    
	    legend: {
	        show: true,
	        placement: 'outsideGrid',
	        location: 's'
	    },    
	    axes: {
	      xaxis: {
	        renderer: $.jqplot.DateAxisRenderer,
	          tickOptions:{
	            formatString:'%b %#d'
	          },
	      },
	      yaxis: {
	        autoscale:true,
	          tickOptions:{
	            formatString:'%s'
	            }<?php if($noresult_rub): ?>,   
	          min:0, 
	          max: 50000,
	          tickInterval:10000
	            <?php endif; ?>
	      },
	      y2axis: {
	          autoscale:true,
	          tickOptions:{
	            formatString:'$%.2f'
	            }<?php if($noresult_rub): ?>,   
	          min:0.000, 
	          max: 50.000,
	          tickInterval:10
	            <?php endif; ?>
	      }
	    }
	  });

	  var line1_gog = <?php echo $line1_gog ?>;
	  var line2_gog = <?php echo $line2_gog ?>;
	 
	  var plot2 = $.jqplot('chartdiv_gog', [line1_gog, line2_gog], {
	    series:[{renderer:$.jqplot.highlighter, label:'Impressions', color:'grey'}, {xaxis:'xaxis', yaxis:'y2axis', label:'Revenue', color:'red'}],
	    axesDefaults: {
	        tickRenderer: $.jqplot.CanvasAxisLabelRenderer,
	    },
	    highlighter: {
	      show: true,
	      showMarker:false,
	      tooltipAxes: 'both',
	      yvalues: 3,
	      // You can customize the tooltip format string of the highlighter
	      // to include any arbitrary text or html and use format string
	      // placeholders (%s here) to represent x and y values.
	      formatString:'<!--%s%s-->%s'
	    },    
	    legend: {
	        show: true,
	        placement: 'outsideGrid',
	        location: 's'
	    },    
	    axes: {
	      xaxis: {
	        renderer: $.jqplot.DateAxisRenderer,
	          tickOptions:{
	            formatString:'%b %#d'
	          },
	      },
	      yaxis: {
	        autoscale:true,
	          tickOptions:{
	            formatString:'%s'
	            }<?php if($noresult_gog): ?>,   
	          min:0, 
	          max: 50000,
	          tickInterval:10000
	            <?php endif; ?>
	      },
	      y2axis: {
	          autoscale:true,
	          tickOptions:{
	            formatString:'$%.2f'
	            }<?php if($noresult_gog): ?>,   
	          min:0.000, 
	          max: 50.000,
	          tickInterval:10
	            <?php endif; ?>
	      }
	    }
	  });

	  var line1_est = <?php echo $line1_est ?>;
	  var line2_est = <?php echo $line2_est ?>;
	 
	  var plot3 = $.jqplot('chartdiv_est', [line1_est, line2_est], {
	    series:[{renderer:$.jqplot.highlighter, label:'Impressions', color:'grey'}, {xaxis:'xaxis', yaxis:'y2axis', label:'Revenue', color:'red'}],
	    axesDefaults: {
	        tickRenderer: $.jqplot.CanvasAxisLabelRenderer,
	    },
	    highlighter: {
	      show: true,
	      showMarker:false,
	      tooltipAxes: 'both',
	      yvalues: 3,
	      // You can customize the tooltip format string of the highlighter
	      // to include any arbitrary text or html and use format string
	      // placeholders (%s here) to represent x and y values.
	      formatString:'<!--%s%s-->%s'
	    },    
	    legend: {
	        show: true,
	        placement: 'outsideGrid',
	        location: 's'
	    },    
	    axes: {
	      xaxis: {
	        renderer: $.jqplot.DateAxisRenderer,
	          tickOptions:{
	            formatString:'%b %#d'
	          },
	      },
	      yaxis: {
	        autoscale:true,
	          tickOptions:{
	            formatString:'%s'
	            }<?php if($noresult_est): ?>,   
	          min:0, 
	          max: 50000,
	          tickInterval:10000
	            <?php endif; ?>
	      },
	      y2axis: {
	          autoscale:true,
	          tickOptions:{
	            formatString:'$%.2f'
	            }<?php if($noresult_est): ?>,   
	          min:0.000, 
	          max: 50.000,
	          tickInterval:10
	            <?php endif; ?>
	      }
	    }
	  });


	  var line1 = <?php echo $line1 ?>;
	  var line2 = <?php echo $line2 ?>;
	 
	  var plot4 = $.jqplot('chartdiv', [line1, line2], {
	    series:[{renderer:$.jqplot.highlighter, label:'Impressions', color:'grey'}, {xaxis:'xaxis', yaxis:'y2axis', label:'Revenue', color:'red'}],
	    axesDefaults: {
	        tickRenderer: $.jqplot.CanvasAxisLabelRenderer,
	    },
	    highlighter: {
	      show: true,
	      showMarker:false,
	      tooltipAxes: 'both',
	      yvalues: 3,
	      // You can customize the tooltip format string of the highlighter
	      // to include any arbitrary text or html and use format string
	      // placeholders (%s here) to represent x and y values.
	      formatString:'<!--%s%s-->%s'
	    },    
	    legend: {
	        show: true,
	        placement: 'outsideGrid',
	        location: 's'
	    },    
	    axes: {
	      xaxis: {
	        renderer: $.jqplot.DateAxisRenderer,
	          tickOptions:{
	            formatString:'%b %#d'
	          },
	      },
	      yaxis: {
	        autoscale:true,
	          tickOptions:{
	            formatString:'%s'
	            }<?php if($noresult): ?>,   
	          min:0, 
	          max: 50000,
	          tickInterval:10000
	            <?php endif; ?>
	      },
	      y2axis: {
	          autoscale:true,
	          tickOptions:{
	            formatString:'$%.2f'
	            }<?php if($noresult): ?>,   
	          min:0.000, 
	          max: 50.000,
	          tickInterval:10
	            <?php endif; ?>
	      }
	    }
	  });
	  
	  
      $('.reportBox').bind('tabsshow', function(event, ui) {
      	  if (ui.index == 0) {
              plot1.replot();
      	  }
      	  else if (ui.index == 1) {
          		plot2.replot();
      	  }
      	  else if(ui.index == 2){
        		plot3.replot();  
      	  } 
          else if(ui.index == 3){
        		plot4.replot();  
      	  }     	  
      	});
	  
}) ;   
</script>

<script	type="text/javascript" src="/font/cufon-yui.js"></script>
<script	type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script><script	type="text/javascript" src="/font/Headline_Two_400.font.js"></script><script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
</script><script	type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script><script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.publisher h4');	
		Cufon.replace('.publisher h4 span');	
		Cufon.replace('.publMail a');	
		Cufon.replace('.logOut span');					
</script><script	type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script><script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.reportTop h5');		
		Cufon.replace('.estimate h5');			
</script><script type="text/javascript">
$(document).ready(function() {
Cufon.set("fontFamily", "Proxima_Nova_Lt_300.font.js");
	$("#reportL li").hover(
		function(){
		$(this).children('a').children('span').addClass('black');
		Cufon.refresh();		
		Cufon.replace('.black', {color: '#000000'});	
		}, 
	  function () {
		$(this).children('a').children('span').removeClass('black');
		Cufon.refresh();			
		Cufon.replace('#reportL li span', {color: '#DE3232'});	
	  }
	);
	$("#showBox").click(
		function(){
		$('.subDate').toggle(220);
		$('.dateBoxInn').toggleClass('curDate');
		}
	);
	
	$(".dCancelBtn").click(
		function(){
		$('.subDate').fadeOut(600);
		$('.dateBoxInn').removeClass('curDate');
		}
	);	
	


	
});
</script><script	type="text/javascript" src="/js/calendar.js.js"></script><script type="text/javascript">
	$(function(){
		$('#singleCont').css('backgroundImage', 'url(/images/contBg_1.png)');
			$(".datepicker").datepicker({dateFormat: 'M d, yy'});
});
</script>