<style type="text/css">

    .contUsL input{ background: none; }
    #contact{ width: 700px; border-collapse: collapse; border: 1px #B7B7B7 solid; margin-top: 20px; }
    #contact tbody tr td{

        border: 1px #B7B7B7 solid;
        font-size: 13px;
        font-family: Arial,Helvetica,sans-serif;
        padding: 5px;
     }

    #contact thead tr th{

        border: 1px #B7B7B7 solid;
        font-size: 16px;
        font-family: Arial,Helvetica,sans-serif;
        padding: 5px;
        text-align: center;
    }

    #contact tfoot tr td{

        border: 1px #B7B7B7 solid;
        font-size: 16px;
        font-family: Arial,Helvetica,sans-serif;
        text-align: center;
    }

    #contact #date-value{
        display: block;
        width: 180px;
        float: left;
        padding: 5px;
        font-size: 16px;
        font-family: Arial,Helvetica,sans-serif;
        text-align: center;
    }

    #act{ display: block; float: right; padding-left: 20px;  border-left: 1px #B7B7B7 solid; }
    #act input { margin: 0px; padding: 0px; }
    #act span{ display: block; float: left; width: 80px; height: 20px; margin: 5px 0px 0px 0px; font-size: 16px; text-align: left; }
    #act input[type=radio]{ display: block; float: left; width: 40px; margin-top: 3px; }
    #act input[type=button]{ display: block; float: left; height: 30px; width: 170px; margin-left: 10px; background-color: #8E8E8E; color:#FFFFFF; font-size: 16px; cursor: pointer; }
    #act input[type=button]:hover{ background-color: #DE3232; }
</style>
<script type="text/javascript" charset="utf-8">

    function mySubmit()
    {
        var choice = $('#act input[type=radio]:checked').val();

             if(choice == 'approve') document.location.href='/administrator/contact/approve/id/<?php echo $this->wait->PubID;?>';
        else if(choice == 'delete')  document.location.href='/administrator/contact/delete/id/<?php echo $this->wait->PubID;?>';
    }

</script>


<h1>Contact Info</h1>

<div class="contUsL">
     <table id="contact">
         <thead>
             <tr>
                 <th>Contact</th>
                 <th>Old</th>
                 <th>New</th>
             </tr>
         </thead>
         <tbody>
             <tr>
                 <td>Company</td>
                 <td><?php echo $this->user->company;?></td>
                 <td><?php echo $this->wait->company;?></td>
             </tr>
             <tr>
                 <td>Name</td>
                 <td><?php echo $this->user->name;?></td>
                 <td><?php echo $this->wait->name;?></td>
             </tr>
             <tr>
                 <td>Email</td>
                 <td><?php echo $this->user->email;?></td>
                 <td><?php echo $this->wait->email;?></td>
             </tr>
             <tr>
                 <td>Phone</td>
                 <td><?php echo $this->user->phone;?></td>
                 <td><?php echo $this->wait->phone;?></td>
             </tr>
         </tbody>
         <tfoot>
             <tr>
                 <td>Date</td>
                 <td colspan="2">
                     <div id="date-value"><?php echo $this->wait->created;?></div>
                     <form id="act">
                         <input type="radio" name="choice" value="approve" checked/><span>Approve</span>
                         <input type="radio" name="choice" value="delete"/><span>Delete</span>
                         <input type="button" value="Submit" onClick="mySubmit();"/>
                     </form>
                 </td>
             </tr>
         </tfoot>

     </table>
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});
		Cufon.replace('#topMenu a');
        Cufon.replace('.error', {color: 'red'});
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');
	Cufon.replace('.footerBann p');
	Cufon.replace('.footerBann a', {hover: true});
	Cufon.replace('.contactUs h1');
    Cufon.replace('h1');

</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');
		Cufon.replace('.fMenu a');
		Cufon.replace('.contactUs p');
		Cufon.replace('.contUsL label');
		Cufon.replace('.contBtn p');
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>