<h2 class="text-center">Networks</h2>
<a class="btn btn-success" href="/administrator/networks/add" role="button">Add new network</a>
<a class="btn btn-info disabled" id="edit_btn" href="#" role="button">Edit selected</a>
<br><br>
<table class="table table-striped table-bordered" id="networks" cellspacing="0" width="100%">
    <thead>
        <tr>
            <td>id</td>
            <td>Name</td>
            <td>Short name</td>
            <td>Created</td>
            <td>Updated</td>
            <td>Active</td>
            <td>Position</td>
            <td>Show</td>
        </tr>
    </thead>
    <tfoot>
    <tr>
        <td>id</td>
        <td>Name</td>
        <td>Short name</td>
        <td>Created</td>
        <td>Updated</td>
        <td>Status</td>
        <td>Position</td>
        <td>Show</td>
    </tr>
    </tfoot>
    <tbody></tbody>
</table>

<script>
    $(document).ready(function() {
        var table = $('#networks').DataTable( {
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url" : "/administrator/networks/get-networks-ajax",
                "type": "POST"
            },
            "order": [[ 6, "asc" ]],
            "columns": [
                {"data" : "id"},
                {"data" : "name"},
                {"data" : "short_name"},
                {"data" : "created_at"},
                {"data" : "updated_at"},
                {
                    "data" : "active",
                    "render" : function ( data, type, full, meta ){
                        if(data==1){
                            return '<i class="fa fa-check text-success"></i>';
                        }else{
                            return '<i class="fa fa-times text-danger"></i>';
                        }
                    }
                },
                {"data" : "position"},
                {
                    "data" : "show",
                    "render" : function ( data, type, full, meta ){
                        if(data==1){
                            return '<i class="fa fa-check text-success"></i>';
                        }else{
                            return '<i class="fa fa-times text-danger"></i>';
                        }
                    }
                }
            ]
        } );

        $('#networks tbody').on( 'click', 'tr', function () {
            var data = table.row(this).data();

            if ( $(this).hasClass('info') ) {
                $(this).removeClass('info');
                $("#edit_btn").attr('href', '#').addClass('disabled');
            }else {
                table.$('tr.info').removeClass('info');
                $(this).addClass('info');
                $("#edit_btn").attr('href', '/administrator/networks/edit/id/'+data.id).removeClass('disabled');
            }
        });
    });
</script>