<script type="text/javascript" src="/js/jquery.qtip.min.js"></script>
<link href="/styles/jquery.qtip.min.css" media="screen" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<style type="text/css">
.reportTop .dateLink{ cursor: pointer; }
.icon {background: url("../images/icon_yd.png") no-repeat scroll left top rgba(0, 0, 0, 0);}
.expExcel { background-position: -221px -124px; color: #484848; float: right; font-family: "calibri"; font-size: 15px; font-weight: bold; height: 28px; line-height: 24px; margin: 7px -2px 0 0; padding: 0 0 0 27px; text-align: center; width: 106px;}
</style>
<script type="text/javascript">
    $(document).ready(function(){       
        
        $(".selectDate").click(function(){
            $("#search-start_date").val($(this).attr('start'));
            $("#search-end_date").val($(this).attr('end'));
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($(this).attr('start')))+' - '+$.datepicker.formatDate('M d, yy', new Date($(this).attr('end'))));            
        })
        
        $("#search-start_date").change(function(){
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($("#search-start_date").val()))+' - '+$.datepicker.formatDate('M d, yy', new Date($("#search-end_date").val())));                        
        })        

        $("#search-end_date").change(function(){
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($("#search-start_date").val()))+' - '+$.datepicker.formatDate('M d, yy', new Date($("#search-end_date").val())));                        
        })        

        $("#update").click(function(){
            $("#formDate").submit();       
        })

        $("#cancel").click(function(){
            $("#showBox").html($(this).attr('txt'));         
        })

    	$('.gtip').qtip({
    		content: '<?php echo $this->tooltip ?>',
    		position: {
    			my: 'top left',
    			target: 'mouse',
    			viewport: $(window), // Keep it on-screen at all times if possible
    			adjust: {
    				x: 10,  y: 10
    			}
    		},
    		hide: {
    			fixed: true // Helps to prevent the tooltip from hiding ocassionally when tracking!
    		},
    		style: 'ui-tooltip-shadow'
    	});
        

        

    }) ;   
    
    function csvReport(start_date, end_date, ad_size, site)
    {
        $.fancybox({
            'width'	: '75%',
            'height'	: '75%',
            'href'          : '/default/report/set-auto-report/start_date/'+start_date+'/end_date/'+end_date+'/ad_size/'+ad_size+'/site/'+site,
            'autoScale'    	: false,
            'transitionIn'	: 'none',
            'transitionOut'	: 'none',
            'type'		: 'iframe'            
        }); 
    }
    
</script>

<form name="size" method="get" id="formDate" action="">	
            <!--report TOP-->                                            
            <div class="reportTop">
            	<h5>Earnings</h5>                
                <div class="dateBox">
                	<p class="dateBoxInn"><a href="#" title="" class="dateLink" id="showBox"><?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?> – <?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?></a></p>
                    <div class="subDate">
                    	<div class="dateRanch">
                        	<h5>Date Range </h5>
                            <input type="text" value="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?>" name="start_date" id="search-start_date"  onfocus="this.value=''" onblur="if (this.value==''){this.value=''}" class="datepicker" />
                            <input type="text" value="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?>" name="end_date" id="search-end_date"  onfocus="this.value=''" onblur="if (this.value==''){this.value=''}" class="datepicker"/>                            
                            <p>
                            	<a href="#" title="" class="dCancelBtn" id="cancel" txt="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?> – <?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?>">Cancel</a>
                            	<a href="#" title="" class="dUpdlBtn" id="update">Update</a>                            
                            </p>
                        </div>
                        
                        <div class="quickDate">
                        	<h5>Quick dates</h5>
                            <br class="clear" />
                            <ul>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y"); ?>" end="<?php echo date("M j, Y"); ?>" title="">Today</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-1,date("Y"))); ?>" title="">Yesterday</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-7,date("Y"))); ?>" end="<?php echo date("M j, Y"); ?>" title="">Last 7 days</a></li>
                            </ul>
                            
                            <ul class="rightUl">
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-30,date("Y"))); ?>" end="<?php echo date("M j, Y"); ?>" title="">Last 30 days</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("t"),date("Y"))); ?>" title="">This month:<span> <?php echo date("F") ?></span></a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m")-1,1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m")-1,date("t", mktime(0,0,0,date("m")-1,1,date("Y"))),date("Y"))); ?>" title="">Last month: <span><?php echo date("F", mktime(0,0,0,date("m")-1,1,date("Y"))); ?></span></a></li>
                            </ul>                            
                        </div>
                    </div>
                </div>
                <p class="sizeSel"><b>Size</b>
                	<select onchange="this.form.submit();" name="ad_size">
                    	<option value="">All Media Types</option>
        <?php foreach($this->ad_sizes as $ad_size) { ?>
            <option value="<?php echo htmlentities($ad_size->id); ?>"<?php if ($this->report_params["ad_size"] ==$ad_size->id) { echo ' selected'; } ?>><?php echo htmlentities($ad_size->name); ?></option>
        <?php } ?>
        <?php if($this->referral_system):?>
                    <option value="-1"<?php if ($this->report_params["ad_size"] == '-1') { echo ' selected'; } ?>>Referrals</option>
        <?php endif;?>    
                </select>
                </p>
                <?php if($this->report_params["ad_size"] != '-1'):?>
	                <p class="sizeSel"><b>Site</b>
	                	<select onchange="this.form.submit();" name="site">
	                    	<option value="">All Sites</option>
							    <?php foreach($this->sites as $site) { ?>
							        <option value="<?php echo htmlentities($site["SiteID"]); ?>"<?php if ($this->report_params["site"] ==$site["SiteID"]) { echo ' selected'; } ?>><?php echo htmlentities($site["SiteName"]); ?></option>  
							    <?php } ?>
	                    </select>
	                </p> 
	                <p class="sizeSel">
	                    <a href="/csv-report/?start_date=<?php echo $this->report_params["start_date"] ?>&end_date=<?php echo $this->report_params["end_date"] ?>&ad_size=<?php echo $this->report_params["ad_size"] ?>&site=<?php echo $this->report_params["site"] ?>">
	                    <img src="/images/csv-24.gif"/>
	                    </a>
	                </p>
                <?php endif;?>
            </div>
            <!--//report TOP--> 
            <?php if($this->auth->role=='admin' || $this->auth->role=='super'):?>
            <br><br><br><p><label>Show Demand Sources</label><input type="checkbox" name="show_demand" <?php echo $this->report_params["show_demand"]==1 ? "checked='checked'" : '' ?> onclick="this.form.submit();" value="1" /></p>
            <?php if($this->siteID): ?>
            <p><a href="/report/edit/?site=<?php echo $this->siteID ?>">Edit report</a></p>
            <?php endif; ?>
            <?php endif;?>
            
</form>
<?php if($this->news): ?>
<?php foreach($this->news as $news): ?>
		<div class="news_content_above">
			<div class="notice">Notice (<?php echo date('m/d/Y',strtotime($news['date']));?>): <?php echo $news['title']?></div>
			<?php echo $news['text'];?>
		</div>
<?php endforeach; ?>
<?php endif; ?>
<br><br><br>
<?php if($this->report_params["ad_size"] != '-1'):?><!-- AD SIZE REPORTS -->
	<div class="reportBox" style="float: left;">	
		<table cellpadding="0" cellspacing="0" id="reportTbl">		
			<tr>			
				<th>Date</th>			
				<th>Impressions</th>
				<th>eCPM</th>			
				<th class="lastTh">Revenue</th>		
			</tr>													       
			<?php 
				$totalimpressions = 0;
				$totalecpm = 0;
				$totalrevenue = 0;
				$impressions = 0;
				$revenue = 0;
				$ecpm = 0;
				$nodata=true;
				$count = 0;
				$asterics = '';
				$pending = false;
			?>
			    
			<?php if($this->report): ?>
				<?php
				$nodata=false;
				$line1 = "[";
				$line2 = "[";	    
				?>
				<?php foreach ($this->report as $item):?>
					<?php   
						$count++;
						$impressions = $item['paid_impressions'];
						$revenue = $item['revenue'];
						$ecpm = '-';
						$pending = false;            
						if($item['estimated']==1)
						{
							if($item['type']==6 || $item['type']==7 || $item['type']==8){
			                	$ecpm = '-';
			                	$revenue=0;
			                	$pending=true;
			                	$asterics = '*';								
							}else{
								$asterics='*';
								if($impressions>0 && $revenue>0)
								{
									$ecpm = $revenue*1000/$impressions;
								}
								elseif($this->absEcpm>0 && $impressions>0)
								{
									$ecpm = $this->absEcpm;
									$revenue = $this->absEcpm*$impressions/1000;                    
								}
								else
								{
									$pending = true;
								}  
							}                  
						}
						else
						{
							$asterics='';
							if($impressions>0 && $revenue>0)
								$ecpm = $revenue*1000/$impressions;
								
							$totalimpressions += $impressions;
							$totalrevenue += $revenue;            						
						}
						//graph
						
						$revenView = $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics;
						$ecpmView = $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics;
						
						$formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>'.$revenView.'</td></tr><tr><td>eCPM:</td><td>'.$ecpmView.'</td></tr></table>';
						if($count==count($this->report))
						{
							$line1.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
							if($item['estimated']!=1)
								$line2.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
						}
						else
						{
							$line1.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
							if($item['estimated']!=1)
								$line2.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
						}                                    
					?>
					<tr>
						<td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
						<?php if($item['type']==6): ?>
						<td><?php echo !$impressions ? 0 : number_format($impressions) ?><?php echo $asterics?></td>
						<?php else: ?>
						<td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>						
						<?php endif; ?>
						<td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
						<td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
					</tr>    
				<?php endforeach; ?>    
				<?php
					$line1.= "]";
					$line2.= "]";
				?>    
			<?php else: ?>
				<?php
					$nodata=true;     
					$line1 = "[";
					$line2 = "[";
					$start = strtotime($this->report_params['start_date']);
					$end = strtotime($this->report_params['end_date']);
					for($i=$start; $i<=$end; $i=$i+86400)
					{
						$formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
						$line1.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
						$line2.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";  
					}
					$line1.= "]";
					$line2.= "]";    
				?>
			<?php endif; ?>   
			<?php 
				if($totalimpressions > 0) 
				{
					$totalecpm = $totalrevenue / ($totalimpressions/1000);
				}
				else
				{
					$totalecpm = "0.00";
				} 
			?>    
			<tr>
				<td class="total">Totals </td>
				<td class="total"><?php echo number_format($totalimpressions) ?></td>
				<td class="total">$<?php echo number_format($totalecpm,2) ?></td>
				<td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
			</tr>
		</table>
		
<a style="cursor: pointer;" onClick="csvReport('<?php echo date('Y-m-d', strtotime($this->report_params["start_date"])) ?>', '<?php echo date('Y-m-d', strtotime($this->report_params["end_date"])) ?>', '<?php echo !empty($this->report_params["ad_size"]) ? $this->report_params["ad_size"] : '' ?>', '<?php echo !empty($this->report_params["site"]) ? $this->report_params["site"] : '' ?>')" class="expExcel icon">Export Options</a>		
		
		<script type="text/javascript">
		$(document).ready(function()
		{
			var line1 = <?php echo $line1 ?>;
			var line2 = <?php echo $line2 ?>;	 
			var plot2 = $.jqplot('chartdiv', [line1, line2], 
			{
				series:[{renderer:$.jqplot.highlighter, label:'Impressions', color:'grey'}, {xaxis:'xaxis', yaxis:'y2axis', label:'Revenue', color:'red'}],
				axesDefaults: 
				{
					tickRenderer: $.jqplot.CanvasAxisLabelRenderer,
				},
				highlighter: 
				{
					show: true,
					showMarker:false,
					tooltipAxes: 'both',
					yvalues: 3,
					// You can customize the tooltip format string of the highlighter
					// to include any arbitrary text or html and use format string
					// placeholders (%s here) to represent x and y values.
					formatString:'<!--%s%s-->%s'
				},    
				legend:
				{
					show: true,
					placement: 'outsideGrid',
					location: 's'
				},    
				axes: 
				{
					xaxis: 
						{
					        renderer: $.jqplot.DateAxisRenderer,
					        tickOptions:
						    {
					        	formatString:'%b %#d'
					        },
					     },
					yaxis:
						{
					        autoscale:true,
					          tickOptions:{
					            formatString:'%s'
					            }<?php if($nodata): ?>,   
					          min:0, 
					          max: 50000,
					          tickInterval:10000
					            <?php endif; ?>
					      },
					      y2axis: 
						  {
					          autoscale:true,
					          tickOptions:{
					            formatString:'$%.2f'
					            }<?php if($nodata): ?>,   
					          min:0.000, 
					          max: 50.000,
					          tickInterval:10
					            <?php endif; ?>
					      }
				}
			});
		}) ;   
		</script>		    
	</div>
	<!--estimate-->
	<div class="estimate"><h5>*Estimates Only. Numbers can take up to 2 days to finalize.</h5>	
	<p><div id="chartdiv" style="height: 300px; width: 750px;"></div>	</p></div>
	<!--//estimate-->
<?php else:?><!-- REFERRALS -->
	<div class="reportBox" style="float: left;">	
		<table cellpadding="0" cellspacing="0" id="reportTbl">		
			<tr>			
				<th>Date</th>						
				<th >Revenue</th>		
			</tr>
			<?php $revenue_total = 0;?>													       
			<?php foreach($this->report as $row):?>
			<tr>
				<td><?php echo $row['query_date'];?></td>
				<td><?php echo number_format($row['revenue'],2); $revenue_total += $row['revenue'];?></td>
			</tr>
			<?php endforeach;?>   
			<tr>
				<td class="total">Totals </td>
				<td class="total lastTd">$<?php echo number_format($revenue_total, 2) ?></td>                                                            
			</tr>
		</table>
	</div>
<?php endif;?><!-- END REFERRALS -->
    

<script	type="text/javascript" src="/font/cufon-yui.js"></script>
<script	type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script><script	type="text/javascript" src="/font/Headline_Two_400.font.js"></script><script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
</script><script	type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script><script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.publisher h4');	
		Cufon.replace('.publisher h4 span');	
		Cufon.replace('.publMail a');	
		Cufon.replace('.logOut span');					
</script><script	type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script><script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.reportTop h5');		
		Cufon.replace('.estimate h5');			
</script><script type="text/javascript">
$(document).ready(function() {
Cufon.set("fontFamily", "Proxima_Nova_Lt_300.font.js");
	$("#reportL li").hover(
		function(){
		$(this).children('a').children('span').addClass('black');
		Cufon.refresh();		
		Cufon.replace('.black', {color: '#000000'});	
		}, 
	  function () {
		$(this).children('a').children('span').removeClass('black');
		Cufon.refresh();			
		Cufon.replace('#reportL li span', {color: '#DE3232'});	
	  }
	);
	$("#showBox").click(
		function(){
		$('.subDate').toggle(220);
		$('.dateBoxInn').toggleClass('curDate');
		}
	);
	
	$(".dCancelBtn").click(
		function(){
		$('.subDate').fadeOut(600);
		$('.dateBoxInn').removeClass('curDate');
		}
	);	
	


	
});
</script>
<script	type="text/javascript" src="/js/calendar.js.js"></script><script type="text/javascript">
	$(function(){
		$('#singleCont').css('backgroundImage', 'url(/images/contBg_1.png)');
			$(".datepicker").datepicker({dateFormat: 'M d, yy'});
});
</script>