<script type="text/javascript" src="/js/jquery.qtip.min.js"></script>
<link href="/styles/jquery.qtip.min.css" media="screen" rel="stylesheet" type="text/css" />

<script type="text/javascript">
    $(document).ready(function(){                        
        $(".selectDate").click(function(){
            $("#search-start_date").val($(this).attr('start'));
            $("#search-end_date").val($(this).attr('end'));
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($(this).attr('start')))+' - '+$.datepicker.formatDate('M d, yy', new Date($(this).attr('end'))));            
        })
        
        $("#search-start_date").change(function(){
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($("#search-start_date").val()))+' - '+$.datepicker.formatDate('M d, yy', new Date($("#search-end_date").val())));                        
        })        

        $("#search-end_date").change(function(){
            $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($("#search-start_date").val()))+' - '+$.datepicker.formatDate('M d, yy', new Date($("#search-end_date").val())));                        
        })        

        $("#update").click(function(){
            $("#formDate").submit();       
        })

        $("#cancel").click(function(){
            $("#showBox").html($(this).attr('txt'));         
        })

    	$('.gtip').qtip({
    		content: 'ECPM and Revenue take 48 hours to display for new users.  After 3 days of finalized data, we will begin to provide accurate estimated data in real-time.',
    		position: {
    			my: 'top left',
    			target: 'mouse',
    			viewport: $(window), // Keep it on-screen at all times if possible
    			adjust: {
    				x: 10,  y: 10
    			}
    		},
    		hide: {
    			fixed: true // Helps to prevent the tooltip from hiding ocassionally when tracking!
    		},
    		style: 'ui-tooltip-shadow'
    	});
        
        $(".reportBox").tabs();


    }) ;   
    
    function toggleMadX(date, objDate, tab)
    {       
        var act = $(objDate).attr('data-act');
        var objTR = $(objDate).parents('tr'); 

        switch(act)
        {
            case 'show' : getMadX(date, objDate, objTR); 
                          break;
            case 'hide' : $('.site-'+date).replaceWith(''); 
                          $(objDate).attr('data-act', 'show'); 
                          $(objDate).removeClass('arrowB'); 
                          $(objDate).addClass('arrowL');
                          $(objTR).css('font-weight', '400'); 
                          break;
                default : break;
        }      
    }
    
    function getMadX(date, objDate, objTR)
    {
        display('block');

        var filterSite = '<?php echo !empty($this->report_params['site']) ? $this->report_params['site'] : 0; ?>';
        var filterSize = '<?php echo !empty($this->report_params['ad_size']) ? $this->report_params['ad_size'] : 0; ?>';        

         $.ajax({ url : '/default/ajax/get-report-madx',
                  data : { date : date, SiteID : filterSite, AdSize : filterSize },
                  type : "POST",
                  dataType : "json",

          success : function(response) { 

               if(response.length){ 

                   var htmlTR = '';

                   $.each(response, function(key, iter){

                       htmlTR += '<tr class="site-'+date+'" style="background: #DAE8F8">';            
                       htmlTR += '<td style="text-align:left; padding-left:20px; padding-right:10px;">Pubmatic</td>';
                       htmlTR += '<td>'+number_format(iter.impressions_pubm, 0,'.',',')+'</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '<td>$'+number_format(iter.revenue_pubm, 2,'.',',')+'</td>';
                       htmlTR += '</tr>';
                       
                       htmlTR += '<tr class="site-'+date+'" style="background: #DAE8F8">';            
                       htmlTR += '<td style="text-align:left; padding-left:20px; padding-right:10px;">TLVMedia</td>';
                       htmlTR += '<td>'+number_format(iter.impressions_tlv, 0,'.',',')+'</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '<td>$'+number_format(iter.revenue_tlv, 2,'.',',')+'</td>';
                       htmlTR += '</tr>';

                       htmlTR += '<tr class="site-'+date+'" style="background: #DAE8F8">';            
                       htmlTR += '<td style="text-align:left; padding-left:20px; padding-right:10px;">Taggify</td>';
                       htmlTR += '<td>'+number_format(iter.impressions_tagg, 0,'.',',')+'</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '<td>$'+number_format(iter.revenue_tagg, 2,'.',',')+'</td>';
                       htmlTR += '</tr>';

                       htmlTR += '<tr class="site-'+date+'" style="background: #DAE8F8">';            
                       htmlTR += '<td style="text-align:left; padding-left:20px; padding-right:10px;">passback</td>';
                       htmlTR += '<td>'+number_format(iter.impressions_passb, 0,'.',',')+'</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '<td>-</td>';
                       htmlTR += '</tr>';                       
                   }); 

                   $(objDate).attr('data-act', 'hide');
                   $(objDate).removeClass('arrowL');
                   $(objDate).addClass('arrowB');
                   $(objTR).css('font-weight', '600');

                   $(htmlTR).insertAfter(objTR);

               }   display('none');
          },

          error : function(){ display('none'); alert('ajax error'); }

        });
    }   
    function display(status)
    {
        $('#mask').css('display', status);
        $('#loading').css('display', status);        
    }  
    
    function number_format( number, decimals, dec_point, thousands_sep ) {	// Format a number with grouped thousands
	// 
	// +   original by: Jonas Raoni Soares Silva (http://www.jsfromhell.com)
	// +   improved by: Kevin van Zonneveld (http://kevin.vanzonneveld.net)
	// +	 bugfix by: Michael White (http://crestidg.com)

	var i, j, kw, kd, km;

	// input sanitation & defaults
	if( isNaN(decimals = Math.abs(decimals)) ){
		decimals = 2;
	}
	if( dec_point == undefined ){
		dec_point = ",";
	}
	if( thousands_sep == undefined ){
		thousands_sep = ".";
	}

	i = parseInt(number = (+number || 0).toFixed(decimals)) + "";

	if( (j = i.length) > 3 ){
		j = j % 3;
	} else{
		j = 0;
	}

	km = (j ? i.substr(0, j) + thousands_sep : "");
	kw = i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + thousands_sep);
	//kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).slice(2) : "");
	kd = (decimals ? dec_point + Math.abs(number - i).toFixed(decimals).replace(/-/, 0).slice(2) : "");


	return km + kw + kd;
    }           
</script>
<form name="size" method="get" id="formDate" action="">	
<input type="hidden" name="id" value="<?php echo $id ?>">				
            <!--report TOP-->                                            
            <div class="reportTop">
            	<h5>Earnings</h5>                
                <div class="dateBox">
                	<p class="dateBoxInn"><a href="#" title="" class="dateLink" id="showBox"><?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?> – <?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?></a></p>
                    <div class="subDate">
                    	<div class="dateRanch">
                        	<h5>Date Range </h5>
                            <input type="text" value="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?>" name="start_date" id="search-start_date"  onfocus="this.value=''" onblur="if (this.value==''){this.value=''}" class="datepicker" />
                            <input type="text" value="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?>" name="end_date" id="search-end_date"  onfocus="this.value=''" onblur="if (this.value==''){this.value=''}" class="datepicker"/>                            
                            <p>
                            	<a href="#" title="" class="dCancelBtn" id="cancel" txt="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?> – <?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?>">Cancel</a>
                            	<a href="#" title="" class="dUpdlBtn" id="update">Update</a>                            
                            </p>
                        </div>
                        
                        <div class="quickDate">
                        	<h5>Quick dates</h5>
                            <br class="clear" />
                            <ul>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y"); ?>" end="<?php echo date("M j, Y"); ?>" title="">Today</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-1,date("Y"))); ?>" title="">Yesterday</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-7,date("Y"))); ?>" end="<?php echo date("M j, Y"); ?>" title="">Last 7 days</a></li>
                            </ul>
                            
                            <ul class="rightUl">
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("d")-30,date("Y"))); ?>" end="<?php echo date("M j, Y"); ?>" title="">Last 30 days</a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m"),1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m"),date("t"),date("Y"))); ?>" title="">This month:<span> <?php echo date("F") ?></span></a></li>
                            	<li><a href="#" class="selectDate" start="<?php echo date("M j, Y", mktime(0,0,0,date("m")-1,1,date("Y"))); ?>" end="<?php echo date("M j, Y", mktime(0,0,0,date("m")-1,date("t", mktime(0,0,0,date("m")-1,1,date("Y"))),date("Y"))); ?>" title="">Last month: <span><?php echo date("F", mktime(0,0,0,date("m")-1,1,date("Y"))); ?></span></a></li>
                            </ul>                            
                        </div>
                    </div>
                </div>
                <p class="sizeSel"><b>Size</b>
                	<select onchange="this.form.submit();" name="ad_size">
                    	<option value="">All Media Types</option>
        <?php foreach($this->ad_sizes as $ad_size) { ?>
            <option value="<?php echo htmlentities($ad_size->id); ?>"<?php if ($this->report_params["ad_size"] ==$ad_size->id) { echo ' selected'; } ?>><?php echo htmlentities($ad_size->name); ?></option>
        <?php } ?>
                    </select>
                </p>
                <p class="sizeSel"><b>Site</b>
                	<select onchange="this.form.submit();" name="site">
                    	<option value="">All Sites</option>
    <?php foreach($this->sites as $site) { ?>
        <option value="<?php echo htmlentities($site["SiteID"]); ?>"<?php if ($this->report_params["site"] ==$site["SiteID"]) { echo ' selected'; } ?>><?php echo htmlentities($site["SiteName"]); ?></option>  
    <?php } ?>
                    </select>
                </p> 
                <p class="sizeSel">
                    <a href="/csv-report/?start_date=<?php echo $this->report_params["start_date"] ?>&end_date=<?php echo $this->report_params["end_date"] ?>&ad_size=<?php echo $this->report_params["ad_size"] ?>&site=<?php echo $this->report_params["site"] ?>">
                    <img src="/images/csv-24.gif"/>
                    </a>
                </p>
            </div>
            <!--//report TOP--> 
            <?php if($this->auth->role=='admin' || $this->auth->role=='super'):?>
            <br><br><br><p><label>Show Demand Sources</label><input type="checkbox" name="show_demand" <?php echo $this->report_params["show_demand"]==1 ? "checked='checked'" : '' ?> onclick="this.form.submit();" value="1" /></p>
            <?php endif;?>
            
</form>
<br><br><br>
<div class="reportBox" style="padding: 0; width: 770px; float: left;">
	<ul>
            <li style="width: 70px"><a style="padding: 0.5em;" href="#rub">Rubicon</a></li>
            <li style="width: 75px"><a style="padding: 0.5em;" href="#estim">Estimated</a></li>
            <li style="width: 60px"><a style="padding: 0.5em;" href="#denied">Denied</a></li>
            <li style="width: 70px"><a style="padding: 0.5em;" href="#pubm">Pubmatic</a></li>
            <li style="width: 65px"><a style="padding: 0.5em;" href="#amazon">Amazon</a></li>
            <li style="width: 80px"><a style="padding: 0.5em;" href="#PulsePoint">PulsePoint</a></li>
            <li style="width: 60px"><a style="padding: 0.5em;" href="#PopAds">PopAds</a></li>
            <li style="width: 65px"><a style="padding: 0.5em;" href="#Sekindo">Sekindo</a></li>
            <li style="width: 40px"><a style="padding: 0.5em;" href="#Aol">AOL</a></li>
            <li style="width: 110px"><a style="padding: 0.5em;" href="#Aol_o">AOL Outstream</a></li>
            <li style="width: 80px"><a style="padding: 0.5em;" href="#bRealTime">bRealTime</a></li>
            <li style="width: 30px"><a style="padding: 0.5em;" href="#all">All</a></li>
	</ul> 
    
    <div id="rub">
    <table cellpadding="0" cellspacing="0" id="reportTbl">		
    <tr>			
        <th>Date</th>			
        <th>Total Impressions</th>
        <th>Paid Impressions</th>
        <th>eCPM</th>	
        <th>PCPM</th>
        <th class="lastTh">Revenue</th>		
    </tr>																    
    
<?php 
$totalImpressions_rubCsv = 0;
$totalimpressions = 0;
$totalecpm = 0;
$totalrevenue = 0;

$impressions = 0;
$revenue = 0;
$ecpm = 0;
$pcpm = 0;

$nodata=true;
$count = 0;
$asterics = '';
$pending = false;
$pendingPcpm = false;
?>
    
<?php if($this->report): ?>
    <?php
        $nodata=false;
        $line1_rub = "[";
        $line2_rub = "[";	    
    ?>
    
    <?php foreach ($this->report as $item):?>
        <?php        
            $count++;
            $impressions = $item['estimated']==1 ? $item['impressions_Rubicon'] : $item['impressions_RubiconCsv'];
            $paid_impressions_rubCsv = $item['paid_impressions_RubiconCsv'];            
            $revenue = $item['estimated']==1 ? $item['revenue_Rubicon'] : $item['revenue_RubiconCsv'];
            $ecpm = '-';
            $pcpm = '-';
            $pending = false;
            $pendingPcpm = false;
            
            if($item['estimated']==1){
                $asterics='*';
                if($impressions>0 && $revenue>0){
                    $ecpm = $revenue*1000/$impressions;
                }elseif($this->absEcpm>0 && $impressions>0){
                    $ecpm = $this->absEcpm;
                    $revenue = $this->absEcpm*$impressions/1000;                    
                }else{
                    $pending = true;
                }      
                
                if($paid_impressions_rubCsv>0 && $revenue>0){
                    $pcpm = $revenue*1000/$paid_impressions_rubCsv;
                }else{
                    $pendingPcpm = true;
                }
                
            }else{
                $asterics='';
                if($impressions>0 && $revenue>0)
                    $ecpm = $revenue*1000/$impressions;
                
                if($paid_impressions_rubCsv>0 && $revenue>0)
                    $pcpm = $revenue*1000/$paid_impressions_rubCsv;                
            }

            $totalImpressions_rubCsv += $paid_impressions_rubCsv;
            $totalimpressions += $impressions;
            $totalrevenue += $revenue;
            
            //graph
            $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

            if($count==count($this->report)){
                    $line1_rub.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                    $line2_rub.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
            }else{
                    $line1_rub.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                    $line2_rub.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
            }                                    
        ?>
        
        <tr>
            <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
            <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
            <td><?php echo !$paid_impressions_rubCsv ? '-' : number_format($paid_impressions_rubCsv).$asterics; ?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
            <td><?php echo $pcpm=='-' ? $pendingPcpm ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($pcpm,2).$asterics?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
        </tr>
    
    <?php endforeach; ?>
    
    <?php
        $line1_rub.= "]";
        $line2_rub.= "]";
    ?>    
<?php else: ?>
    <?php
    $nodata=true; 
    
    $line1_rub = "[";
    $line2_rub = "[";

    $start = strtotime($this->report_params['start_date']);
    $end = strtotime($this->report_params['end_date']);

    for($i=$start; $i<=$end; $i=$i+86400){

        $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

        $line1_rub.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
        $line2_rub.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";  
    }

    $line1_rub.= "]";
    $line2_rub.= "]"; 
    
    ?>
<?php endif; ?>   
<?php 
    if($totalimpressions > 0) {
            $totalecpm = $totalrevenue / ($totalimpressions/1000);
    }else{
            $totalecpm = "0.00";
    } 

    if($totalImpressions_rubCsv > 0) {
            $totalpcpm = $totalrevenue / ($totalImpressions_rubCsv/1000);
    }else{
            $totalpcpm = "0.00";
    } 
    
?>    
    <tr>
            <td class="total">Totals </td>
            <td class="total"><?php echo number_format($totalimpressions) ?></td>
            <td class="total"><?php echo number_format($totalImpressions_rubCsv) ?></td>
            <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
            <td class="total">$<?php echo number_format($totalpcpm,2) ?></td>
            <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
    </tr>
    </table>

		<div id="chartdiv_rub" style="height: 300px; width: 750px;"></div>        
    </div>

    <div id="estim">
    <table cellpadding="0" cellspacing="0" id="reportTbl">		
    <tr>			
        <th>Date</th>			
        <th>Impressions</th>
        <th>eCPM</th>			
        <th class="lastTh">Revenue</th>		
    </tr>																    
    
<?php 
$totalimpressions = 0;
$totalecpm = 0;
$totalrevenue = 0;

$impressions = 0;
$revenue = 0;
$ecpm = 0;

$nodata=true;
$count = 0;
$asterics = '';
$pending = false;
?>
    
<?php if($this->report): ?>
    <?php
        $nodata=false;
        $line1_est = "[";
        $line2_est = "[";	    
    ?>
    
    <?php foreach ($this->report as $item):?>
        <?php        
            $count++;
            $impressions = $item['impressions_estimated'];
            $revenue = 0;
            $ecpm = '-';
            $pending = false;
            
            if($item['estimated']==1){
                $asterics='*';
                if($impressions>0 && $revenue>0){
                    $ecpm = $revenue*1000/$impressions;
                }elseif($this->absEcpm>0 && $impressions>0){
                    $ecpm = $this->absEcpm;
                    $revenue = $this->absEcpm*$impressions/1000;                    
                }else{
                    $pending = true;
                }                    
            }else{
                $asterics='';
                if($impressions>0 && $revenue>0)
                    $ecpm = $revenue*1000/$impressions;
            }

            $totalimpressions += $impressions;
            $totalrevenue += $revenue;
            
            //graph
            $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

            if($count==count($this->report)){
                    $line1_est.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                    $line2_est.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
            }else{
                    $line1_est.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                    $line2_est.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
            }                                    
        ?>
        
        <tr>
            <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
            <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
        </tr>
    
    <?php endforeach; ?>
    
    <?php
        $line1_est.= "]";
        $line2_est.= "]";
    ?>    
<?php else: ?>
    <?php
    $nodata=true; 
    
    $line1_est = "[";
    $line2_est = "[";

    $start = strtotime($this->report_params['start_date']);
    $end = strtotime($this->report_params['end_date']);

    for($i=$start; $i<=$end; $i=$i+86400){

        $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

        $line1_est.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
        $line2_est.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";  
    }

    $line1_est.= "]";
    $line2_est.= "]"; 
    
    ?>
<?php endif; ?>   
<?php 
    if($totalimpressions > 0) {
            $totalecpm = $totalrevenue / ($totalimpressions/1000);
    }else{
            $totalecpm = "0.00";
    } 
?>    
    <tr>
            <td class="total">Totals </td>
            <td class="total"><?php echo number_format($totalimpressions) ?></td>
            <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
            <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
    </tr>
    </table>
		<div id="chartdiv_est" style="height: 300px; width: 750px;"></div>                   
    </div>

    <div id="denied">
    <table cellpadding="0" cellspacing="0" id="reportTbl">		
    <tr>			
        <th>Date</th>			
        <th>Impressions</th>
    </tr>																    
    
<?php 
$totalimpressions = 0;

$impressions = 0;

$nodata=true;
$count = 0;
?>
    
<?php if($this->report): ?>
    <?php
        $nodata=false;
        $line1_deni = "[";
    ?>
    
    <?php foreach ($this->report as $item):?>
        <?php        
            $count++;
            $impressions = $item['impressions_denied'];            
            
            $totalimpressions += $impressions;
            
            //graph
            $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr></table>';

            if($count==count($this->report)){
                    $line1_deni.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
            }else{
                    $line1_deni.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
            }                                    
        ?>
        
        <tr>
            <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
            <td><?php echo !$impressions ? '-' : number_format($impressions) ?></td>
        </tr>
    
    <?php endforeach; ?>
    
    <?php
        $line1_deni.= "]";
    ?>    
<?php else: ?>
    <?php
    $nodata=true; 
    
    $line1_deni = "[";

    $start = strtotime($this->report_params['start_date']);
    $end = strtotime($this->report_params['end_date']);

    for($i=$start; $i<=$end; $i=$i+86400){

        $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr></table>';

        $line1_deni.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
    }

    $line1_deni.= "]";
    
    ?>
<?php endif; ?>   
    <tr>
            <td class="total">Totals </td>
            <td class="total"><?php echo number_format($totalimpressions) ?></td>
    </tr>
    </table>

		<div id="chartdiv_deni" style="height: 300px; width: 750px;"></div>                
    </div>    

    <div id="pubm">
    <table cellpadding="0" cellspacing="0" id="reportTbl">		
    <tr>			
        <th>Date</th>			
        <th>Impressions</th>
        <th>Paid Impressions</th>
        <th>eCPM</th>			
        <th class="lastTh">Revenue</th>		
    </tr>																    
    
<?php 
$totalimpressions = 0;
$totalPaidImpress = 0;
$totalecpm = 0;
$totalrevenue = 0;

$impressions = 0;
$paid_impressions = 0;
$revenue = 0;
$ecpm = 0;

$nodata=true;
$count = 0;
$asterics = '';
$pending = false;
?>
    
<?php if($this->report): ?>
    <?php
        $nodata=false;
        $line1_bur = "[";
        $line2_bur = "[";	    
    ?>
    
    <?php foreach ($this->report as $item):?>
        <?php        
            $count++;
            $impressions = $item['impressions_pubmatic'];
            $paid_impressions = $item['paid_impressions_pubmatic'];
            $revenue = $item['revenue_pubmatic'];
            if($revenue && $paid_impressions)
	            $ecpm = $revenue*1000/$paid_impressions;
			else
				$ecpm = '-';	            
            
            $totalimpressions += $impressions;
            $totalPaidImpress += $paid_impressions;
            $totalrevenue += $revenue;
            
            //graph
            $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

            if($count==count($this->report)){
                    $line1_pubm.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                    $line2_pubm.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
            }else{
                    $line1_pubm.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                    $line2_pubm.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
            }                                    
        ?>
        
        <tr>
            <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
            <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
            <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
        </tr>
    
    <?php endforeach; ?>
    
    <?php
        $line1_pubm.= "]";
        $line2_pubm.= "]";
    ?>    
<?php else: ?>
    <?php
    $nodata=true; 
    
    $line1_pubm = "[";
    $line2_pubm = "[";

    $start = strtotime($this->report_params['start_date']);
    $end = strtotime($this->report_params['end_date']);

    for($i=$start; $i<=$end; $i=$i+86400){

        $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

        $line1_pubm.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
        $line2_pubm.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";  
    }

    $line1_pubm.= "]";
    $line2_pubm.= "]"; 
    
    ?>
<?php endif; ?>   
<?php 
    if($totalPaidImpress > 0) {
            $totalecpm = $totalrevenue / ($totalPaidImpress/1000);
    }else{
            $totalecpm = "0.00";
    } 
    
?>    
    <tr>
            <td class="total">Totals </td>
            <td class="total"><?php echo number_format($totalimpressions) ?></td>
            <td class="total">$<?php echo number_format($totalPaidImpress,2) ?></td>
            <td class="total">$<?php echo number_format($totalecpm,2) ?></td>            
            <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
    </tr>
    </table>
		<div id="chartdiv_pubm" style="height: 300px; width: 750px;"></div>                   
    </div>    

    <div id="amazon">
        <table cellpadding="0" cellspacing="0" id="reportTbl">
            <tr>
                <th>Date</th>
                <th>Impressions</th>
                <th>Paid Impressions</th>
                <th>eCPM</th>
                <th class="lastTh">Revenue</th>
            </tr>

            <?php
            $totalimpressions = 0;
            $totalPaidImpress = 0;
            $totalecpm = 0;
            $totalrevenue = 0;

            $impressions = 0;
            $paid_impressions = 0;
            $revenue = 0;
            $ecpm = 0;

            $nodata=true;
            $count = 0;
            $asterics = '';
            $pending = false;
            ?>

            <?php if($this->report): ?>
                <?php
                $nodata=false;
                $line1_bur = "[";
                $line2_bur = "[";
                ?>

                <?php foreach ($this->report as $item):?>
                    <?php
                    $count++;
                    $impressions = $item['impressions_amazon'];
                    $paid_impressions = $item['paid_impressions_amazon'];
                    $revenue = $item['revenue_amazon'];
                    if($revenue && $paid_impressions)
                        $ecpm = $revenue*1000/$paid_impressions;
                    else
                        $ecpm = '-';

                    $totalimpressions += $impressions;
                    $totalPaidImpress += $paid_impressions;
                    $totalrevenue += $revenue;

                    //graph
                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

                    if($count==count($this->report)){
                        $line1_pubm.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                        $line2_pubm.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
                    }else{
                        $line1_pubm.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                        $line2_pubm.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
                    }
                    ?>

                    <tr>
                        <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
                        <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
                        <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
                    </tr>

                <?php endforeach; ?>

                <?php
                $line1_pubm.= "]";
                $line2_pubm.= "]";
                ?>
            <?php else: ?>
                <?php
                $nodata=true;

                $line1_pubm = "[";
                $line2_pubm = "[";

                $start = strtotime($this->report_params['start_date']);
                $end = strtotime($this->report_params['end_date']);

                for($i=$start; $i<=$end; $i=$i+86400){

                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

                    $line1_pubm.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
                    $line2_pubm.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";
                }

                $line1_pubm.= "]";
                $line2_pubm.= "]";

                ?>
            <?php endif; ?>
            <?php
            if($totalPaidImpress > 0) {
                $totalecpm = $totalrevenue / ($totalPaidImpress/1000);
            }else{
                $totalecpm = "0.00";
            }

            ?>
            <tr>
                <td class="total">Totals </td>
                <td class="total"><?php echo number_format($totalimpressions) ?></td>
                <td class="total">$<?php echo number_format($totalPaidImpress,2) ?></td>
                <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
                <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>
            </tr>
        </table>
        <div id="chartdiv_amazon" style="height: 300px; width: 750px;"></div>
    </div>

    <div id="PulsePoint">
        <table cellpadding="0" cellspacing="0" id="reportTbl">
            <tr>
                <th>Date</th>
                <th>Impressions</th>
                <th>Paid Impressions</th>
                <th>eCPM</th>
                <th class="lastTh">Revenue</th>
            </tr>

            <?php
            $totalimpressions = 0;
            $totalPaidImpress = 0;
            $totalecpm = 0;
            $totalrevenue = 0;

            $impressions = 0;
            $paid_impressions = 0;
            $revenue = 0;
            $ecpm = 0;

            $nodata=true;
            $count = 0;
            $asterics = '';
            $pending = false;
            ?>

            <?php if($this->report): ?>
                <?php
                $nodata=false;
                $line1_bur = "[";
                $line2_bur = "[";
                ?>

                <?php foreach ($this->report as $item):?>
                    <?php
                    $count++;
                    $impressions = $item['impressions_pulse'];
                    $paid_impressions = $item['paid_impressions_pulse'];
                    $revenue = $item['revenue_pulse'];
                    if($revenue && $paid_impressions)
                        $ecpm = $revenue*1000/$paid_impressions;
                    else
                        $ecpm = '-';

                    $totalimpressions += $impressions;
                    $totalPaidImpress += $paid_impressions;
                    $totalrevenue += $revenue;

                    //graph
                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

                    if($count==count($this->report)){
                        $line1_pubm.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                        $line2_pubm.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
                    }else{
                        $line1_pubm.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                        $line2_pubm.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
                    }
                    ?>

                    <tr>
                        <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
                        <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
                        <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
                    </tr>

                <?php endforeach; ?>

                <?php
                $line1_pubm.= "]";
                $line2_pubm.= "]";
                ?>
            <?php else: ?>
                <?php
                $nodata=true;

                $line1_pubm = "[";
                $line2_pubm = "[";

                $start = strtotime($this->report_params['start_date']);
                $end = strtotime($this->report_params['end_date']);

                for($i=$start; $i<=$end; $i=$i+86400){

                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

                    $line1_pubm.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
                    $line2_pubm.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";
                }

                $line1_pubm.= "]";
                $line2_pubm.= "]";

                ?>
            <?php endif; ?>
            <?php
            if($totalPaidImpress > 0) {
                $totalecpm = $totalrevenue / ($totalPaidImpress/1000);
            }else{
                $totalecpm = "0.00";
            }

            ?>
            <tr>
                <td class="total">Totals </td>
                <td class="total"><?php echo number_format($totalimpressions) ?></td>
                <td class="total">$<?php echo number_format($totalPaidImpress,2) ?></td>
                <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
                <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>
            </tr>
        </table>
        <div id="chartdiv_PulsePoint" style="height: 300px; width: 750px;"></div>
    </div>

    <div id="PopAds">
        <table cellpadding="0" cellspacing="0" id="reportTbl">
            <tr>
                <th>Date</th>
                <th>Impressions</th>
                <th>Paid Impressions</th>
                <th>eCPM</th>
                <th class="lastTh">Revenue</th>
            </tr>

            <?php
            $totalimpressions = 0;
            $totalPaidImpress = 0;
            $totalecpm = 0;
            $totalrevenue = 0;

            $impressions = 0;
            $paid_impressions = 0;
            $revenue = 0;
            $ecpm = 0;

            $nodata=true;
            $count = 0;
            $asterics = '';
            $pending = false;
            ?>

            <?php if($this->report): ?>
                <?php
                $nodata=false;
                $line1_bur = "[";
                $line2_bur = "[";
                ?>

                <?php foreach ($this->report as $item):?>
                    <?php
                    $count++;
                    $impressions = $item['impressions_pop'];
                    $paid_impressions = $item['paid_impressions_pop'];
                    $revenue = $item['revenue_pop'];
                    if($revenue && $paid_impressions)
                        $ecpm = $revenue*1000/$paid_impressions;
                    else
                        $ecpm = '-';

                    $totalimpressions += $impressions;
                    $totalPaidImpress += $paid_impressions;
                    $totalrevenue += $revenue;

                    //graph
                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

                    if($count==count($this->report)){
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
                    }else{
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
                    }
                    ?>

                    <tr>
                        <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
                        <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
                        <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
                    </tr>

                <?php endforeach; ?>

                <?php
                $line1_pop.= "]";
                $line2_pop.= "]";
                ?>
            <?php else: ?>
                <?php
                $nodata=true;

                $line1_pop = "[";
                $line2_pop = "[";

                $start = strtotime($this->report_params['start_date']);
                $end = strtotime($this->report_params['end_date']);

                for($i=$start; $i<=$end; $i=$i+86400){

                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

                    $line1_pop.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
                    $line2_pop.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";
                }

                $line1_pop.= "]";
                $line2_pop.= "]";

                ?>
            <?php endif; ?>
            <?php
            if($totalPaidImpress > 0) {
                $totalecpm = $totalrevenue / ($totalPaidImpress/1000);
            }else{
                $totalecpm = "0.00";
            }

            ?>
            <tr>
                <td class="total">Totals </td>
                <td class="total"><?php echo number_format($totalimpressions) ?></td>
                <td class="total">$<?php echo number_format($totalPaidImpress,2) ?></td>
                <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
                <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>
            </tr>
        </table>
        <div id="chartdiv_PopAds" style="height: 300px; width: 750px;"></div>
    </div>

    <div id="Sekindo">
        <table cellpadding="0" cellspacing="0" id="reportTbl">
            <tr>
                <th>Date</th>
                <th>Impressions</th>
                <th>Paid Impressions</th>
                <th>eCPM</th>
                <th class="lastTh">Revenue</th>
            </tr>

            <?php
            $totalimpressions = 0;
            $totalPaidImpress = 0;
            $totalecpm = 0;
            $totalrevenue = 0;

            $impressions = 0;
            $paid_impressions = 0;
            $revenue = 0;
            $ecpm = 0;

            $nodata=true;
            $count = 0;
            $asterics = '';
            $pending = false;
            ?>

            <?php if($this->report): ?>
                <?php
                $nodata=false;
                $line1_bur = "[";
                $line2_bur = "[";
                ?>

                <?php foreach ($this->report as $item):?>
                    <?php
                    $count++;
                    $impressions = $item['impressions_sekindo'];
                    $paid_impressions = $item['paid_impressions_sekindo'];
                    $revenue = $item['revenue_sekindo'];
                    if($revenue && $paid_impressions)
                        $ecpm = $revenue*1000/$paid_impressions;
                    else
                        $ecpm = '-';

                    $totalimpressions += $impressions;
                    $totalPaidImpress += $paid_impressions;
                    $totalrevenue += $revenue;

                    //graph
                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

                    if($count==count($this->report)){
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
                    }else{
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
                    }
                    ?>

                    <tr>
                        <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
                        <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
                        <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
                    </tr>

                <?php endforeach; ?>

                <?php
                $line1_pop.= "]";
                $line2_pop.= "]";
                ?>
            <?php else: ?>
                <?php
                $nodata=true;

                $line1_pop = "[";
                $line2_pop = "[";

                $start = strtotime($this->report_params['start_date']);
                $end = strtotime($this->report_params['end_date']);

                for($i=$start; $i<=$end; $i=$i+86400){

                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

                    $line1_pop.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
                    $line2_pop.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";
                }

                $line1_pop.= "]";
                $line2_pop.= "]";

                ?>
            <?php endif; ?>
            <?php
            if($totalPaidImpress > 0) {
                $totalecpm = $totalrevenue / ($totalPaidImpress/1000);
            }else{
                $totalecpm = "0.00";
            }

            ?>
            <tr>
                <td class="total">Totals </td>
                <td class="total"><?php echo number_format($totalimpressions) ?></td>
                <td class="total">$<?php echo number_format($totalPaidImpress,2) ?></td>
                <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
                <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>
            </tr>
        </table>
        <div id="chartdiv_Sekindo" style="height: 300px; width: 750px;"></div>
    </div>
    
    <div id="Aol">
        <table cellpadding="0" cellspacing="0" id="reportTbl">
            <tr>
                <th>Date</th>
                <th>Impressions</th>
                <th>Paid Impressions</th>
                <th>eCPM</th>
                <th class="lastTh">Revenue</th>
            </tr>

            <?php
            $totalimpressions = 0;
            $totalPaidImpress = 0;
            $totalecpm = 0;
            $totalrevenue = 0;

            $impressions = 0;
            $paid_impressions = 0;
            $revenue = 0;
            $ecpm = 0;

            $nodata=true;
            $count = 0;
            $asterics = '';
            $pending = false;
            ?>

            <?php if($this->report): ?>
                <?php
                $nodata=false;
                $line1_bur = "[";
                $line2_bur = "[";
                ?>

                <?php foreach ($this->report as $item):?>
                    <?php
                    $count++;
                    $impressions = $item['impressions_aol'];
                    $paid_impressions = $item['paid_impressions_aol'];
                    $revenue = $item['revenue_aol'];
                    if($revenue && $paid_impressions)
                        $ecpm = $revenue*1000/$paid_impressions;
                    else
                        $ecpm = '-';

                    $totalimpressions += $impressions;
                    $totalPaidImpress += $paid_impressions;
                    $totalrevenue += $revenue;

                    //graph
                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

                    if($count==count($this->report)){
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
                    }else{
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
                    }
                    ?>

                    <tr>
                        <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
                        <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
                        <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
                    </tr>

                <?php endforeach; ?>

                <?php
                $line1_pop.= "]";
                $line2_pop.= "]";
                ?>
            <?php else: ?>
                <?php
                $nodata=true;

                $line1_pop = "[";
                $line2_pop = "[";

                $start = strtotime($this->report_params['start_date']);
                $end = strtotime($this->report_params['end_date']);

                for($i=$start; $i<=$end; $i=$i+86400){

                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

                    $line1_pop.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
                    $line2_pop.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";
                }

                $line1_pop.= "]";
                $line2_pop.= "]";

                ?>
            <?php endif; ?>
            <?php
            if($totalPaidImpress > 0) {
                $totalecpm = $totalrevenue / ($totalPaidImpress/1000);
            }else{
                $totalecpm = "0.00";
            }

            ?>
            <tr>
                <td class="total">Totals </td>
                <td class="total"><?php echo number_format($totalimpressions) ?></td>
                <td class="total">$<?php echo number_format($totalPaidImpress,2) ?></td>
                <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
                <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>
            </tr>
        </table>
        <div id="chartdiv_Aol" style="height: 300px; width: 750px;"></div>
    </div>
    
    <div id="Aol_o">
        <table cellpadding="0" cellspacing="0" id="reportTbl">
            <tr>
                <th>Date</th>
                <th>Impressions</th>
                <th>Paid Impressions</th>
                <th>eCPM</th>
                <th class="lastTh">Revenue</th>
            </tr>

            <?php
            $totalimpressions = 0;
            $totalPaidImpress = 0;
            $totalecpm = 0;
            $totalrevenue = 0;

            $impressions = 0;
            $paid_impressions = 0;
            $revenue = 0;
            $ecpm = 0;

            $nodata=true;
            $count = 0;
            $asterics = '';
            $pending = false;
            ?>

            <?php if($this->report): ?>
                <?php
                $nodata=false;
                $line1_bur = "[";
                $line2_bur = "[";
                ?>

                <?php foreach ($this->report as $item):?>
                    <?php
                    $count++;
                    $impressions = $item['impressions_aol_o'];
                    $paid_impressions = $item['paid_impressions_aol_o'];
                    $revenue = $item['revenue_aol_o'];
                    if($revenue && $paid_impressions)
                        $ecpm = $revenue*1000/$paid_impressions;
                    else
                        $ecpm = '-';

                    $totalimpressions += $impressions;
                    $totalPaidImpress += $paid_impressions;
                    $totalrevenue += $revenue;

                    //graph
                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

                    if($count==count($this->report)){
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
                    }else{
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
                    }
                    ?>

                    <tr>
                        <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
                        <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
                        <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
                    </tr>

                <?php endforeach; ?>

                <?php
                $line1_pop.= "]";
                $line2_pop.= "]";
                ?>
            <?php else: ?>
                <?php
                $nodata=true;

                $line1_pop = "[";
                $line2_pop = "[";

                $start = strtotime($this->report_params['start_date']);
                $end = strtotime($this->report_params['end_date']);

                for($i=$start; $i<=$end; $i=$i+86400){

                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

                    $line1_pop.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
                    $line2_pop.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";
                }

                $line1_pop.= "]";
                $line2_pop.= "]";

                ?>
            <?php endif; ?>
            <?php
            if($totalPaidImpress > 0) {
                $totalecpm = $totalrevenue / ($totalPaidImpress/1000);
            }else{
                $totalecpm = "0.00";
            }

            ?>
            <tr>
                <td class="total">Totals </td>
                <td class="total"><?php echo number_format($totalimpressions) ?></td>
                <td class="total">$<?php echo number_format($totalPaidImpress,2) ?></td>
                <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
                <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>
            </tr>
        </table>
        <div id="chartdiv_Aol_o" style="height: 300px; width: 750px;"></div>
    </div>
    
    <div id="bRealTime">
        <table cellpadding="0" cellspacing="0" id="reportTbl">
            <tr>
                <th>Date</th>
                <th>Impressions</th>
                <th>Paid Impressions</th>
                <th>eCPM</th>
                <th class="lastTh">Revenue</th>
            </tr>

            <?php
            $totalimpressions = 0;
            $totalPaidImpress = 0;
            $totalecpm = 0;
            $totalrevenue = 0;

            $impressions = 0;
            $paid_impressions = 0;
            $revenue = 0;
            $ecpm = 0;

            $nodata=true;
            $count = 0;
            $asterics = '';
            $pending = false;
            ?>

            <?php if($this->report): ?>
                <?php
                $nodata=false;
                $line1_bur = "[";
                $line2_bur = "[";
                ?>

                <?php foreach ($this->report as $item):?>
                    <?php
                    $count++;
                    $impressions = $item['impressions_brt'];
                    $paid_impressions = $item['paid_impressions_brt'];
                    $revenue = $item['revenue_brt'];
                    if($revenue && $paid_impressions)
                        $ecpm = $revenue*1000/$paid_impressions;
                    else
                        $ecpm = '-';

                    $totalimpressions += $impressions;
                    $totalPaidImpress += $paid_impressions;
                    $totalrevenue += $revenue;

                    //graph
                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';

                    if($count==count($this->report)){
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
                    }else{
                        $line1_pop.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                        $line2_pop.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
                    }
                    ?>

                    <tr>
                        <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
                        <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
                        <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
                        <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
                    </tr>

                <?php endforeach; ?>

                <?php
                $line1_pop.= "]";
                $line2_pop.= "]";
                ?>
            <?php else: ?>
                <?php
                $nodata=true;

                $line1_pop = "[";
                $line2_pop = "[";

                $start = strtotime($this->report_params['start_date']);
                $end = strtotime($this->report_params['end_date']);

                for($i=$start; $i<=$end; $i=$i+86400){

                    $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';

                    $line1_pop.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
                    $line2_pop.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";
                }

                $line1_pop.= "]";
                $line2_pop.= "]";

                ?>
            <?php endif; ?>
            <?php
            if($totalPaidImpress > 0) {
                $totalecpm = $totalrevenue / ($totalPaidImpress/1000);
            }else{
                $totalecpm = "0.00";
            }

            ?>
            <tr>
                <td class="total">Totals </td>
                <td class="total"><?php echo number_format($totalimpressions) ?></td>
                <td class="total">$<?php echo number_format($totalPaidImpress,2) ?></td>
                <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
                <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>
            </tr>
        </table>
        <div id="chartdiv_bRealTime" style="height: 300px; width: 750px;"></div>
    </div>

    <div id="all">
    <table cellpadding="0" cellspacing="0" id="reportTbl">		
    <tr>			
        <th>Date</th>			
        <th>Impressions</th>
        <th>Paid Impressions</th>
        <th>eCPM</th>			
        <th class="lastTh">Revenue</th>		
    </tr>																    
    
<?php 
$totalimpressions = 0;
$totalPaidimpressions = 0;
$totalecpm = 0;
$totalrevenue = 0;

$impressions = 0;
$revenue = 0;
$ecpm = 0;

$nodata=true;
$count = 0;
$asterics = '';
$pending = false;
?>
    
<?php if($this->report): ?>
    <?php
        $nodata=false;
        $line1 = "[";
        $line2 = "[";	
        $line3 = "[";
    ?>
    
    <?php foreach ($this->report as $item):?>
        <?php        
            $count++;
            $impressions = $item['impressions'];
            $paid_impressions = $item['paid_impressions'];
            $revenue = $item['revenue'];
            $ecpm = '-';
            $pending = false;
            
            if($item['estimated']==1){
                $asterics='*';
                if($impressions>0 && $revenue>0){
                    $ecpm = $revenue*1000/$paid_impressions;
                }elseif($this->absEcpm>0 && $paid_impressions>0){
                    $ecpm = $this->absEcpm;
                    $revenue = $this->absEcpm*$paid_impressions/1000;                    
                }else{
                    $pending = true;
                }                    
            }else{
                $asterics='';
                if($impressions>0 && $revenue>0)
                    $ecpm = $revenue*1000/$paid_impressions;
            }

            $totalimpressions += $impressions;
            $totalPaidimpressions += $paid_impressions;
            $totalrevenue += $revenue;
            
            //graph
            $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Impressions:</td><td>'.number_format($impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';
            $formatLinePaid = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", strtotime($item['query_date'])).'</td></tr><tr><td>Paid Impressions:</td><td>'.number_format($paid_impressions).'</td></tr><tr><td>Revenue:</td><td>$'.number_format($revenue,2).'</td></tr><tr><td>eCPM:</td><td>$'.number_format($ecpm!='-' ? $ecpm : 0 ,2).'</td></tr></table>';
            

            if($count==count($this->report)){
                    $line1.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine']";
                    $line2.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine']";
                    $line3.= "['$item[query_date]', ".str_replace(',','.',$paid_impressions).", '$formatLinePaid']";
            }else{
                    $line1.= "['$item[query_date]', ".str_replace(',','.',$impressions).", '$formatLine'], ";
                    $line2.= "['$item[query_date]', ".str_replace(',','.',$revenue).", '$formatLine'], ";
                    $line3.= "['$item[query_date]', ".str_replace(',','.',$paid_impressions).", '$formatLinePaid'], ";
            }                                    
        ?>
        
        <tr>
            <td><?php echo '<a href="/report/view/date/'.$item['query_date'].'">'.$item['query_date'].'<a>'?><?php echo $asterics?></td>
            <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>
            <td><?php echo !$paid_impressions ? '-' : number_format($paid_impressions) ?><?php echo $asterics?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
        </tr>
    
    <?php endforeach; ?>
    
    <?php
        $line1.= "]";
        $line2.= "]";
        $line3.= "]";
    ?>    
<?php else: ?>
    <?php
    $nodata=true; 
    
    $line1 = "[";
    $line2 = "[";
    $line3 = "[";

    $start = strtotime($this->report_params['start_date']);
    $end = strtotime($this->report_params['end_date']);

    for($i=$start; $i<=$end; $i=$i+86400){

        $formatLine = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
        $formatLinePaid = '<table class=\"jqplot-highlighter\"><tr><td>Date:</td><td>'.date("M d, Y", $i).'</td></tr><tr><td>Paid Impressions:</td><td>0,000</td></tr><tr><td>Revenue:</td><td>$0.00</td></tr><tr><td>eCPM:</td><td>$0.00</td></tr></table>';
        
        $line1.= "['".date("M d, Y", $i)."', 0.000, '$formatLine'], ";
        $line2.= "['".date("M d, Y", $i)."', 0.00, '$formatLine'], ";
        $line3.= "['".date("M d, Y", $i)."', 0.000, '$formatLinePaid'], ";
    }

    $line1.= "]";
    $line2.= "]"; 
    $line3.= "]"; 
    
    ?>
<?php endif; ?>   
<?php 
    if($totalPaidimpressions > 0) {
            $totalecpm = $totalrevenue / ($totalPaidimpressions/1000);
    }else{
            $totalecpm = "0.00";
    } 
?>    
    <tr>
            <td class="total">Totals </td>
            <td class="total"><?php echo number_format($totalimpressions) ?></td>
            <td class="total"><?php echo number_format($totalPaidimpressions) ?></td>
            <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
            <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
    </tr>
    </table>
        <div id="chartdiv" style="height: 300px; width: 750px;"></div>
    </div>    
</div>
<div class="estimate"><h5>*Estimates Only. Numbers can take up to 2 days to finalize.</h5>	
</div><!--//estimate-->


<script type="text/javascript">
$(document).ready(function(){
	  var line1_rub = <?php echo $line1_rub ?>;
	  var line2_rub = <?php echo $line2_rub ?>;
	 
	  var plot1 = $.jqplot('chartdiv_rub', [line1_rub, line2_rub], {
	    series:[{renderer:$.jqplot.highlighter, label:'Impressions', color:'grey'}, {xaxis:'xaxis', yaxis:'y2axis', label:'Revenue', color:'red'}],
	    axesDefaults: {
	        tickRenderer: $.jqplot.CanvasAxisLabelRenderer,
	    },
	    highlighter: {
	      show: true,
	      showMarker:false,
	      tooltipAxes: 'both',
	      yvalues: 3,
	      // You can customize the tooltip format string of the highlighter
	      // to include any arbitrary text or html and use format string
	      // placeholders (%s here) to represent x and y values.
	      formatString:'<!--%s%s-->%s'
	    },    
	    legend: {
	        show: true,
	        placement: 'outsideGrid',
	        location: 's'
	    },    
	    axes: {
	      xaxis: {
	        renderer: $.jqplot.DateAxisRenderer,
	          tickOptions:{
	            formatString:'%b %#d'
	          },
	      },
	      yaxis: {
	        autoscale:true,
	          tickOptions:{
	            formatString:'%s'
	            }<?php if($noresult_rub): ?>,   
	          min:0, 
	          max: 50000,
	          tickInterval:10000
	            <?php endif; ?>
	      },
	      y2axis: {
	          autoscale:true,
	          tickOptions:{
	            formatString:'$%.2f'
	            }<?php if($noresult_rub): ?>,   
	          min:0.000, 
	          max: 50.000,
	          tickInterval:10
	            <?php endif; ?>
	      }
	    }
	  });

	  var line1_est = <?php echo $line1_est ?>;
	  var line2_est = <?php echo $line2_est ?>;
	 
	  var plot3 = $.jqplot('chartdiv_est', [line1_est, line2_est], {
	    series:[{renderer:$.jqplot.highlighter, label:'Impressions', color:'grey'}, {xaxis:'xaxis', yaxis:'y2axis', label:'Revenue', color:'red'}],
	    axesDefaults: {
	        tickRenderer: $.jqplot.CanvasAxisLabelRenderer,
	    },
	    highlighter: {
	      show: true,
	      showMarker:false,
	      tooltipAxes: 'both',
	      yvalues: 3,
	      // You can customize the tooltip format string of the highlighter
	      // to include any arbitrary text or html and use format string
	      // placeholders (%s here) to represent x and y values.
	      formatString:'<!--%s%s-->%s'
	    },    
	    legend: {
	        show: true,
	        placement: 'outsideGrid',
	        location: 's'
	    },    
	    axes: {
	      xaxis: {
	        renderer: $.jqplot.DateAxisRenderer,
	          tickOptions:{
	            formatString:'%b %#d'
	          },
	      },
	      yaxis: {
	        autoscale:true,
	          tickOptions:{
	            formatString:'%s'
	            }<?php if($noresult_est): ?>,   
	          min:0, 
	          max: 50000,
	          tickInterval:10000
	            <?php endif; ?>
	      },
	      y2axis: {
	          autoscale:true,
	          tickOptions:{
	            formatString:'$%.2f'
	            }<?php if($noresult_est): ?>,   
	          min:0.000, 
	          max: 50.000,
	          tickInterval:10
	            <?php endif; ?>
	      }
	    }
	  });


	  var line1 = <?php echo $line1 ?>;
	  var line2 = <?php echo $line2 ?>;
	  var line3 = <?php echo $line3 ?>;
	 
	  var plot2 = $.jqplot('chartdiv', [line1, line2, line3], {
	    series:[{renderer:$.jqplot.highlighter, label:'Impressions', color:'grey'}, {xaxis:'xaxis', yaxis:'y2axis', label:'Revenue', color:'red'}, {renderer:$.jqplot.highlighter, label:'Paid Impressions', color:'green'}],
	    axesDefaults: {
	        tickRenderer: $.jqplot.CanvasAxisLabelRenderer,
	    },
	    highlighter: {
	      show: true,
	      showMarker:false,
	      tooltipAxes: 'both',
	      yvalues: 3,
	      // You can customize the tooltip format string of the highlighter
	      // to include any arbitrary text or html and use format string
	      // placeholders (%s here) to represent x and y values.
	      formatString:'<!--%s%s-->%s'
	    },    
	    legend: {
	        show: true,
	        placement: 'outsideGrid',
	        location: 's'
	    },    
	    axes: {
	      xaxis: {
	        renderer: $.jqplot.DateAxisRenderer,
	          tickOptions:{
	            formatString:'%b %#d'
	          },
	      },
	      yaxis: {
	        autoscale:true,
	          tickOptions:{
	            formatString:'%s'
	            }<?php if($nodata): ?>,   
	          min:0, 
	          max: 50000,
	          tickInterval:10000
	            <?php endif; ?>
	      },
	      y2axis: {
	          autoscale:true,
	          tickOptions:{
	            formatString:'$%.2f'
	            }<?php if($nodata): ?>,   
	          min:0.000, 
	          max: 50.000,
	          tickInterval:10
	            <?php endif; ?>
	      }
	    }
	  });
	  
	  
      $('.reportBox').bind('tabsshow', function(event, ui) {
      	  if (ui.index == 0) {
              plot1.replot();
      	  }
      	  else if(ui.index == 2){
        		plot3.replot();  
      	  } 
      	});
	  
}) ;   
</script>

<script	type="text/javascript" src="/font/cufon-yui.js"></script>
<script	type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script><script	type="text/javascript" src="/font/Headline_Two_400.font.js"></script><script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
</script><script	type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script><script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.publisher h4');	
		Cufon.replace('.publisher h4 span');	
		Cufon.replace('.publMail a');	
		Cufon.replace('.logOut span');					
</script><script	type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script><script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.reportTop h5');		
		Cufon.replace('.estimate h5');			
</script><script type="text/javascript">
$(document).ready(function() {
Cufon.set("fontFamily", "Proxima_Nova_Lt_300.font.js");
	$("#reportL li").hover(
		function(){
		$(this).children('a').children('span').addClass('black');
		Cufon.refresh();		
		Cufon.replace('.black', {color: '#000000'});	
		}, 
	  function () {
		$(this).children('a').children('span').removeClass('black');
		Cufon.refresh();			
		Cufon.replace('#reportL li span', {color: '#DE3232'});	
	  }
	);
	$("#showBox").click(
		function(){
		$('.subDate').toggle(220);
		$('.dateBoxInn').toggleClass('curDate');
		}
	);
	
	$(".dCancelBtn").click(
		function(){
		$('.subDate').fadeOut(600);
		$('.dateBoxInn').removeClass('curDate');
		}
	);	
	


	
});
</script><script	type="text/javascript" src="/js/calendar.js.js"></script><script type="text/javascript">
	$(function(){
		$('#singleCont').css('backgroundImage', 'url(/images/contBg_1.png)');
			$(".datepicker").datepicker({dateFormat: 'M d, yy'});
});
</script>