<link type="text/css" rel="stylesheet" media="screen" href="/styles/table.css"></link>
<style type="text/css">
    
    .reportTop .dateLink{ cursor: pointer; }
    .subDate { width: 307px; }
    #site-name{ display: block; float: left; font-size: 16px; margin-left: 10px; }
    #site-name span{ font-weight: bold; font-size: 17px; margin-right: 5px; }
    
</style>
<script src="/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script type="text/javascript">
    
    
jQuery.fn.dataTableExt.oSort['numeric-comma-asc']  = function(a,b) {
   
    var x = a.replace( /,/g, '' );
    var y = b.replace( /,/g, '' );

    x = parseFloat( x );
    y = parseFloat( y );
    
    return ((x < y) ? -1 : ((x > y) ?  1 : 0));

};
 
jQuery.fn.dataTableExt.oSort['numeric-comma-desc'] = function(a,b) {

    var x = a.replace( /,/g, '' );
    var y = b.replace( /,/g, '' );

    x = parseFloat( x );
    y = parseFloat( y );
    
    return ((x < y) ?  1 : ((x > y) ? -1 : 0));
    
};

jQuery.fn.dataTableExt.oSort['num-html-asc']  = function(a,b) {
   
    var x = a.replace( '$', '' );
    var y = b.replace( '$', '' );
    
    if(x.indexOf('Pending') != -1 || y.indexOf('Pending') != -1){
    
        x = x.replace( /<.*?>/g, '' );
        y = y.replace( /<.*?>/g, '' );

        x = x.replace( 'Pending', '0' );
        y = y.replace( 'Pending', '0' );
    
    } else {
    
        if(x.indexOf('-') && x.length == 1) x = x.replace( '-', '0' );
        if(y.indexOf('-') && y.length == 1) y = y.replace( '-', '0' );
    
    }
  
    x = parseFloat( x );
    y = parseFloat( y );
    
    return ((x < y) ? -1 : ((x > y) ?  1 : 0));

};
 
jQuery.fn.dataTableExt.oSort['num-html-desc'] = function(a,b) {

    var x = a.replace( '$', '' );
    var y = b.replace( '$', '' );
    
    if(x.indexOf('Pending') != -1 || y.indexOf('Pending') != -1){
    
        x = x.replace( /<.*?>/g, '' );
        y = y.replace( /<.*?>/g, '' );

        x = x.replace( 'Pending', '0' );
        y = y.replace( 'Pending', '0' );
    
    } else {
        
        if(x.indexOf('-') && x.length == 1) x = x.replace( '-', '0' );
        if(y.indexOf('-') && y.length == 1) y = y.replace( '-', '0' );
        
    }
  
    x = parseFloat( x );
    y = parseFloat( y );
    
    return ((x < y) ?  1 : ((x > y) ? -1 : 0));
    
};
    
    
    $(document).ready(function() {

            $("#search-date").datepicker({
                            dateFormat: 'M d, yy',
                            changeYear: true,
                            changeMonth: true
            });
    
    
            $("#search-date").change(function(){
                    $("#showBox").html($.datepicker.formatDate('M d, yy', new Date($("#search-date").val()))); 
            }); 
            
    
            $("#showBox").click(function(){

                    $('.subDate').toggle(220);
                    $('.dateBoxInn').toggleClass('curDate');
            });
            $(".dCancelBtn").click(function(){

                    $('.subDate').fadeOut(600);
                    $('.dateBoxInn').removeClass('curDate');
            });
            $("#update").click(function(){
                    $("#formDate").submit();       
            })
                        
            var oTable2 = $('#reportTbl').dataTable( {
                        "bFilter": false,
                        "bProcessing": true,
                        "bLengthChange": false,
                        "bPaginate": false,
                        "aoColumns": [
                            { 
                              "sTitle": "Sizes",
                              "bSortable": false 
                            }, 
                            { 
                              "sTitle": "Impressions",
                              "sType": "numeric-comma" 
                            }, 
                            { 
                              "sTitle": "eCPM",
                              "sType": "num-html" 
                            },
                            { 
                              "sTitle": "Revenue",
                              "sType": "num-html" 
                            }
                        ],                                                
                        "aaSorting": [[ 0, "desc" ]]
            });
                        
     });
    
</script>

<form name="size" method="get" id="formDate" action="/report/size/site/<?php echo $this->curent["site"] ?>">	
      <div class="reportTop">

          <h5>Earnings</h5>              
          <div class="dateBox">
              <p class="dateBoxInn">
                  <a title="" class="dateLink" id="showBox"><?php echo date("M j, Y", strtotime($this->curent["date"])); ?></a>
              </p>
              <div class="subDate">
                 <div class="dateRanch">
                    <h5>Date</h5> 
                    <input type="text" value="<?php echo date("M j, Y", strtotime($this->curent["date"])); ?>" name="date" id="search-date" onfocus="this.value=''" onblur="if (this.value==''){this.value=''}" class="datepicker" />
                    <p>
                        <a href="#" title="" class="dCancelBtn" id="cancel" txt="<?php echo htmlentities(date("M j, Y", strtotime($this->report_params["start_date"]))); ?> – <?php echo htmlentities(date("M j, Y", strtotime($this->report_params["end_date"]))); ?>">Cancel</a>
                        <a href="#" title="" class="dUpdlBtn" id="update">Update</a>                            
                    </p>
                 </div>
              </div>
          </div>
          <!--
          <p class="sizeSel"><b>Size</b>
              	<select onchange="this.form.submit();" name="ad_size">
                    	<option value="">All Media Types</option>
                    <?php foreach($this->ad_sizes as $size) { ?>
                        <option value="<?php echo $size->id ?>"<?php if ($this->curent["ad_size"] == $size->id) { echo ' selected'; } ?>><?php echo $size->name ?></option>
                    <?php } ?>
                </select>
          </p>
          -->
          <!--
          <p class="sizeSel">
              <a href="/csv-report-view/?date=<?php echo $this->curent["date"] ?>&ad_size=<?php echo $this->curent["ad_size"] ?>">
                  <img src="/images/csv-24.gif"/>
              </a>
          </p>
          -->
       </div>
</form>


<br />
<div id="site-name"><span>SITE:</span><?php echo $this->site->SiteName;?></div>
<br />   

<div class="reportBox" style="float: left;">	
    <table cellpadding="0" cellspacing="0" width="741px" class="display" id="reportTbl">	

            <thead>       
                <tr>			
                    <th>Sizes</th>			
                    <th>Impressions</th>
                    <th>eCPM</th>			
                    <th class="lastTh">Revenue</th>		
                </tr>
            </thead>
            <tbody>
    
<?php 
$totalimpressions = 0;
$totalecpm = 0;
$totalrevenue = 0;

$impressions = 0;
$revenue = 0;
$ecpm = 0;

$nodata=true;
$count = 0;
$asterics = '';
$pending = false;
?>
    
<?php if($this->report): ?>    
    <?php foreach ($this->report as $item):?>
        <?php      
            /*
            if($item['impressions'] && $item['estimated']==1){
                if($this->previosAllocted && $this->previosImpressoin){
                    $item['impressions'] = ($this->previosAllocted/$this->previosImpressoin)*$item['impressions'];
                }
            }        
            */
            $count++;
            $impressions = $item['paid_impressions'];
            $revenue = $item['revenue'];
            $ecpm = '-';
            $pending = false;
            
            if($item['estimated']==1){
            	if($item['type']==6 || $item['type']==7 || $item['type']==8){
	            	$ecpm = '-';
	            	$revenue=0;
	            	$pending=true;
	            	$asterics = '*';									            		            	
            	}else{
	                $asterics='*';
	                if($impressions>0 && $revenue>0){
	                    $ecpm = $revenue*1000/$impressions;
	                }elseif($this->absEcpm>0 && $impressions>0){
	                    $ecpm = $this->absEcpm;
	                    $revenue = $this->absEcpm*$impressions/1000;                    
	                }else{
	                    $pending = true;
	                }
                }                    
            }else{
                $asterics='';
                if($impressions>0 && $revenue>0)
                    $ecpm = $revenue*1000/$impressions;
                    
	            $totalimpressions += $impressions;
	            $totalrevenue += $revenue;                    
            }
            
        ?>
        
        <tr>
            <td><?php echo $item['name'] ?><?php echo $asterics?></td> 
            <?php if($item['type']==6): ?>           
            <td><?php echo !$impressions ? 0 : number_format($impressions) ?><?php echo $asterics?></td>
            <?php else: ?>
            <td><?php echo !$impressions ? '-' : number_format($impressions) ?><?php echo $asterics?></td>            
            <?php endif; ?>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($ecpm,2).$asterics?></td>
            <td><?php echo $ecpm=='-' ? $pending ? '<span class="gtip">Pending</span>' : '-'.$asterics : "$".number_format($revenue,2).$asterics?></td>
        </tr>
    
    <?php endforeach; ?>
    </tbody>
<?php else: ?>
<?php endif; ?>   
<?php 
    if($totalimpressions > 0) {
            $totalecpm = $totalrevenue / ($totalimpressions/1000);
    }else{
            $totalecpm = "0.00";
    } 
?>    
    <tfoot>
    <tr>
            <td class="total">Totals </td>
            <td class="total"><?php echo number_format($totalimpressions) ?></td>
            <td class="total">$<?php echo number_format($totalecpm,2) ?></td>
            <td class="total lastTd">$<?php echo number_format($totalrevenue, 2) ?></td>                                                            
    </tr>
    </tfoot>
    </table>
</div><!--estimate-->

<div class="estimate">
    <h5>*Estimates Only. Numbers can take up to 2 days to finalize.</h5>
</div>

<script	type="text/javascript" src="/font/cufon-yui.js"></script>
<script	type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script><script	type="text/javascript" src="/font/Headline_Two_400.font.js"></script><script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
</script><script	type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script><script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.publisher h4');	
		Cufon.replace('.publisher h4 span');	
		Cufon.replace('.publMail a');	
		Cufon.replace('.logOut span');					
</script><script	type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script><script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.reportTop h5');		
		Cufon.replace('.estimate h5');			
</script>