<script type="text/javascript">
$(document).ready(function(){
	$("#action").change(function(){
		if($(this).val()=='add_vend' || $(this).val()=='get_vend'){
			$(".bills_act").css('display', 'none');
			$(".vendors_act").css('display', 'block');			
		}
		
		if($(this).val()=='add_bill' || $(this).val()=='get_bill'){
			$(".vendors_act").css('display', 'none');
			$(".bills_act").css('display', 'block');			
		}		
	})
})	
</script>
<h1>Quickbooks API</h1>
<div class="contUsL" style="width: 750px;">
    <form action="" method="post" class="sign-up">        
        <p>
            <label style="width:130px">Action: </label>
            <select name="action" id="action">
                <option value="">--Select action--</option>
                <option value="add_vend">Add vendors</option>
                <option value="get_vend">Get vendors</option>
                <option value="add_bill">Add bills</option>
                <option value="get_bill">Get bills</option>
            </select>
	    <?php if(isset($this->formErrors['action'])): ?>
	        <ul class="error">
	        <?php foreach($this->formErrors['action'] as $errors): ?>
	            <li><?php echo $errors ?></li>
	        <?php endforeach; ?>
	        </ul>
	    <?php endif; ?>                            
       </p>            

        <p class="vendors_act" style="display:none">
            <label style="width:150px">Only new vendors: </label>
            <input style="width:20px" type="checkbox" checked="checked" name="new_vend" value="1" />
	    <?php if(isset($this->formErrors['new_vend'])): ?>
	        <ul class="error">
	        <?php foreach($this->formErrors['new_vend'] as $errors): ?>
	            <li><?php echo $errors ?></li>
	        <?php endforeach; ?>
	        </ul>
	    <?php endif; ?>                                      
        </p>       		
        
        <p class="bills_act" style="display:none">
        	<label style="width:130px">Year/Month: </label><select style="width:60px;" name="year"><?php for($i=2012; $i<=date("Y"); $i++){ $select=$i==date("Y") ? "selected='selected'" : ''; echo "<option $select value='".$i."'>".$i."</option>"; }?></select> 
        	/ <select style="width:50px;" name="month"><?php for($i=1; $i<=12; $i++){ $select=$i==date("n") ? "selected='selected'" : ''; echo "<option $select value='".$i."'>".$i."</option>"; }?></select>        	
	    <?php if(isset($this->formErrors['year'])): ?>
	        <ul class="error">
	        <?php foreach($this->formErrors['year'] as $errors): ?>
	            <li><?php echo $errors ?></li>
	        <?php endforeach; ?>
	        </ul>
	    <?php endif; ?>                            
	    <?php if(isset($this->formErrors['month'])): ?>
	        <ul class="error">
	        <?php foreach($this->formErrors['month'] as $errors): ?>
	            <li><?php echo $errors ?></li>
	        <?php endforeach; ?>
	        </ul>
	    <?php endif; ?>                                    	
        </p>       		
        
        <p>
            <label style="width:130px">By vendor id: </label>
            <input type="text" name="by_id" value="" />
	    <?php if(isset($this->formErrors['by_id'])): ?>
	        <ul class="error">
	        <?php foreach($this->formErrors['by_id'] as $errors): ?>
	            <li><?php echo $errors ?></li>
	        <?php endforeach; ?>
	        </ul>
	    <?php endif; ?>                                        
        </p>       		                
       
        <p>
            <label style="width:130px">By vendor email: </label>
            <input type="text" name="by_email" value="" />
	    <?php if(isset($this->formErrors['by_email'])): ?>
	        <ul class="error">
	        <?php foreach($this->formErrors['by_email'] as $errors): ?>
	            <li><?php echo $errors ?></li>
	        <?php endforeach; ?>
	        </ul>
	    <?php endif; ?>                                        
        </p>       		                
       
        <p>
            <label style="width:130px">By vendor name: </label>
            <input type="text" name="by_name" value="" />
	    <?php if(isset($this->formErrors['by_name'])): ?>
	        <ul class="error">
	        <?php foreach($this->formErrors['by_name'] as $errors): ?>
	            <li><?php echo $errors ?></li>
	        <?php endforeach; ?>
	        </ul>
	    <?php endif; ?>                                        
        </p>       		                
               
       <p><a onclick="document.getElementById('sub').click(); return false;" class="sendMasBtn link">Start</a></p>
       <input type="submit" style="display: none" id="sub" />
    </form>
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>