<style type="text/css">
    
     #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
</style>
<script type="text/javascript" charset="utf-8">
    
        var filterDeniedUser = 0; 
        
        $(document).ready(function() {            
                        
                oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/index/ajax-approved-date-user',
                        "fnServerParams": function ( aoData ) {aoData.push({ "name": "cofirmDate", "value": "<?php echo $this->cofirmDate; ?>" }, { "name": "filterDeniedUser", "value": filterDeniedUser } ); },
                        "fnDrawCallback": function( oSettings ) { display('none'); },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100,
                        "aoColumns": [ 
                            { 
                               "sTitle": "",
                               "fnRender": function(obj){ 
                            	   var res = null;
                            	   if(obj.aData[0]==1 && obj.aData[11]==3){
                            	   		res = '<input type="checkbox" style="width: 10px;" checked="checked" name="reg_AdExchage['+obj.aData[9]+']" value="1">';                            	   		
                            	   }else{
                            		   res = '<input type="checkbox" style="width: 10px;" name="reg_AdExchage['+obj.aData[9]+']" value="1">';
                            	   }                           	
                            	   res += '<input type="hidden" name="PubID['+obj.aData[9]+']" value="'+obj.aData[9]+'">';
                                   return res } 
                            },                        
                            { 
                              "sTitle": "AdX Network Name",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Company",
                              "bVisible": false,
                              "fnRender": function(obj){ return obj.aData[2]; } 
                            },
                            { 
                              "sTitle": "Email",
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[9]+'">'+obj.aData[3]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Sites",
                              "sClass": "siteDropDown",
                              "fnRender": function(obj){ 
                                  
                                  var res = '';
                                                                                                   
                                  if(obj.aData[4]){                                      
                                  
                                      res = '<select id="siteItem_'+obj.aData[10]+'" style="width: auto;">';
                                      var arr = obj.aData[4].split(/[,]/);
                                      
                                      $.each(arr, function(key, iter){

                                          var value = iter.split(/[:]/);

                                          res += '<option value="'+value[0]+'">'+value[1]+'</option>';

                                      });
                                  
                                           res += '</select><a href="#" onClick="goToSite('+obj.aData[10]+')" class="sendMasBtn goSite" style="width: auto;">Go</a>'; 
                                  } else { res += obj.aData[12]; }
                                           
                                  return res; } 

                            },
                            { 
                                "sTitle": "Revenue Today",
                                "fnRender": function(obj)
                                {
                                    if(obj.aData[5] != null) return parseFloat(obj.aData[5]).toFixed(2);
                                                         else return 0;
	                        } 
                            },  
                            { 
                                "sTitle": "Revenue Yesterday",
                                "fnRender": function(obj)
                                {
                                    if(obj.aData[6] != null) return parseFloat(obj.aData[6]).toFixed(2);
                                                         else return 0;
	                        } 
                            },  
                            { 
                              "sTitle": "Created",
                              "fnRender": function(obj){ return $.format.date(new Date(obj.aData[7]), "yyyy MMM, dd"); } 
                            },
                            { 
                              "sTitle": "Wire Transfer",
                              "sClass": "wire_status",
                              "bSortable": false,
                              "fnRender": function(obj){ 
                                  
                                  if(parseInt(obj.aData[8])) return '<img id="wire_'+obj.aData[9]+'" onClick="disableWire('+obj.aData[9]+')" src="/images/status-green-check.gif"/>';
                                  else                       return '<img id="wire_'+obj.aData[9]+'" onClick="enableWire('+obj.aData[9]+')" src="/images/stats-red-x.gif"/>';       } 
                            },
                            { 
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[9]+'">View</a>'; } 
                            },
                            { 
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[10]+'" target="_blank">Login</a>'; } 
                            }
                            
                            ], 
                      
                        "aaSorting": [[ 7, "desc" ]]
                });
          
                $('#user_denied').change(function(){ filterDeniedUser = ($('#user_denied:checked').val() ? 1 : 0); oTable.fnClearTable(); display('block'); });          

        });
        
        function goToSite(id)
        { 
            var site = $('#siteItem_'+id+' option:selected').val();
            
            if(site){
                location.href = '/administrator/sites/view/id/'+site;
            }else{
                return false;
            }
        }
        
        function loginUser(id)
        {
            window.open('/administrator/index/auth/id/'+id, '_blank');
        }
        
        function enableWire(userId)
        {
            $('#wire_'+userId).html('loading');
            
            $.ajax({ url : '/administrator/ajax/index',
                       data : { id : userId, wire : 1 },
                       type : "POST",
                       dataType : "json",

             success : function(response) { console.log(response.result);

                   if(response.result.status){ 
                       
                       $('#wire_'+userId).attr({src: '/images/status-green-check.gif'}); 
                       $('#wire_'+userId).attr({onClick: 'disableWire('+userId+')'}); 
                   
               } else { /*$('#wire_'+userId).html('not found');*/ }

               },
               
             error : function(){ /*$('#wire_'+userId).html('error');*/ alert('ajax error'); }
            });

        }
        
        function disableWire(userId)
        {
            $.ajax({ url : '/administrator/ajax/index',
                       data : { id : userId, wire : 0 },
                       type : "POST",
                       dataType : "json",

             success : function(response) { console.log(response.result);

                   if(response.result.status){ 
                       
                       $('#wire_'+userId).attr({src: '/images/stats-red-x.gif'}); 
                       $('#wire_'+userId).attr({onClick: 'enableWire('+userId+')'}); 
                   
                   } else { /*$('#wire_'+userId).html('not found');*/ }

               },
               
             error : function(){ /*$('#wire_'+userId).html('error');*/ alert('ajax error'); }
            });
        }
                
        function display(status)
        {
            $('#mask').css('display', status);
            $('#loading').css('display', status);         
        }
        
</script>

    <h1>Who Was Approved</h1>
<div class="contUsL" style="width: 750px;">
<br />
   
<p>    
    <input type="checkbox" name="user_denied" id="user_denied" value="1" style="background: none; height: 15px; width: 20px; margin-left: 3px;"/>
    <span style="font-size: 15px;">Show Denied Users</span>
</p>

<br />    
<form action="/administrator/index/updateaprovd/" method="post">
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
		    <th width="5%"></th>
                    <th width="30%">AdX Network Name</th>
                    <th width="10%">Company</th>
                    <th width="10%">Email</th>
                    <th width="20%">Sites</th>
                    <th width="10%">Revenue Today</th>
                    <th width="10%">Revenue Yesterday</th>
                    <th width="15%">Created</th>
                    <th width="5%">Wire Transfer</th>
                    <th width="5%"></th>
                    <th width="5%"></th>
		</tr>
	</thead>
        
	<tbody></tbody>
        
	<tfoot>
		<tr>
		    <th></th>
                    <th>AdX Network Name</th>
                    <th>Company</th>
                    <th>Email</th>
                    <th>Sites</th>
                    <th>Revenue Today</th>
                    <th>Revenue Yesterday</th>
                    <th>Created</th>
                    <th>Wire Transfer</th>
                    <th></th>
                    <th></th>
		</tr>
	</tfoot>
</table>
<br><br>
<p>
<a class="sendMasBtn" style="float: left; cursor: pointer;" onclick="document.getElementById('subForm').click(); return false;" title="">Update</a>
</p>
<input type="hidden" name="redirect" value="<?php echo $_SERVER["REQUEST_URI"]; ?>"/>
<input id="subForm" type="submit" style="display: none;"/>
</form>
</div>    
    
<div id="mask"></div>
<div id="loading"><span>processing...</span></div>
    
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
