<script type="text/javascript" src="/js/jquery.fileDownload.js"></script>

<style type="text/css">
    
     #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
    #dialog-form
    {
    	font-size: 16px;
    	font-weight: bold;
    	z-index: 999999999;
    }
    
    #dialog-form textarea
    {
	    resize: none;
	    width: 305px;
    }
    
    #optimization_value
    {
    	position: relative;
    	width: 300px;
    	z-index: 999999999;
    }
    
    #csv_all
    {
    	position: relative;
    	width: 24px;
    	height: 24px;
    	cursor: pointer;
    	float: right;
    	top: 60px;
    	background-image: url(/images/csv-24.gif);
    	z-index: 100;
    }
    .emptyPadding{ padding: 0px !important; }
    
</style>
<script type="text/javascript" charset="utf-8">
		
        var oTable = new Object();        
                
        $(document).ready(function() {
            
                var filterNeverLive = $('#never_live:checked').val() ? 1 : 0;
                                      
                oTable = $('#site-approve').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/index/ajax-approve-live',
                        "fnServerParams": function ( aoData ) {aoData.push( { "name" : "data-live", "value" : '<?php echo $this->dateLive; ?>' }, { "name" : "never-live", "value" : filterNeverLive } ); },
                        "fnDrawCallback": function( oSettings ) { display('none'); },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100,
                     
                        "aoColumns": [
                            { 
                              "sTitle": "PID",
                              "sClass": "emptyPadding",
                              "fnRender": function(obj){ var result = '<span style="display: block; padding: 4px 8px; font-size: 12px;">'+obj.aData[0]+'</span>';
                                                         var adxStatus = parseInt(obj.aData[20]);
                                                         
                                       if(adxStatus == 1 || 
                                          adxStatus == 4){ result = '<span style="background: #FFA301; display: block; padding: 4px 8px; font-size: 12px;">'+obj.aData[0]+'</span>'; }
                                  else if(adxStatus == 2){ result = '<span style="background: #F20300; display: block; padding: 4px 8px; font-size: 12px;">'+obj.aData[0]+'</span>'; }
                                  
                                  return result ; } 
                            },
                            { 
                              "sTitle": "SID",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Website",
                              "fnRender": function(obj){ return '<a href="/administrator/sites/view/id/'+obj.aData[1]+'">'+obj.aData[2]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Contact",
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[19]+'">'+obj.aData[3]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Impres yesterday",
                              "fnRender": function(obj){ return obj.aData[4]; } 
                            },
                            { 
                              "sTitle": "Impres 2day ago",
                              "fnRender": function(obj){ return obj.aData[5]; } 
                            },
                            { 
                              "sTitle": "Impres change",
                              "fnRender": function(obj){ var percent = 0; if(obj.aData[6]) percent = obj.aData[6]; return percent+'%'; } 
                            },
                            { 
                              "sTitle": "Denied Impres Yesterday",
                              "fnRender": function(obj){ return '<a style="cursor: pointer" onClick="showNotApproved('+obj.aData[1]+')">'+obj.aData[7]+'</a>'; } 
                            },
                            { 
                              "sTitle": "Impres avg 7day",
                              "fnRender": function(obj){ return obj.aData[8]; } 
                            },
                            { 
                                "sTitle": "Revenue",
                                "fnRender": function(obj)
                                {
                                    if(obj.aData[9] != null)
					return parseFloat(obj.aData[9]).toFixed(2);
                                    else
                                        return 0;
	                             } 
                            },                            
                            { 
                              "sTitle": "Alexa rank",
                              "fnRender": function(obj){ return obj.aData[10]; } 
                            },
                            { 
                              "sTitle": "Top Alexa Country",
                              "fnRender": function(obj){ return obj.aData[11]; } 
                            },                            
                            { 
                              "sTitle": "Live",
                              "fnRender": function(obj){ 
                                  if(obj.aData[12]){ return  '<img src="/images/status-green-check.gif">'; }
                                  else             { return  '<img src="/images/stats-red-x.gif">';    } 
                                  
                                  }
                                                        
                            },
                            { 
                              "sTitle": "DFP",
                              "bSortable": false,
                              "fnRender": function(obj){  
                                  
                                  if(obj.aData[14] == 4) return '<a href="/administrator/tags/edit/tag/'+obj.aData[18]+'/site/'+obj.aData[1]+'/user/'+obj.aData[20]+'"><img src="/images/status-green-check.gif"></a>';
                                  else                   return '<a href="/administrator/tags/edit/tag/'+obj.aData[18]+'/site/'+obj.aData[1]+'/user/'+obj.aData[20]+'"><img src="/images/stats-red-x.gif"></a>';    }  
                                                 
                            },
                            { 
                              "sTitle": "Login",
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[20]+'" target="_blank">Login</a>'; } 
                            },
                            { 
                              "sTitle": "CSV",
                              "sClass": "csv",
                              "bSortable": false,
                              "fnRender": function(obj){ return '<div id="csv_'+obj.aData[1]+'"><a onClick="getCsv('+obj.aData[1]+')">create</a></div>'; obj.aData[20]; }
                            }
                        ],                                                
                        "aaSorting": [[ 13, "desc" ]]
                         
                } );
                
                $('#never_live').change(function(){ filterNeverLive = ($('#never_live:checked').val() ? 1 : 0); oTable.fnClearTable(); display('block'); });
                
                
        } );
  

function getCsv(id){
    
    $('#csv_'+id).html('loading...');
    
    $.ajax({ url : '/administrator/ajax/csv',
                       data : { id : id },
                       type : "POST",
                       dataType : "json",

             success : function(response) { 

                   if(response.result.status){ 

                      $('#csv_'+id).html('<a href="'+response.result.file+'">download</a>');

                   } else { 
                   
                      $('#csv_'+id).html('not found');
                   
                   }

               },
               
             error : function(){ $('#csv_'+id).html('error'); }
     });
    
}

function loginUser(id){ 

    location.href='/administrator/index/auth/id/'+id;
    
}

function showNotApproved(siteID){
    
    $.fancybox({
            'width'	: '75%',
            'height'	: '75%',
            'href'      : '/administrator/url/index/id/'+siteID,
            'autoScale'    	: false,
            'transitionIn'	: 'none',
            'transitionOut'	: 'none',
            'type'		: 'iframe'
    }); 
}

function display(status)
{
    $('#mask').css('display', status);
    $('#loading').css('display', status);         
}

function setOrangeStatus(id)
{
    $.fancybox({
            'width' : '75%',
            'height': '75%',
            'href'  : '/administrator/sites/mail-ever-live/id/'+id,
            'autoScale'     : false,
            'transitionIn'  : 'none',
            'transitionOut' : 'none',
            'type'	    : 'iframe',
            'onClosed'      : function(){ oTable.fnClearTable(); display('block'); }
    });    
}

</script>

<h1>Who Went Live</h1>
<div class="contUsL" style="width: 750px;">

<br /><br />
    <p>
        <input type="checkbox" name="never_live" id="never_live" value="1" checked style="background: none; height: 15px; width: 20px; margin-left: 3px;"/>
        <span style="font-size: 15px;">Show sites who never went live</span>
    </p>
<br />
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="site-approve">
	<thead>
		<tr>
                    <th width="5%">PID</th>
                    <th width="5%">SID</th>
                    <th width="20%">Website</th>
                    <th width="20%">Contact</th>
                    <th width="10%">Impres yesterday</th>
                    <th width="10%">Impres 2day ago</th>
                    <th width="10%">Impres change</th>
                    <th width="10%">Denied Impres Yesterday</th>
                    <th width="10%">Impres Avg 7day</th>
                    <th width="10%">Revenue</th>
                    <th width="10%">Alexa rank</th>
                    <th width="10%">Top Alexa Country</th>
                    <th width="10%">Live</th>
                    <th width="10%">DFP</th>                   
                    <th width="10%">Login</th>
                    <th width="20%">CSV</th>
		</tr>
	</thead>
	<tbody></tbody>
	<tfoot>
		<tr>
                    <th>PID</th>
                    <th>SID</th>
                    <th>Website</th>
                    <th>Contact</th>
                    <th>Impres yesterday</th>
                    <th>Impres 2day ago</th>
                    <th>Impres change</th>
                    <th>Denied Impres Yesterday</th>
                    <th>Impres Avg 7day</th>
                    <th>Revenue</th>
                    <th>Alexa rank</th>
                    <th>Top Alexa Country</th>
                    <th>Live</th>
                    <th>DFP</th>               
                    <th>Login</th>
                    <th>CSV</th>                    
		</tr>
	</tfoot>
</table>
</div> 

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
