<style type="text/css">

    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }

    #loading{
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }

    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px;
    }

    #dialog-form
    {
        font-size: 16px;
        font-weight: bold;
        z-index: 999999999;
    }

    #dialog-form textarea
    {
        resize: none;
        width: 305px;
    }

    #optimization_value
    {
        position: relative;
        width: 300px;
        z-index: 999999999;
    }

    #csv_all
    {
        position: relative;
        width: 24px;
        height: 24px;
        cursor: pointer;
        float: left;
        top: 21px;
        left: 308px;
        background-image: url(/images/csv-24.gif);
        z-index: 100;
    }
    #dsp_all
    {
        position: relative;
        width: 24px;
        height: 24px;
        cursor: pointer;
        float: left;
        top: 21px;
        left: 308px;
        background-image: url(/images/dsp-24.png);
        z-index: 100;
    }
    .emptyPadding{ padding: 0px !important; }
    #block_prev_live{ display: none; margin-top: 10px; float: left; }
    .itemEcpm{ cursor: pointer; }

    #users_wrapper{ top: -25px; }
    #users_filter{ float: left; }
    #tableScroll{
        width: 1300px;
        overflow-y: auto;
        margin-top: 20px;
        float: left;
        resize: horizontal;
    }

    /*#tableRotate, #tableScroll{
        transform:rotateX(180deg);
        -ms-transform:rotateX(180deg);
        -webkit-transform:rotateX(180deg);
    }*/


</style>

<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.js"></script>
<script type="text/javascript" charset="utf-8">
		var oTable = new Object();
        $(document).ready(function() { 
                <?php if($this->dataAuth->role == 'super'):?>
                    var accounts = $('#accounts').val();
                <?php else:?>
                    var accounts = <?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>;
                <?php endif;?> 
                    var userSite = $('#user-site').val();
                
                var oTable = $('#users').dataTable( {
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/index/ajax-approved',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "accounts", "value": accounts }, { "name": "usersite", "value": userSite } ); },
                        "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                        "iDisplayLength": 100,
                        "aoColumns": [ 
                            { 
                               "sTitle": "",
                               "fnRender": function(obj){ 
                            	   var res = null;
                            	   if(obj.aData[0]==1){
                            	   		res = '<input type="checkbox" style="width: 10px;" checked="checked" name="reg_AdExchage['+obj.aData[10]+']" value="1">';
                            	   }else{
                            		   res = '<input type="checkbox" style="width: 10px;" name="reg_AdExchage['+obj.aData[10]+']" value="1">';
                            	   }                           	
                            	   res += '<input type="hidden" name="PubID['+obj.aData[10]+']" value="'+obj.aData[10]+'">';
                                   return res } 
                            },                        
                            { 
                              "sTitle": "Name",
                              "fnRender": function(obj){ return obj.aData[1]; } 
                            },
                            { 
                              "sTitle": "Company",
                              "fnRender": function(obj){ return obj.aData[2]; } 
                            },
                            { 
                              "sTitle": "Email",
                              "fnRender": function(obj){ return obj.aData[3]; } 
                            },
                            { 
                              "sTitle": "Sites",
                              "sClass": "siteDropDown",
                              "fnRender": function(obj){ 
                                  
                                  var res = null;
                                  
                                  if(obj.aData[4]){
                                  
                                      var arr = obj.aData[4].split(/[,]/);

                                      res = '<select id="siteItem_'+obj.aData[10]+'" style="width: auto;">';

                                      $.each(arr, function(key, iter){

                                          var value = iter.split(/[:]/);

                                          res += '<option value="'+value[0]+'">'+value[1]+'</option>';

                                      });

                                      res += '</select><a href="#" onClick="goToSite('+obj.aData[10]+')" class="sendMasBtn goSite" style="width: auto;">Go</a>';
                                  }   
                                  return res; } 

                            },
                            {
                                "sTitle": "Revenue Today",
                                "fnRender": function(obj)
                                {
                                    if(obj.aData[5] != null) return parseFloat(obj.aData[5]).toFixed(2);
                                    else return 0;
                                }
                            },
                            {
                                "sTitle": "Revenue Yesterday",
                                "fnRender": function(obj)
                                {
                                    if(obj.aData[6] != null) return parseFloat(obj.aData[6]).toFixed(2);
                                    else return 0;
                                }
                            },
                            { 
                              "sTitle": "Created",
                              "fnRender": function(obj){ return $.format.date(new Date(obj.aData[7]), "yyyy MMM, dd"); }
                            },
                            { 
                              "sTitle": "Wire Transfer",
                              "sClass": "wire_status",
                              "bSortable": false,
                              "fnRender": function(obj){ 
                                  
                                  if(obj.aData[8]) return '<img id="wire_'+obj.aData[10]+'" onClick="disableWire('+obj.aData[10]+')" src="/images/status-green-check.gif"/>';
                                  else             return '<img id="wire_'+obj.aData[10]+'" onClick="enableWire('+obj.aData[10]+')" src="/images/stats-red-x.gif"/>';       }
                            },
                            { 
                              "sTitle": "30 Day Reachout?",
                              "sClass": "wire_status",
                              "bSortable": false,
                              "fnRender": function(obj){                                   
                                  if(parseInt(obj.aData[9]))
                                  	return '<img onClick="mailReachout('+obj.aData[10]+')" src="/images/status-green-check.gif"/>';
                                  else                       
                                  	return '<img onClick="mailReachout('+obj.aData[10]+')" src="/images/stats-red-x.gif"/>';
                              } 
                            },                                                        
                            { 
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/view/id/'+obj.aData[10]+'">View</a>'; }
                            },
                            { 
                              "bSortable": false,
                              "fnRender": function(obj){ return '<a href="/administrator/index/auth/id/'+obj.aData[11]+'" target="_blank">Login</a>'; }
                            }
                            
                            ], 
                      
                        "aaSorting": [[ 7, "desc" ]]
                } );
                
                $('#accounts').change(function(){ accounts = $('#accounts').val(); oTable.fnClearTable(); });
                $('#user-site').change(function(){ userSite = $('#user-site').val(); oTable.fnClearTable(); });
        } );
        
        function goToSite(id)
        { 
            var site = $('#siteItem_'+id+' option:selected').val();
            
            if(site){
                location.href = '/administrator/sites/view/id/'+site;
            }else{
                return false;
            }
        }
        
        function loginUser(id)
        {
            //location.href='/administrator/index/auth/id/'+id;
            window.open('/administrator/index/auth/id/'+id, '_blank');
        }
        
        function enableWire(userId)
        {
            $('#wire_'+userId).html('loading');
            
            $.ajax({ url : '/administrator/ajax/index',
                       data : { id : userId, wire : 1 },
                       type : "POST",
                       dataType : "json",

             success : function(response) { console.log(response.result);

                   if(response.result.status){ 
                       
                       $('#wire_'+userId).attr({src: '/images/status-green-check.gif'}); 
                       $('#wire_'+userId).attr({onClick: 'disableWire('+userId+')'}); 
                   
               } else { /*$('#wire_'+userId).html('not found');*/ }

               },
               
             error : function(){ /*$('#wire_'+userId).html('error');*/ alert('ajax error'); }
            });

        }
        
        function disableWire(userId)
        {
            $.ajax({ url : '/administrator/ajax/index',
                       data : { id : userId, wire : 0 },
                       type : "POST",
                       dataType : "json",

             success : function(response) { console.log(response.result);

                   if(response.result.status){ 
                       
                       $('#wire_'+userId).attr({src: '/images/stats-red-x.gif'}); 
                       $('#wire_'+userId).attr({onClick: 'enableWire('+userId+')'}); 
                   
                   } else { /*$('#wire_'+userId).html('not found');*/ }

               },
               
             error : function(){ /*$('#wire_'+userId).html('error');*/ alert('ajax error'); }
            });
        }
        
        function mailReachout(PubID)
        {
            $.fancybox({
                'width'	: '75%',
                'height'	: '75%',
                'href'          : '/administrator/index/reachout/PubID/'+PubID,
                'autoScale'    	: false,
                'transitionIn'	: 'none',
                'transitionOut'	: 'none',
                'type'		: 'iframe',
                'onClosed'      : function(){ oTable.fnClearTable(); }
            }); 
        }        
</script>

    <h1>Approved Users</h1>
<div class="contUsL" style="width: 750px;">
<p>
    <select id="accounts">
    <?php if($this->dataAuth->role == 'super'):?>
        <option value="-1">All</option>
        <?php foreach($this->contactManager as $iter):?>
             <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
        <?php endforeach;?>
    <?php else: ?>
        <option value="<?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>">Show My Accounts</option>                 
        <option value="-1">Show All Accounts</option>
    <?php endif;?>    
    </select>   
    
    <select name="user-site" id="user-site" style="margin-left: 75px;">
        <option value="have-site">Show Users (that have sites)</option>
        <option value="not-have-site">Show Users (that do not have sites)</option>
    </select>
</p>
    <div id="tableScroll">
        <div id="tableRotate">

<form action="/administrator/index/updateaprovd/" method="post">
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="users">
	<thead>
		<tr>
					<th width="5%"></th>
                    <th width="25%">Name</th>
                    <th width="10%">Company</th>
                    <th width="10%">Email</th>
                    <th width="20%">Sites</th>
                    <th width="20%">Revenue Today</th>
                    <th width="20%">Revenue Yesterday</th>
                    <th width="20%">Created</th>
                    <th width="5%">Wire Transfer</th>
                    <th width="5%">30 Day Reachout?</th>
                    <th width="5%"></th>
                    <th width="5%"></th>
		</tr>
	</thead>
        
	<tbody></tbody>
        
	<tfoot>
		<tr>
					<th></th>
                    <th>Name</th>
                    <th>Company</th>
                    <th>Email</th>
                    <th>Sites</th>
                    <th>Revenue Today</th>
                    <th>Revenue Yesterday</th>
                    <th>Created</th>
                    <th>Wire Transfer</th>
                    <th>30 Day Reachout?</th>
                    <th></th>
                    <th></th>
		</tr>
	</tfoot>
</table>
<br><br>
<p>
<a class="sendMasBtn" style="float: left" onclick="document.getElementById('subForm').click(); return false;" title="" href="#">Update</a>
</p>
<input id="subForm" type="submit" style="display: none;">
</form>
</div>
    </div>
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
