<style type="text/css">
    
    #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
</style>    
<script type="text/javascript">

    var filterStatus = null;
    var filterAccounts = null;
    var oTable = null;
    var PubID = 0;

    $(document).ready(function() {        
                    
            filterStatus = $('#filter-status').val();        
            filterAccounts = $('#accounts').val();        
                    
            oTable = $('#tablePsaUrl').dataTable( {
                        "bFilter": true,
                        "bProcessing": true,
                        "bServerSide": true,
                        "sAjaxSource": '/administrator/index/denied',
                        "fnServerParams": function ( aoData ) {  aoData.push( { "name": "PubID", "value": PubID }, { "name": "filterStatus", "value": filterStatus }, { "name": "filterAccounts", "value": filterAccounts } ); },
                        "iDisplayLength": 100,
                        "bLengthChange": true,
                        "bPaginate": true,
                        "aoColumns": [
                            { 
                              "sTitle": "PubID",
                              "fnRender": function(obj){ return obj.aData[0]; }
                            }, 
                            { 
                              "sTitle": "SiteID",
                              "fnRender": function(obj){ return obj.aData[1]; }
                            }, 
                            { 
                              "sTitle": "Domain",
                              "fnRender": function(obj){ return obj.aData[2]; }
                            }, 
                            { 
                              "sTitle": "Impressions",
                              "fnRender": function(obj){ return obj.aData[3]; }
                            }, 
                            { 
                              "sTitle": "Ad Tag",
                              "fnRender": function(obj){ return obj.aData[4] ? '<a href="/administrator/sites/view/id/'+obj.aData[10]+'">'+obj.aData[4]+'</a>' : ''; }
                            },
                            { 
                              "sTitle": "SiteURL",
                              "sClass": "table-link",
                              "fnRender": function(obj){ return '<img src="/images/details_open.png">'; } 
                            },
                            {
                               "sTitle": "Status", 
                               "fnRender": function(obj){ 
                                   
                                    var result = 'none';

                                    switch(obj.aData[6]){
                                      case '0': result = '<span style="color: black;">Pending</span>'; break;
                                      case '1': result = '<span style="color: green;">Approved</span>'; break;
                                      case '2': result = '<span style="color: red;">Denied</span>'; break;    
                                    }
                                    return result;                          
                                }
                            },
                            {
                               "sTitle": "Approved", 
                               "bSortable": false,
                               "fnRender": function(obj){  var result = '';
                                   if(obj.aData[13]==4){
                                                           switch(obj.aData[7]){
                                                             case '0' : result = '<a style="cursor: pointer; color: blue;" onClick="ajaxStatusGam(1, \''+obj.aData[12]+'\', '+obj.aData[10]+')">Approve</a>'; break;
                                                             case '1' : result = '<a>Approved</a>'; break;
                                                             case '2' : result = '<a style="cursor: pointer; color: blue;" onClick="ajaxStatusGam(1, \''+obj.aData[12]+'\', '+obj.aData[10]+')">Approve</a>'; break;
                                                           }                                                                           
                                                           return result;                
	                                   
                                   }else{
                                                           switch(obj.aData[7]){
                                                             case '0' : result = '<a style="cursor: pointer; color: blue;" onClick="ajaxStatus(1, \''+obj.aData[12]+'\', '+obj.aData[10]+')">Approve</a>'; break;
                                                             case '1' : result = '<a>Approved</a>'; break;
                                                             case '2' : result = '<a style="cursor: pointer; color: blue;" onClick="ajaxStatus(1, \''+obj.aData[12]+'\', '+obj.aData[10]+')">Approve</a>'; break;
                                                           }                                                                           
                                                           return result;                
	                                   
                                   }
                                                        }
                            },
                            {
                                "sTitle": "Deny",
                                "bSortable": false,
                                "fnRender": function(obj){  var result = ''; 
                                    
                                                            switch(obj.aData[8]){
                                                                case '0' : result = '<a style="cursor: pointer; color: blue;" onClick="ajaxStatus(2, \''+obj.aData[12]+'\', '+obj.aData[10]+')">Deny</a>'; break;
                                                                case '1' : result = '<a style="cursor: pointer; color: blue;" onClick="ajaxStatus(2, \''+obj.aData[12]+'\', '+obj.aData[10]+')">Deny</a>'; break;
                                                                case '2' : result = '<a>Denied</a>'; break; 
                                                            }                                                                            
                                                            return result;                
                                                         }
                            },
                            { 
                              "sTitle": "Last Attempt",
                              "fnRender": function(obj){ var date = new Date(obj.aData[9]);
                                                             date.setDate(date.getUTCDate());
                                             return $.format.date(date, "yyyy MMM, dd"); }
                            },
                            
                        ],                                                
                        "aaSorting": [[ 9, "desc" ]],
                        "fnDrawCallback": function(oSettings){ $("#url tbody td img").click(); display('none'); }     
            });
            
            /*$('#sites').change(function(){ SiteID = $('#sites').val(); oTable2.fnClearTable();  });*/
            
            $('#tablePsaUrl tbody td img').live('click', function(){
                
                    var nTr = $(this).parents('tr')[0];     
                    if ( oTable.fnIsOpen(nTr) )
                    {
                        /* This row is already open - close it */
                        this.src = "/images/details_open.png";
                        oTable.fnClose( nTr );
                    }
                    else
                    {
                        /* Open this row */
                        this.src = "/images/details_close.png";
                        var objTr = oTable.fnOpen( nTr, fnFormatDetails(oTable, nTr), 'details' );
                        objTr.setAttribute('class', nTr.className);
                        objTr.getElementBy
                    }
            }); 
            
            $( "#testUser" ).autocomplete({

                            close: function(event, ui){ $('#testUser').css('background', 'url("/images/inpBg.png") no-repeat scroll left top transparent'); },
                            open: function(event, ui){ $('input[name=user]').val(''); },
                            source: function( request, response ) {
                                
                                  $.getJSON( "/administrator/sites/get-ajax-user/", { term: extractLast( request.term ) }, response );
                            },
                            search: function(){
                                
                                $('#testUser').css('background', 'url("/images/ui-anim_basic_16x16.gif") no-repeat scroll right center white');  
                                var term = extractLast( this.value );                                              
                                if ( term.length < 2 ) { return false; }                                                          
                            },
                            focus: function(){ return false; },

                            select: function( event, ui ){     

                                this.value = '(PubID: '+ui.item.id+') '+ui.item.label;
                                $('#userSearch').val(ui.item.id); 
                                
                                   PubID = $('#userSearch').val();
                                if(PubID){ oTable.fnClearTable(); display('block'); }
                                
                                return false;
                            }
             });
             
             $("#testUser").keyup(function(){
                 
                 if($("#testUser").val() == '')
                 { 
                     PubID = 0; 
                     oTable.fnClearTable(); 
                     $('#testUser').css('background', 'url("/images/inpBg.png") no-repeat scroll left top transparent');
                     display('block'); 
                 }
                 
             });
             
             $('#filter-status').change(function(){ filterStatus = $('#filter-status').val(); oTable.fnClearTable(); display('block'); });
             $('#accounts').change(function(){ filterAccounts = $('#accounts').val(); oTable.fnClearTable(); display('block'); });
                       
     });
     
     function extractLast( term )
     {
        return split( term ).pop();
     }  
     function split( val ) 
     {
        return val.split( /,\s*/ );
     }
     
     function fnFormatDetails ( oTable, nTr )
     {
        var aData = oTable.fnGetData( nTr );
        var siteURL = aData[11];  
        var result = '';

            if(siteURL){

                var arrUrl = siteURL.split('\n');    

                    result += '<div class="url-holder">';

                    $.each(arrUrl ,function(key, url){
            

                        result += url+'<br />';
                             

                     }); result += '</div>';                 
             } 

        return result;
     }
     
     function ajaxStatus(status, url, SiteID)
     {
         if(status == 1){
                  
         if(confirm("Regenerate tags for this site ?")){ var regen = 1; }
                                                       else{ var regen = 0; }   
                                                   
         } else { var regen = 0; }
         
         display('block');
         
         $.ajax({ url : '/administrator/index/ajax-status-psaurl',
                     data : { status : status, url : url, SiteID : SiteID, regen : regen },
                     type : "POST",
                     async: false, /* java script wait ajax */
                     dataType : "json",

          success : function(response) { 
                 
               if(response.result)
               { 
                    if(response.message)
                    { 
                        display('none'); 
                        alert(response.message);
                        display('block'); 
                    }
                                    
                    oTable.fnClearTable(); 
                                    
               } else{ alert('please try again'); display('none'); }

          }, error : function(){ display('none'); alert('ajax request return error'); }});    
     }

     function ajaxStatusGam(status, url, SiteID)
     {
         if(status == 1){
         
         alert('This site is running AdX, please add the URL to AdX and Adsense now.');
         
         if(confirm("Regenerate tags for this site ?")){ var regen = 1; }
                                                       else{ var regen = 0; }   
                                                   
         } else { var regen = 0; }
         
         display('block');
         
         $.ajax({ url : '/administrator/index/ajax-status-psaurl',
                     data : { status : status, url : url, SiteID : SiteID, regen : regen },
                     type : "POST",
                     async: false, /* java script wait ajax */
                     dataType : "json",

          success : function(response) { 
                 
               if(response.result)
               { 
                    if(response.message)
                    { 
                        display('none'); 
                        alert(response.message);
                        display('block'); 
                    }
                                    
                    oTable.fnClearTable(); 
                                    
               } else{ alert('please try again'); display('none'); }

          }, error : function(){ display('none'); alert('ajax request return error'); }});    
     }
    
     function display(status)
     {
        $('#mask').css('display', status);
        $('#loading').css('display', status);         
     }
    
</script>

<div class="contUsL" style="width: 850px;">
    
    <h1 class="applTitle">Denied URLs Report</h1>
    
    <br /><br />
    
    <div style="margin-bottom: 20px;">
       <select id="accounts">
           <?php if($this->dataAuth->role == 'super'):?>
               <option value="-1">All</option>
               <?php foreach($this->contactManager as $iter):?>
                    <option value="<?php echo $iter['id']?>"><?php echo $iter['mail'];?></option>
               <?php endforeach;?>
           <?php else: ?>
               <option value="<?php echo $this->manager['id'] ? $this->manager['id'] : -1; ?>">Show My Accounts</option>                 
               <option value="-1">Show All Accounts</option>
           <?php endif;?>    
       </select>
    </div>
    <div style="display: block;">
       <div class="ui-widget" style="float: left;">
           <input type="text" name="testUser" id="testUser" value="" placeholder="Filter User by Email or Name" />
           <input type="hidden" name="user" id="userSearch" value=""/>
       </div>
    
       <select style="float: left; margin-left: 127px;" id="filter-status">
            <option value="all">Show All Status</option>
            <option value="0" selected>Pending</option>
            <option value="1">Approved</option>
            <option value="2">Denied</option>
       </select>   
   </div>    
        
    <table width="840px" cellpadding="0" cellspacing="0" border="0" class="display" id="tablePsaUrl">
        <thead>
            <tr>			
                <th width="3%">PubID</th>
                <th width="3%">SiteID</th>
                <th width="30%">Domain</th>			
                <th width="15%">Impressions</th>
                <th width="20%">Ad Tag</th>
                <th width="10%">SiteURL</th>
                <th width="5%"></th>
                <th width="5%"></th>
                <th width="5%"></th>
                <th width="10%">Last Attempt</th>                
            </tr>																    
        </thead>
        <tbody></tbody>
        <tfoot>
            <tr>
                <th>PubID</th>
                <th>SiteID</th>
                <th>Domain</th>			
                <th>Impressions</th>
                <th>Ad Tag</th>
                <th>Site URL</th>
                <th></th>
                <th></th>
                <th></th>
                <th>Last Attempt</th>                
            </tr>
        </tfoot>
    </table>
    
</div>

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>

