
<style type="text/css">
    
    
    #main{ display: block; width: 1300px; float: left; padding: 10px; }
    
    #main #left{ display: block; float: left; width: 700px; }
    #main #right{ display: block; float: left; width: 530px; margin-left: 15px; overflow: scroll; height: 549px; overflow-x: hidden; border: 1px solid #D3D3D3; padding-top: 4px; padding-left: 4px; }
    
    #right .itemMail{ display: block; float: left; width: 510px; }
    .itemMail .itemHead{ float: left; background: #D3D3D3; padding: 1px 5px 2px; width: 500px; }
    .itemMail .itemDate{ display: block; float: right; width: 150px; text-align: right; }
    .itemMail .itemAuthor{ display: block; float: left; width: 320px; }
    .itemMail .itemSubject{ display: block; float: left; width: 500px; padding: 0px 4px 0px 4px; border: 1px solid #D3D3D3; margin: 0px 0px 2px 0px; }
    .itemMail .itemText{ display: block; float: left; width: 500px; padding: 0px 4px 0px 4px; border: 1px solid #D3D3D3; margin: 2px 0px 7px 0px; }    

    #main #label-subject{ float: left; width: 100px; }
    #main #subject { float: left; width: 696px; margin-bottom: 2px; padding-left: 5px; }
    
    #main #label-text{ float: left; width: 100px; margin-top: 7px; }
    #main #text { float: left; width: 600px; height: 300px; margin-top: 7px; }
    

	#main #reach_out {
	    background-color: #8e8e8e;
	    color: #ffffff;
	    cursor: pointer;
	    display: block;
	    float: left;
	    font-size: 16px;
	    height: 28px;
	    margin-left: 167px;
		position: relative;
		top: 7px;
	    width: 329px;
	}
	
    #main #reach_out:hover{ background-color: #DC2323; }
    #main #reach_out span{ float: left; margin: 4px 0px 0px 46px; } 

    #main #mySubmit{ display: block; float: left; height: 28px; width: 129px; font-size: 16px; background-color: #8E8E8E; color: #FFFFFF; cursor: pointer; top: -20px; position: relative; margin-left: 567px; }
    #main #mySubmit:hover{ background-color: #DC2323; }
    #main #mySubmit span{ float: left; margin: 4px 0px 0px 46px; } 
    
    #radioStatus{ display: block; margin-left: 100px; margin-bottom: 5px; border: 1px solid #DBDFE6; padding-bottom: 2px; padding-top: 2px; }
    #radioStatus span{ margin-right: 10px; } 
    
    #messageActiveUser{ display: block; font-weight: 600; font-size: 16px;  margin-bottom: 20px; margin-left: 100px; }
    #cke_text{ margin-left: 0px; margin-top: 5px; }
    
    .error{ color: #CF2B2B; font-weight: 600; font-size: 16px; display: block; }
    
</style>

<script type="text/javascript" src="/js/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/js/ckeditor/adapters/jquery.js"></script>

<script type="text/javascript">

  $(document).ready(function(){
    
      $('#mySubmit').click(function(){
		  $("#mark_reach_out").val(0);
          if(validation()){ $('#main form').submit(); }
      });

	  $('#reach_out').click(function(){
    	  $("#mark_reach_out").val(1);
          $('#main form').submit();
      });
      
      $('#text').ckeditor(function() {}, { 
                toolbar : [   [ 'Source','-','Save','NewPage','DocProps','Preview','Print','-','Templates' ],
                              [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ],
                              [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ],
                              [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ],
                              [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat','-','Blockquote','CreateDiv','-','BidiLtr','BidiRtl','-','Link','Unlink','Anchor' ],
                              [ 'NumberedList','BulletedList','-','Outdent','Indent','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock', 'Styles','Format','Font','FontSize','-','TextColor','BGColor' ],
                              [ 'Image','Flash','Table','HorizontalRule','Smiley','SpecialChar','PageBreak','Iframe' ]],
                width : '685px',
                height : '300px',
                language : 'en',
                enterMode : CKEDITOR.ENTER_BR,
                filebrowserBrowseUrl : '/js/ckfinder/ckfinder.html',
                filebrowserImageBrowseUrl : '/js/ckfinder/ckfinder.html?type=Images',
                filebrowserFlashBrowseUrl : '/js/ckfinder/ckfinder.html?type=Flash',
                filebrowserUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Files',
                filebrowserImageUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Images',
                filebrowserFlashUploadUrl : '/js/ckfinder/core/connector/php/connector.php?command=QuickUpload&type=Flash'
      });
            
  });
  
  function validation()
  {
      var valid = true;
      
      $('.error').replaceWith('');
      
      if(!$('#subject').val()){ $("<div class='error'>Field is required</div>").insertAfter("#subject"); valid = false; }
      
      var textEditor = $('#text').ckeditorGet();
      if(!textEditor.checkDirty()){ $("<div class='error'>Field is required</div>").insertAfter("#cke_text"); valid = false; }   
      
      return valid;
  }
 

</script>

<div id="main">    
    <div id="left">

        <form method="post" action="" enctype="multipart/form-data">            
           
            <div id="form-field">
                
                <div style="padding-bottom: 5px; padding-left: 5px;">
                    <span style="">From (Account Manager):</span>
                    <select name="accountManager" id="accountManager" style="width: 200px; margin-left: 10px;">
                        <?php foreach($this->contactManager as $iter):?>
                              <option value="<?php echo $iter['id']?>" <?php echo $iter['id'] == $this->dataUser['account_manager_id'] ? 'selected' : '';?>><?php echo $iter['name']?></option>
                        <?php endforeach;?>
                    </select>
                </div>
                
                <input type="text" name="subject" id="subject" value="" placeholder="Enter Subject"/>
                <div style="clear: both"></div>            

                <textarea name="text" id="text"></textarea>            
            </div>
                     
            <input type="hidden" id="mark_reach_out" name="mark_reach_out" value="0"/>
            <div style="clear: both"></div>
            <a id="reach_out"><span>Mark as "Reached Out" & Don't Email</span></a>
            <a id="mySubmit"><span>Submit</span></a>

        </form>
        
    </div>
    <div id="right">
        
        <?php foreach($this->data as $iter):?>
        
        <div class="itemMail">   
            <div class="itemHead">
                <div class="itemAuthor">sent by: <?php echo /*$iter['admin_name'].' / '.*/$iter['author']; ?></div>
                <div class="itemDate"><?php echo date('M j, Y', strtotime($iter['created'])); ?></div>
            </div>
            <?php if(strlen($iter['subject'])):?>            
            	<div class="itemSubject"><?php echo $iter['subject']; ?></div>
            <?php endif;?>
            <div class="itemText"><?php echo $iter['text']; ?></div>            
        </div>
        
        <?php endforeach;?>
        
    </div>    
</div>

<?php if(!empty($this->message)):?>
<?php echo $this->message;?>
<?php endif; ?>