<style type="text/css">  

    
</style>
<script type="text/javascript">       
        
        jQuery(document).ready(function(){
              
             $('#table_view').dataTable({
                 "bProcessing": true,
                 "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                 "iDisplayLength": -1,
                 "aoColumns": [
                     null,
                     null,
                     null,
                     null,
                     null                
                 ],
                  "aaSorting": [[ 2, "asc" ]]
             });

        });
        
</script>

<h1>Total Live Sites</h1>
<div class="contUsL" style="width: 750px;">

        <table width="700px" cellpadding="0" cellspacing="0" border="0" class="display" id="table_view">
            <thead>
                <tr>
                    <th width="7%">SiteID</th>
                    <th width="20%">PubID</th>
                    <th width="10%">SiteName</th>
                    <th width="10%">Email</th>
                    <th width="7%">Login</th>
                </tr>
            </thead>
            <tbody>

                <?php foreach ($this->data as $iter): ?>
                <tr>
                    <td><?php echo $iter['SiteID'] ?></td>
                    <td><?php echo $iter['PubID']; ?></td>      
                    <td><a href="/administrator/sites/view/id/<?php echo $iter['SiteID']; ?>" target="_blank"><?php echo $iter['SiteName']; ?></a></td>
                    <td><a href="/administrator/index/view/id/<?php echo $iter['PubID']; ?>" target="_blank"><?php echo $iter['email']; ?></a></td>
                    <td><a href="/administrator/index/auth/id/<?php echo $iter['PubID']; ?>" target="_blank">login</a></td>
                </tr>
                <?php endforeach; ?>

            </tbody>
        </table>    

</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>