<link rel="stylesheet" type="text/css" href="/fancybox/jquery.fancybox-1.3.4.css" media="screen" />
<style type="text/css">
    
    #linkMinusRevShare a{ cursor: pointer; color: red; margin: 7px 0px 0px 165px; display: none; }/* style */
    #revenue-level{ border: 1px solid black; margin-left: 128px; margin-top: 50px; }
    #revenue-level th{ font-size: 16px; padding: 5px 0px 5px 0px; }
    #revenue-level td{ font-size: 14px; padding: 3px; }
    select[name=revenue-level_length]{ width: 100px; }
    #revenue-level_length{ position: absolute; width: 100px; left: 145px; }
    #revenue-level_paginate{ margin-right: 75px; }
   
    
</style>
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript">
    
var userStatus = <?php echo $this->userData['active'];?>;
    
jQuery.extend( jQuery.fn.dataTableExt.oSort, {
    "monthYear-pre": function ( s ) {
        var a = s.split(' ');
        var objMonth = new Object({ 'Jan':'01', 'Feb':'02', 'Mar':'03', 'Apr':'04', 'May':'05', 'Jun':'06', 'Jul':'07', 'Aug':'08', 'Sep':'09', 'Oct':'10', 'Nov':'11', 'Dec':'12' });
        // Date uses the American "MM DD YY" format
        return new Date(objMonth[a[0]]+' 01 '+a[1]);
    },
 
    "monthYear-asc": function ( a, b ) {
        return ((a < b) ? -1 : ((a > b) ? 1 : 0));
    },
 
    "monthYear-desc": function ( a, b ) {
        return ((a < b) ? 1 : ((a > b) ?  -1 : 0));
    }
});

jQuery.fn.dataTableExt.oSort['money-asc'] = function(a,b) {
    var x = a.replace( "$", "" );
        x = x.replace( " ", "" );
    var y = b.replace( "$", "" );
        y = y.replace( " ", "" );

    x = parseFloat( x );
    y = parseFloat( y );
    
    return ((x < y || isNaN(y) ) ? -1 : ((x > y || isNaN(x)) ? 1 : 0));
};
jQuery.fn.dataTableExt.oSort['money-desc'] = function(a,b) {
    var x = a.replace( "$", "" ); 
        x = x.replace( " ", "" );
    var y = b.replace( "$", "" );
        y = y.replace( " ", "" );

    x = parseFloat( x );
    y = parseFloat( y );

    return ((x < y || isNaN(x)) ? 1 : ((x > y || isNaN(y) ) ? -1 : 0));
}; 
    
    $(document).ready(function(){
                   
        $('#revenue-level').dataTable({
             "bProcessing": true,
             "aLengthMenu": [[12, 25, 50, 100, -1], [12, 25, 50, 100, "All"]],
             "iDisplayLength": 12,
             "bFilter": false,
             "bInfo": false,
             "bPaginate": true,
             "aoColumns": [
                 {"sType": "monthYear"},
                 {"sType": "money"},
                 null             
             ],
             "aaSorting": [[ 0, "desc" ]]
        });      
                
        $("input[name=action]").click(function(){
            if($(this).val()==1){
                
                $("#title_2").val('Your Application to Join MadAdsMedia.com (<?php echo $this->userData['url'] ?>)');
                $("#message_2").val('We regret to inform you, but we’re unable to accept your site into the Mad Ads Media network at this time.<br /><br />\r\n\r\n<strong>Reason:</strong><br />\r\n(enter reason here)<br /><br />\r\n\r\nWe encourage you to make the required changes and to submit your site for approval again.<br /><br />\r\n\r\nThank You,<br />\r\nMadAdsMedia.com Publisher Team');                
            
            }else if($(this).val()==2){
                $("#divInviteAdx").css('display','block');
                /*
                var disableInvite = $('input[name=inviteAdx]:checked').val(); 
                
                if(disableInvite != 1){
                
                    $("#title").val('Your Application to Join MadAdsMedia.com');
                    $("#message").val('Congratulations, your application has been approved!<br /><br />\r\n\r\nWe are now working on preparing your ad tags and building up advertiser demand for your website. This process can take anywhere from 3-5 business days.<br /><br />\r\n\r\n<b>In the meantime</b>, please ensure you have a privacy policy created and the following text is in it: <a href="http://madadsmedia.com/help/privacy-policy-example.html">http://madadsmedia.com/help/privacy-policy-example.html</a>. Your privacy policy must be linked from your website\'s homepage.  Without a privacy policy, your site may be excluded from major ad campaigns.<br /><br />\r\n\r\nWe will send a follow up email when this process is complete.<br /><br />\r\n\r\nWelcome to the MadAds Media Network!<br /><br />\r\n\r\n-MadAdsMedia.com Publisher Team');                
            
                } else {
                    
                    $("#title").val('');
                    $("#message").val("");     
                }
                */
                $("#title_1").val('Your Application to Join MadAdsMedia.com (<?php echo $this->userData['url'] ?>)');
                $("#message_1").val('Congratulations, your application has been approved!<br /><br />\r\n\r\nWe are now working on preparing your ad tags and building up advertiser demand for your website. This process can take up to several weeks.<br /><br />\r\n\r\n<b>In the meantime</b>, please ensure you have a privacy policy created and the following text is in it: <a href="http://madadsmedia.com/help/privacy-policy-example.html">http://madadsmedia.com/help/privacy-policy-example.html</a>. Your privacy policy must be linked from your website\'s homepage.  Without a privacy policy, your site may be excluded from major ad campaigns.<br /><br />\r\n\r\nWe will send a follow up email when this process is complete.<br /><br />\r\n\r\nWelcome to the MadAds Media Network!<br /><br />\r\n\r\n-MadAdsMedia.com Publisher Team');                

            }else{
                $("#title_1").val('');
                $("#message_1").val('');
                $("#divInviteAdx").css('display','none');
            }
        });

		if(userStatus != 1){ $('input[name="action"][value="2"]').click(); }

    	$( ".datepicker" ).live('click', function(){
    		$(this).datepicker({
    			showOn:'focus',
    			'dateFormat'  : "yy-mm-dd"
    			}).focus();				
    	});

    	$(".addPrice").click(function(){
            
                var num = $('#revShareContent').children().length + 1;
            
    		$("#revShareContent").append('<div id="item-'+num+'"><label style="width: 160px;"></label><input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo date("Y-m-d") ?>" /> <input type="text" style="width: 100px;" name="revShare_price[]" value="70" /></div>');
    		
                $('#linkMinusRevShare a').css('display', 'block');
                
                return false;
    	});
        
        if(<?php echo count($this->revShare);?> > 1){ $('#linkMinusRevShare a').css('display', 'block'); }
        
        $('#inviteAdx').change(function(){
            
            var disableInvite = $('input[name=inviteAdx]:checked').val();
            
            if(disableInvite == 1){
                
                $("#title").val('');
                $("#message").val("");  
                $("#divInviteURL").css('display', 'none');
            }else{
                $("#title").val('Your Application to Join MadAdsMedia.com (<?php echo $this->userData['url'] ?>)');
                $("#message").val('Congratulations, your application has been approved!<br /><br />\r\n\r\nWe are now working on preparing your ad tags and building up advertiser demand for your website. This process can take up to several weeks.<br /><br />\r\n\r\n<b>In the meantime</b>, please ensure you have a privacy policy created and the following text is in it: <a href="http://madadsmedia.com/help/privacy-policy-example.html">http://madadsmedia.com/help/privacy-policy-example.html</a>. Your privacy policy must be linked from your website\'s homepage.  Without a privacy policy, your site may be excluded from major ad campaigns.<br /><br />\r\n\r\nWe will send a follow up email when this process is complete.<br /><br />\r\n\r\nWelcome to the MadAds Media Network!<br /><br />\r\n\r\n-MadAdsMedia.com Publisher Team');                                
                $("#divInviteURL").css('display', 'block');
            }
            
        });
        
        $('#inviteAdx_2').click(function(){
                        
            if($('#inviteAdx_2').attr('checked')=='checked'){
                
                $("#divInviteURL_2").css('display', 'none');
                $("#inviteURL_2").val('');
            }else{
                $("#divInviteURL_2").css('display', 'block');                
            }
            
        });        
        
        $("#tabs").tabs();
        
        $("#account_manager_id").change(function(){
            var account_manager_id = <?php echo $this->userData['account_manager_id'] ? $this->userData['account_manager_id'] : '""'; ?>;
            var id_select = $(this).val();
            if(id_select!=account_manager_id){
                $("#account_manager_notify").css('display', 'block');
            }else{
                $("#account_manager_notify").css('display', 'none');
            }
        })
                        
    })
    
    function minusRevShare()
    {
        var num = $('#revShareContent').children().length; 

        if(num > 1) $('#revShareContent #item-'+num).remove();
        if(num <= 2) $('#linkMinusRevShare a').css('display', 'none');
    }
    
    
    function submitForm(num)
    {
        if($('#enable_wire_transfer').attr('checked')=="checked"){
            $('#enable_wire_transfer_'+num).val(1);
        }else{
            $('#enable_wire_transfer_'+num).val('');
        }
        if($('#notification_control_admin').attr('checked')=="checked"){
            $('#notification_control_admin_'+num).val(1);
        }else{
            $('#notification_control_admin_'+num).val('');
        }        
        document.getElementById('subForm_'+num).click();
    }
    
    function mailContact(PubID)
    {
        $.fancybox({
            'width'	: '75%',
            'height'	: '80%',
            'href'          : '/administrator/index/contact/PubID/'+PubID,
            'autoScale'    	: false,
            'transitionIn'	: 'none',
            'transitionOut'	: 'none',
            'type'		: 'iframe',
            'onClosed'      : function(){}
        }); 
    }

    function denied()
    {
        $.fancybox({
            width  : '75%',
            height : '75%',
            href   : '/administrator/index/disable/PubID/<?php echo $this->userData['id']?>',
            autoSize   : false,
            type       : 'iframe',
            'onClosed' : function(){ location.reload(); }
        });
    }

</script>


<table style="margin-top: 25px; width: 760px;">
    <tr>
        <td width="20%">Contact:</td>
        <td width="80%"><button style="cursor: pointer" type="button" onClick="mailContact(<?php echo $this->userData['id'] ?>)">Contact</button></td>
    </tr>
    <tr>        
        <td width="20%"><strong>
                Company Name:</strong> </td>
        <td width="80%"><?php echo $this->userData['company'] ?></td>
    </tr>
    <tr>
        <td><strong>Contact Name:</strong> </td>
        <td><?php echo $this->userData['name'] ?></td>
    </tr>
    <tr>
        <td><strong>Email:</strong> </td>
        <td><?php echo $this->userData['email'] ?></td>
    </tr>
    <tr>
        <td><strong>Phone Number:</strong> </td>
        <td><?php echo $this->userData['phone'] ?></td>
    </tr>
    <tr>
        <td><strong>Time Zone:</strong> </td>
        <td><?php echo $this->userData['timezone'] ?></td>
    </tr>
    <tr>
        <td><strong>Country:</strong> </td>
        <td><?php echo $this->userData['country'] ?></td>
    </tr>
    <tr>
        <td><strong>SSN or EIN:</strong> </td>
        <td><?php echo $this->userData['ssn'] ?></td>
    </tr>
    <tr>
        <td><strong>Ad Server:</strong> </td>
        <td><?php echo $this->userData['server'] ?></td>
    </tr>
    <tr>
        <td><strong>URL:</strong> </td>
        <td><?php echo $this->userData['url'] ?></td>
    </tr>
    <tr>
        <td><strong>Title:</strong> </td>
        <td><?php echo $this->userData['title'] ?></td>
    </tr>
    <tr>
        <td><strong>Description:</strong> </td>
        <td><?php echo $this->userData['description'] ?></td>
    </tr>
    <tr>
        <td><strong>Keywords:</strong> </td>
        <td><?php echo $this->userData['keywords'] ?></td>
    </tr>
    <tr>
        <td><strong>Category:</strong> </td>
        <td><?php echo $this->userData['category'] ?></td>
    </tr>
    <tr>
        <td><strong>Privacy Policy:</strong> </td>
        <td><?php echo $this->userData['privacy']==0 ? 'No' : 'Yes' ?></td>
    </tr>
    <tr>
        <td><strong>Site Type:</strong> </td>
        <td><?php
            switch ($this->userData['type']){
                case 1:
                    echo 'Web Site';
                    break;
                case 2:
                    echo 'Application';
                    break;
                case 3:
                    echo 'Tumblr Account';
                    break;                
            }
         ?>
        
        </td>
    </tr>
    <tr>
        <td><strong>Daily Visits:</strong> </td>
        <td><?php echo $this->userData['daily'] ?></td>
    </tr>
    <tr>
        <td><strong>Followers:</strong> </td>
        <td><?php echo $this->userData['followers'] ?></td>
    </tr>

    <tr>
        <td><strong>Alexa rank:</strong> </td>
        <td><?php echo isset($this->userData['alexaRank']) ? '<a href="http://www.alexa.com/siteinfo/'.$this->userData['url'].'" target="_blank">'.number_format($this->userData['alexaRank']).'</a> (Last update: '.$this->userData['alexaRank_update'].')' : '' ?></td>
    </tr>  
    <tr>
        <td><strong>Top Alexa Country:</strong> </td>
        <td><?php echo isset($this->userData['alexaRankUS']) ? '<a href="http://www.alexa.com/siteinfo/'.$this->userData['url'].'" target="_blank">'.number_format($this->userData['alexaRankUS']).'</a> (Last update: '.$this->userData['alexaRank_update'].')' : '' ?></td>
    </tr>
    <!--
    <tr>
        <td><strong>Approved by:</strong> </td>
        <td><?php echo $this->userData['approved_by'] ?></td>
    </tr>  
    <tr>
        <td><strong>Denied by:</strong> </td>
        <td><?php echo $this->userData['denied_by'] ?></td>
    </tr>  
    -->
    <?php if($this->userData['referral_id']):?>
    <tr>
        <td><strong>Referred User:</strong></td>
        <td><?php echo $this->userData['referral_name']?></td>
    </tr> 
    <?php endif;?>
    <?php if($this->userData['note']): ?>
    <tr>
        <td><strong>Notes:</strong></td>
        <td><?php echo $this->userData['note']?></td>
    </tr>     
    <?php endif; ?>
    <?php if($this->userData['active'] != 1):?>
        <?php if($this->userData['date_confirm']):?>
            <tr>
                <td style="padding-top: 5px; padding-bottom: 5px;"><strong>Status:</strong></td>
                <td>
                    <span style="color: red; font-weight: 600;">Disable</span> &nbsp;&nbsp;&nbsp; <a href="/administrator/index/un-disable/PubID/<?php echo $this->userData['id']?>" style="color: green;  font-weight: 600; cursor: pointer;">change the status to Active</a>
                </td>
            </tr>
        <?php endif;?>
        <?php if($this->userData['denied_by']):?>
            <tr>
                <td><strong>Reviewed by:</strong> </td>
                <td><?php echo $this->userData['denied_by'] ?></td>
            </tr>
        <?php endif;?>
        <tr>
            <td><label>Wire Transfer</label></td>
            <td><input type="checkbox" id="enable_wire_transfer" name="enable_wire_transfer" value="1" <?php echo $this->formValues['enable_wire_transfer']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px;">(Enable as Payment Option)</span></td>
        </tr>
        <tr>
            <td><label style="width: 158px;">Disable Notifications</label> </td>
            <td><input type="checkbox" id="notification_control_admin" name="notification_control_admin" value="1" <?php echo $this->formValues['notification_control_admin'] == 1 ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px;"></span></td>
        </tr>
    <?php elseif($this->userData['active'] == 1):?>
        <tr>
            <td style="padding-top: 5px; padding-bottom: 5px;"><strong>Status:</strong></td>
            <td>
                <span style="color: green; font-weight: 600;">Active</span> &nbsp;&nbsp;&nbsp; <a onClick="denied()" style="color: red;  font-weight: 600; cursor: pointer;">change the status to DISABLE</a>
            </td>
        </tr>
        <?php if($this->userData['approved_by']):?>
            <tr>
                <td><strong>Reviewed by:</strong> </td>
                <td><?php echo $this->userData['approved_by'] ?></td>
            </tr>
        <?php endif;?>
    <?php endif;?>
</table>
<?php if($this->userData['active']==1): ?>
<br />
<form method="post" class="sign-up" action="/administrator/index/save/">
<input type="hidden" name="userID" value="<?php echo $this->userData['id'] ?>" />
<div class="contUsL">

<p><label style="width: 258px;">Registered in Google AdExchage:</label> <input type="checkbox"  name="reg_AdExchage" value="1" <?php echo $this->userData['reg_AdExchage'] == 1 ? 'checked="checked"' : ''; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px; float: right;"></span></p>    
<p><label style="width: 158px;">Don't Invite To AdX</label> <input type="checkbox" id="inviteAdx_2" name="inviteAdx" value="1" <?php echo $this->formValues['inviteURL'] ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px; float: right;"></span></p>    
<div id="divInviteURL_2" <?php echo $this->formValues['inviteURL'] ? 'style="display:block"' : 'style="display:none"' ?>>
<label>Invite URL:</label><input type="text" name="inviteURL" id="inviteURL_2" value="<?php echo $this->formValues['inviteURL'] ?>" placeholder="Google AdX" />
<?php if(isset($this->formErrors['inviteURL'])): ?>
    <ul class="error">
    <?php foreach($this->formErrors['inviteURL'] as $errors): ?>
        <li><?php echo $errors ?></li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>                                            
</div>

<p><label style="width: 158px;">Wire Transfer</label> <input type="checkbox" id="enable_wire_transfer" name="enable_wire_transfer" value="1" <?php echo $this->userData['enable_wire_transfer']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /><span style="margin: 4px 75px 0px 0px; float: right;">(Enable as Payment Option)</span></p>
<p><label style="width: 158px;">Disable Notifications</label> <input type="checkbox" id="notification_control_admin" name="notification_control_admin" value="1" <?php echo $this->formValues['notification_control_admin'] == 1 ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px; float: right;"></span></p>    
    
    <label style="width: 160px;">RevShare: <a href="#" class="addPrice">+</a></label>
    <div id="revShareContent"> 
    <?php if($this->revShare):?>
        <?php $count = 0;?>
    	<?php foreach ($this->revShare as $item):?>
        <?php $count++;?>
            <div id="item-<?php echo $count;?>">
    		<label style="width: 160px;"></label>
    		<input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo $item['date'] ?>" />
                <input type="text" style="width: 100px;" name="revShare_price[]" value="<?php echo $item['price'] ?>" />
 	    </div>
    	<?php endforeach;?>        
    <?php else: ?>
        <div id="item-1">
            <label style="width: 160px;"></label>
            <input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo date("Y-m-d") ?>" /> 
            <input type="text" style="width: 100px;" name="revShare_price[]" value="70" />
        </div>   
    <?php endif;?>
    </div>
    <div id="linkMinusRevShare"><a onClick="minusRevShare()">- Minus RevShare</a></div>

    <p><label style="width: 190px;">Auto-Approve Min. CPM:</label> <input type="checkbox" id="auto_min_cpm" name="auto_min_cpm" value="1" <?php echo $this->formValues['auto_min_cpm']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /> <span style="margin: 4px 110px 0px 0px; float: right;"></span></p>        
<p><label style="width: 90px;">Referred By:</label> 
    <select name="referralID">
        <option>Select...</option>
        <?php foreach ($this->referrals as $item): ?>
        <option value="<?php echo $item->id ?>" <?php echo $this->userData['referral_id']==$item->id ? "selected='selected'" : "" ?>><?php echo $item->name ?></option>
        <?php endforeach; ?>
    </select>
</p>            
<p><label style="width: 130px;">Account Manager:</label> 
    <select name="account_manager_id" id="account_manager_id">
        <option>Select...</option>
        <?php foreach ($this->managers as $item): ?>
        <option value="<?php echo $item->id ?>" <?php echo $this->userData['account_manager_id']==$item->id ? "selected='selected'" : "" ?>><?php echo $item->name ?></option>
        <?php endforeach; ?>
    </select>
</p>   
<p><label style="width: 190px;">Lock Account Manager:</label> <input type="checkbox" id="lock_am" name="lock_am" value="1" <?php echo $this->formValues['lock_am']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /> <span style="margin: 4px 110px 0px 0px; float: right;"></span></p>        
<p><label style="width: 190px;">Enable Referral Program:</label> <input type="checkbox" id="referral_system" name="referral_system" value="1" <?php echo $this->formValues['referral_system']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /> <span style="margin: 4px 110px 0px 0px; float: right;"></span></p> 
<p id="account_manager_notify" style="display: none"><input style="width: 20px; height: auto;" type="checkbox" name="account_manager_notify" value="1" checked="checked" /> Notify Publisher</p>
<p><a href="#" title="" onclick="document.getElementById('subFormSeting').click(); return false;" class="sendMasBtn">Save</a></p>
<input type="submit" id="subFormSeting" style="display: none;" />
</div>
</form>
<?php endif;?>
<br />

<div class="contUsL" style="width: 700px">
    
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Approve</a></li>
            <li><a href="#tabs-2">Deny</a></li>
        </ul>
        
        <div id="tabs-1">
            <form method="post" class="sign-up">
                <?php if($this->userData['active']!=1):?>
                    <input type="hidden" id="enable_wire_transfer_1" name="enable_wire_transfer" value="" />
                    <input type="hidden" id="notification_control_admin_1" name="notification_control_admin" value="" />
                    <div id="revShareContent">
                        <?php if($this->revShare):?>
                            <?php $count = 0;?>
                            <?php foreach ($this->revShare as $item):?>
                                <?php $count++;?>
                                <div id="item-<?php echo $count;?>">
                                    <?php if($count==1): ?>
                                        <label style="width: 160px;">RevShare: <a href="#" class="addPrice">+</a></label>
                                    <?php else: ?>
                                        <label style="width: 160px;"></label>
                                    <?php endif; ?>
                                    <input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo $item['date'] ?>" />
                                    <input type="text" style="width: 100px;" name="revShare_price[]" value="<?php echo $item['price'] ?>" />
                                </div>
                            <?php endforeach;?>
                        <?php else:?>
                            <div id="item-1">
                                <label style="width: 160px;">RevShare: <a href="#" class="addPrice">+</a></label>
                                <input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo date("Y-m-d") ?>" />
                                <input type="text" style="width: 100px;" name="revShare_price[]" value="70" />
                            </div>
                        <?php endif;?>
                    </div>
                    <div id="linkMinusRevShare"><a onClick="minusRevShare()">- Minus RevShare</a></div>
                    <?php if($this->formErrors['revShare_date']): ?>
                        <ul class="error">
                            <?php foreach($this->formErrors['revShare_date'] as $errors): ?>
                                <li><?php echo $errors ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <?php if($this->formErrors['revShare_price']): ?>
                        <ul class="error">
                            <?php foreach($this->formErrors['revShare_price'] as $errors): ?>
                                <li><?php echo $errors ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <p><label style="width: 190px;">Auto-Approve Min. CPM:</label> <input type="checkbox" id="auto_min_cpm" name="auto_min_cpm" value="1" <?php echo $this->formValues['auto_min_cpm']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /> <span style="margin: 4px 110px 0px 0px; float: right;"></span></p>
                    <p><label style="width: 135px;">Desired Ad Types:</label>
                        <select name="desired_types">
                            <option value="1" <?php echo $this->formValues['desired_types']==1 ? 'selected' : '' ?>>Banner Ads Only</option>
                            <option value="2" <?php echo $this->formValues['desired_types']==2 ? 'selected' : '' ?>>Video Ads Only</option>
                            <option value="3" <?php echo $this->formValues['desired_types']==3 ? 'selected' : '' ?>>Banner & Video Ads</option>
                        </select>
                    </p>
                    <p><label style="width: 90px;">Referred By:</label>
                        <select name="referralID">
                            <option>Select...</option>
                            <?php foreach ($this->referrals as $item): ?>
                                <option value="<?php echo $item->id ?>" <?php echo $this->userData['referral_id']==$item->id ? "selected='selected'" : "" ?>><?php echo $item->name ?></option>
                            <?php endforeach; ?>
                        </select>
                    </p>
                    <p><label style="width: 130px;">Account Manager:</label>
                        <select name="account_manager_id" id="account_manager_id">
                            <option>Select...</option>
                            <?php foreach ($this->managers as $item): ?>
                                <option value="<?php echo $item->id ?>" <?php echo $this->userData['account_manager_id']==$item->id ? "selected='selected'" : "" ?>><?php echo $item->name ?></option>
                            <?php endforeach; ?>
                        </select>
                    </p>

                <?php endif;?>

                <p><label><a target="_blank" href="http://www.alexa.com/siteinfo/<?php echo $this->userData['url'] ?>%2FAlexaWebInfoService%2Flatest#clickstream">Alexa Clickstream</a></label>
                    <input type="checkbox" name="alexa" value="1" <?php echo !empty($this->formValues['alexa']) ? 'checked="checked"' : '' ?> />
                </p>
                    <?php if($this->formErrors['alexa']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['alexa'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
                    <?php endif; ?>

                <p><label style="width: 150px"><a target="_blank" href='https://www.google.com/search?q=site:<?php echo $this->userData['url'] ?>+"nude"&hl=en&tbo=d&tbm=isch'>Google Search - Nude</a></label>
                    <input type="checkbox" name="nude" value="1" <?php echo !empty($this->formValues['nude']) ? 'checked="checked"' : '' ?> />
                </p>
                    <?php if($this->formErrors['nude']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['nude'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
                    <?php endif; ?>

                <p><label style="width: 150px"><a target="_blank" href='https://www.google.com/search?q=site:<?php echo $this->userData['url'] ?>+"porn"&hl=en&tbo=d&tbm=isch'>Google Search - Porn</a></label>
                    <input type="checkbox" name="porn" value="1" <?php echo !empty($this->formValues['porn']) ? 'checked="checked"' : '' ?> />
                </p>
                    <?php if($this->formErrors['porn']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['porn'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
                    <?php endif; ?>

                <p><label style="width: 150px"><a target="_blank" href='https://www.google.com/search?q=site:<?php echo $this->userData['url'] ?>+"sex"&hl=en&tbo=d&tbm=isch'>Google Search - Sex</a></label>
                    <input type="checkbox" name="sex" value="1" <?php echo !empty($this->formValues['sex']) ? 'checked="checked"' : '' ?> />
                </p>
                    <?php if($this->formErrors['sex']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['sex'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
                    <?php endif; ?>

                <p><label style="width: 150px"><a target="_blank" href='https://www.google.com/search?q=site:<?php echo $this->userData['url'] ?>+"nsfw"&hl=en&tbo=d&tbm=isch'>Google Search - NSFW</a></label>
                    <input type="checkbox" name="nswf" value="1" <?php echo !empty($this->formValues['nswf']) ? 'checked="checked"' : '' ?> />
                </p>
                    <?php if($this->formErrors['nswf']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['nswf'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
                    <?php endif; ?>

                <p><label style="width: 150px"><a target="_blank" href='https://www.google.com/search?q=site:<?php echo $this->userData['url'] ?>+"fuck"&hl=en&tbo=d&tbm=isch'>Google Search - Fuck</a></label>
                    <input type="checkbox" name="fuck" value="1" <?php echo !empty($this->formValues['fuck']) ? 'checked="checked"' : '' ?> />
                </p>
                    <?php if($this->formErrors['fuck']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['fuck'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
                    <?php endif; ?>

                <p><label style="width: 150px"><a target="_blank" href='http://gbanned.com/?domain=<?php echo $this->userData['url'] ?>'>Adsense Ban Check</a></label>
                </p>
                <br><br>

                <?php if($this->co_approval_page == true):?>

                    <p><label>Message title</label> <input type="text" name="title" id="title_1" value="<?php echo $this->formValues['title'] ?>" /></p>
                    <?php if($this->formErrors['title']): ?>
                        <ul class="error">
                            <?php foreach($this->formErrors['title'] as $errors): ?>
                                <li><?php echo $errors ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <p><label>Message</label> <textarea rows="10" cols="50" name="message" id="message_1"><?php echo $this->formValues['message'] ?></textarea></p>
                    <?php if($this->formErrors['message']): ?>
                        <ul class="error">
                            <?php foreach($this->formErrors['message'] as $errors): ?>
                                <li><?php echo $errors ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <table><tr><td><label id="additionalNoteHeader2" onclick="toggleAdditionalNoteHide2()">Add Additional Comments</label></td><td><img id="additionalNoteImg2" onclick="toggleAdditionalNoteHide2()" src="/images/details_open.png"/></td></tr></table>

                    <div id="additionalNoteContainer2" style="display: none;">
                        <p><label>Additional Comments</label> <textarea rows="10" cols="50" name="additionalNote" id="additionalNoteBox2"></textarea></p>
                    </div>

                    <div id="divInviteAdx" <?php echo $this->formValues['action'] == 2 ? 'style="display:block"' : 'style="display:none"' ?> style="display:none">
                        <div id="blockInviteURL">
                        <p><label style="width: 158px;">Don't Invite To AdX</label> <input type="checkbox" id="inviteAdx" name="inviteAdx" value="1" <?php echo $this->formValues['inviteAdx'] == 1 ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px; float: right;"></span></p>
                            <div id="divInviteURL" <?php echo $this->formValues['inviteAdx'] == 1 ? 'style="display:block"' : 'style="display:none"' ?>>
                                <label>Invite URL:</label><input type="text" name="inviteURL" id="inviteURL" value="<?php echo $this->formValues['inviteURL'] ?>" placeholder="Google AdX" />
                                <?php if(isset($this->formErrors['inviteURL'])): ?>
                                    <ul class="error">
                                        <?php foreach($this->formErrors['inviteURL'] as $errors): ?>
                                            <li><?php echo $errors ?></li>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>

                    <p><label style="width: 290px">Added to AdX Represented Domains</label>
                    <input type="checkbox" name="represent_domain" value="1" style="width: 20px;" checked="checked" />
                    </p>
                    <?php if($this->formErrors['represent_domain']): ?>
                        <ul class="error">
                            <?php foreach($this->formErrors['represent_domain'] as $errors): ?>
                                <li><?php echo $errors ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <p><label style="width: 290px">Added to Adsense Authorize Domains</label>
                    <input type="checkbox" name="authorize_domain" value="1" style="width: 20px;" checked="checked" />
                    </p>
                    <?php if($this->formErrors['authorize_domain']): ?>
                        <ul class="error">
                            <?php foreach($this->formErrors['authorize_domain'] as $errors): ?>
                                <li><?php echo $errors ?></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                <?php else: ?>

                    <p style="display: none;"><label>Message title</label> <input type="text" name="title" id="title_1" value="<?php echo $this->formValues['title'] ?>" /></p>
                    <?php if($this->formErrors['title']): ?>
                        <ul class="error">
                        <?php foreach($this->formErrors['title'] as $errors): ?>
                            <li><?php echo $errors ?></li>
                        <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <p style="display: none;"><label>Message</label> <textarea rows="10" cols="50" name="message" id="message_1"><?php echo $this->formValues['message'] ?></textarea></p>
                    <?php if($this->formErrors['message']): ?>
                        <ul class="error">
                        <?php foreach($this->formErrors['message'] as $errors): ?>
                            <li><?php echo $errors ?></li>
                        <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>

                    <table style="display: none;"><tr><td><label id="additionalNoteHeader2" onclick="toggleAdditionalNoteHide2()">Add Additional Comments</label></td><td><img id="additionalNoteImg2" onclick="toggleAdditionalNoteHide2()" src="/images/details_open.png"/></td></tr></table>
                    <div id="additionalNoteContainer2" style="display: none;">
                        <p><label>Additional Comments</label> <textarea rows="10" cols="50" name="additionalNote" id="additionalNoteBox2"></textarea></p>
                    </div>

                    <div id="divInviteAdx" <?php echo $this->formValues['action'] == 2 ? 'style="display:block"' : 'style="display:none"' ?> style="display:none">
                        <div id="blockInviteURL">
                        <p style="display: none;"><label style="width: 158px;">Don't Invite To AdX</label> <input type="checkbox" id="inviteAdx" name="inviteAdx" value="1" <?php echo $this->formValues['inviteAdx'] == 1 ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px; float: right;"></span></p>
                        <div id="divInviteURL" style="display: none;">
                            <label>Invite URL:</label><input type="text" name="inviteURL" id="inviteURL" value="<?php echo $this->formValues['inviteURL'] ?>" placeholder="Google AdX" />
                            <?php if(isset($this->formErrors['inviteURL'])): ?>
                                <ul class="error">
                                    <?php foreach($this->formErrors['inviteURL'] as $errors): ?>
                                        <li><?php echo $errors ?></li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                        </div>
                        </div>

                        <p style="display: none;"><label style="width: 290px">Added to AdX Represented Domains</label>
                            <input type="checkbox" name="represent_domain" value="1" style="width: 20px;" checked="checked" />
                        </p>
                            <?php if($this->formErrors['represent_domain']): ?>
                                <ul class="error">
                                <?php foreach($this->formErrors['represent_domain'] as $errors): ?>
                                    <li><?php echo $errors ?></li>
                                <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>

                        <p style="display: none;"><label style="width: 290px">Added to Adsense Authorize Domains</label>
                            <input type="checkbox" name="authorize_domain" value="1" style="width: 20px;" checked="checked" />
                        </p>
                            <?php if($this->formErrors['authorize_domain']): ?>
                            <ul class="error">
                                <?php foreach($this->formErrors['authorize_domain'] as $errors): ?>
                                    <li><?php echo $errors ?></li>
                                <?php endforeach; ?>
                            </ul>
                            <?php endif; ?>
                    </div>

                <?php endif; ?>

                <p><label>Confirm User</label><input type="radio" style="width: 20px;" name="action" value="2" <?php echo $this->formValues['action']==2 ? 'checked' : '' ?> /></p>

                <?php if($this->userData['active']==1):?>
                <p><label>Send message only</label><input type="radio" style="width: 20px;" name="action" value="3" <?php echo $this->formValues['active']==1 ? 'checked' : '' ?> /></p>
                <?php endif; ?>

                <?php if($this->formErrors['action']): ?>
                    <ul class="error">
                        <?php foreach($this->formErrors['action'] as $errors): ?>
                            <li><?php echo $errors ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>

                <p><a href="#" title="" onclick="submitForm(1); return false;" class="sendMasBtn"><?php echo $this->userData['active']!=1 ? 'Save & Send' : 'Send' ?></a></p>
                <input type="submit" id="subForm_1" style="display: none;" />

            </form>
        </div>

        <div id="tabs-2">
            <form method="post" class="sign-up">
                <?php if($this->userData['active']!=1):?>
                    <input type="hidden" id="enable_wire_transfer_2" name="enable_wire_transfer" value="" />
                    <input type="hidden" id="notification_control_admin_2" name="notification_control_admin" value="" />
                <?php endif;?>
                <p><label>Message title</label> <input type="text" name="title" id="title_2" value="<?php echo $this->formValues['title'] ?>" />
                    <?php if($this->formErrors['title']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['title'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
                </p>
                <p><label>Message</label> <textarea rows="10" cols="50" name="message" id="message_2"><?php echo $this->formValues['message'] ?></textarea>
                    <?php if($this->formErrors['message']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['message'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
                </p>

                <p><label>Reject User</label><input type="radio" style="width: 20px;" name="action" value="1" <?php echo $this->formValues['action']==1 ? 'checked' : '' ?> /></p>
                <?php if($this->formErrors['action']): ?>
                    <ul class="error">
                        <?php foreach($this->formErrors['action'] as $errors): ?>
                            <li><?php echo $errors ?></li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                </p>
                <p><label>Notes</label> <textarea rows="5" cols="50" name="notes" ><?php echo $this->formValues['notes'] ?></textarea>
                    <?php if($this->formErrors['notes']): ?>
                <ul class="error">
                    <?php foreach($this->formErrors['notes'] as $errors): ?>
                        <li><?php echo $errors ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
                <table><tr><td><label id="additionalNoteHeader" onclick="toggleAdditionalNoteHide()">Add Additional Comments</label></td><td><img id="additionalNoteImg" onclick="toggleAdditionalNoteHide()" src="/images/details_open.png"/></td></tr></table>
                <div id="additionalNoteContainer" style="display: none;">

                    <p><label>Additional Comments</label> <textarea rows="10" cols="50" name="additionalNote" id="additionalNoteBox"></textarea></p></div>
                </p>

                <p><a href="#" title="" onclick="submitForm(2); return false;" class="sendMasBtn"><?php echo $this->userData['active']!=1 ? 'Save & Send' : 'Send' ?></a></p>
                <input type="submit" id="subForm_2" style="display: none;" />
            </form>
        </div>
        
    </div>
</div>

<div class="contUsL" style="width: 500px">
    <table id="revenue-level" width="460px">

        <thead>
            <tr>
                <th colspan="3" style="padding: 20px 0px 20px 0px; font-size: 20px; border-bottom: 1px solid black;"><center>Revenue Statistic</center></th>
            </tr>    
            <tr>
                <th>Date</th>
                <th>Revenue</th>
                <th>Level</th>
            </tr>
        </thead>
        <tbody>

            <?php foreach($this->level as $iter):?>

                <tr>
                    <td><?php echo date('M Y', strtotime($iter['date'])); ?></td>
                    <td>$<?php echo number_format($iter['revenue'], 2, '.', ' '); ?></td>
                    <td><?php echo $iter['level_name']; ?></td>                
                </tr>

            <?php endforeach;?>

        </tbody>    

    </table>    
</div>    
    
<script>
    function toggleAdditionalNoteHide()
    {
        header = document.getElementById("additionalNoteHeader");
        container = document.getElementById("additionalNoteContainer");
        img = document.getElementById("additionalNoteImg");
        box = document.getElementById("additionalNoteBox");
        if (container.style.display !== 'none') {
            header.innerHTML = 'Add Additional Comments';
            container.style.display = 'none';
            img.src = '/images/details_open.png';
        } else {
            header.innerHTML = 'Clear Additional Comments';
            container.style.display = 'block';
            img.src = '/images/details_close.png';
            box.value='';
        }
    }
    function toggleAdditionalNoteHide2()
    {
        header = document.getElementById("additionalNoteHeader2");
        container = document.getElementById("additionalNoteContainer2");
        img = document.getElementById("additionalNoteImg2");
        box = document.getElementById("additionalNoteBox2");
        if (container.style.display !== 'none') {
            header.innerHTML = 'Add Additional Comments';
            container.style.display = 'none';
            img.src = '/images/details_open.png';
        } else {
            header.innerHTML = 'Clear Additional Comments';
            container.style.display = 'block';
            img.src = '/images/details_close.png';
            box.value='';
        }
    }
    </script>
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
    Cufon.replace('.error', {color: 'red'});	    

</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('#location');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.headquaters');		
</script>