<style type="text/css">
    
    #linkMinusRevShare a{ cursor: pointer; color: red; margin: 7px 0px 0px 165px; display: none; }
    
</style>

<script type="text/javascript">
    $(document).ready(function(){
                
        $("input[name=action]").click(function(){
            if($(this).val()==1){
                
                $("#title_2").val('Your Application to Join MadAdsMedia.com');
                $("#message_2").val('We regret to inform you, but we’re unable to accept your site into the Mad Ads Media network at this time.<br /><br />\r\n\r\n<strong>Reason:</strong><br />\r\n(enter reason here)<br /><br />\r\n\r\nWe encourage you to make the required changes and to submit your site for approval again.<br /><br />\r\n\r\nThank You,<br />\r\nMadAdsMedia.com Publisher Team');                
            
            }else if($(this).val()==2){
                $("#divInviteAdx").css('display','block');
                /*
                var disableInvite = $('input[name=inviteAdx]:checked').val(); 
                
                if(disableInvite != 1){
                
                    $("#title").val('Your Application to Join MadAdsMedia.com');
                    $("#message").val('Congratulations, your application has been approved!<br /><br />\r\n\r\nWe are now working on preparing your ad tags and building up advertiser demand for your website. This process can take anywhere from 3-5 business days.<br /><br />\r\n\r\n<b>In the meantime</b>, please ensure you have a privacy policy created and the following text is in it: <a href="http://madadsmedia.com/help/privacy-policy-example.html">http://madadsmedia.com/help/privacy-policy-example.html</a>. Your privacy policy must be linked from your website\'s homepage.  Without a privacy policy, your site may be excluded from major ad campaigns.<br /><br />\r\n\r\nWe will send a follow up email when this process is complete.<br /><br />\r\n\r\nWelcome to the MadAds Media Network!<br /><br />\r\n\r\n-MadAdsMedia.com Publisher Team');                
            
                } else {
                    
                    $("#title").val('');
                    $("#message").val("");     
                }
                */
                $("#title_1").val('Your Application to Join MadAdsMedia.com');
                $("#message_1").val('Congratulations, your application has been approved!<br /><br />\r\n\r\nWe are now working on preparing your ad tags and building up advertiser demand for your website. This process can take anywhere from 3-5 business days.<br /><br />\r\n\r\n<b>In the meantime</b>, please ensure you have a privacy policy created and the following text is in it: <a href="http://madadsmedia.com/help/privacy-policy-example.html">http://madadsmedia.com/help/privacy-policy-example.html</a>. Your privacy policy must be linked from your website\'s homepage.  Without a privacy policy, your site may be excluded from major ad campaigns.<br /><br />\r\n\r\nWe will send a follow up email when this process is complete.<br /><br />\r\n\r\nWelcome to the MadAds Media Network!<br /><br />\r\n\r\n-MadAdsMedia.com Publisher Team');                

            }else{
                $("#title_1").val('');
                $("#message_1").val('');
                $("#divInviteAdx").css('display','none');
            }
        });

    	$( ".datepicker" ).live('click', function(){
    		$(this).datepicker({
    			showOn:'focus',
    			'dateFormat'  : "yy-mm-dd"
    			}).focus();				
    	});

    	$(".addPrice").click(function(){
            
                var num = $('#revShareContent').children().length + 1;
            
    		$("#revShareContent").append('<div id="item-'+num+'"><label style="width: 160px;"></label><input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo date("Y-m-d") ?>" /> <input type="text" style="width: 100px;" name="revShare_price[]" value="70" /></div>');
    		
                $('#linkMinusRevShare a').css('display', 'block');
                
                return false;
    	});
        
        if(<?php echo count($this->revShare);?> > 1){ $('#linkMinusRevShare a').css('display', 'block'); }
        
        $('#inviteAdx').change(function(){
            
            var disableInvite = $('input[name=inviteAdx]:checked').val();
            
            if(disableInvite == 1){
                
                $("#title").val('');
                $("#message").val("");  
                $("#divInviteURL").css('display', 'none');
            }else{
                $("#title").val('Your Application to Join MadAdsMedia.com');
                $("#message").val('Congratulations, your application has been approved!<br /><br />\r\n\r\nWe are now working on preparing your ad tags and building up advertiser demand for your website. This process can take anywhere from 3-5 business days.<br /><br />\r\n\r\n<b>In the meantime</b>, please ensure you have a privacy policy created and the following text is in it: <a href="http://madadsmedia.com/help/privacy-policy-example.html">http://madadsmedia.com/help/privacy-policy-example.html</a>. Your privacy policy must be linked from your website\'s homepage.  Without a privacy policy, your site may be excluded from major ad campaigns.<br /><br />\r\n\r\nWe will send a follow up email when this process is complete.<br /><br />\r\n\r\nWelcome to the MadAds Media Network!<br /><br />\r\n\r\n-MadAdsMedia.com Publisher Team');                                
                $("#divInviteURL").css('display', 'block');
            }
            
        });
        
        $("#tabs").tabs();
                        
    })
    
    function minusRevShare()
    {
        var num = $('#revShareContent').children().length; 

        if(num > 1) $('#revShareContent #item-'+num).remove();
        if(num <= 2) $('#linkMinusRevShare a').css('display', 'none');
    }
    
</script>


<table width="760px">
    <tr>
        <td width="20%"><strong>Company Name:</strong> </td>
        <td width="80%"><?php echo $this->userData['company'] ?></td>
    </tr>
    <tr>
        <td><strong>Contact Name:</strong> </td>
        <td><?php echo $this->userData['name'] ?></td>
    </tr>
    <tr>
        <td><strong>Email:</strong> </td>
        <td><?php echo $this->userData['email'] ?></td>
    </tr>
    <tr>
        <td><strong>Phone Number:</strong> </td>
        <td><?php echo $this->userData['phone'] ?></td>
    </tr>
    <tr>
        <td><strong>Time Zone:</strong> </td>
        <td><?php echo $this->userData['timezone'] ?></td>
    </tr>
    <tr>
        <td><strong>Country:</strong> </td>
        <td><?php echo $this->userData['country'] ?></td>
    </tr>
    <tr>
        <td><strong>SSN or EIN:</strong> </td>
        <td><?php echo $this->userData['ssn'] ?></td>
    </tr>
    <tr>
        <td><strong>Ad Server:</strong> </td>
        <td><?php echo $this->userData['server'] ?></td>
    </tr>
    <tr>
        <td><strong>URL:</strong> </td>
        <td><?php echo $this->userData['url'] ?></td>
    </tr>
    <tr>
        <td><strong>Title:</strong> </td>
        <td><?php echo $this->userData['title'] ?></td>
    </tr>
    <tr>
        <td><strong>Description:</strong> </td>
        <td><?php echo $this->userData['description'] ?></td>
    </tr>
    <tr>
        <td><strong>Keywords:</strong> </td>
        <td><?php echo $this->userData['keywords'] ?></td>
    </tr>
    <tr>
        <td><strong>Category:</strong> </td>
        <td><?php echo $this->userData['category'] ?></td>
    </tr>
    <tr>
        <td><strong>Privacy Policy:</strong> </td>
        <td><?php echo $this->userData['privacy']==0 ? 'No' : 'Yes' ?></td>
    </tr>
    <tr>
        <td><strong>Site Type:</strong> </td>
        <td><?php
            switch ($this->userData['type']){
                case 1:
                    echo 'Web Site';
                    break;
                case 2:
                    echo 'Application';
                    break;
                case 3:
                    echo 'Tumblr Account';
                    break;                
            }
         ?>
        
        </td>
    </tr>
    <tr>
        <td><strong>Daily Visits:</strong> </td>
        <td><?php echo $this->userData['daily'] ?></td>
    </tr>
    <tr>
        <td><strong>Followers:</strong> </td>
        <td><?php echo $this->userData['followers'] ?></td>
    </tr>

    <tr>
        <td><strong>Alexa rank:</strong> </td>
        <td><?php echo isset($this->userData['alexaRank']) ? '<a href="http://www.alexa.com/siteinfo/'.$this->userData['url'].'" target="_blank">'.number_format($this->userData['alexaRank']).'</a> (Last update: '.$this->userData['alexaRank_update'].')' : '' ?></td>
    </tr>  
    <?php if($this->userData['referral_id']):?>
    <tr>
        <td><strong>Referred User:</strong></td>
        <td><?php echo $this->userData['referral_name']?></td>
    </tr> 
    <?php endif;?>
</table>
<?php if($this->userData['active']==1): ?>
<br />
<form method="post" class="sign-up" action="/administrator/index/save/">
<input type="hidden" name="userID" value="<?php echo $this->userData['id'] ?>" />
<div class="contUsL">

<p><label style="width: 258px;">Registered in Google AdExchage:</label> <input type="checkbox"  name="reg_AdExchage" value="1" <?php echo $this->userData['reg_AdExchage'] == 1 ? 'checked="checked"' : ''; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px; float: right;"></span></p>    
<p><label style="width: 158px;">Wire Transfer</label> <input type="checkbox" id="enable_wire_transfer" name="enable_wire_transfer" value="1" <?php echo $this->userData['enable_wire_transfer']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /><span style="margin: 4px 75px 0px 0px; float: right;">(Enable as Payment Option)</span></p>
<p><label style="width: 158px;">Disable Notifications</label> <input type="checkbox" id="notification_control_admin" name="notification_control_admin" value="1" <?php echo $this->formValues['notification_control_admin'] == 1 ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px; float: right;"></span></p>    
    
    <label style="width: 160px;">RevShare: <a href="#" class="addPrice">+</a></label>
    <div id="revShareContent"> 
    <?php if($this->revShare):?>
        <?php $count = 0;?>
    	<?php foreach ($this->revShare as $item):?>
        <?php $count++;?>
            <div id="item-<?php echo $count;?>">
    		<label style="width: 160px;"></label>
    		<input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo $item['date'] ?>" />
                <input type="text" style="width: 100px;" name="revShare_price[]" value="<?php echo $item['price'] ?>" />
 	    </div>
    	<?php endforeach;?>        
    <?php else: ?>
        <div id="item-1">
            <label style="width: 160px;"></label>
            <input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo date("Y-m-d") ?>" /> 
            <input type="text" style="width: 100px;" name="revShare_price[]" value="70" />
        </div>   
    <?php endif;?>
    </div>
    <div id="linkMinusRevShare"><a onClick="minusRevShare()">- Minus RevShare</a></div>
        
    
<p><a href="#" title="" onclick="document.getElementById('subFormSeting').click(); return false;" class="sendMasBtn">Save</a></p>
<input type="submit" id="subFormSeting" style="display: none;" />
</div>
</form>
<?php endif;?>
<br />

<div class="contUsL" style="width: 700px">
    
    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Approve</a></li>
            <li><a href="#tabs-2">Deny</a></li>
        </ul>
        
        <div id="tabs-1">
<form method="post" class="sign-up">
<?php if($this->userData['active']!=1):?>
    
    <p><label>Wire Transfer</label> <input type="checkbox" id="enable_wire_transfer" name="enable_wire_transfer" value="1" <?php echo $this->formValues['enable_wire_transfer']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px;">(Enable as Payment Option)</span></p>
    <p><label style="width: 158px;">Disable Notifications</label> <input type="checkbox" id="notification_control_admin" name="notification_control_admin" value="1" <?php echo $this->formValues['notification_control_admin'] == 1 ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px;"></span></p>
    
    <label style="width: 160px;">RevShare: <a href="#" class="addPrice">+</a></label> 
    <div id="revShareContent">
    <?php if($this->revShare):?>
    	<?php $count = 0;?>
    	<?php foreach ($this->revShare as $item):?>
        <?php $count++;?>       
              <div id="item-<?php echo $count;?>">
    		 <label style="width: 160px;"></label>
                 <input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo $item['date'] ?>" /> 
                 <input type="text" style="width: 100px;" name="revShare_price[]" value="<?php echo $item['price'] ?>" />
              </div>    		   	
    	<?php endforeach;?>
    <?php else:?>
        <div id="item-1">
            <label style="width: 160px;"></label>  
            <input type="text" style="width: 100px;" class="datepicker" name="revShare_date[]" value="<?php echo date("Y-m-d") ?>" />
            <input type="text" style="width: 100px;" name="revShare_price[]" value="70" />
        </div>    
    <?php endif;?>
    </div>      
    <div id="linkMinusRevShare"><a onClick="minusRevShare()">- Minus RevShare</a></div>        
    
<?php endif;?>
<p><label>Message title</label> <input type="text" name="title" id="title_1" value="<?php echo $this->formValues['title'] ?>" />
    <?php if($this->formErrors['title']): ?>
        <ul class="error">
        <?php foreach($this->formErrors['title'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                                            
</p>
<p><label>Message</label> <textarea rows="10" cols="50" name="message" id="message_1"><?php echo $this->formValues['message'] ?></textarea>
    <?php if($this->formErrors['message']): ?>
        <ul class="error">
        <?php foreach($this->formErrors['message'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                                            
</p>
<div id="divInviteAdx" <?php echo $this->formValues['action'] == 2 ? 'style="display:block"' : 'style="display:none"' ?> style="display:none">
<p id="blockInviteURL">
        <p><label style="width: 158px;">Don't Invite To AdX</label> <input type="checkbox" id="inviteAdx" name="inviteAdx" value="1" <?php echo $this->formValues['inviteAdx'] == 1 ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px; float: right;"></span></p>    
        <div id="divInviteURL" <?php echo $this->formValues['inviteAdx'] == 1 ? 'style="display:block"' : 'style="display:none"' ?>>
        <label>Invite URL:</label><input type="text" name="inviteURL" id="inviteURL" value="<?php echo $this->formValues['inviteURL'] ?>" placeholder="Google AdX" />
        <?php if(isset($this->formErrors['inviteURL'])): ?>
            <ul class="error">
            <?php foreach($this->formErrors['inviteURL'] as $errors): ?>
                <li><?php echo $errors ?></li>
            <?php endforeach; ?>
            </ul>
        <?php endif; ?>                                            
        </div>
</p>   
</div>
<p><label>Confirm User</label><input type="radio" style="width: 20px;" name="action" value="2" <?php echo $this->formValues['action']==2 ? 'checked' : '' ?> /></p>
<p><label>Send message only</label><input type="radio" style="width: 20px;" name="action" value="3" <?php echo $this->formValues['action']==3 ? 'checked' : '' ?> /></p>
    <?php if($this->formErrors['action']): ?>
        <ul class="error">
        <?php foreach($this->formErrors['action'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                                            
</p>
<p><a href="#" title="" onclick="document.getElementById('subForm_1').click(); return false;" class="sendMasBtn"><?php echo $this->userData['active']!=1 ? 'Save & Send' : 'Send' ?></a></p>
<input type="submit" id="subForm_1" style="display: none;" />
</form>

        </div>

        <div id="tabs-2">
<form method="post" class="sign-up">
<?php if($this->userData['active']!=1):?>
    
    <p><label>Wire Transfer</label> <input type="checkbox" id="enable_wire_transfer" name="enable_wire_transfer" value="1" <?php echo $this->formValues['enable_wire_transfer']==1 ? 'checked="checked"' : '' ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px;">(Enable as Payment Option)</span></p>
    <p><label style="width: 158px;">Disable Notifications</label> <input type="checkbox" id="notification_control_admin" name="notification_control_admin" value="1" <?php echo $this->formValues['notification_control_admin'] == 1 ? '' : 'checked="checked"'; ?> style="width: 20px;" /><span style="margin: 4px 110px 0px 0px;"></span></p>
          
    
<?php endif;?>
<p><label>Message title</label> <input type="text" name="title" id="title_2" value="<?php echo $this->formValues['title'] ?>" />
    <?php if($this->formErrors['title']): ?>
        <ul class="error">
        <?php foreach($this->formErrors['title'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                                            
</p>
<p><label>Message</label> <textarea rows="10" cols="50" name="message" id="message_2"><?php echo $this->formValues['message'] ?></textarea>
    <?php if($this->formErrors['message']): ?>
        <ul class="error">
        <?php foreach($this->formErrors['message'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                                            
</p>
<p><label>Reject User</label><input type="radio" style="width: 20px;" name="action" value="1" <?php echo $this->formValues['action']==1 ? 'checked' : '' ?> /></p>
    <?php if($this->formErrors['action']): ?>
        <ul class="error">
        <?php foreach($this->formErrors['action'] as $errors): ?>
            <li><?php echo $errors ?></li>
        <?php endforeach; ?>
        </ul>
    <?php endif; ?>                                            
</p>
<p><a href="#" title="" onclick="document.getElementById('subForm_2').click(); return false;" class="sendMasBtn"><?php echo $this->userData['active']!=1 ? 'Save & Send' : 'Send' ?></a></p>
<input type="submit" id="subForm_2" style="display: none;" />
</form>
        </div>
        
    </div>
    
</div>
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
    Cufon.replace('.error', {color: 'red'});	    

</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('#location');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.headquaters');		
</script>