<h2 class="text-center">Ad Size Requests</h2>
<table class="table table-striped table-bordered" id="request" cellspacing="0" width="100%">
    <thead>
    <tr>
        <td>SID</td>
        <td>Website</td>
        <td>Contact</td>
        <td>Date Requested</td>
        <td>Size</td>
        <td>Primary Network</td>
        <td>Size Network</td>
        <td>Actions</td>
    </tr>
    </thead>
    <tfoot>
    <tr>
        <td>SID</td>
        <td>Website</td>
        <td>Contact</td>
        <td>Date Requested</td>
        <td>Size</td>
        <td>Primary Network</td>
        <td>Size Network</td>
        <td>Actions</td>
    </tr>
    </tfoot>
    <tbody></tbody>
</table>

<script>
    $(document).ready(function() {
        var table = $('#request').DataTable( {
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url" : "/administrator/sizes-requests/get-ajax",
                "type": "POST"
            },
            "order": [[ 3, "desc" ]],
            "columns": [
                {"data" : "site_id"},
                {"data" : "SiteName"},
                {"data" : "email"},
                {"data" : "created_at"},
                {"data" : "size_name"},
                {"data" : "network_current"},
                {"data" : "network_submited"},
                {
                    "data" : "id",
                    "render" : function ( data, type, full, meta ){
                        return '<a class="btn btn-success" href="/administrator/sizes-requests/enable/id/'+data+'" role="button">Enable</a>'
                            +' <a class="btn btn-danger" href="/administrator/sizes-requests/disable/id/'+data+'" role="button">Disable</a>';
                    }
                }
            ]
        } );
    });
</script>