<style type="text/css">
    
     #mask{
        position: fixed;
        height: 100%;
        width: 100%;
        display: none;
        opacity: 0.3;
        filter: alpha(opacity=30);
        background-color: #000000;
        z-index: 9000;
        left:0;
        top:0;
    }
    
    #loading{ 
        position: fixed;
        display: none;
        height: 50px;
        width: 200px;
        z-index: 10000;
        border: 1px solid #B7B7B7;
        border-radius: 4px;
        background-color: #F4F4F4;
        left: 43%;
        top: 44%;
    }
    
    #loading span{
        font-size: 14px;
        display: block;
        margin: 15px 0px 0px 62px; 
    }
    
    #status_active
    {
    	height: 20px; 
    }
    
    .error-js
    {
    	display: block; width: 700px; font-size: 14px; font-weight: 600; color: red;
    }
    
    #dialog
    {
    	display: none;
    }
    
    #manage,#button
    {
    	cursor: pointer;
    }    
</style>
<script type="text/javascript" src="/js/validate.1.9.0.js"></script>
<?php
 $this->headScript()->offsetSetFile(20,$this->baseUrl().'/js/manage-referals.js','text/javascript');
?>
<h1>Edit Contact Notification</h1>
<br /><br />
   <?php echo $this->form; ?>
   
<div id="dialog">
	<input type="hidden" name="id" id="contact_notification_id" value="<?php echo $this->id;?>">
	<table width="840px" cellpadding="0" cellspacing="0" border="0" class="display" id="referal">
		<thead>
			<tr>
				<th width="5%">ID</th>
				<th width="30%">Name</th>
				<th width="10%">Click</th>
				<th width="20%">Conversion</th>
				<th width="20%">Total Impressions</th>
				<th width="13%">Total Revenue</th>
				<th width="2%">Operation</th>
                                <th width="2%">Primary</th>
			</tr>
		</thead>
		<tbody></tbody>
		<tfoot>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Click</th>
				<th>Conversion</th>
				<th>Total Impressions</th>
				<th>Total Revenue</th>
				<th>Operation</th> 
                                <th>Primary</th>
			</tr>
		</tfoot>
	</table>
</div>

<div id="mask"></div>
<div id="loading"><span>processing...</span></div>
 
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>

