<style>    
#title-page{
    color: #414141;
    font-size: 52px;
    line-height: 52px;
    text-align: center;
    font-family: Arial,Helvetica,sans-serif;
    font-weight: normal;
} 
input[name="name"]{ border-right: 1px solid #DADADA !important; }

input[name="submit"]{
    background: #8e8e8e !important;
    border: 1px solid #797979 !important;
    color: #ffffff;
    cursor: pointer;
    float: left;
    font-size: 16px;
    line-height: 0px !important;
    height: 26px;
    width: 129px !important;
    margin-left: 290px;
}

input[name="submit"]:hover{ background: #dc2323 !important; }

#default_admin_form{ margin-top: 20px; }
</style>
<link href="/styles/table.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/style.css" media="screen" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="/js/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="/js/jquery.dataTables.min.js"></script>

<div id="title-page">Add Sub</div>
<div class="contUsL" style="width: 750px;">
<p>
    <a href="/administrator/sub/index">Back to menu</a>
</p>   
<?php echo $this->form; ?>
</div>
 
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>