		<div class="signCont signContM">
        	<h1>Why Mad Ads Media?</h1>
            <p class="whyMedSlog">Mad Ads Media for Publishers</p>
            <div class="ourPluzBox">
                <div class="ourPlus">
                    <h5>Industry High CPMs</h5>
                    <p>We align 100's of ad networks, ad exchanges, and RTB advertisers to compete for your inventory. Our optimization technology assures the ad provider with the highest CPM is served, earning you the most for every impression.</p>
                </div>
                <div class="ourPlus ourPlusR">
                    <h5>High Fill Rates </h5>
                    <p>While most ad networks can fill only the first few of your impressions, our mass pool of advertisers ensures a large majority of your impressions will be filled. </p>
                </div> 
            </div>
            
            <div class="ourPluzBox">            
                <div class="ourPlus">                   
                    <h5>Quality Advertisers </h5>
                    <p>We provide you access to campaigns from the Internet's highest profile brand advertisers. Our wide range of campaigns include CPM, CPC, CPA, and CPL.</p>
                </div>
                <div class="ourPlus ourPlusR">
                    <h5>Team of Optimization Specialists </h5>
                    <p>We work side-by-side with our publishers to optimize their websites to generate higher revenue. Our team of experts will provide suggestions for better ad positioning and additional ad placements. Some publishers are seeing as much as a 100% increase in revenue, overnight!  </p>
                </div>
            </div>
            
            <div class="ourPluzBox ourPluzBoxL">            
                <div class="ourPlus">                   
                    <h5>Dedicated Account Manager </h5>
                    <p>Each publisher is assigned a dedicated account manager to help them every step of the way.</p>
                </div>
                <div class="ourPlus ourPlusR">
                    <h5>Low Traffic Requirements </h5>
                    <p>We're looking for sites with at least 10,000 page views per day. We're looking for well designed sites with family friendly content. If you fall into this category, feel free to apply today!  </p>
                </div>            
            </div>                      
            <!--our client-->
            <div class="ourClient">
            	<a href="#" title="" class="clientTitle">We work with over 100 of the industries top companies and ad providers to provide our publishers with <br /> the best technology and rates. </a>
                <div>
                    <table cellpadding="0" cellspacing="0" class="clientTbl">
                        <tr>
                            <td>
                                <a href="#" title=""><img src="/images/rubiconHov.png" width="180" height="80" alt="" /></a>                        
                            </td>
                            <td>
                                <a href="#" title=""><img src="/images/mediaplexHov.png" width="179" height="48" alt="" /></a>                          
                            </td>
                            <td>
                                <a href="#" title=""><img src="/images/dubleClickHov.png" width="96" height="59" alt="" /></a>                        
                            </td>
                            <td>
                                <a href="#" title=""><img src="/images/micrAdvHov.png" width="180" height="62" alt="" /></a>                        
                            </td>
                        </tr>
                        <tr align="center">
                          <td><a href="#" title=""><img src="/images/turnHov.png" width="165" height="44" alt="" /></a></td>
                          <td><a href="#" title=""><img src="/images/aolHov.png" alt="" width="123" height="81" /></a></td>
                          <td><a href="#" title=""><img src="/images/openXHov.png" width="123" height="52" alt="" /></a></td>
                          <td><a href="#" title=""><img src="/images/pubmaticHov.png" width="180" height="48" alt="" /></a></td>
                        </tr>
                        <tr>
                            <td>
                                <a href="#" title="" ><img src="/images/brandScHov.png" width="175" height="39" alt="" /></a>                        
                            </td>
                            <td>
                                <a href="#" title=""><img src="/images/mediaMathHov.png" width="145" height="85" alt="" /></a>                        
                             </td>
                            <td>
                                <a href="#" title=""><img src="/images/quancastHov.png" width="149" height="55" alt="" /></a>                        
                            </td>
                            <td>
                                <a href="#" title=""><img src="/images/invitemediaHov.png" width="150" height="47" alt="" /></a>                        
                           </td>
                        </tr>                                
                    </table>
                </div>
                
            </div>
            <!--//our client-->            
        </div>
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.signCont h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.signCont p');
		Cufon.replace('.clientTitle');		
			
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.ourPlus h5');
</script>