		<div class="signCont signContM">
		
        	<h1>Careers</h1>
            <p class="whyMedSlog">MadAdsMedia.com, one of the largest advertising networks in the Philadelphia/South Jersey area, is looking for a motivated individuals to join its team. </p>
			
            <div class="ourPluzBox" style="width:100%">
                <div class="ourPlus" style="width:100%">
                    <h5>Account Manager / Publisher Services (Mount Laurel, NJ)</h5>
					<br>
					<b style="font-size:13px">Position overview:</b><br>
					As an account manager, you will be responsible for initiating and evaluating partnership opportunities with new websites/accounts. <br>
<br>
Post-launch, the account manager is responsible for overseeing the publisher relationship and continuing to improve performance via ad placement optimization, campaign optimization, and frequent email, Skype, and phone conversations.  <br>
<br>
As an account manager, you will have revenue goals based on maintaining current businses and securing upsell opportunities.  You will work with the business develpoment team to increase product adoption among MadAds' publisher-facing products that best meet the publisher's needs.

                    <p>
					<br>
					<b style="font-size:13px">Required skills and experience:</b>
                    <ul>
                      <li>&bull; Education: BA/BS degree or equivalent</li>
                      <li>&bull; Strong verbal and written communication skills</li>
                      <li>&bull; Highly developed attention to detail</li>
                      <li>&bull; Consistent use of effective time-management and organization methods</li>
                      <li>&bull; Ability to constantly adapt to change and use change as an opportunity</li>
                      <li>&bull; Experience in online media monetization</li>
                      <li>&bull; 4+ years of relevant experience</li>
                      <li>&bull; Track record of exceptional performance</li>
                    </ul>
					</p>
                </div>
        </div>
		
		<!--Start career-->
            <div class="ourPluzBox" style="width:100%">
                <div class="ourPlus" style="width:100%">
                    <h5>Account Manager Platform Demand Team (Mount Laurel, NJ)</h5>
					<br>
					<em style="font-size:13px">Position overview:</em>
					You will work closely with Business Development leads to manage day-to-day workflow and communication between MadAds and its demand clients (DSPs and Ad Networks).  Drive revenue by identifying client growth opportunities, upselling clients on new product offerings and ad formats, and monitoring key performance indicators to maintain healthy technology and relationships.  Interface directly with internal MadAds teams to resolve client requests while managing expectations throughout the customer life cycle.     MadAds is looking for a highly motivated, self-starter, and someone who is dedicated to providing the highest level of customer satisfaction.   
                    <p>
					<br>
					<em style="font-size:13px">Responsibilities:</em>
                      <li>&bull; Actively recruit new DSPs/Ad Network relationships</li>
                      <li>&bull; Coordinate re-occurring meetings via phone and in-person with customers including quarterly business reviews</li>
                      <li>&bull; Help streamline and document processes for addressing customer issues</li>
                      <li>&bull; Maintain customer engagements documents and pipeline documents</li>
                      <li>&bull; Work with publisher yield teams to drive revenue by sourcing demand for high priority publishers</li>
                      <li>&bull; Develop strong working relationships with all client accounts</li>
                    <p>
					<br>
					<em style="font-size:13px">Required skills and experience:</em>
                    <ul>
                      <li>&bull; Experience working with Ad Exchanges, DSPs/SSPs, Ad Networks, digital advertising agencies or ad servers</li>
                      <li>&bull; An understanding of the emerging online RTB ecosystem</li>
                      <li>&bull; Education: BA/BS degree or equivalent</li>
                      <li>&bull; Strong verbal and written communication skills</li>
                      <li>&bull; Highly developed attention to detail</li>
                      <li>&bull; Ability to constantly adapt to change and use change as an opportunity</li>
                      <li>&bull; Experience in online media monetization</li>
                      <li>&bull; 2+ years of relevant experience</li>
                      <li>&bull; Track record of exceptional performance</li>
                    </ul>
					</p>
                </div>
        </div>
		<!--End career-->


        </div>
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.signCont h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.signCont p');
		Cufon.replace('.clientTitle');		
			
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.ourPlus h5');
</script>