		<div class="signCont signContM">
        	<h1>Frequently Asked Questions</h1>
            <p class="whyMedSlog"></p>
            <div class="faqBox">
                <div class="theFaq">
                    <h5>What Are The Payment Terms?</h5>
                    <p>Payments are made on a net-45 basis.  You will receive your payment 45 days after the the current month's end (provided you met your set minimum payment).  You can see information for past and future payments in your <a href="/payments/" class="exception">payments</a> area.</p>
                </div>
            </div>
            
            <div class="faqBox">
                <div class="theFaq">
                    <h5>How Often Are The Reports Updated?</h5>
                    <p>Because we're partnered with over 130 ad networks, exchanges, DSPs, we must wait for them to report their final numbers before we can report them to you.  Because of this, finalized impressions and revenue are reported 24-48 hours later.</p>
                </div>
            </div>
            
            <div class="faqBox">
                <div class="theFaq">
                    <h5>How Much Money Do I Need To Make Before I Can Receive Payment?</h5>
                    <p>The minimum payment amount is determined by you.  You can control the amount in the <a href="/payment/" class="exception">payment profile</a> area of your account.  The minimum you can select is $50.</p>
                </div>
            </div>
            
            <div class="faqBox">            
                <div class="theFaq">                   
                    <h5>How can I make more money/increase my CPM?</h5>
                    <p>To make the most money, we recommend running all available ad sizes.  To increase your eCPM, make sure your ads are placed above the fold and in high click-through rate areas.  
					<br>Examples of high click-through rate areas include: 
					<br> &middot; 728x90 directly below the top navigation.
					<br> &middot; 160x600 on the left side/panel of the page.
					<br> &middot; 300x250 directly above or inside the site's main content.</p>
                </div>
            </div>
            
            <div class="faqBox faqBoxL">            
                <div class="theFaq">                   
                    <h5>How many ads can I put on a page?</h5>
                    <p>We allow up to 5 ad units per page. </p>
                </div>
            </div>                      

            <div class="faqBox faqBoxL">            
                <div class="theFaq">                   
                    <h5>Does Mad Ads Media Offer Floor Tags?</h5>
                    <p>We do. You can setup your floor tags by accessing the &quot;<a href="/minimum-cpm">Minimum CPM</a>&quot; section in your account. <br>
                  *Floor tags allow you to name the minimum CPM you're willing to accept.  When we cannot match or beat the desired CPM, we send the impression to another ad network you work with.				  </p>
                </div>
            </div>                      

            <div class="faqBox faqBoxL">            
                <div class="theFaq">                   
                    <h5>Can I Run Mad Ads Media On Other Sites I Own?</h5>
                    <p>Yes, you may have multiple websites under your account.  In order to run Mad Ads Media on additional websites, you will need to <a href="/new-site/" class="exception">submit the website</a> to us for approval.  Upon being approved, you'll be able to generate the ad tags for it in the "Ad Code" area of your account.</p>
                </div>
            </div>                      

            <div class="faqBox faqBoxL">            
                <div class="theFaq">                   
                    <h5>My Question Still Wasn't Answered.</h5>
                    <p>Still have a question?  Feel free to <a href="/contact-us/" class="exception">contact us</a> at any time.</p>
                </div>
            </div>

        </div>
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.signCont h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.signCont p');
		Cufon.replace('.clientTitle');		
			
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.theFaq h5');
		Cufon.replace('.theFaq a');
    	Cufon.replace('.exception', {color: 'red'});
</script>