    	<div>
            <div class="contInf" onclick="location.href='/about-us/'">
                <h3>Guaranteed Highest CPM!</h3>
                <div class="contInfImg">&nbsp;</div>
                <p>Make the most of your impressions. Our optimization technology will drive the maximum yield and an industry leading CPM. </p>
            </div>
            
            <div class="contInf" onclick="location.href='/about-us/'">
                <h3>High Fill Rates!</h3>
                <div class="contInfImg fillFree">&nbsp;</div>
                <p>With over 100 ad networks, ad exchanges, and DSPs competing for your inventory, we can fill a majority of your impressions at a premium CPM.</p>
            </div>
            
            <div class="contInf contInfR" onclick="location.href='#'">
                <h3>Define Your Minimum CPM </h3>
                <div class="contInfImg howMuch">&nbsp;</div>
                <p>Let us know what the lowest CPM you're willing to accept.  We'll only serve advertisers paying that rate or higher.</p>
            </div>                
        </div>
        
        <div class="companyLogo">
        	<table cellpadding="0" cellspacing="0" class="companyTbl">
            	<tr>
                	<td>
                    	<a href="#" title=""><img src="/images/rubicon.png" width="180" height="80" alt="" /></a>
						<a href="#" title="" class="hovLogo"><img src="/images/rubiconHov.png" width="180" height="80" alt="" /></a>                        
                    </td>
                	<td>
                    	<a href="#" title=""><img src="/images/mediaplex.png" width="179" height="48" alt="" /></a>
						<a href="#" title="" class="hovLogo"><img src="/images/mediaplexHov.png" width="179" height="48" alt="" /></a>                          
                    </td>
                	<td>
                    	<a href="#" title=""><img src="/images/dubleClick.png" width="96" height="59" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/dubleClickHov.png" width="96" height="59" alt="" /></a>                        
                    </td>
                	<td>
                    	<a href="#" title=""><img src="/images/micrAdv.png" width="180" height="62" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/micrAdvHov.png" width="180" height="62" alt="" /></a>                        
                    </td>
                </tr>
            	<tr>
                	<td>
                    	<a href="#" title=""><img src="/images/turn.png" width="165" height="44" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/turnHov.png" width="165" height="44" alt="" /></a>                        
                    </td>
                	<td>
                    	<a href="#" title=""><img src="/images/aol.png" width="123" height="81" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/aolHov.png" width="123" height="81" alt="" /></a>                        
                    </td>
                	<td>
                    	<a href="#" title=""><img src="/images/openX.png" width="123" height="52" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/openXHov.png" width="123" height="52" alt="" /></a>                        
                    </td>
                	<td>
                    	<a href="#" title=""><img src="/images/pubmatic.png" width="180" height="48" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/pubmaticHov.png" width="180" height="48" alt="" /></a>                        
                    </td>
                </tr>
            	<tr>
                	<td>
                    	<a href="#" title=""><img src="/images/brandSc.png" width="175" height="39" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/brandScHov.png" width="175" height="39" alt="" /></a>                        
                    </td>
                	<td>
                    	<a href="#" title=""><img src="/images/mediaMath.png" width="145" height="85" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/mediaMathHov.png" width="145" height="85" alt="" /></a>                        
                     </td>
                	<td>
                    	<a href="#" title=""><img src="/images/quancast.png" width="149" height="55" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/quancastHov.png" width="149" height="55" alt="" /></a>                        
                    </td>
                	<td>
                    	<a href="#" title=""><img src="/images/invitemedia.png" width="150" height="47" alt="" /></a>
                    	<a href="#" title="" class="hovLogo"><img src="/images/invitemediaHov.png" width="150" height="47" alt="" /></a>                        
                   </td>
                </tr>                                
            </table>

        </div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});				
	Cufon.replace('.signCont h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.signCont p');
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
<script type="text/javascript">
$(document).ready(function() {
Cufon.set("fontFamily", "Headline_Two_400.font.js");
	$(".contInf").hover(
		function(){
		$(this).children("h3").addClass('white');
		$(this).children("p").addClass('white');		
		Cufon.refresh();		
		Cufon.replace('.white', {color: '#FFFFFF'});	
		}, 
	  function () {
		$(this).children("h3").removeClass('white');
		$(this).children("p").removeClass('white');		
		Cufon.refresh();			
		Cufon.replace('.contInf h3', {color: '#DC2323'});	
		Cufon.replace('.contInf p', {color: '#333333'});			
	  }
	);
});
</script>
        