<h4><ins>Terms of Service:</ins></h4>

Publishers that agree to MadAds Media's Terms of Service are required to adhere to the following policies, so please read them carefully. If you fail to comply with these policies without permission from MadAds Media, we reserve the right to disable ad serving to your site and/or disable your MadAds account at any time. <strong style="font-weight:bold">If your account is disabled, you will not be eligible for further participation in the MadAds program, nor will you receive any payment.</strong>
<br /><br />
Because we may change our policies at any time, please check here often for updates. In accordance with our online Terms and Conditions, it's your responsibility to keep up to date with, and adhere to, the policies posted here. Exceptions to these policies are permitted only with authorization from MadAds Media.

<h4><ins><br>
Invalid Clicks & Impressions</ins></h4>

Publishers may not click their own ads or use any means to inflate impressions and/or clicks artificially, including manual methods.
<br />
<br />
Clicks on MadAds ads must result from genuine user interest. Any method that artificially generates clicks or impressions on your MadAds ads is strictly prohibited. These prohibited methods include, but are not limited to, repeated manual clicks or impressions, automated click and impression generating tools and the use of robots or deceptive software. <strong>Please note that clicking your own ads for any reason is prohibited.</strong>

<h4><ins><br>
Encouraging clicks</ins></h4>

Publishers may not ask others to click their ads or use deceptive implementation methods to obtain clicks. This includes, but is not limited to, offering compensation to users for viewing ads or performing searches, promising to raise money for third parties for such behavior or placing images next to individual ads.
<br />
<br />
In order to ensure a good experience for users and advertisers, publishers participating in the MadAds program may not:
<br />
<ul>
	<li>Compensate users for viewing ads or performing searches, or promise compensation to a third party for such behavior.</li> 
	<li>Encourage users to click the MadAds ads using phrases such as "click the ads", "support us", "visit these links" or other similar language.</li> 
	<li>Direct user attention to the ads using arrows or other graphical gimmicks.</li> 
	<li>Place misleading images alongside individual ads.</li> 
	<li>Place ads in a floating box script.</li>
	<li>Format ads so that they become indistinguishable from other content on that page.</li> 
	<li>Format site content so that it is difficult to distinguish it from ads.</li> 
</ul>

<h4><ins><br>
Content guidelines</ins></h4>

Publishers may not place MadAds code on pages with content that violates any of our content guidelines. Some examples include content that is adult, violent or advocating racial intolerance.
<br />
<br />
Sites with MadAds ads may not include or link to:
<br />
<ul>
	<li>Pornography, adult or mature content</li> 
	<li>Violent content</li> 
	<li>Content related to racial intolerance or advocacy against any individual, group or organization</li> 
	<li>Excessive profanity</li> 
	<li>Hacking/cracking content</li> 
	<li>Gambling or casino-related content</li> 
	<li>Illicit drugs and drug paraphernalia content</li> 
	<li>Sales of beer or hard alcohol</li> 
	<li>Sales of tobacco or tobacco-related products</li> 
	<li>Sales of prescription drugs</li> 
	<li>Content regarding programs which compensate users for clicking ads or offers, performing searches, surfing websites or reading emails</li> 
	<li>Any other content that is illegal, promotes illegal activity or infringes on the legal rights of others</li> 
</ul>

<h4><ins><br>
Copyrighted material</ins></h4>

MadAds publishers may not display MadAds ads on webpages with content protected by copyright law unless they have the necessary legal rights to display that content. Please see a DCMA policy for further information on this subject. 

<h4><ins><br>
Traffic sources</ins></h4>

MadAds ads may not be placed on pages receiving traffic from certain sources. For example, publishers may not participate in paid-to-click programs, send unwanted emails or display ads as the result of the action of any software application.
<br />
<br />
To ensure a positive experience for Internet users and MadAds advertisers, sites displaying MadAds ads may not:
<br />
<ul>
	<li>Use third-party services that generate clicks or impressions such as paid-to-click, paid-to-surf, autosurf and click-exchange programs.</li> 
	<li>Users are forbidden from purchasing traffic in any way, shape, or form.</li>
	<li>Be promoted through unsolicited mass emails or unwanted advertisements on third-party websites.</li> 
	<li>Be loaded by any software that can trigger pop-ups, redirect users to unwanted websites, modify browser settings or otherwise interfere with site navigation. It is your responsibility to ensure that no ad network or affiliate uses such methods to direct traffic to pages that contain your MadAds code.</li> 
</ul>
<br />
***MadAds Media reserves the right to suspend your account if source to your site are deemed unacceptable; this is done completely at the discretion of MadAds Media

<h4><ins><br>
Ad behavior</ins></h4>

MadAds code may not be altered in any way, nor may ads be targeted or delivered in any way that is not approved by MadAds Media.

<br>
<br>
<h4><ins>Ad placement<ins></h4>

Publishers are encouraged to experiment with a variety of placements and ad formats. However, MadAds code may not be placed in inappropriate places such as pop-ups, emails or software. Publishers must also adhere to the policies for each product used.
<br /><br />
MadAds ads, search boxes or search results may not (be):
<br />
<ul>
	<li>Exceed more than 3 ad units per page.</li>
        <li>Displayed on any site and/or page that is not previously approved by the MadAds Media Policy Team</li>
	<li>Displayed in pop-ups or pop-unders (without the approval of MadAds Media)</li>
	<li>Obscured by elements on a page.</li> 
	<li>Placed on any non-content-based page.</li> 
	<li>Placed on pages published specifically for the purpose of showing ads.</li> 
	<li>Placed on pages whose content or URL could confuse users into thinking it is associated with MadAds due to the misuse of logos, trademarks or other brand features.</li> 
	<li>Placed on, within or alongside other third products or services in a manner that violates the policies of that product or service.</li> 
</ul>

<h4><ins><br>
Site behavior</ins></h4>

Sites showing MadAds ads should be easy for users to navigate. Sites may not change user preferences, redirect users to unwanted websites, initiate downloads, include malware or contain pop-ups or pop-unders that interfere with site navigation. 

<h4><ins><br>
Advertising cookies</ins></h4>

MadAds publishers must have and abide by a privacy policy that discloses that third parties may be placing and reading cookies on your users' browsers, or using web beacons to collect information as a result of ad serving on your website. 
<br />
<br />
To learn more about creating your privacy policy, visit this link: link

<h4><ins><br>
Summary</ins></h4>

To work with MadAds and to keep your account in good standing, please remember to follow our Terms of Service, and stay up to date if any changes are made.  Carefully read the Terms of Service; here is a brief summary:
<br />
<ol>
	<li>Do NOT clickon your own ads.</li> 
	<li>Do NOT ask others to click on your ads.</li> 
	<li>Do NOT include any prohibited site content, including adult content, violence or excessive profanity, drugs (including alcohol and tobacco), or copyrighted material.</li> 
	<li>Do NOT modify the MadAds ad code in any way.</li>
	<li>Do NOT place more than 3 ads per page.</li>
	<li>Do NOT place images near ads in a way that may mislead users into thinking that the images are associated with the ads.</li> 
</ol>
<br />
If you're ever concerned that you might be violating policies, feel free to reach out to us at 

<a href="mailto:support@madadsmedia.com">support@madadsmedia.com</a>.  Our policy team will be more than happy to answer your questions or concerns.  We are mad about making you money!  We just want to go about it in the best possible manner.
<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.signCont h1');		
				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		Cufon.replace('.signCont p');
		Cufon.replace('.clientTitle');		
			
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.ourPlus h5');
</script>