<style type="text/css">
    
    #form_approve{ display: block; }
    #form_approve label { display: block; float: left; }
    #form_approve #floor_date { display: block; float: left; }
    #form_approve #floor_price { display: block; float: left; }
    #form_approve #floor_percent { display: block; float: left; }
    #form_approve #floor_button { display: block; float: left; margin-left: 20px; }
    #form_approve #message { display: block; float: left; width: 100%; height: 21px; font-size: 17px; text-align: center; margin-bottom: 40px; background-color: #DE3232; color: white; }
    #form_approve input[name=notify_user] { display: block; float: left; width: 40px; margin: 5px 0px 0px 114px; }
    #form_approve #label_notify_user { display: block; float: left; width: 250px; margin: 5px 0px 0px 0px; }
    #form_approve #email{ display: block; float: left; margin-top: 8px; }
    #form_approve #subject{ display: block; float: left; width: 468px; background: none; padding-left: 0px; border: 1px solid #D7D7D7;  }
    #form_approve #lable_text{ display: block; float: left; }
    #form_approve #label_subject{ display: block; float: left; }
    #form_approve #text{ width: 468px; height: 210px; }
    #form_approve #label_to{ display: block; float: left; width: 400px; margin-bottom: 5px; }
    #form_approve #label_to span{ font-size: 18px; margin-left: 103px; }
    
</style>

<script>
    
	$(document).ready(function(){
            
            $(".datepicker").live('click', function(){
                $(this).datepicker({ showOn:'focus', 'dateFormat' : "yy-mm-dd" }).focus();				
            });

            if(<?php echo $this->data->status ?> == 3){ 

                $('#floor_date').attr('disabled', 'disabled');
                $('#floor_price').attr('disabled', 'disabled');
                $('#floor_percent').attr('disabled', 'disabled');
            }
            
            $('input[name=notify_user]').change(function(){
                
                var value = $('input[name=notify_user]:checked').val();
                
                if(value == 1) $('#email').show();
                else           $('#email').hide();
                                
            });
            
            var value = $('input[name=notify_user]:checked').val();
                
            if(value == 1) $('#email').show();
            else           $('#email').hide();

	});
        
</script>


<div class="contUsL" style="width: 700px;">
    <h1>Approve Minimum CPM</h1><br /><br />    
    
    <form action="" method="post" class="" id="form_approve">  

            <?php if($this->data->status == 3):?><div id="message">These data have been confirmed</div><?php endif;?>
        
            <label>Floor price:</label> 
            <input type="text" style="width: 100px;" class="datepicker" name="floor_date" id="floor_date" value="<?php echo date('Y-m-d'); ?>" /> 
            <input type="text" style="width: 100px;" name="floor_price" id="floor_price" value="<?php echo $this->data->cpm; ?>" /> 
            <input type="text" style="width: 100px;" name="floor_percent" id="floor_percent" value="0.5" />

            <div id="floor_button"><a href="#" title="" onclick="document.getElementById('subForm').click(); return false;" class="sendMasBtn">Save</a></div>
            <input type="submit" id="subForm" style="display: none;" />
            
            <div style="clear: both"></div>
            <input name="notify_user" type="checkbox" value="1" <?php echo $this->site['notification_control_user'] ? 'checked' : '' ;?>/><label id="label_notify_user">Notify user about approval</label>
            
            <div style="clear: both"></div>
            <div id="email">
                <label id="label_to">To:<span><?php echo $this->site['email'];?></span></label>
                
                <div style="clear: both"></div>
                <label id="label_subject">Subject:</label>
                <input type="text" name="subject" id="subject" value="Minimum CPM Request for <?php echo $this->site['SiteName'];?> Approved"/>
                
                <div style="clear: both"></div>
                <label id="label_text">Body:</label>
                <textarea name="text" id="text">Hello,<br /><br />

This email is to notify you that your following minimum CPM request has been approved:<br />
Website: <?php echo $this->site['SiteName'];?><br />
New CPM: <?php echo $this->data->cpm != 'Max Fill' ? '$' : ''; echo $this->data->cpm;?><br />
Prev. CPM: <?php echo $this->data->prev_cpm != 'Max Fill' ? '$' : ''; echo $this->data->prev_cpm;?><br /><br />

If you have any questions, please feel free to respond to this email.<br /><br />

Regards,<br />
The MadAds Media Publisher Team</textarea>
            </div>
            
    </form> 
            
</div>    

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
    Cufon.replace('.error', {color: 'red'});	    

</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});	
	Cufon.replace('.contactUs h1');		
    Cufon.replace('h1');				
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.fMenu a');		
		Cufon.replace('.contactUs p');	
		Cufon.replace('.contUsL label');		
		Cufon.replace('#location');		
		Cufon.replace('.contBtn p');			
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
		Cufon.replace('.headquaters');		
</script> 