
<style type="text/css">
    
    #table_cpm .action a{ margin: 0px 5px 0px 5px; }
    
</style>

<script type="text/javascript">
        
        jQuery(document).ready(function(){
              
             $('#table_cpm').dataTable({
                 "bProcessing": true,
                 "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                 "iDisplayLength": -1,
                 "aoColumns": [
                     null,
                     null,
                     null,
                     null,
                     null,
                     {"bSortable": false }  
                 ]
             });
             
                        
        });

        
</script>

<h1>Value Minimum Cpm</h1>
<br />
<div class="contUsL" style="width: 750px;">
        
<a href="/administrator/cpm/add-value">Add minimum cpm value</a>    
    
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="table_cpm">

    <thead>
        
        <tr>
            <th width="10%">Position</th>
            <th width="17%">Name</th>
            <th width="17%">Value</th>
            <th width="17%">Estim eCpm</th>
            <th width="17%">Estim Fill Rate</th>
            <th width="17%">Action</th>
        </tr>
        
    </thead>
    <tbody>

        <?php foreach ($this->data as $iter): ?>

           <tr>
               <td><?php echo $iter->position;?></td>
               <td><?php echo $iter->name;?></td>
               <td><?php echo $iter->value;?></td>
               <td><?php echo $iter->estim_cpm;?></td>
               <td><?php echo $iter->estim_rate;?></td>
               <td class="action">
                   <a href="/administrator/cpm/edit-value/id/<?php echo $iter->id;?>">edit</a>
                   <a href="/administrator/cpm/delete-value/id/<?php echo $iter->id;?>" onclick="return confirm('Delete ?');">delete</a>
               </td>

           </tr>
        
        
        <?php endforeach; ?>

    </tbody>
        
</table>

</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
