<script type="text/javascript">
        
        jQuery(document).ready(function(){
              
             $('#table_level').dataTable({
                 "bProcessing": true,
                 "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, "All"]],
                 "iDisplayLength": -1,
                 "aoColumns": [
                     null,
                     null,
                     null,
                     null,
                     null,
                     null 
                 ],
                  "aaSorting": [[ 4, "asc" ]]
             }); 
        });

        
</script>

<h1>Revenue Level</h1>
<div id="showTable" class="contUsL" style="width: 750px;">
    <a href="/administrator/payments/level-add/">Create new level</a>
<table width="740px" cellpadding="0" cellspacing="0" border="0" class="display" id="table_level">

    <thead>
        
        <tr>
            <th width="7%">id</th>
            <th width="20%">Name</th>
            <th width="10%">Min</th>
            <th width="10%">Max</th>
            <th width="15%">Position</th>
            <th width="10%">Delete</th>    
        </tr>
        
    </thead>
    <tbody>
   
            <?php foreach ($this->data as $iter): ?>
                <tr>
                    <td><?php echo $iter['id']; ?></td>
                    <td><a href="/administrator/payments/level-edit/id/<?php echo $iter['id']; ?>"><?php echo $iter['name']; ?></a></td>
                    <td><?php echo $iter['min'] == $this->min ? '-' : $iter['min']; ?></td>
                    <td><?php echo $iter['max'] == $this->max ? '+' : $iter['max']; ?></td>
                    <td><?php echo $iter['position']; ?></td>
                    <td><a href="/administrator/payments/level-delete/id/<?php echo $iter['id']; ?>" onclick="return confirm('Confirm ?');">Delete</a></td>
                </tr>
            <?php endforeach; ?>
  

    </tbody>
        
</table>    
    
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});	
		Cufon.replace('#topMenu a');
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.contInf h3', {hover: true});	
	Cufon.replace('.contInf h3');
	Cufon.replace('.contInf h3.white', {color: '#FFF'});	
	Cufon.replace('.footerBann h5');		
	Cufon.replace('.footerBann p');	
	Cufon.replace('.footerBann a', {hover: true});		
    Cufon.replace('h1');		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');	
		Cufon.replace('.contInf p', {hover: true});		
		Cufon.replace('.contInf p', {color: '#333333'});	
		Cufon.replace('.contInf p.white', {color: '#FFF'});	
		Cufon.replace('.fMenu a', {textDecoration: 'underline'});		
		
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>
