<style type="text/css">

    .contUsL input{ background: none; }
    #contact{ width: 700px; border-collapse: collapse; border: 1px #B7B7B7 solid; margin-top: 20px; }
    #contact tbody tr td{

        border: 1px #B7B7B7 solid;
        font-size: 13px;
        font-family: Arial,Helvetica,sans-serif;
        padding: 5px;
     }

    #contact thead tr th{

        border: 1px #B7B7B7 solid;
        font-size: 16px;
        font-family: Arial,Helvetica,sans-serif;
        padding: 5px;
        text-align: center;
    }

    #contact tfoot tr td{

        border: 1px #B7B7B7 solid;
        font-size: 16px;
        font-family: Arial,Helvetica,sans-serif;
        text-align: center;
    }

    #contact #date-value{
        display: block;
        width: 180px;
        float: left;
        padding: 5px;
        font-size: 16px;
        font-family: Arial,Helvetica,sans-serif;
        text-align: center;
    }

    #act{ display: block; float: right; padding-left: 20px;  border-left: 1px #B7B7B7 solid; }
    #act input { margin: 0px; padding: 0px; }
    #act span{ display: block; float: left; width: 80px; height: 20px; margin: 5px 0px 0px 0px; font-size: 16px; text-align: left; }
    #act input[type=radio]{ display: block; float: left; width: 40px; margin-top: 3px; }
    #act input[type=button]{ display: block; float: left; height: 30px; width: 170px; margin-left: 10px; background-color: #8E8E8E; color:#FFFFFF; font-size: 16px; cursor: pointer; }
    #act input[type=button]:hover{ background-color: #DE3232; }
    #report
    {
	   background-image: none;
       border-right: solid 1px #E2E2E2;
       border-left: solid 1px #E2E2E2;
    }
    #reportL
    {
	   background-image: none;
       border-right: solid 1px #E2E2E2;
       border-left: solid 1px #E2E2E2;
    }
    .contUsL
    {
	   margin-left: 125px;
    }
</style>
<script type="text/javascript" charset="utf-8">

    function mySubmit()
    {
        var choice = $('#act input[type=radio]:checked').val();

             if(choice == 'approve') document.location.href='/administrator/payments/pending-approve/id/<?php echo $this->data['new']['PubID'];?>';
        else if(choice == 'delete')  document.location.href='/administrator/payments/pending-delete/id/<?php echo $this->data['new']['PubID'];?>';
    }

</script>


<h1>Payment Info</h1>

<div class="contUsL">
     <table id="contact">
         <thead>
             <tr>
                 <th>Payment Info</th>
                 <th>Old</th>
                 <th>New</th>
             </tr>
         </thead>
         <tbody>
             <tr>
                 <td>PubID</td>
                 <td><?php echo $this->data['old']['id'];?></td>
                 <td><?php echo $this->data['new']['PubID'];?></td>
             </tr>
             <tr>
                 <td>Email</td>
                 <td><?php echo $this->data['old']['email'];?></td>
                 <td><?php echo $this->data['new']['email'];?></td>
             </tr>
             <tr>
                 <td>Name</td>
                 <td><?php echo $this->data['old']['name'];?></td>
                 <td><?php echo $this->data['new']['name'];?></td>
             </tr>
             <tr>
                 <td>Type</td>
                 <td><?php echo $this->data['old']['payType'];?></td>
                 <td><?php echo $this->data['new']['payType'];?></td>
             </tr>
             <tr>
                 <td>Street</td>
                 <td><?php echo $this->data['old']['street1'];?></td>
                 <td><?php echo $this->data['new']['street1'];?></td>
             </tr>
             <tr>
                 <td>Street</td>
                 <td><?php echo $this->data['old']['street2'];?></td>
                 <td><?php echo $this->data['new']['street2'];?></td>
             </tr>
             <tr>
                 <td>Country</td>
                 <td><?php echo $this->data['old']['country'];?></td>
                 <td><?php echo $this->data['new']['country'];?></td>
             </tr>
             <tr>
                 <td>State</td>
                 <td><?php echo $this->data['old']['state'];?></td>
                 <td><?php echo $this->data['new']['state'];?></td>
             </tr>
             <tr>
                 <td>City</td>
                 <td><?php echo $this->data['old']['city'];?></td>
                 <td><?php echo $this->data['new']['city'];?></td>
             </tr>
             <tr>
                 <td>Zip/Postal</td>
                 <td><?php echo $this->data['old']['zip'];?></td>
                 <td><?php echo $this->data['new']['zip'];?></td>
             </tr>
             <tr>
                 <td>Payment Amount</td>
                 <td><?php echo $this->data['old']['paymentAmout'];?></td>
                 <td><?php echo $this->data['new']['paymentAmout'];?></td>
             </tr>
             <tr>
                 <td>Payment Method</td>
                 <td><?php echo $this->data['old']['paymentBy'];?></td>
                 <td><?php echo $this->data['new']['paymentBy'];?></td>
             </tr>
             <tr>
                 <td>PayPal Email</td>
                 <td><?php echo $this->data['old']['paypalmail'];?></td>
                 <td><?php echo $this->data['new']['paypalmail'];?></td>
             </tr>
             <tr>
                 <td>Bank Country</td>
                 <td><?php echo $this->data['old']['bank'];?></td>
                 <td><?php echo $this->data['new']['bank'];?></td>
             </tr>
             <tr>
                 <td>Account Name</td>
                 <td><?php echo $this->data['old']['accName'];?></td>
                 <td><?php echo $this->data['new']['accName'];?></td>
             </tr>
             <tr>
                 <td>Bank Name</td>
                 <td><?php echo $this->data['old']['bankName'] ? $this->data['old']['bankName'] : $this->data['old']['bankName2'];?></td>
                 <td><?php echo $this->data['new']['bankName'] ? $this->data['new']['bankName'] : $this->data['new']['bankName2'];?></td>
             </tr>
             <tr>
                 <td>Bank Adress</td>
                 <td><?php echo $this->data['old']['bankAdress'];?></td>
                 <td><?php echo $this->data['new']['bankAdress'];?></td>
             </tr>
             <tr>
                 <td>Beneficiary Name</td>
                 <td><?php echo $this->data['old']['accName'] ? $this->data['old']['accName'] : $this->data['old']['accName2'];?></td>
                 <td><?php echo $this->data['new']['accName'] ? $this->data['new']['accName'] : $this->data['new']['accName2'];?></td>
             </tr>
             <tr>
                 <td>Account Type</td>
                 <td><?php echo $this->data['old']['accType'];?></td>
                 <td><?php echo $this->data['new']['accType'];?></td>
             </tr>
             <tr>
                 <td>Account Number</td>
                 <td><?php echo $this->data['old']['accNumber'] ? $this->data['old']['accNumber'] : $this->data['old']['accNumber2'];?></td>
                 <td><?php echo $this->data['new']['accNumber'] ? $this->data['new']['accNumber'] : $this->data['new']['accNumber2'];?></td>
             </tr>
             <tr>
                 <td>Routing Number</td>
                 <td><?php echo $this->data['old']['routNumber'];?></td>
                 <td><?php echo $this->data['new']['routNumber'];?></td>
             </tr>
             <tr>
                 <td>Swift</td>
                 <td><?php echo $this->data['old']['swift'];?></td>
                 <td><?php echo $this->data['new']['swift'];?></td>
             </tr>
             <tr>
                 <td>IBAN</td>
                 <td><?php echo $this->data['old']['iban'];?></td>
                 <td><?php echo $this->data['new']['iban'];?></td>
             </tr>
         </tbody>
         <tfoot>
             <tr>
                 <td>Date</td>
                 <td colspan="2">
                     <span style="font-size: 15px; position: relative; top: 5px;"><?php echo date('Y-m-d',strtotime($this->data['new']['created']));?></span>
                     <form id="act">
                         <input type="radio" name="choice" value="approve" checked/><span>Approve</span>
                         <input type="radio" name="choice" value="delete"/><span>Delete</span>
                         <input type="button" value="Submit" onClick="mySubmit();"/>
                     </form>
                 </td>
             </tr>
         </tfoot>

     </table>
</div>

<script type="text/javascript" src="/font/cufon-yui.js"></script>
<script type="text/javascript" src="/font/Bebas_400.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#topMenu a', {hover: true});
		Cufon.replace('#topMenu a');
        Cufon.replace('.error', {color: 'red'});
</script>
<script type="text/javascript" src="/font/Headline_Two_400.font.js"></script>
<script type="text/javascript">
	Cufon.replace('.footerBann h5');
	Cufon.replace('.footerBann p');
	Cufon.replace('.footerBann a', {hover: true});
	Cufon.replace('.contactUs h1');
    Cufon.replace('h1');

</script>
<script type="text/javascript" src="/font/Proxima_Nova_Lt_300.font.js"></script>
<script type="text/javascript">
		Cufon.replace('#footCopyr');
		Cufon.replace('.fMenu a');
		Cufon.replace('.contactUs p');
		Cufon.replace('.contUsL label');
		Cufon.replace('.contBtn p');
		Cufon.replace('.sendMasBtn',{textShadow: '-1px -1px #5F5F5F'});
</script>
<script type="text/javascript" src="/font/Proxima_Nova_Rg_700.font.js"></script>
<script type="text/javascript">
		Cufon.replace('.fMenu h4');
</script>