<?php

/**
 * Created by PhpStorm.
 * User: nick
 * Date: 25.04.16
 * Time: 09:39
 */
class Administrator_ApiManagerController extends  Zend_Controller_Action{

    public function init(){
        parent::init(); // TODO: Change the autogenerated stub

        $layout = Zend_Layout::getMvcInstance();
        $layout->setLayout('admin_v2');
    }

    public function indexAction(){
        $this->view->dateCurr = date("Y-m-d");
        $this->view->datePrev = date("Y-m-d", time()-86400);
    }

    public function setRubiconAction(){
        $this->_helper->layout()->disableLayout(); // disable layout
        $this->_helper->viewRenderer->setNoRender(); // disable view rendering
        $rubApiModel = new Application_Model_DbTable_RubiconApi();

        $id = $rubApiModel->insert([
            'report_id'=>$this->getRequest()->getPost('report_id'),
            'status'=>0,
            'created_at'=>date("Y-m-d H:i:s")
        ]);

        $data = [];

        if($id)
            $data['status'] = 'ok';
        else
            $data['status'] = 'DB Error';

        $this->getResponse()->setBody(Zend_Json::encode($data))->setHeader('content-type', 'application/json', true);
    }

    public function setPubmAction(){
        $this->_helper->layout()->disableLayout(); // disable layout
        $this->_helper->viewRenderer->setNoRender(); // disable view rendering

        $rubApiModel = new Application_Model_DbTable_PubmaticApi();

        $id = $rubApiModel->insert([
            'start'=>$this->getRequest()->getPost('start'),
            'end'=>$this->getRequest()->getPost('finish'),
            'status'=>0,
            'created_at'=>date("Y-m-d H:i:s")
        ]);

        $data = [];

        if($id)
            $data['status'] = 'ok';
        else
            $data['status'] = 'DB Error';

        $this->getResponse()->setBody(Zend_Json::encode($data))->setHeader('content-type', 'application/json', true);
    }

    public function setPopAction()
    {
        $this->_helper->layout()->disableLayout(); // disable layout
        $this->_helper->viewRenderer->setNoRender(); // disable view rendering

        $popApiModel = new Application_Model_DbTable_PopApi();

        $id = $popApiModel->insert([
            'start'=>$this->getRequest()->getPost('start'),
            'end'=>$this->getRequest()->getPost('finish'),
            'status'=>0,
            'created_at'=>date("Y-m-d H:i:s")
        ]);

        $data = [];

        if($id)
            $data['status'] = 'ok';
        else
            $data['status'] = 'DB Error';

        $this->getResponse()->setBody(Zend_Json::encode($data))->setHeader('content-type', 'application/json', true);
    }
}